import { useEffect, useRef, useState } from "react";
import { EditableText } from "../Shared/EditableText";
import { EditableImage } from "../Shared/EditableImage";
import { getEffectiveTheme } from "../../../../theme/Theme";
import { RepeatableControls, RepeatableRemoveButton, cloneLast, removeLast } from "../Shared/RepeatableControls";

const reviews = [
  { avatar:"/storage/cms-images/avatars/avatar-1.jpg", name:"Alex Morgan", company:"North & Co.", quote:"Sample review — replace this with a verified customer testimonial." },
  { avatar:"/storage/cms-images/avatars/avatar-2.jpg", name:"Jordan Lee", company:"Studio Lane", quote:"Sample review — use a real quote before publishing this section." },
  { avatar:"/storage/cms-images/avatars/avatar-3.jpg", name:"Taylor Brooks", company:"Arc Works", quote:"Sample review — add customer-approved feedback here." },
  { avatar:"/storage/cms-images/avatars/avatar-4.jpg", name:"Casey Rivera", company:"Field House", quote:"Sample review — replace with authentic social proof." },
];

const base = (type,title,description,count=4) => ({
  type,title,category:"Testimonials",purpose:description,description,tags:["testimonials","reviews","social proof","premium"],
  defaults:{eyebrow:"CLIENT STORIES",heading:"Proof that feels personal.",text:"Bring authentic customer voices forward with a premium editorial treatment.",testimonials:reviews.slice(0,count)},
  fields:[{key:"eyebrow",type:"text",label:"Eyebrow"},{key:"heading",type:"text",label:"Heading"},{key:"text",type:"textarea",label:"Description"},{key:"testimonials",type:"repeater",label:"Testimonials",fields:[{key:"avatar",type:"image",label:"Avatar"},{key:"name",type:"text",label:"Name"},{key:"company",type:"text",label:"Company"},{key:"quote",type:"textarea",label:"Quote"}]}]
});

export const TestimonialsVideoSchema={...base("testimonials_video_premium","Video Testimonials","Editorial testimonial spotlight with an optional customer video URL."),defaults:{...base("x","x","x").defaults,video_url:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",video_label:"Demo video — replace before publishing"},fields:[...base("x","x","x").fields,{key:"video_url",type:"text",label:"Video URL"},{key:"video_label",type:"text",label:"Video label"}]};
export const TestimonialsMarqueeSchema=base("testimonials_scrolling_marquee","Scrolling Marquee","Continuous premium social-proof rail with a readable static layout.");
export const TestimonialsWallOfLoveSchema=base("testimonials_wall_of_love","Wall of Love","Dense social-proof wall for brands with multiple customer voices.");
export const TestimonialsCardStackSchema=base("testimonials_card_stack","Card Stack","Layered editorial testimonial cards with strong visual hierarchy.");
export const TestimonialsTrustDashboardSchema=base("testimonials_trust_dashboard","Trust Dashboard","Premium proof dashboard combining customer voices with trust-oriented summary cards.");
export const TestimonialsReviewGridSchema=base("testimonials_review_grid","Review Grid","Balanced premium review grid for displaying several customer stories at once.");
export const TestimonialsReviewCarouselProSchema=base("testimonials_review_carousel_pro","Review Carousel Pro","Editorial carousel-style review layout with strong featured-card hierarchy and static export fallback.");

function Header({data,onUpdate,theme}){return <div className="mx-auto mb-14 max-w-3xl text-center"><EditableText value={data.eyebrow} className={`block text-xs font-semibold uppercase tracking-[.32em] ${theme.sub}`} onSave={v=>onUpdate({eyebrow:v})}/><EditableText value={data.heading} className={`mt-4 block text-4xl font-bold tracking-tight sm:text-5xl ${theme.text}`} onSave={v=>onUpdate({heading:v})}/><EditableText value={data.text} isTextArea className={`mx-auto mt-5 block max-w-2xl text-base leading-7 ${theme.sub}`} onSave={v=>onUpdate({text:v})}/></div>}

function TestimonialControls({data,onUpdate}){
  const items=Array.isArray(data.testimonials)?data.testimonials:[];
  const add=()=>items.length<8&&onUpdate({testimonials:cloneLast(items,reviews[0])});
  const remove=()=>onUpdate({testimonials:removeLast(items,1)});
  return <RepeatableControls onAdd={add} onRemove={remove} canAdd={items.length<8} canRemove={items.length>1} addLabel="Add testimonial" removeLabel="Remove last testimonial" showRemove={false} className="justify-center"/>;
}
function Review({item,index,data,onUpdate,theme,className=""}){const update=(field,value)=>{const testimonials=[...data.testimonials];testimonials[index]={...testimonials[index],[field]:value};onUpdate({testimonials});};const remove=()=>{if(data.testimonials.length<=1)return;onUpdate({testimonials:data.testimonials.filter((_,i)=>i!==index)});};return <article className={`group relative rounded-3xl border p-6 ${theme.border} ${theme.card} ${className}`}><RepeatableRemoveButton hoverScope="card" overlay onRemove={remove} disabled={data.testimonials.length<=1} label="Remove testimonial"/><div className="mb-5 flex items-center gap-3"><EditableImage src={item.avatar} alt={item.name} className="h-12 w-12 rounded-full object-cover" overlayVariant="compact" onSave={v=>update("avatar",v)}/><div><EditableText value={item.name} className={`block font-semibold ${theme.text}`} onSave={v=>update("name",v)}/><EditableText value={item.company} className={`block text-sm ${theme.sub}`} onSave={v=>update("company",v)}/></div></div><EditableText value={item.quote} isTextArea className={`block text-base leading-7 ${theme.text}`} onSave={v=>update("quote",v)}/></article>}

export function TestimonialsVideoBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme),data={...TestimonialsVideoSchema.defaults,...block};return <section className={`group/repeatable-section px-7 py-28 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={data} onUpdate={onUpdate} theme={theme}/><div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><div className={`relative min-h-[360px] overflow-hidden rounded-3xl border ${theme.border} ${theme.card}`}>{data.video_url?<video className="absolute inset-0 h-full w-full object-cover" src={data.video_url} controls preload="metadata"/>:<div className="absolute inset-0 flex items-center justify-center bg-black/10"><span className={`rounded-full border px-5 py-3 text-sm font-semibold ${theme.border} ${theme.text}`}>Add customer video URL</span></div>}<div className="absolute bottom-5 left-5 right-5"><EditableText value={data.video_label} className="inline-block rounded-full bg-black/65 px-4 py-2 text-sm font-semibold text-white" onSave={v=>onUpdate({video_label:v})}/></div></div><div className="grid gap-6">{data.testimonials.map((x,i)=><Review key={i} item={x} index={i} data={data} onUpdate={onUpdate} theme={theme}/>)}</div></div><TestimonialControls data={data} onUpdate={onUpdate}/></div></section>}
export function TestimonialsMarqueeBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme),data={...TestimonialsMarqueeSchema.defaults,...block};const rail=useRef(null);const paused=useRef(false);useEffect(()=>{let raf,last=performance.now();const tick=(now)=>{const el=rail.current;if(el&&!paused.current&&el.scrollWidth>el.clientWidth){const delta=Math.min(32,now-last);el.scrollLeft+=delta*0.035;if(el.scrollLeft>=el.scrollWidth-el.clientWidth-2)el.scrollLeft=0;}last=now;raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[data.testimonials.length]);return <section className={`group/repeatable-section overflow-hidden px-7 py-28 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={data} onUpdate={onUpdate} theme={theme}/><div ref={rail} onMouseEnter={()=>paused.current=true} onMouseLeave={()=>paused.current=false} onFocusCapture={()=>paused.current=true} onBlurCapture={()=>paused.current=false} className="cosmic-hide-scrollbar flex gap-5 overflow-x-auto scroll-smooth pb-4" aria-label="Customer testimonials marquee">{data.testimonials.map((x,i)=><div key={i} className="group relative min-w-[86%] max-w-sm flex-1 sm:min-w-[300px]"><Review item={x} index={i} data={data} onUpdate={onUpdate} theme={theme}/></div>)}</div><p className={`mt-3 text-center text-xs ${theme.sub}`}>Auto-scroll pauses on hover or keyboard focus. Drag or scroll manually anytime.</p><TestimonialControls data={data} onUpdate={onUpdate}/></div></section>}
export function TestimonialsWallOfLoveBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme),data={...TestimonialsWallOfLoveSchema.defaults,...block};return <section className={`group/repeatable-section px-7 py-28 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={data} onUpdate={onUpdate} theme={theme}/><div className="columns-1 gap-5 space-y-5 md:columns-2 lg:columns-3">{data.testimonials.map((x,i)=><div key={i} className="group relative break-inside-avoid"><Review item={x} index={i} data={data} onUpdate={onUpdate} theme={theme}/></div>)}</div><TestimonialControls data={data} onUpdate={onUpdate}/></div></section>}
export function TestimonialsCardStackBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme),data={...TestimonialsCardStackSchema.defaults,...block};const [active,setActive]=useState(0);const total=data.testimonials.length||1;useEffect(()=>{setActive(v=>Math.min(v,Math.max(0,total-1)))},[total]);const go=(dir)=>setActive(v=>(v+dir+total)%total);return <section className={`group/repeatable-section px-7 py-28 ${theme.bg}`}><div className="mx-auto max-w-6xl"><Header data={data} onUpdate={onUpdate} theme={theme}/><div className="relative mx-auto min-h-[260px] max-w-3xl">{data.testimonials.map((x,i)=>{const offset=(i-active+total)%total;if(offset>2)return null;return <div key={i} className="group relative absolute inset-x-0 top-0 transition duration-300" style={{transform:`translateY(${offset*14}px) scale(${1-offset*.035}) rotate(${offset%2?1:-1}deg)`,zIndex:30-offset,opacity:1-offset*.18}}><Review item={x} index={i} data={data} onUpdate={onUpdate} theme={theme} className="shadow-xl"/></div>})}</div><div className="mt-8 flex items-center justify-center gap-3"><button type="button" onClick={()=>go(-1)} className={`rounded-full border px-5 py-2 text-sm font-semibold ${theme.border} ${theme.text}`}>Previous</button><span className={`text-xs ${theme.sub}`}>{active+1} / {total}</span><button type="button" onClick={()=>go(1)} className={`rounded-full border px-5 py-2 text-sm font-semibold ${theme.border} ${theme.text}`}>Next</button></div><TestimonialControls data={data} onUpdate={onUpdate}/></div></section>}

export function TestimonialsTrustDashboardBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme),data={...TestimonialsTrustDashboardSchema.defaults,...block};const total=data.testimonials.length;return <section className={`group/repeatable-section px-7 py-28 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={data} onUpdate={onUpdate} theme={theme}/><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><aside className={`rounded-3xl border p-8 ${theme.border} ${theme.card}`}><div className={`text-sm ${theme.sub}`}>Customer proof</div><div className={`mt-3 text-6xl font-bold ${theme.text}`}>{total}</div><div className={`mt-2 text-sm ${theme.sub}`}>review cards ready to replace with verified feedback</div><div className={`mt-8 grid grid-cols-2 gap-3 text-center text-sm ${theme.sub}`}><div className={`rounded-2xl border p-4 ${theme.border}`}>Verified-copy ready</div><div className={`rounded-2xl border p-4 ${theme.border}`}>Theme aware</div></div></aside><div className="grid gap-5 sm:grid-cols-2">{data.testimonials.map((x,i)=><Review key={i} item={x} index={i} data={data} onUpdate={onUpdate} theme={theme}/>)}</div></div><TestimonialControls data={data} onUpdate={onUpdate}/></div></section>}
export function TestimonialsReviewGridBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme),data={...TestimonialsReviewGridSchema.defaults,...block};return <section className={`group/repeatable-section px-7 py-28 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={data} onUpdate={onUpdate} theme={theme}/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{data.testimonials.map((x,i)=><Review key={i} item={x} index={i} data={data} onUpdate={onUpdate} theme={theme}/>)}</div><TestimonialControls data={data} onUpdate={onUpdate}/></div></section>}
export function TestimonialsReviewCarouselProBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme),data={...TestimonialsReviewCarouselProSchema.defaults,...block};const rail=useRef(null);const move=(dir)=>{const el=rail.current;if(!el)return;el.scrollBy({left:dir*Math.max(280,el.clientWidth*.72),behavior:"smooth"})};return <section className={`group/repeatable-section px-7 py-28 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><Header data={data} onUpdate={onUpdate} theme={theme}/><div className="flex gap-2"><button type="button" onClick={()=>move(-1)} aria-label="Previous review" className={`h-11 w-11 rounded-full border text-lg ${theme.border} ${theme.text}`}>←</button><button type="button" onClick={()=>move(1)} aria-label="Next review" className={`h-11 w-11 rounded-full border text-lg ${theme.border} ${theme.text}`}>→</button></div></div><div ref={rail} className="cosmic-hide-scrollbar mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto scroll-smooth pb-4">{data.testimonials.map((x,i)=><div key={i} className={`group relative min-w-[82%] snap-center sm:min-w-[52%] lg:min-w-[34%] ${i===0?'lg:min-w-[44%]':''}`}><Review item={x} index={i} data={data} onUpdate={onUpdate} theme={theme} className={i===0?'lg:p-9':''}/></div>)}</div><TestimonialControls data={data} onUpdate={onUpdate}/></div></section>}
