import React from "react";

const u=(value)=>String(value||"").trim();
const vars=(resolved)=>{
    const primary=String(resolved||"").toLowerCase()==="primary";
    return {
        "--b3-bg":primary?"var(--cosmic-local-bg-primary,var(--cosmic-bg-primary,var(--cosmic-primary,#243447)))":"var(--cosmic-local-bg-surface,var(--cosmic-bg-surface,#ffffff))",
        "--b3-surface":primary?"var(--cosmic-bg-primary-surface,var(--cosmic-surface,#30475E))":"#f7f7f5",
        "--b3-text":primary?"var(--cosmic-on-primary,#f8fafc)":"var(--cosmic-on-surface,#172033)",
        "--b3-muted":primary?"var(--cosmic-on-primary-muted,rgba(248,250,252,.76))":"var(--cosmic-on-surface-muted,#64748b)",
        "--b3-border":primary?"rgba(248,250,252,.18)":"rgba(15,23,42,.12)",
        "--b3-accent":"var(--cosmic-accent,#60A5FA)",
    };
};
const Img=({item})=>{const src=u(item?.image_url);return <div data-cosmic-luna-display="image" data-luna-target="image" className="b3-img">{src?<img src={src} alt="" className="h-full w-full object-cover pointer-events-none"/>:<div className="h-full min-h-[15rem] w-full bg-[var(--b3-surface)]"/>}</div>};
const Copy=({item,index,family})=><div className="b3-copy">
    <span className="b3-label">{item?.label || String(index+1).padStart(2,"0")}</span>
    <span data-cosmic-luna-display="text" data-cosmic-type={family==="stats"?"stat-title":"card-title"} data-luna-target="heading" className="b3-title">{item?.title}</span>
    <span data-cosmic-luna-display="text" data-cosmic-type="card-body" data-luna-target="text" className="b3-text">{item?.text}</span>
</div>;

const Batch3Section=({block,variant,family})=>{
 const items=Array.isArray(block?.items)?block.items:[];
 const resolved=block?.resolvedTheme||block?.theme||"light";
 return <section className={`group/repeatable-section cosmic-b3 b3-${family} b3-${variant}`} style={vars(resolved)}>
   <div className="b3-shell">
    <div className="b3-head">
      <span data-cosmic-luna-display="text" data-luna-target="label" className="b3-eyebrow">{block?.eyebrow}</span>
      <span data-cosmic-luna-display="text" data-cosmic-type="h2" data-luna-target="heading" className="b3-heading">{block?.heading}</span>
      <span data-cosmic-luna-display="text" data-cosmic-type="lead" data-luna-target="text" className="b3-intro">{block?.text}</span>
    </div>
    <div className="b3-grid">{items.map((item,index)=><article className="b3-card group relative" key={`${item?.title||"item"}-${index}`}><Img item={item}/><Copy item={item} index={index} family={family}/></article>)}</div>
    <div className="b3-actions">
      {block?.button_label&&<a href={block?.button_url||"#"} className="b3-primary" data-cosmic-luna-display="button" data-luna-target="button">{block.button_label}</a>}
      {block?.secondary_label&&<a href={block?.secondary_url||"#"} className="b3-secondary" data-cosmic-luna-display="button" data-luna-target="button">{block.secondary_label}</a>}
    </div>
   </div>
   <style>{`
    .cosmic-b3{background:var(--b3-bg);color:var(--b3-text);padding:7rem 1.75rem}
    .cosmic-b3 .b3-shell{width:100%;max-width:88rem;margin:0 auto}
    .cosmic-b3 .b3-head{max-width:50rem;margin-bottom:3.5rem}
    .cosmic-b3 .b3-eyebrow{display:block;font-size:.75rem;font-weight:500;letter-spacing:.28em;text-transform:uppercase;color:var(--b3-muted)}
    .cosmic-b3 .b3-heading{display:block;margin-top:1rem;font-size:clamp(2.4rem,5vw,4.6rem);line-height:.98;letter-spacing:-.045em;font-weight:700}
    .cosmic-b3 .b3-intro{display:block;margin-top:1.25rem;max-width:42rem;font-size:1.05rem;line-height:1.8;color:var(--b3-muted)}
    .cosmic-b3 .b3-grid{display:grid;gap:1.25rem}
    .cosmic-b3 .b3-card{position:relative;overflow:hidden;border:1px solid var(--b3-border);background:var(--b3-surface);border-radius:1.75rem}
    .cosmic-b3 .b3-img{overflow:hidden;min-height:15rem}
    .cosmic-b3 .b3-img img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .55s ease}
    .cosmic-b3 .b3-card:hover .b3-img img{transform:scale(1.035)}
    .cosmic-b3 .b3-copy{padding:1.5rem}
    .cosmic-b3 .b3-label{display:block;font-size:.72rem;letter-spacing:.18em;text-transform:uppercase;color:var(--b3-muted);margin-bottom:.75rem}
    .cosmic-b3 .b3-title{display:block;font-size:1.45rem;line-height:1.12;font-weight:700}
    .cosmic-b3 .b3-text{display:block;margin-top:.7rem;line-height:1.7;color:var(--b3-muted)}
    .cosmic-b3 .b3-actions{display:flex;gap:.8rem;flex-wrap:wrap;margin-top:2.25rem}
    .cosmic-b3 .b3-primary,.cosmic-b3 .b3-secondary{display:inline-flex;min-height:50px;align-items:center;justify-content:center;border-radius:100px;padding:.75rem 1.5rem;font-weight:700}
    .cosmic-b3 .b3-primary{background:var(--b3-text);color:var(--b3-bg)}
    .cosmic-b3 .b3-secondary{border:1px solid var(--b3-border);color:var(--b3-text)}

    .b3-editorial .b3-grid,.b3-logos .b3-grid,.b3-certifications .b3-grid,.b3-offices .b3-grid,.b3-cards .b3-grid,.b3-directory .b3-grid{grid-template-columns:repeat(4,minmax(0,1fr))}
    .b3-photo .b3-grid,.b3-proof .b3-grid,.b3-form .b3-grid,.b3-split .b3-grid,.b3-spotlight .b3-grid{grid-template-columns:1.25fr .75fr;align-items:stretch}
    .b3-photo .b3-card:first-child,.b3-proof .b3-card:first-child,.b3-form .b3-card:first-child,.b3-split .b3-card:first-child,.b3-spotlight .b3-card:first-child{grid-row:1 / span 2;display:flex;flex-direction:column;height:100%}
    .b3-photo .b3-card:first-child .b3-img,.b3-proof .b3-card:first-child .b3-img,.b3-form .b3-card:first-child .b3-img,.b3-split .b3-card:first-child .b3-img,.b3-spotlight .b3-card:first-child .b3-img{min-height:34rem;flex:1}

    .b3-panels .b3-grid,.b3-partners .b3-grid,.b3-inquiry .b3-grid,.b3-tiles .b3-grid{grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}
    .b3-panels .b3-card:nth-child(even),.b3-inquiry .b3-card:nth-child(even){margin-top:1.5rem}

    .b3-mosaic .b3-grid,.b3-asymmetric .b3-grid{grid-template-columns:repeat(12,minmax(0,1fr));grid-auto-rows:7rem}
    .b3-mosaic .b3-card,.b3-asymmetric .b3-card{grid-column:span 5;grid-row:span 3}
    .b3-mosaic .b3-card:nth-child(2),.b3-asymmetric .b3-card:nth-child(2){grid-column:span 7;grid-row:span 3}
    .b3-mosaic .b3-img,.b3-asymmetric .b3-img{position:absolute;inset:0;height:100%;opacity:.35}
    .b3-mosaic .b3-copy,.b3-asymmetric .b3-copy{position:relative;z-index:2}

    .b3-rail .b3-grid{grid-auto-flow:column;grid-auto-columns:minmax(18rem,28rem);overflow-x:auto;padding-bottom:.5rem;scroll-snap-type:x proximity}
    .b3-rail .b3-card{scroll-snap-align:start}.b3-rail .b3-img{aspect-ratio:4/3}

        .b3-mosaic .b3-copy,.b3-asymmetric .b3-copy{display:flex;min-height:100%;flex-direction:column;justify-content:flex-end;padding:1.75rem;background:linear-gradient(to top,color-mix(in srgb,var(--b3-surface,var(--cosmic-bg-primary-surface,#30475E)) 88%,transparent),transparent 78%)}
@media(max-width:900px){.b3-photo .b3-card:first-child,.b3-proof .b3-card:first-child,.b3-form .b3-card:first-child,.b3-split .b3-card:first-child,.b3-spotlight .b3-card:first-child{grid-row:auto;height:auto}.b3-photo .b3-card:first-child .b3-img,.b3-proof .b3-card:first-child .b3-img,.b3-form .b3-card:first-child .b3-img,.b3-split .b3-card:first-child .b3-img,.b3-spotlight .b3-card:first-child .b3-img{flex:none}.cosmic-b3{padding:5rem 1.25rem}.cosmic-b3 .b3-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.b3-mosaic .b3-grid,.b3-asymmetric .b3-grid{grid-auto-rows:auto}.b3-mosaic .b3-card,.b3-asymmetric .b3-card{grid-column:auto;grid-row:auto;min-height:21rem}.b3-rail .b3-grid{display:grid;grid-auto-flow:row;grid-auto-columns:auto}}
    @media(max-width:640px){.cosmic-b3{padding:4rem 1rem}.cosmic-b3 .b3-heading{font-size:clamp(2.2rem,12vw,3.4rem)}.cosmic-b3 .b3-grid{grid-template-columns:1fr!important}.b3-panels .b3-card:nth-child(even),.b3-inquiry .b3-card:nth-child(even){margin-top:0}}
   
    .b3-card, .b3-copy{min-width:0}`}</style>
 </section>
};

export const StatsPhotoMetricsPremiumBlock=(props)=><Batch3Section {...props} variant="photo" family="stats"/>;
export const StatsPhotoMetricsPremiumSchema={"type":"stats_photo_metrics_premium","title":"Stats Photo Metrics","description":"Image-rich stats section with a distinct photo composition.","defaults":{"type":"stats_photo_metrics_premium","theme":"auto","eyebrow":"By the numbers","heading":"Stats Photo Metrics","text":"A visual snapshot of the outcomes and momentum behind the work.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"42%","text":"Average lift in qualified enquiries after launch.","label":"Growth","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"3.1\u00d7","text":"Faster content publishing with a simpler workflow.","label":"Efficiency","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"98%","text":"Responsive coverage across modern device sizes.","label":"Quality","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"24/7","text":"A digital presence that keeps working after hours.","label":"Always on","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const StatsEditorialNumbersPremiumBlock=(props)=><Batch3Section {...props} variant="editorial" family="stats"/>;
export const StatsEditorialNumbersPremiumSchema={"type":"stats_editorial_numbers_premium","title":"Stats Editorial Numbers","description":"Image-rich stats section with a distinct editorial composition.","defaults":{"type":"stats_editorial_numbers_premium","theme":"auto","eyebrow":"By the numbers","heading":"Stats Editorial Numbers","text":"A visual snapshot of the outcomes and momentum behind the work.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"42%","text":"Average lift in qualified enquiries after launch.","label":"Growth","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"3.1\u00d7","text":"Faster content publishing with a simpler workflow.","label":"Efficiency","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"98%","text":"Responsive coverage across modern device sizes.","label":"Quality","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"24/7","text":"A digital presence that keeps working after hours.","label":"Always on","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const StatsImagePanelsPremiumBlock=(props)=><Batch3Section {...props} variant="panels" family="stats"/>;
export const StatsImagePanelsPremiumSchema={"type":"stats_image_panels_premium","title":"Stats Image Panels","description":"Image-rich stats section with a distinct panels composition.","defaults":{"type":"stats_image_panels_premium","theme":"auto","eyebrow":"By the numbers","heading":"Stats Image Panels","text":"A visual snapshot of the outcomes and momentum behind the work.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"42%","text":"Average lift in qualified enquiries after launch.","label":"Growth","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"3.1\u00d7","text":"Faster content publishing with a simpler workflow.","label":"Efficiency","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"98%","text":"Responsive coverage across modern device sizes.","label":"Quality","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"24/7","text":"A digital presence that keeps working after hours.","label":"Always on","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const StatsVisualMosaicPremiumBlock=(props)=><Batch3Section {...props} variant="mosaic" family="stats"/>;
export const StatsVisualMosaicPremiumSchema={"type":"stats_visual_mosaic_premium","title":"Stats Visual Mosaic","description":"Image-rich stats section with a distinct mosaic composition.","defaults":{"type":"stats_visual_mosaic_premium","theme":"auto","eyebrow":"By the numbers","heading":"Stats Visual Mosaic","text":"A visual snapshot of the outcomes and momentum behind the work.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"42%","text":"Average lift in qualified enquiries after launch.","label":"Growth","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"3.1\u00d7","text":"Faster content publishing with a simpler workflow.","label":"Efficiency","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"98%","text":"Responsive coverage across modern device sizes.","label":"Quality","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"24/7","text":"A digital presence that keeps working after hours.","label":"Always on","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const TrustLogoStoryPremiumBlock=(props)=><Batch3Section {...props} variant="logos" family="trust"/>;
export const TrustLogoStoryPremiumSchema={"type":"trust_logo_story_premium","title":"Trust Logo Story","description":"Image-rich trust section with a distinct logos composition.","defaults":{"type":"trust_logo_story_premium","theme":"auto","eyebrow":"Why teams trust us","heading":"Trust Logo Story","text":"Proof points that make the decision feel easier and more confident.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Trusted collaboration","text":"Clear communication, practical decisions, and dependable delivery.","label":"Partnership","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Built with care","text":"Thoughtful design and development with quality checks throughout.","label":"Quality","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to scale","text":"Flexible foundations that can grow with the business.","label":"Longevity","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Real support","text":"A human process with clear ownership from start to finish.","label":"Support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const TrustImageProofPremiumBlock=(props)=><Batch3Section {...props} variant="proof" family="trust"/>;
export const TrustImageProofPremiumSchema={"type":"trust_image_proof_premium","title":"Trust Image Proof","description":"Image-rich trust section with a distinct proof composition.","defaults":{"type":"trust_image_proof_premium","theme":"auto","eyebrow":"Why teams trust us","heading":"Trust Image Proof","text":"Proof points that make the decision feel easier and more confident.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Trusted collaboration","text":"Clear communication, practical decisions, and dependable delivery.","label":"Partnership","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Built with care","text":"Thoughtful design and development with quality checks throughout.","label":"Quality","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to scale","text":"Flexible foundations that can grow with the business.","label":"Longevity","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Real support","text":"A human process with clear ownership from start to finish.","label":"Support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const TrustCertificationCardsPremiumBlock=(props)=><Batch3Section {...props} variant="certifications" family="trust"/>;
export const TrustCertificationCardsPremiumSchema={"type":"trust_certification_cards_premium","title":"Trust Certification Cards","description":"Image-rich trust section with a distinct certifications composition.","defaults":{"type":"trust_certification_cards_premium","theme":"auto","eyebrow":"Why teams trust us","heading":"Trust Certification Cards","text":"Proof points that make the decision feel easier and more confident.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Trusted collaboration","text":"Clear communication, practical decisions, and dependable delivery.","label":"Partnership","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Built with care","text":"Thoughtful design and development with quality checks throughout.","label":"Quality","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to scale","text":"Flexible foundations that can grow with the business.","label":"Longevity","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Real support","text":"A human process with clear ownership from start to finish.","label":"Support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const TrustPartnerShowcasePremiumBlock=(props)=><Batch3Section {...props} variant="partners" family="trust"/>;
export const TrustPartnerShowcasePremiumSchema={"type":"trust_partner_showcase_premium","title":"Trust Partner Showcase","description":"Image-rich trust section with a distinct partners composition.","defaults":{"type":"trust_partner_showcase_premium","theme":"auto","eyebrow":"Why teams trust us","heading":"Trust Partner Showcase","text":"Proof points that make the decision feel easier and more confident.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Trusted collaboration","text":"Clear communication, practical decisions, and dependable delivery.","label":"Partnership","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Built with care","text":"Thoughtful design and development with quality checks throughout.","label":"Quality","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to scale","text":"Flexible foundations that can grow with the business.","label":"Longevity","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Real support","text":"A human process with clear ownership from start to finish.","label":"Support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const ContactImageFormPremiumBlock=(props)=><Batch3Section {...props} variant="form" family="contact"/>;
export const ContactImageFormPremiumSchema={"type":"contact_image_form_premium","title":"Contact Image Form","description":"Image-rich contact section with a distinct form composition.","defaults":{"type":"contact_image_form_premium","theme":"auto","eyebrow":"Get in touch","heading":"Contact Image Form","text":"Choose the best way to start the conversation.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"New project","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"General enquiry","text":"Have a question or want to explore an idea? Start here.","label":"Say hello","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Partnership","text":"For collaborations, referrals, and ongoing delivery partnerships.","label":"Work together","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Support","text":"Existing clients can reach us for help, updates, and next steps.","label":"Client support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const ContactEditorialSplitPremiumBlock=(props)=><Batch3Section {...props} variant="split" family="contact"/>;
export const ContactEditorialSplitPremiumSchema={"type":"contact_editorial_split_premium","title":"Contact Editorial Split","description":"Image-rich contact section with a distinct split composition.","defaults":{"type":"contact_editorial_split_premium","theme":"auto","eyebrow":"Get in touch","heading":"Contact Editorial Split","text":"Choose the best way to start the conversation.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"New project","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"General enquiry","text":"Have a question or want to explore an idea? Start here.","label":"Say hello","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Partnership","text":"For collaborations, referrals, and ongoing delivery partnerships.","label":"Work together","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Support","text":"Existing clients can reach us for help, updates, and next steps.","label":"Client support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const ContactOfficeCardsPremiumBlock=(props)=><Batch3Section {...props} variant="offices" family="contact"/>;
export const ContactOfficeCardsPremiumSchema={"type":"contact_office_cards_premium","title":"Contact Office Cards","description":"Image-rich contact section with a distinct offices composition.","defaults":{"type":"contact_office_cards_premium","theme":"auto","eyebrow":"Get in touch","heading":"Contact Office Cards","text":"Choose the best way to start the conversation.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"New project","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"General enquiry","text":"Have a question or want to explore an idea? Start here.","label":"Say hello","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Partnership","text":"For collaborations, referrals, and ongoing delivery partnerships.","label":"Work together","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Support","text":"Existing clients can reach us for help, updates, and next steps.","label":"Client support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const ContactVisualInquiryPremiumBlock=(props)=><Batch3Section {...props} variant="inquiry" family="contact"/>;
export const ContactVisualInquiryPremiumSchema={"type":"contact_visual_inquiry_premium","title":"Contact Visual Inquiry","description":"Image-rich contact section with a distinct inquiry composition.","defaults":{"type":"contact_visual_inquiry_premium","theme":"auto","eyebrow":"Get in touch","heading":"Contact Visual Inquiry","text":"Choose the best way to start the conversation.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"New project","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"General enquiry","text":"Have a question or want to explore an idea? Start here.","label":"Say hello","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Partnership","text":"For collaborations, referrals, and ongoing delivery partnerships.","label":"Work together","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Support","text":"Existing clients can reach us for help, updates, and next steps.","label":"Client support","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const GalleryEditorialGridPremiumBlock=(props)=><Batch3Section {...props} variant="editorial" family="gallery"/>;
export const GalleryEditorialGridPremiumSchema={"type":"gallery_editorial_grid_premium","title":"Gallery Editorial Grid","description":"Image-rich gallery section with a distinct editorial composition.","defaults":{"type":"gallery_editorial_grid_premium","theme":"auto","eyebrow":"Selected moments","heading":"Gallery Editorial Grid","text":"A visual collection designed to break up the page and add depth.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Brand detail","text":"A closer look at the craft, decisions, and details that shape the final experience.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"In the studio","text":"Process, collaboration, and in-between moments that show how the work comes together.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built environment","text":"Photography that adds context, atmosphere, and a more human sense of the project.","label":"03","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch moment","text":"The finished work in the world, captured with enough detail to tell the story clearly.","label":"04","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const GalleryAsymmetricPremiumBlock=(props)=><Batch3Section {...props} variant="asymmetric" family="gallery"/>;
export const GalleryAsymmetricPremiumSchema={"type":"gallery_asymmetric_premium","title":"Gallery Asymmetric","description":"Image-rich gallery section with a distinct asymmetric composition.","defaults":{"type":"gallery_asymmetric_premium","theme":"auto","eyebrow":"Selected moments","heading":"Gallery Asymmetric","text":"A visual collection designed to break up the page and add depth.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Brand detail","text":"A closer look at the craft, decisions, and details that shape the final experience.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"In the studio","text":"Process, collaboration, and in-between moments that show how the work comes together.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built environment","text":"Photography that adds context, atmosphere, and a more human sense of the project.","label":"03","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch moment","text":"The finished work in the world, captured with enough detail to tell the story clearly.","label":"04","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const GalleryStoryTilesPremiumBlock=(props)=><Batch3Section {...props} variant="tiles" family="gallery"/>;
export const GalleryStoryTilesPremiumSchema={"type":"gallery_story_tiles_premium","title":"Gallery Story Tiles","description":"Image-rich gallery section with a distinct tiles composition.","defaults":{"type":"gallery_story_tiles_premium","theme":"auto","eyebrow":"Selected moments","heading":"Gallery Story Tiles","text":"A visual collection designed to break up the page and add depth.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Brand detail","text":"A closer look at the craft, decisions, and details that shape the final experience.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"In the studio","text":"Process, collaboration, and in-between moments that show how the work comes together.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built environment","text":"Photography that adds context, atmosphere, and a more human sense of the project.","label":"03","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch moment","text":"The finished work in the world, captured with enough detail to tell the story clearly.","label":"04","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const GalleryImageRailPremiumBlock=(props)=><Batch3Section {...props} variant="rail" family="gallery"/>;
export const GalleryImageRailPremiumSchema={"type":"gallery_image_rail_premium","title":"Gallery Image Rail","description":"Image-rich gallery section with a distinct rail composition.","defaults":{"type":"gallery_image_rail_premium","theme":"auto","eyebrow":"Selected moments","heading":"Gallery Image Rail","text":"A visual collection designed to break up the page and add depth.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Brand detail","text":"A closer look at the craft, decisions, and details that shape the final experience.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"In the studio","text":"Process, collaboration, and in-between moments that show how the work comes together.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built environment","text":"Photography that adds context, atmosphere, and a more human sense of the project.","label":"03","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch moment","text":"The finished work in the world, captured with enough detail to tell the story clearly.","label":"04","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const LocationPhotoCardsPremiumBlock=(props)=><Batch3Section {...props} variant="cards" family="locations"/>;
export const LocationPhotoCardsPremiumSchema={"type":"location_photo_cards_premium","title":"Location Photo Cards","description":"Image-rich locations section with a distinct cards composition.","defaults":{"type":"location_photo_cards_premium","theme":"auto","eyebrow":"Find us","heading":"Location Photo Cards","text":"Locations, contact points, and useful details in one visual section.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Main Studio","text":"123 Market Street · Mon–Fri, 9am–5pm. A central studio for consultations, planning, and project conversations.","label":"City Centre","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"North Office","text":"42 River Road · By appointment. A quieter meeting point for focused reviews and one-to-one sessions.","label":"North District","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Project Hub","text":"18 Harbour Lane · Flexible hours. Convenient for project workshops, handovers, and scheduled client visits.","label":"Waterfront","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Regional Desk","text":"7 Green Avenue · Mon–Thu. A local base for meetings, support, and ongoing project collaboration.","label":"Regional","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const LocationCitySpotlightPremiumBlock=(props)=><Batch3Section {...props} variant="spotlight" family="locations"/>;
export const LocationCitySpotlightPremiumSchema={"type":"location_city_spotlight_premium","title":"Location City Spotlight","description":"Image-rich locations section with a distinct spotlight composition.","defaults":{"type":"location_city_spotlight_premium","theme":"auto","eyebrow":"Find us","heading":"Location City Spotlight","text":"Locations, contact points, and useful details in one visual section.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Main Studio","text":"123 Market Street · Mon–Fri, 9am–5pm. A central studio for consultations, planning, and project conversations.","label":"City Centre","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"North Office","text":"42 River Road · By appointment. A quieter meeting point for focused reviews and one-to-one sessions.","label":"North District","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Project Hub","text":"18 Harbour Lane · Flexible hours. Convenient for project workshops, handovers, and scheduled client visits.","label":"Waterfront","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Regional Desk","text":"7 Green Avenue · Mon–Thu. A local base for meetings, support, and ongoing project collaboration.","label":"Regional","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const LocationMultiOfficePremiumBlock=(props)=><Batch3Section {...props} variant="offices" family="locations"/>;
export const LocationMultiOfficePremiumSchema={"type":"location_multi_office_premium","title":"Location Multi Office","description":"Image-rich locations section with a distinct offices composition.","defaults":{"type":"location_multi_office_premium","theme":"auto","eyebrow":"Find us","heading":"Location Multi Office","text":"Locations, contact points, and useful details in one visual section.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Main Studio","text":"123 Market Street · Mon–Fri, 9am–5pm. A central studio for consultations, planning, and project conversations.","label":"City Centre","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"North Office","text":"42 River Road · By appointment. A quieter meeting point for focused reviews and one-to-one sessions.","label":"North District","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Project Hub","text":"18 Harbour Lane · Flexible hours. Convenient for project workshops, handovers, and scheduled client visits.","label":"Waterfront","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Regional Desk","text":"7 Green Avenue · Mon–Thu. A local base for meetings, support, and ongoing project collaboration.","label":"Regional","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};

export const LocationVisualDirectoryPremiumBlock=(props)=><Batch3Section {...props} variant="directory" family="locations"/>;
export const LocationVisualDirectoryPremiumSchema={"type":"location_visual_directory_premium","title":"Location Visual Directory","description":"Image-rich locations section with a distinct directory composition.","defaults":{"type":"location_visual_directory_premium","theme":"auto","eyebrow":"Find us","heading":"Location Visual Directory","text":"Locations, contact points, and useful details in one visual section.","button_label":"Learn more","button_url":"#","secondary_label":"Contact us","secondary_url":"#","items":[{"title":"Main Studio","text":"123 Market Street · Mon–Fri, 9am–5pm. A central studio for consultations, planning, and project conversations.","label":"City Centre","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"North Office","text":"42 River Road · By appointment. A quieter meeting point for focused reviews and one-to-one sessions.","label":"North District","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Project Hub","text":"18 Harbour Lane · Flexible hours. Convenient for project workshops, handovers, and scheduled client visits.","label":"Waterfront","image_url":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=82"},{"title":"Regional Desk","text":"7 Green Avenue · Mon–Thu. A local base for meetings, support, and ongoing project collaboration.","label":"Regional","image_url":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=82"}]}};
