import React from "react";

const url=(value)=>String(value||"").trim();
const vars=(resolved)=>{
    const primary=String(resolved||"").toLowerCase()==="primary";
    return {
        "--b2-bg":primary?"var(--cosmic-local-bg-primary,var(--cosmic-bg-primary,var(--cosmic-primary,#243447)))":"var(--cosmic-local-bg-surface,var(--cosmic-bg-surface,#ffffff))",
        "--b2-surface":primary?"var(--cosmic-bg-primary-surface,var(--cosmic-surface,#30475E))":"#f7f7f5",
        "--b2-text":primary?"var(--cosmic-on-primary,#f8fafc)":"var(--cosmic-on-surface,#172033)",
        "--b2-muted":primary?"var(--cosmic-on-primary-muted,rgba(248,250,252,.76))":"var(--cosmic-on-surface-muted,#64748b)",
        "--b2-border":primary?"rgba(248,250,252,.18)":"rgba(15,23,42,.12)",
        "--b2-accent":"var(--cosmic-accent,#60A5FA)",
    };
};
const Img=({item})=>{const src=url(item?.image_url);return <div data-cosmic-luna-display="image" data-luna-target="image" className="b2-img">{src?<img src={src} alt="" className="h-full w-full object-cover pointer-events-none"/>:<div className="h-full min-h-[15rem] w-full bg-[var(--b2-surface)]"/>}</div>};
const Meta=({item,index})=><div className="b2-copy">
    <span className="b2-num">{item?.label || String(index+1).padStart(2,"0")}</span>
    <span data-cosmic-luna-display="text" data-cosmic-type="card-title" data-luna-target="heading" className="b2-title">{item?.title}</span>
    <span data-cosmic-luna-display="text" data-cosmic-type="card-body" data-luna-target="text" className="b2-text">{item?.text}</span>
</div>;

const Batch2Section=({block,variant,family})=>{
 const items=Array.isArray(block?.items)?block.items:[];
 const visibleItems=["split","featured","spotlight"].includes(variant)?items.slice(0,3):items;
 const resolved=block?.resolvedTheme||block?.theme||"light";
 return <section className={`group/repeatable-section cosmic-b2 b2-${family} b2-${variant}`} style={vars(resolved)}>
   <div className="b2-shell">
    <div className="b2-head">
      <span data-cosmic-luna-display="text" data-luna-target="label" className="b2-eyebrow">{block?.eyebrow}</span>
      <span data-cosmic-luna-display="text" data-cosmic-type="h2" data-luna-target="heading" className="b2-heading">{block?.heading}</span>
      <span data-cosmic-luna-display="text" data-cosmic-type="lead" data-luna-target="text" className="b2-intro">{block?.text}</span>
    </div>
    <div className="b2-grid">{visibleItems.map((item,index)=><article className="b2-card group relative" key={`${item?.title||"item"}-${index}`}><Img item={item}/><Meta item={item} index={index}/></article>)}</div>
    <div className="b2-actions">
      {block?.button_label&&<a href={block?.button_url||"#"} className="b2-primary" data-cosmic-luna-display="button" data-luna-target="button">{block.button_label}</a>}
      {block?.secondary_label&&<a href={block?.secondary_url||"#"} className="b2-secondary" data-cosmic-luna-display="button" data-luna-target="button">{block.secondary_label}</a>}
    </div>
   </div>
   <style>{`
    .cosmic-b2{background:var(--b2-bg);color:var(--b2-text);padding:7rem 1.75rem}
    .cosmic-b2 .b2-shell{width:100%;max-width:88rem;margin:0 auto}
    .cosmic-b2 .b2-head{max-width:50rem;margin-bottom:3.5rem}
    .cosmic-b2 .b2-eyebrow{display:block;font-size:.75rem;font-weight:500;letter-spacing:.28em;text-transform:uppercase;color:var(--b2-muted)}
    .cosmic-b2 .b2-heading{display:block;margin-top:1rem;font-size:clamp(2.4rem,5vw,4.6rem);line-height:.98;letter-spacing:-.045em;font-weight:700}
    .cosmic-b2 .b2-intro{display:block;margin-top:1.25rem;max-width:42rem;font-size:1.05rem;line-height:1.8;color:var(--b2-muted)}
    .cosmic-b2 .b2-grid{display:grid;gap:1.25rem}
    .cosmic-b2 .b2-card{position:relative;overflow:hidden;border:1px solid var(--b2-border);background:var(--b2-surface);border-radius:1.75rem}
    .cosmic-b2 .b2-img{overflow:hidden;min-height:15rem}
    .cosmic-b2 .b2-img img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .55s ease}
    .cosmic-b2 .b2-card:hover .b2-img img{transform:scale(1.035)}
    .cosmic-b2 .b2-copy{padding:1.5rem}
    .cosmic-b2 .b2-num{display:block;font-size:.72rem;letter-spacing:.18em;text-transform:uppercase;color:var(--b2-muted);margin-bottom:.75rem}
    .cosmic-b2 .b2-title{display:block;font-size:1.35rem;line-height:1.15;font-weight:700}
    .cosmic-b2 .b2-text{display:block;margin-top:.7rem;line-height:1.7;color:var(--b2-muted)}
    .cosmic-b2 .b2-actions{display:flex;gap:.8rem;flex-wrap:wrap;margin-top:2.25rem}
    .cosmic-b2 .b2-primary,.cosmic-b2 .b2-secondary{display:inline-flex;min-height:50px;align-items:center;justify-content:center;border-radius:100px;padding:.75rem 1.5rem;font-weight:700}
    .cosmic-b2 .b2-primary{background:var(--b2-text);color:var(--b2-bg)}
    .cosmic-b2 .b2-secondary{border:1px solid var(--b2-border);color:var(--b2-text)}
    .b2-grid .b2-grid,.b2-portrait .b2-grid,.b2-editorial .b2-grid,.b2-cards .b2-grid{grid-template-columns:repeat(4,minmax(0,1fr))}
    .b2-grid .b2-img,.b2-portrait .b2-img{aspect-ratio:4/5}
    .b2-split .b2-grid,.b2-featured .b2-grid,.b2-spotlight .b2-grid{grid-template-columns:1.25fr .75fr;align-items:stretch}
    .b2-split .b2-card:first-child,.b2-featured .b2-card:first-child,.b2-spotlight .b2-card:first-child{grid-row:1 / span 2;display:flex;flex-direction:column;height:100%}
    .b2-split .b2-card:first-child .b2-img,.b2-featured .b2-card:first-child .b2-img,.b2-spotlight .b2-card:first-child .b2-img{min-height:34rem;flex:1}
    .b2-overlay .b2-grid,.b2-background .b2-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
    .b2-overlay .b2-card,.b2-background .b2-card{min-height:28rem}
    .b2-overlay .b2-img,.b2-background .b2-img{position:absolute;inset:0;height:100%}
    .b2-overlay .b2-card:after,.b2-background .b2-card:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(2,6,23,.88),rgba(2,6,23,.08))}
    .b2-overlay .b2-copy,.b2-background .b2-copy{position:absolute;z-index:2;left:0;right:0;bottom:0;color:white}
    .b2-overlay .b2-text,.b2-background .b2-text,.b2-overlay .b2-num,.b2-background .b2-num{color:rgba(255,255,255,.72)}
    .b2-mosaic .b2-grid{grid-template-columns:repeat(12,minmax(0,1fr));grid-auto-rows:7rem}
    .b2-mosaic .b2-card{grid-column:span 5;grid-row:span 3}
    .b2-mosaic .b2-card:nth-child(2){grid-column:span 7;grid-row:span 3}
    .b2-mosaic .b2-img{position:absolute;inset:0;height:100%;opacity:.35}
    .b2-mosaic .b2-copy{position:relative;z-index:2}

    /* Testimonial wall keeps the editorial split, but both halves now carry purpose:
       portrait/image on one side and the full quote/meta hierarchy on the other. */
    .b2-wall .b2-grid{grid-template-columns:repeat(2,minmax(0,1fr));align-items:stretch}
    .b2-wall .b2-card{display:grid;grid-template-columns:minmax(10rem,.82fr) minmax(0,1.18fr);min-height:19rem}
    .b2-wall .b2-img{position:relative;inset:auto;height:100%;min-height:19rem;opacity:1}
    .b2-wall .b2-copy{position:relative;z-index:2;display:flex;min-width:0;flex-direction:column;justify-content:center;padding:2rem}
    .b2-wall .b2-num{margin-bottom:.9rem}
    .b2-wall .b2-title{font-size:1.45rem}
    .b2-wall .b2-text{margin-top:1rem;line-height:1.75}
    .b2-steps .b2-grid,.b2-timeline .b2-grid,.b2-journey .b2-grid,.b2-roadmap .b2-grid{grid-template-columns:1fr}
    .b2-steps .b2-card,.b2-timeline .b2-card,.b2-journey .b2-card,.b2-roadmap .b2-card{display:grid;grid-template-columns:minmax(17rem,.8fr) 1.2fr;align-items:center}
    .b2-steps .b2-card:nth-child(even),.b2-journey .b2-card:nth-child(even){grid-template-columns:1.2fr minmax(17rem,.8fr)}
    .b2-steps .b2-card:nth-child(even) .b2-img,.b2-journey .b2-card:nth-child(even) .b2-img{order:2}
    .b2-panels .b2-grid,.b2-floating .b2-grid{grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}
    .b2-panels .b2-card:nth-child(even),.b2-floating .b2-card:nth-child(even){margin-top:1.5rem}
    @media(max-width:900px){.b2-split .b2-card:first-child,.b2-featured .b2-card:first-child,.b2-spotlight .b2-card:first-child{grid-row:auto;height:auto}.b2-split .b2-card:first-child .b2-img,.b2-featured .b2-card:first-child .b2-img,.b2-spotlight .b2-card:first-child .b2-img{flex:none}.cosmic-b2{padding:5rem 1.25rem}.cosmic-b2 .b2-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.b2-mosaic .b2-grid{grid-auto-rows:auto}.b2-mosaic .b2-card{grid-column:auto;grid-row:auto;min-height:21rem}.b2-wall .b2-grid{grid-template-columns:1fr!important}.b2-wall .b2-card{grid-template-columns:minmax(11rem,.8fr) minmax(0,1.2fr);min-height:18rem}.b2-wall .b2-img{min-height:18rem}}
    @media(max-width:640px){.cosmic-b2{padding:4rem 1rem}.cosmic-b2 .b2-heading{font-size:clamp(2.2rem,12vw,3.4rem)}.cosmic-b2 .b2-grid{grid-template-columns:1fr!important}.b2-wall .b2-card{display:block;min-height:0}.b2-wall .b2-img{height:auto;min-height:15rem;aspect-ratio:16/10}.b2-wall .b2-copy{padding:1.5rem}.b2-steps .b2-card,.b2-timeline .b2-card,.b2-journey .b2-card,.b2-roadmap .b2-card,.b2-steps .b2-card:nth-child(even),.b2-journey .b2-card:nth-child(even){display:block}.b2-steps .b2-card:nth-child(even) .b2-img,.b2-journey .b2-card:nth-child(even) .b2-img{order:initial}.b2-panels .b2-card:nth-child(even),.b2-floating .b2-card:nth-child(even){margin-top:0}}
   `}</style>
 </section>
};

export const TeamPortraitEditorialPremiumBlock=(props)=><Batch2Section {...props} variant="portrait" family="team"/>;
export const TeamPortraitEditorialPremiumSchema={"type":"team_portrait_editorial_premium","title":"Team Portrait Editorial","description":"Image-rich team section with a distinct portrait composition.","defaults":{"type":"team_portrait_editorial_premium","theme":"auto","eyebrow":"Our team","heading":"Team Portrait Editorial","text":"Meet the people bringing strategy, design, and technology together.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Alex Morgan","text":"Creative Director shaping brand direction, visual systems, and the ideas that connect every touchpoint.","label":"Strategy & design","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Jamie Lee","text":"Product Designer turning complex journeys into clear, intuitive experiences people can use with confidence.","label":"Experience design","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Taylor Cruz","text":"Developer translating design into fast, reliable digital experiences with care for every interaction.","label":"Digital build","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Morgan Reyes","text":"Client Partner keeping strategy, communication, and delivery aligned from kickoff through launch.","label":"Delivery & growth","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TeamImageGridPremiumBlock=(props)=><Batch2Section {...props} variant="grid" family="team"/>;
export const TeamImageGridPremiumSchema={"type":"team_image_grid_premium","title":"Team Image Grid","description":"Image-rich team section with a distinct grid composition.","defaults":{"type":"team_image_grid_premium","theme":"auto","eyebrow":"Our team","heading":"Team Image Grid","text":"Meet the people bringing strategy, design, and technology together.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Alex Morgan","text":"Creative Director shaping brand direction, visual systems, and the ideas that connect every touchpoint.","label":"Strategy & design","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Jamie Lee","text":"Product Designer turning complex journeys into clear, intuitive experiences people can use with confidence.","label":"Experience design","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Taylor Cruz","text":"Developer translating design into fast, reliable digital experiences with care for every interaction.","label":"Digital build","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Morgan Reyes","text":"Client Partner keeping strategy, communication, and delivery aligned from kickoff through launch.","label":"Delivery & growth","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TeamLeadershipSplitPremiumBlock=(props)=><Batch2Section {...props} variant="split" family="team"/>;
export const TeamLeadershipSplitPremiumSchema={"type":"team_leadership_split_premium","title":"Team Leadership Split","description":"Image-rich team section with a distinct split composition.","defaults":{"type":"team_leadership_split_premium","theme":"auto","eyebrow":"Our team","heading":"Team Leadership Split","text":"Meet the people bringing strategy, design, and technology together.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Alex Morgan","text":"Creative Director shaping brand direction, visual systems, and the ideas that connect every touchpoint.","label":"Strategy & design","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Jamie Lee","text":"Product Designer turning complex journeys into clear, intuitive experiences people can use with confidence.","label":"Experience design","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Taylor Cruz","text":"Developer translating design into fast, reliable digital experiences with care for every interaction.","label":"Digital build","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Morgan Reyes","text":"Client Partner keeping strategy, communication, and delivery aligned from kickoff through launch.","label":"Delivery & growth","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TeamProfileOverlayPremiumBlock=(props)=><Batch2Section {...props} variant="overlay" family="team"/>;
export const TeamProfileOverlayPremiumSchema={"type":"team_profile_overlay_premium","title":"Team Profile Overlay","description":"Image-rich team section with a distinct overlay composition.","defaults":{"type":"team_profile_overlay_premium","theme":"auto","eyebrow":"Our team","heading":"Team Profile Overlay","text":"Meet the people bringing strategy, design, and technology together.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Alex Morgan","text":"Creative Director shaping brand direction, visual systems, and the ideas that connect every touchpoint.","label":"Strategy & design","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Jamie Lee","text":"Product Designer turning complex journeys into clear, intuitive experiences people can use with confidence.","label":"Experience design","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Taylor Cruz","text":"Developer translating design into fast, reliable digital experiences with care for every interaction.","label":"Digital build","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Morgan Reyes","text":"Client Partner keeping strategy, communication, and delivery aligned from kickoff through launch.","label":"Delivery & growth","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TeamPeopleMosaicPremiumBlock=(props)=><Batch2Section {...props} variant="mosaic" family="team"/>;
export const TeamPeopleMosaicPremiumSchema={"type":"team_people_mosaic_premium","title":"Team People Mosaic","description":"Image-rich team section with a distinct mosaic composition.","defaults":{"type":"team_people_mosaic_premium","theme":"auto","eyebrow":"Our team","heading":"Team People Mosaic","text":"Meet the people bringing strategy, design, and technology together.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Alex Morgan","text":"Creative Director shaping brand direction, visual systems, and the ideas that connect every touchpoint.","label":"Strategy & design","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Jamie Lee","text":"Product Designer turning complex journeys into clear, intuitive experiences people can use with confidence.","label":"Experience design","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Taylor Cruz","text":"Developer translating design into fast, reliable digital experiences with care for every interaction.","label":"Digital build","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Morgan Reyes","text":"Client Partner keeping strategy, communication, and delivery aligned from kickoff through launch.","label":"Delivery & growth","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TestimonialsPortraitCardsPremiumBlock=(props)=><Batch2Section {...props} variant="portrait" family="testimonials"/>;
export const TestimonialsPortraitCardsPremiumSchema={"type":"testimonials_portrait_cards_premium","title":"Testimonials Portrait Cards","description":"Image-rich testimonials section with a distinct portrait composition.","defaults":{"type":"testimonials_portrait_cards_premium","theme":"auto","eyebrow":"Client stories","heading":"Testimonials Portrait Cards","text":"Real feedback from teams we have worked alongside.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Jordan Lee","text":"The process felt clear from day one, and the final result gave our brand a much stronger presence.","label":"Founder, North Studio","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Avery Santos","text":"Thoughtful, fast, and easy to collaborate with. The new site feels much more like us.","label":"Director, Common Ground","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Riley Chen","text":"We launched with confidence and finally had a digital experience that matched the quality of our work.","label":"Partner, Field Notes","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Casey Morgan","text":"Every decision felt intentional and the handoff was incredibly smooth.","label":"Founder, Studio Nine","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TestimonialsFeaturedStoryPremiumBlock=(props)=><Batch2Section {...props} variant="featured" family="testimonials"/>;
export const TestimonialsFeaturedStoryPremiumSchema={"type":"testimonials_featured_story_premium","title":"Testimonials Featured Story","description":"Image-rich testimonials section with a distinct featured composition.","defaults":{"type":"testimonials_featured_story_premium","theme":"auto","eyebrow":"Client stories","heading":"Testimonials Featured Story","text":"Real feedback from teams we have worked alongside.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Jordan Lee","text":"The process felt clear from day one, and the final result gave our brand a much stronger presence.","label":"Founder, North Studio","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Avery Santos","text":"Thoughtful, fast, and easy to collaborate with. The new site feels much more like us.","label":"Director, Common Ground","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Riley Chen","text":"We launched with confidence and finally had a digital experience that matched the quality of our work.","label":"Partner, Field Notes","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Casey Morgan","text":"Every decision felt intentional and the handoff was incredibly smooth.","label":"Founder, Studio Nine","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TestimonialsImageWallPremiumBlock=(props)=><Batch2Section {...props} variant="wall" family="testimonials"/>;
export const TestimonialsImageWallPremiumSchema={"type":"testimonials_image_wall_premium","title":"Testimonials Image Wall","description":"Image-rich testimonials section with a distinct wall composition.","defaults":{"type":"testimonials_image_wall_premium","theme":"auto","eyebrow":"Client stories","heading":"Testimonials Image Wall","text":"Real feedback from teams we have worked alongside.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Jordan Lee","text":"The process felt clear from day one, and the final result gave our brand a much stronger presence.","label":"Founder, North Studio","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Avery Santos","text":"Thoughtful, fast, and easy to collaborate with. The new site feels much more like us.","label":"Director, Common Ground","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Riley Chen","text":"We launched with confidence and finally had a digital experience that matched the quality of our work.","label":"Partner, Field Notes","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Casey Morgan","text":"Every decision felt intentional and the handoff was incredibly smooth.","label":"Founder, Studio Nine","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TestimonialsEditorialQuotesPremiumBlock=(props)=><Batch2Section {...props} variant="editorial" family="testimonials"/>;
export const TestimonialsEditorialQuotesPremiumSchema={"type":"testimonials_editorial_quotes_premium","title":"Testimonials Editorial Quotes","description":"Image-rich testimonials section with a distinct editorial composition.","defaults":{"type":"testimonials_editorial_quotes_premium","theme":"auto","eyebrow":"Client stories","heading":"Testimonials Editorial Quotes","text":"Real feedback from teams we have worked alongside.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Jordan Lee","text":"The process felt clear from day one, and the final result gave our brand a much stronger presence.","label":"Founder, North Studio","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Avery Santos","text":"Thoughtful, fast, and easy to collaborate with. The new site feels much more like us.","label":"Director, Common Ground","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Riley Chen","text":"We launched with confidence and finally had a digital experience that matched the quality of our work.","label":"Partner, Field Notes","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Casey Morgan","text":"Every decision felt intentional and the handoff was incredibly smooth.","label":"Founder, Studio Nine","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const TestimonialsClientSpotlightPremiumBlock=(props)=><Batch2Section {...props} variant="spotlight" family="testimonials"/>;
export const TestimonialsClientSpotlightPremiumSchema={"type":"testimonials_client_spotlight_premium","title":"Testimonials Client Spotlight","description":"Image-rich testimonials section with a distinct spotlight composition.","defaults":{"type":"testimonials_client_spotlight_premium","theme":"auto","eyebrow":"Client stories","heading":"Testimonials Client Spotlight","text":"Real feedback from teams we have worked alongside.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Jordan Lee","text":"The process felt clear from day one, and the final result gave our brand a much stronger presence.","label":"Founder, North Studio","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Avery Santos","text":"Thoughtful, fast, and easy to collaborate with. The new site feels much more like us.","label":"Director, Common Ground","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Riley Chen","text":"We launched with confidence and finally had a digital experience that matched the quality of our work.","label":"Partner, Field Notes","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Casey Morgan","text":"Every decision felt intentional and the handoff was incredibly smooth.","label":"Founder, Studio Nine","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const ProcessVisualStepsPremiumBlock=(props)=><Batch2Section {...props} variant="steps" family="process"/>;
export const ProcessVisualStepsPremiumSchema={"type":"process_visual_steps_premium","title":"Process Visual Steps","description":"Image-rich process section with a distinct steps composition.","defaults":{"type":"process_visual_steps_premium","theme":"auto","eyebrow":"How we work","heading":"Process Visual Steps","text":"A simple process that keeps momentum high and decisions clear.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Discover","text":"We clarify goals, audience, and what success needs to look like.","label":"01","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Shape","text":"We turn the brief into a clear direction and practical plan.","label":"02","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Build","text":"We design, develop, and refine the experience with focus.","label":"03","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch","text":"We test, polish, and prepare everything for a confident release.","label":"04","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const ProcessImageTimelinePremiumBlock=(props)=><Batch2Section {...props} variant="timeline" family="process"/>;
export const ProcessImageTimelinePremiumSchema={"type":"process_image_timeline_premium","title":"Process Image Timeline","description":"Image-rich process section with a distinct timeline composition.","defaults":{"type":"process_image_timeline_premium","theme":"auto","eyebrow":"How we work","heading":"Process Image Timeline","text":"A simple process that keeps momentum high and decisions clear.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Discover","text":"We clarify goals, audience, and what success needs to look like.","label":"01","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Shape","text":"We turn the brief into a clear direction and practical plan.","label":"02","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Build","text":"We design, develop, and refine the experience with focus.","label":"03","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch","text":"We test, polish, and prepare everything for a confident release.","label":"04","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const ProcessNumberedPanelsPremiumBlock=(props)=><Batch2Section {...props} variant="panels" family="process"/>;
export const ProcessNumberedPanelsPremiumSchema={"type":"process_numbered_panels_premium","title":"Process Numbered Panels","description":"Image-rich process section with a distinct panels composition.","defaults":{"type":"process_numbered_panels_premium","theme":"auto","eyebrow":"How we work","heading":"Process Numbered Panels","text":"A simple process that keeps momentum high and decisions clear.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Discover","text":"We clarify goals, audience, and what success needs to look like.","label":"01","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Shape","text":"We turn the brief into a clear direction and practical plan.","label":"02","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Build","text":"We design, develop, and refine the experience with focus.","label":"03","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch","text":"We test, polish, and prepare everything for a confident release.","label":"04","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const ProcessEditorialJourneyPremiumBlock=(props)=><Batch2Section {...props} variant="journey" family="process"/>;
export const ProcessEditorialJourneyPremiumSchema={"type":"process_editorial_journey_premium","title":"Process Editorial Journey","description":"Image-rich process section with a distinct journey composition.","defaults":{"type":"process_editorial_journey_premium","theme":"auto","eyebrow":"How we work","heading":"Process Editorial Journey","text":"A simple process that keeps momentum high and decisions clear.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Discover","text":"We clarify goals, audience, and what success needs to look like.","label":"01","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Shape","text":"We turn the brief into a clear direction and practical plan.","label":"02","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Build","text":"We design, develop, and refine the experience with focus.","label":"03","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch","text":"We test, polish, and prepare everything for a confident release.","label":"04","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const ProcessMediaRoadmapPremiumBlock=(props)=><Batch2Section {...props} variant="roadmap" family="process"/>;
export const ProcessMediaRoadmapPremiumSchema={"type":"process_media_roadmap_premium","title":"Process Media Roadmap","description":"Image-rich process section with a distinct roadmap composition.","defaults":{"type":"process_media_roadmap_premium","theme":"auto","eyebrow":"How we work","heading":"Process Media Roadmap","text":"A simple process that keeps momentum high and decisions clear.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Discover","text":"We clarify goals, audience, and what success needs to look like.","label":"01","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Shape","text":"We turn the brief into a clear direction and practical plan.","label":"02","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Build","text":"We design, develop, and refine the experience with focus.","label":"03","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"},{"title":"Launch","text":"We test, polish, and prepare everything for a confident release.","label":"04","image_url":"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1400&q=82"}]}};

export const CtaImageSplitPremiumBlock=(props)=><Batch2Section {...props} variant="split" family="cta"/>;
export const CtaImageSplitPremiumSchema={"type":"cta_image_split_premium","title":"CTA Image Split","description":"Image-rich cta section with a distinct split composition.","defaults":{"type":"cta_image_split_premium","theme":"auto","eyebrow":"Ready when you are","heading":"CTA Image Split","text":"A clear next step for teams ready to move forward.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Start with a conversation","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Explore our work","text":"See how we approach design, development, and digital delivery.","label":"Selected work","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Plan your next move","text":"Get a clearer path from idea to launch.","label":"Get started","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"}]}};

export const CtaBackgroundMediaPremiumBlock=(props)=><Batch2Section {...props} variant="background" family="cta"/>;
export const CtaBackgroundMediaPremiumSchema={"type":"cta_background_media_premium","title":"CTA Background Media","description":"Image-rich cta section with a distinct background composition.","defaults":{"type":"cta_background_media_premium","theme":"auto","eyebrow":"Ready when you are","heading":"CTA Background Media","text":"A clear next step for teams ready to move forward.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Start with a conversation","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Explore our work","text":"See how we approach design, development, and digital delivery.","label":"Selected work","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Plan your next move","text":"Get a clearer path from idea to launch.","label":"Get started","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"}]}};

export const CtaFloatingPanelPremiumBlock=(props)=><Batch2Section {...props} variant="floating" family="cta"/>;
export const CtaFloatingPanelPremiumSchema={"type":"cta_floating_panel_premium","title":"CTA Floating Panel","description":"Image-rich cta section with a distinct floating composition.","defaults":{"type":"cta_floating_panel_premium","theme":"auto","eyebrow":"Ready when you are","heading":"CTA Floating Panel","text":"A clear next step for teams ready to move forward.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Start with a conversation","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Explore our work","text":"See how we approach design, development, and digital delivery.","label":"Selected work","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Plan your next move","text":"Get a clearer path from idea to launch.","label":"Get started","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"}]}};

export const CtaEditorialBannerPremiumBlock=(props)=><Batch2Section {...props} variant="editorial" family="cta"/>;
export const CtaEditorialBannerPremiumSchema={"type":"cta_editorial_banner_premium","title":"CTA Editorial Banner","description":"Image-rich cta section with a distinct editorial composition.","defaults":{"type":"cta_editorial_banner_premium","theme":"auto","eyebrow":"Ready when you are","heading":"CTA Editorial Banner","text":"A clear next step for teams ready to move forward.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Start with a conversation","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Explore our work","text":"See how we approach design, development, and digital delivery.","label":"Selected work","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Plan your next move","text":"Get a clearer path from idea to launch.","label":"Get started","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"}]}};

export const CtaMediaCardsPremiumBlock=(props)=><Batch2Section {...props} variant="cards" family="cta"/>;
export const CtaMediaCardsPremiumSchema={"type":"cta_media_cards_premium","title":"CTA Media Cards","description":"Image-rich cta section with a distinct cards composition.","defaults":{"type":"cta_media_cards_premium","theme":"auto","eyebrow":"Ready when you are","heading":"CTA Media Cards","text":"A clear next step for teams ready to move forward.","button_label":"Start a conversation","button_url":"#","secondary_label":"View work","secondary_url":"#","items":[{"title":"Start with a conversation","text":"Tell us what you are planning and where you need support.","label":"Project enquiry","image_url":"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=82"},{"title":"Explore our work","text":"See how we approach design, development, and digital delivery.","label":"Selected work","image_url":"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=82"},{"title":"Plan your next move","text":"Get a clearer path from idea to launch.","label":"Get started","image_url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1400&q=82"}]}};
