import React from "react";

const escUrl=(value)=>String(value||"").trim();
const themeVars=(resolved)=>{
    const primary=String(resolved||"").toLowerCase()==="primary";
    return {
        "--x-bg":primary?"var(--cosmic-local-bg-primary,var(--cosmic-bg-primary,var(--cosmic-primary,#243447)))":"var(--cosmic-local-bg-surface,var(--cosmic-bg-surface,#ffffff))",
        "--x-surface":primary?"var(--cosmic-bg-primary-surface,var(--cosmic-surface,#30475E))":"#f7f7f5",
        "--x-text":primary?"var(--cosmic-on-primary,#f8fafc)":"var(--cosmic-on-surface,#172033)",
        "--x-muted":primary?"var(--cosmic-on-primary-muted,rgba(248,250,252,.76))":"var(--cosmic-on-surface-muted,#64748b)",
        "--x-border":primary?"rgba(248,250,252,.18)":"rgba(15,23,42,.12)",
        "--x-accent":"var(--cosmic-accent,#60A5FA)",
    };
};
const CardImage=({item,className=""})=><div data-cosmic-luna-display="image" data-luna-target="image" className={`x-img ${className}`}><img src={escUrl(item?.image_url)} alt="" className="h-full w-full object-cover pointer-events-none"/></div>;
const Copy=({item,index})=><div className="x-card-copy"><span className="x-index">{String(index+1).padStart(2,"0")}</span><span data-cosmic-luna-display="text" data-cosmic-type="card-title" data-luna-target="heading" className="x-title">{item?.title}</span><span data-cosmic-luna-display="text" data-cosmic-type="card-body" data-luna-target="text" className="x-text">{item?.text}</span></div>;

const ExpansionSection=({block,variant})=>{
 const items=Array.isArray(block?.items)?block.items:[];
 const resolved=block?.resolvedTheme||block?.theme||"light";
 return <section className={`group/repeatable-section cosmic-image-rich x-${variant}`} style={themeVars(resolved)}>
   <div className="x-shell">
    <div className="x-head">
      <span data-cosmic-luna-display="text" data-luna-target="label" className="x-eyebrow">{block?.eyebrow}</span>
      <span data-cosmic-luna-display="text" data-cosmic-type="h2" data-luna-target="heading" className="x-heading">{block?.heading}</span>
      <span data-cosmic-luna-display="text" data-cosmic-type="lead" data-luna-target="text" className="x-intro">{block?.text}</span>
    </div>
    <div className="x-grid">{items.map((item,index)=><article className="x-card group relative" key={`${item?.title||"item"}-${index}`}><CardImage item={item}/><Copy item={item} index={index}/></article>)}</div>
    {block?.button_label&&<a className="x-cta" href={block?.button_url||"#"} data-cosmic-luna-display="button" data-luna-target="button">{block.button_label}</a>}
   </div>
   <style>{`
    .cosmic-image-rich{background:var(--x-bg);color:var(--x-text);padding:7rem 1.75rem}
    .cosmic-image-rich .x-shell{width:100%;max-width:88rem;margin:0 auto}
    .cosmic-image-rich .x-head{max-width:48rem;margin-bottom:3.5rem}
    .cosmic-image-rich .x-eyebrow{display:block;font-size:.75rem;font-weight:600;letter-spacing:.28em;text-transform:uppercase;color:var(--x-muted)}
    .cosmic-image-rich .x-heading{display:block;margin-top:1rem;font-size:clamp(2.4rem,5vw,4.75rem);line-height:.98;letter-spacing:-.045em;font-weight:700}
    .cosmic-image-rich .x-intro{display:block;margin-top:1.25rem;max-width:42rem;font-size:1.05rem;line-height:1.8;color:var(--x-muted)}
    .cosmic-image-rich .x-grid{display:grid;gap:1.25rem}
    .cosmic-image-rich .x-card{position:relative;overflow:hidden;border:1px solid var(--x-border);background:var(--x-surface);border-radius:1.75rem}
    .cosmic-image-rich .x-img{overflow:hidden;min-height:15rem}
    .cosmic-image-rich .x-img img{transition:transform .55s ease}
    .cosmic-image-rich .x-card:hover .x-img img{transform:scale(1.035)}
    .cosmic-image-rich .x-card-copy{padding:1.5rem}
    .cosmic-image-rich .x-index{display:block;font-size:.72rem;letter-spacing:.2em;color:var(--x-muted);margin-bottom:.75rem}
    .cosmic-image-rich .x-title{display:block;font-size:1.35rem;line-height:1.15;font-weight:700}
    .cosmic-image-rich .x-text{display:block;margin-top:.7rem;color:var(--x-muted);line-height:1.7}
    .cosmic-image-rich .x-cta{display:inline-flex;margin-top:2rem;min-height:50px;align-items:center;justify-content:center;border-radius:100px;padding:.75rem 1.5rem;background:var(--x-text);color:var(--x-bg);font-weight:700}
    .x-trio .x-grid,.x-spotlight .x-grid,.x-editorial .x-grid{grid-template-columns:repeat(3,minmax(0,1fr))}
    .x-trio .x-card:first-child,.x-spotlight .x-card:first-child{grid-column:span 2}.x-trio .x-card:first-child .x-img,.x-spotlight .x-card:first-child .x-img{min-height:25rem}
    .x-overlay .x-grid,.x-cinematic .x-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
    .x-overlay .x-card,.x-cinematic .x-card{min-height:29rem}.x-overlay .x-img,.x-cinematic .x-img{position:absolute;inset:0;height:100%}
    .x-overlay .x-card:after,.x-cinematic .x-card:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(2,6,23,.84),rgba(2,6,23,.08))}
    .x-overlay .x-card-copy,.x-cinematic .x-card-copy{position:absolute;z-index:2;left:0;right:0;bottom:0;color:white}.x-overlay .x-card-copy .x-text,.x-cinematic .x-card-copy .x-text,.x-overlay .x-index,.x-cinematic .x-index{color:rgba(255,255,255,.72)}
    .x-rows .x-grid,.x-steps .x-grid,.x-journey .x-grid{grid-template-columns:1fr}.x-rows .x-card,.x-steps .x-card,.x-journey .x-card{display:grid;grid-template-columns:minmax(18rem,.8fr) 1.2fr;align-items:center}.x-rows .x-card:nth-child(even),.x-journey .x-card:nth-child(even){grid-template-columns:1.2fr minmax(18rem,.8fr)}.x-rows .x-card:nth-child(even) .x-img,.x-journey .x-card:nth-child(even) .x-img{order:2}
    .x-horizontal .x-grid,.x-numbered .x-grid,.x-index .x-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.x-horizontal .x-img,.x-numbered .x-img,.x-index .x-img{aspect-ratio:4/5}
    .x-mosaic .x-grid,.x-asymmetric .x-grid,.x-collage .x-grid{grid-template-columns:repeat(12,minmax(0,1fr));grid-auto-rows:7rem}.x-mosaic .x-card,.x-asymmetric .x-card,.x-collage .x-card{grid-column:span 5;grid-row:span 3}.x-mosaic .x-card:nth-child(2),.x-asymmetric .x-card:nth-child(2),.x-collage .x-card:nth-child(2){grid-column:span 7;grid-row:span 3}.x-mosaic .x-card:nth-child(3),.x-asymmetric .x-card:nth-child(3),.x-collage .x-card:nth-child(3){grid-column:span 7}.x-mosaic .x-card:nth-child(4),.x-asymmetric .x-card:nth-child(4),.x-collage .x-card:nth-child(4){grid-column:span 5}.x-mosaic .x-img,.x-asymmetric .x-img,.x-collage .x-img{position:absolute;inset:0;height:100%;opacity:.32}.x-mosaic .x-card-copy,.x-asymmetric .x-card-copy,.x-collage .x-card-copy{position:relative;z-index:2}
    .x-split .x-grid,.x-showcase .x-grid,.x-manifesto .x-grid,.x-founder .x-grid{grid-template-columns:repeat(2,minmax(0,1fr));align-items:stretch}.x-split .x-card:first-child,.x-showcase .x-card:first-child,.x-manifesto .x-card:first-child,.x-founder .x-card:first-child{grid-row:1 / span 2;display:flex;flex-direction:column;height:100%}.x-split .x-card:first-child .x-img,.x-showcase .x-card:first-child .x-img,.x-manifesto .x-card:first-child .x-img,.x-founder .x-card:first-child .x-img{min-height:32rem;flex:1}
    .x-stack .x-grid,.x-panels .x-grid{grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}.x-stack .x-card:nth-child(even),.x-panels .x-card:nth-child(even){margin-top:1.75rem}
        .x-mosaic .x-copy,.x-asymmetric .x-copy,.x-collage .x-copy{display:flex;min-height:100%;flex-direction:column;justify-content:flex-end;padding:1.75rem;background:linear-gradient(to top,color-mix(in srgb,var(--x-surface,var(--cosmic-bg-primary-surface,#30475E)) 88%,transparent),transparent 78%)}
@media(max-width:900px){.x-split .x-card:first-child,.x-showcase .x-card:first-child,.x-manifesto .x-card:first-child,.x-founder .x-card:first-child{grid-row:auto;height:auto}.x-split .x-card:first-child .x-img,.x-showcase .x-card:first-child .x-img,.x-manifesto .x-card:first-child .x-img,.x-founder .x-card:first-child .x-img{flex:none}.cosmic-image-rich{padding:5rem 1.25rem}.x-trio .x-grid,.x-spotlight .x-grid,.x-editorial .x-grid,.x-overlay .x-grid,.x-cinematic .x-grid,.x-horizontal .x-grid,.x-numbered .x-grid,.x-index .x-grid,.x-split .x-grid,.x-showcase .x-grid,.x-manifesto .x-grid,.x-founder .x-grid,.x-stack .x-grid,.x-panels .x-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.x-trio .x-card:first-child,.x-spotlight .x-card:first-child{grid-column:auto}.x-mosaic .x-grid,.x-asymmetric .x-grid,.x-collage .x-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));grid-auto-rows:auto}.x-mosaic .x-card,.x-asymmetric .x-card,.x-collage .x-card,.x-mosaic .x-card:nth-child(n),.x-asymmetric .x-card:nth-child(n),.x-collage .x-card:nth-child(n){grid-column:auto;grid-row:auto;min-height:22rem}}
    @media(max-width:640px){.cosmic-image-rich{padding:4rem 1rem}.cosmic-image-rich .x-heading{font-size:clamp(2.2rem,12vw,3.4rem)}.cosmic-image-rich .x-grid,.x-trio .x-grid,.x-spotlight .x-grid,.x-editorial .x-grid,.x-overlay .x-grid,.x-cinematic .x-grid,.x-horizontal .x-grid,.x-numbered .x-grid,.x-index .x-grid,.x-split .x-grid,.x-showcase .x-grid,.x-manifesto .x-grid,.x-founder .x-grid,.x-stack .x-grid,.x-panels .x-grid,.x-mosaic .x-grid,.x-asymmetric .x-grid,.x-collage .x-grid{grid-template-columns:1fr}.x-rows .x-card,.x-steps .x-card,.x-journey .x-card,.x-rows .x-card:nth-child(even),.x-journey .x-card:nth-child(even){display:block}.x-rows .x-card:nth-child(even) .x-img,.x-journey .x-card:nth-child(even) .x-img{order:initial}.x-stack .x-card:nth-child(even),.x-panels .x-card:nth-child(even){margin-top:0}}
   
    .x-card, .x-copy{min-width:0}`}</style>
 </section>
};

export const ServicesImageTrioPremiumBlock=(props)=><ExpansionSection {...props} variant="trio"/>;
export const ServicesImageTrioPremiumSchema={"type":"services_image_trio_premium","title":"Services Image Trio","description":"Image-rich services section with a distinct trio composition.","defaults":{"type":"services_image_trio_premium","theme":"auto","eyebrow":"Services","heading":"Services Image Trio","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Strategy","text":"Clear direction for the work that matters most.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Design","text":"Thoughtful experiences shaped around real people.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Delivery","text":"Reliable execution from first concept to launch.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Growth","text":"Practical improvements that keep compounding.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesOverlayGridPremiumBlock=(props)=><ExpansionSection {...props} variant="overlay"/>;
export const ServicesOverlayGridPremiumSchema={"type":"services_overlay_grid_premium","title":"Services Overlay Grid","description":"Image-rich services section with a distinct overlay composition.","defaults":{"type":"services_overlay_grid_premium","theme":"auto","eyebrow":"Services","heading":"Services Overlay Grid","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Strategy","text":"Clear direction for the work that matters most.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Design","text":"Thoughtful experiences shaped around real people.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Delivery","text":"Reliable execution from first concept to launch.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Growth","text":"Practical improvements that keep compounding.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesEditorialRowsPremiumBlock=(props)=><ExpansionSection {...props} variant="rows"/>;
export const ServicesEditorialRowsPremiumSchema={"type":"services_editorial_rows_premium","title":"Services Editorial Rows","description":"Image-rich services section with a distinct rows composition.","defaults":{"type":"services_editorial_rows_premium","theme":"auto","eyebrow":"Services","heading":"Services Editorial Rows","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Strategy","text":"Clear direction for the work that matters most.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Design","text":"Thoughtful experiences shaped around real people.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Delivery","text":"Reliable execution from first concept to launch.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Growth","text":"Practical improvements that keep compounding.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesHorizontalMediaPremiumBlock=(props)=><ExpansionSection {...props} variant="horizontal"/>;
export const ServicesHorizontalMediaPremiumSchema={"type":"services_horizontal_media_premium","title":"Services Horizontal Media","description":"Image-rich services section with a distinct horizontal composition.","defaults":{"type":"services_horizontal_media_premium","theme":"auto","eyebrow":"Services","heading":"Services Horizontal Media","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Strategy","text":"Clear direction for the work that matters most.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Design","text":"Thoughtful experiences shaped around real people.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Delivery","text":"Reliable execution from first concept to launch.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Growth","text":"Practical improvements that keep compounding.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesNumberedImagesPremiumBlock=(props)=><ExpansionSection {...props} variant="numbered"/>;
export const ServicesNumberedImagesPremiumSchema={"type":"services_numbered_images_premium","title":"Services Numbered Images","description":"Image-rich services section with a distinct numbered composition.","defaults":{"type":"services_numbered_images_premium","theme":"auto","eyebrow":"Services","heading":"Services Numbered Images","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Strategy","text":"Clear direction for the work that matters most.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Design","text":"Thoughtful experiences shaped around real people.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Delivery","text":"Reliable execution from first concept to launch.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Growth","text":"Practical improvements that keep compounding.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesMosaicMediaPremiumBlock=(props)=><ExpansionSection {...props} variant="mosaic"/>;
export const ServicesMosaicMediaPremiumSchema={"type":"services_mosaic_media_premium","title":"Services Mosaic Media","description":"Image-rich services section with a distinct mosaic composition.","defaults":{"type":"services_mosaic_media_premium","theme":"auto","eyebrow":"Services","heading":"Services Mosaic Media","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Strategy","text":"Clear direction for the work that matters most.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Design","text":"Thoughtful experiences shaped around real people.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Delivery","text":"Reliable execution from first concept to launch.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Growth","text":"Practical improvements that keep compounding.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesVisualSplitPremiumBlock=(props)=><ExpansionSection {...props} variant="split"/>;
export const FeaturesVisualSplitPremiumSchema={"type":"features_visual_split_premium","title":"Features Visual Split","description":"Image-rich features section with a distinct split composition.","defaults":{"type":"features_visual_split_premium","theme":"auto","eyebrow":"Features","heading":"Features Visual Split","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Built for clarity","text":"A focused experience with less friction and more confidence.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Made to adapt","text":"Flexible foundations that evolve with your needs.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to perform","text":"Fast, responsive, and considered across every screen.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Easy to manage","text":"Simple content patterns your team can keep current.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesImageStackPremiumBlock=(props)=><ExpansionSection {...props} variant="stack"/>;
export const FeaturesImageStackPremiumSchema={"type":"features_image_stack_premium","title":"Features Image Stack","description":"Image-rich features section with a distinct stack composition.","defaults":{"type":"features_image_stack_premium","theme":"auto","eyebrow":"Features","heading":"Features Image Stack","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Built for clarity","text":"A focused experience with less friction and more confidence.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Made to adapt","text":"Flexible foundations that evolve with your needs.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to perform","text":"Fast, responsive, and considered across every screen.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Easy to manage","text":"Simple content patterns your team can keep current.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesSpotlightCardsPremiumBlock=(props)=><ExpansionSection {...props} variant="spotlight"/>;
export const FeaturesSpotlightCardsPremiumSchema={"type":"features_spotlight_cards_premium","title":"Features Spotlight Cards","description":"Image-rich features section with a distinct spotlight composition.","defaults":{"type":"features_spotlight_cards_premium","theme":"auto","eyebrow":"Features","heading":"Features Spotlight Cards","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Built for clarity","text":"A focused experience with less friction and more confidence.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Made to adapt","text":"Flexible foundations that evolve with your needs.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to perform","text":"Fast, responsive, and considered across every screen.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Easy to manage","text":"Simple content patterns your team can keep current.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesMediaStepsPremiumBlock=(props)=><ExpansionSection {...props} variant="steps"/>;
export const FeaturesMediaStepsPremiumSchema={"type":"features_media_steps_premium","title":"Features Media Steps","description":"Image-rich features section with a distinct steps composition.","defaults":{"type":"features_media_steps_premium","theme":"auto","eyebrow":"Features","heading":"Features Media Steps","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Built for clarity","text":"A focused experience with less friction and more confidence.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Made to adapt","text":"Flexible foundations that evolve with your needs.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to perform","text":"Fast, responsive, and considered across every screen.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Easy to manage","text":"Simple content patterns your team can keep current.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesAsymmetricMediaPremiumBlock=(props)=><ExpansionSection {...props} variant="asymmetric"/>;
export const FeaturesAsymmetricMediaPremiumSchema={"type":"features_asymmetric_media_premium","title":"Features Asymmetric Media","description":"Image-rich features section with a distinct asymmetric composition.","defaults":{"type":"features_asymmetric_media_premium","theme":"auto","eyebrow":"Features","heading":"Features Asymmetric Media","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Built for clarity","text":"A focused experience with less friction and more confidence.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Made to adapt","text":"Flexible foundations that evolve with your needs.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Ready to perform","text":"Fast, responsive, and considered across every screen.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Easy to manage","text":"Simple content patterns your team can keep current.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioCinematicGridPremiumBlock=(props)=><ExpansionSection {...props} variant="cinematic"/>;
export const PortfolioCinematicGridPremiumSchema={"type":"portfolio_cinematic_grid_premium","title":"Portfolio Cinematic Grid","description":"Image-rich portfolio section with a distinct cinematic composition.","defaults":{"type":"portfolio_cinematic_grid_premium","theme":"auto","eyebrow":"Portfolio","heading":"Portfolio Cinematic Grid","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"North House","text":"A warm identity and digital home for a growing hospitality brand.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Field Notes","text":"An editorial commerce experience built around discovery.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Common Ground","text":"A community-first platform with a calm visual system.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Studio Nine","text":"A confident portfolio designed to let the work lead.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioEditorialCardsPremiumBlock=(props)=><ExpansionSection {...props} variant="editorial"/>;
export const PortfolioEditorialCardsPremiumSchema={"type":"portfolio_editorial_cards_premium","title":"Portfolio Editorial Cards","description":"Image-rich portfolio section with a distinct editorial composition.","defaults":{"type":"portfolio_editorial_cards_premium","theme":"auto","eyebrow":"Portfolio","heading":"Portfolio Editorial Cards","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"North House","text":"A warm identity and digital home for a growing hospitality brand.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Field Notes","text":"An editorial commerce experience built around discovery.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Common Ground","text":"A community-first platform with a calm visual system.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Studio Nine","text":"A confident portfolio designed to let the work lead.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioProjectPanelsPremiumBlock=(props)=><ExpansionSection {...props} variant="panels"/>;
export const PortfolioProjectPanelsPremiumSchema={"type":"portfolio_project_panels_premium","title":"Portfolio Project Panels","description":"Image-rich portfolio section with a distinct panels composition.","defaults":{"type":"portfolio_project_panels_premium","theme":"auto","eyebrow":"Portfolio","heading":"Portfolio Project Panels","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"North House","text":"A warm identity and digital home for a growing hospitality brand.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Field Notes","text":"An editorial commerce experience built around discovery.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Common Ground","text":"A community-first platform with a calm visual system.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Studio Nine","text":"A confident portfolio designed to let the work lead.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioImageIndexPremiumBlock=(props)=><ExpansionSection {...props} variant="index"/>;
export const PortfolioImageIndexPremiumSchema={"type":"portfolio_image_index_premium","title":"Portfolio Image Index","description":"Image-rich portfolio section with a distinct index composition.","defaults":{"type":"portfolio_image_index_premium","theme":"auto","eyebrow":"Portfolio","heading":"Portfolio Image Index","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"North House","text":"A warm identity and digital home for a growing hospitality brand.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Field Notes","text":"An editorial commerce experience built around discovery.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Common Ground","text":"A community-first platform with a calm visual system.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Studio Nine","text":"A confident portfolio designed to let the work lead.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioSplitShowcasePremiumBlock=(props)=><ExpansionSection {...props} variant="showcase"/>;
export const PortfolioSplitShowcasePremiumSchema={"type":"portfolio_split_showcase_premium","title":"Portfolio Split Showcase","description":"Image-rich portfolio section with a distinct showcase composition.","defaults":{"type":"portfolio_split_showcase_premium","theme":"auto","eyebrow":"Portfolio","heading":"Portfolio Split Showcase","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"North House","text":"A warm identity and digital home for a growing hospitality brand.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Field Notes","text":"An editorial commerce experience built around discovery.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Common Ground","text":"A community-first platform with a calm visual system.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Studio Nine","text":"A confident portfolio designed to let the work lead.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const AboutStoryCollagePremiumBlock=(props)=><ExpansionSection {...props} variant="collage"/>;
export const AboutStoryCollagePremiumSchema={"type":"about_story_collage_premium","title":"About Story Collage","description":"Image-rich about section with a distinct collage composition.","defaults":{"type":"about_story_collage_premium","theme":"auto","eyebrow":"About","heading":"About Story Collage","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Where we started","text":"A small idea grew through close collaboration and useful work.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"What guides us","text":"Clarity, craft, and care shape the decisions we make.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"How we work","text":"We stay close to the problem and keep the process practical.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Where we are going","text":"Building durable experiences that remain useful over time.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const AboutImageManifestoPremiumBlock=(props)=><ExpansionSection {...props} variant="manifesto"/>;
export const AboutImageManifestoPremiumSchema={"type":"about_image_manifesto_premium","title":"About Image Manifesto","description":"Image-rich about section with a distinct manifesto composition.","defaults":{"type":"about_image_manifesto_premium","theme":"auto","eyebrow":"About","heading":"About Image Manifesto","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Where we started","text":"A small idea grew through close collaboration and useful work.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"What guides us","text":"Clarity, craft, and care shape the decisions we make.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"How we work","text":"We stay close to the problem and keep the process practical.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Where we are going","text":"Building durable experiences that remain useful over time.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const AboutFounderVisualPremiumBlock=(props)=><ExpansionSection {...props} variant="founder"/>;
export const AboutFounderVisualPremiumSchema={"type":"about_founder_visual_premium","title":"About Founder Visual","description":"Image-rich about section with a distinct founder composition.","defaults":{"type":"about_founder_visual_premium","theme":"auto","eyebrow":"About","heading":"About Founder Visual","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Where we started","text":"A small idea grew through close collaboration and useful work.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"What guides us","text":"Clarity, craft, and care shape the decisions we make.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"How we work","text":"We stay close to the problem and keep the process practical.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Where we are going","text":"Building durable experiences that remain useful over time.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const AboutJourneyGalleryPremiumBlock=(props)=><ExpansionSection {...props} variant="journey"/>;
export const AboutJourneyGalleryPremiumSchema={"type":"about_journey_gallery_premium","title":"About Journey Gallery","description":"Image-rich about section with a distinct journey composition.","defaults":{"type":"about_journey_gallery_premium","theme":"auto","eyebrow":"About","heading":"About Journey Gallery","text":"A visual section designed to give the page more depth while keeping content clear and easy to scan.","button_label":"Learn more","button_url":"#","items":[{"title":"Where we started","text":"A small idea grew through close collaboration and useful work.","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"What guides us","text":"Clarity, craft, and care shape the decisions we make.","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"How we work","text":"We stay close to the problem and keep the process practical.","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Where we are going","text":"Building durable experiences that remain useful over time.","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};
