import React from "react";

import { sparkTw } from "../Shared/sparkTailwindRuntime";
const mediaUrl=(value)=>String(value||"").trim();
const themeVars=(resolved)=>{
    const primary=String(resolved||"").toLowerCase()==="primary";
    return {
        "--b4-bg":primary?"var(--cosmic-local-bg-primary,var(--cosmic-bg-primary,var(--cosmic-primary,#243447)))":"var(--cosmic-local-bg-surface,var(--cosmic-bg-surface,#ffffff))",
        "--b4-surface":primary?"var(--cosmic-local-bg-primary-surface,var(--cosmic-bg-primary-surface,var(--cosmic-surface,#30475E)))":"var(--cosmic-local-bg-surface,var(--cosmic-bg-surface,#f7f7f5))",
        "--b4-text":primary?"var(--cosmic-local-on-primary,var(--cosmic-on-primary,#f8fafc))":"var(--cosmic-local-on-surface,var(--cosmic-on-surface,#172033))",
        "--b4-muted":primary?"var(--cosmic-local-on-primary-muted,var(--cosmic-on-primary-muted,rgba(248,250,252,.76)))":"var(--cosmic-local-on-surface-muted,var(--cosmic-on-surface-muted,#64748b))",
        "--b4-border":primary?"rgba(248,250,252,.18)":"rgba(15,23,42,.12)",
        "--b4-accent":"var(--cosmic-accent,#60A5FA)",
    };
};
const IndustrySection=({block,variant,family})=>{
 const items=Array.isArray(block?.items)?block.items:[];
 const resolved=block?.resolvedTheme||block?.theme||"light";
 return <section className={sparkTw(block, "auto_1", `group/repeatable-section cosmic-b4 b4-${family} b4-${variant}`)} style={themeVars(resolved)}>
   <div className={sparkTw(block, "auto_2", "b4-shell")}>
      <div className={sparkTw(block, "auto_3", "b4-head")}>
        <span data-cosmic-luna-display="text" data-luna-target="label" className={sparkTw(block, "auto_4", "b4-eyebrow")}>{block?.eyebrow}</span>
        <span data-cosmic-luna-display="text" data-cosmic-type="h2" data-luna-target="heading" className={sparkTw(block, "auto_5", "b4-heading")}>{block?.heading}</span>
        <span data-cosmic-luna-display="text" data-cosmic-type="lead" data-luna-target="text" className={sparkTw(block, "auto_6", "b4-intro")}>{block?.text}</span>
      </div>
      <div className={sparkTw(block, "auto_7", "b4-grid")}>{items.map((item,index)=><article className={sparkTw(block, "auto_8", "b4-card group relative")} key={`${item?.title||"item"}-${index}`}>
        <div data-cosmic-luna-display="image" data-luna-target="image" className={sparkTw(block, "auto_9", "b4-img")}>{mediaUrl(item?.image_url)?<img src={mediaUrl(item?.image_url)} alt="" className={sparkTw(block, "auto_10", "h-full w-full object-cover pointer-events-none")}/>:<div className={sparkTw(block, "auto_11", "h-full min-h-[15rem] w-full bg-[var(--b4-surface)]")}/>}</div>
        <div className={sparkTw(block, "auto_12", "b4-copy")}>
          <span className={sparkTw(block, "auto_13", "b4-label")}>{item?.label || String(index+1).padStart(2,"0")}</span>
          <span data-cosmic-luna-display="text" data-cosmic-type="card-title" data-luna-target="heading" className={sparkTw(block, "auto_14", "b4-title")}>{item?.title}</span>
          <span data-cosmic-luna-display="text" data-cosmic-type="card-body" data-luna-target="text" className={sparkTw(block, "auto_15", "b4-text")}>{item?.text}</span>
        </div>
      </article>)}</div>
      <div className={sparkTw(block, "auto_16", "b4-actions")}>
        {block?.button_label&&<a className={sparkTw(block, "auto_17", "b4-primary")} href={block?.button_url||"#"} data-cosmic-luna-display="button" data-luna-target="button">{block.button_label}</a>}
        {block?.secondary_label&&<a className={sparkTw(block, "auto_18", "b4-secondary")} href={block?.secondary_url||"#"} data-cosmic-luna-display="button" data-luna-target="button">{block.secondary_label}</a>}
      </div>
   </div>
   <style>{`
    .cosmic-b4{container-type:inline-size;container-name:cosmic-b4;min-width:0;overflow:hidden;background:var(--b4-bg);color:var(--b4-text);padding:7rem 1.75rem}
    .cosmic-b4 .b4-shell{width:100%;max-width:88rem;margin:0 auto}
    .cosmic-b4 .b4-head{max-width:52rem;margin-bottom:3.5rem}
    .cosmic-b4 .b4-eyebrow{display:block;font-size:.75rem;font-weight:500;letter-spacing:.28em;text-transform:uppercase;color:var(--b4-muted)}
    .cosmic-b4 .b4-heading{display:block;margin-top:1rem;font-size:clamp(2.4rem,5vw,4.6rem);line-height:.98;letter-spacing:-.045em;font-weight:700}
    .cosmic-b4 .b4-intro{display:block;margin-top:1.25rem;max-width:44rem;font-size:1.05rem;line-height:1.8;color:var(--b4-muted)}
    .cosmic-b4 .b4-grid{display:grid;gap:1.25rem}
    .cosmic-b4 .b4-card{position:relative;overflow:hidden;border:1px solid var(--b4-border);background:var(--b4-surface);border-radius:1.75rem}
    .cosmic-b4 .b4-img{overflow:hidden;min-height:16rem}
    .cosmic-b4 .b4-img img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .55s ease}
    .cosmic-b4 .b4-card:hover .b4-img img{transform:scale(1.035)}
    .cosmic-b4 .b4-copy{padding:1.5rem}
    .cosmic-b4 .b4-label{display:block;font-size:.72rem;letter-spacing:.16em;text-transform:uppercase;color:var(--b4-muted);margin-bottom:.75rem}
    .cosmic-b4 .b4-title{display:block;font-size:1.45rem;line-height:1.12;font-weight:700}
    .cosmic-b4 .b4-text{display:block;margin-top:.7rem;line-height:1.7;color:var(--b4-muted)}
    .cosmic-b4 .b4-actions{display:flex;gap:.8rem;flex-wrap:wrap;margin-top:2.25rem}
    .cosmic-b4 .b4-primary,.cosmic-b4 .b4-secondary{display:inline-flex;min-height:50px;align-items:center;justify-content:center;border-radius:100px;padding:.75rem 1.5rem;font-weight:700}
    .cosmic-b4 .b4-primary{background:var(--b4-text);color:var(--b4-bg)}
    .cosmic-b4 .b4-secondary{border:1px solid var(--b4-border);color:var(--b4-text)}

    .b4-dishes .b4-grid,.b4-projects .b4-grid,.b4-treatments .b4-grid,.b4-properties .b4-grid,.b4-rooms .b4-grid,.b4-experiences .b4-grid{grid-template-columns:repeat(4,minmax(0,1fr))}
    .b4-dishes .b4-img,.b4-treatments .b4-img,.b4-properties .b4-img,.b4-rooms .b4-img{aspect-ratio:4/5}

    .b4-story .b4-grid,.b4-capabilities .b4-grid,.b4-featured .b4-grid,.b4-agent .b4-grid,.b4-destination .b4-grid{grid-template-columns:1.25fr .75fr;align-items:stretch}
    .b4-story .b4-card:first-child,.b4-capabilities .b4-card:first-child,.b4-featured .b4-card:first-child,.b4-agent .b4-card:first-child,.b4-destination .b4-card:first-child{grid-row:1 / span 2;display:flex;flex-direction:column;height:100%}
    .b4-story .b4-card:first-child .b4-img,.b4-capabilities .b4-card:first-child .b4-img,.b4-featured .b4-card:first-child .b4-img,.b4-agent .b4-card:first-child .b4-img,.b4-destination .b4-card:first-child .b4-img{min-height:34rem;flex:1}

    .b4-gallery .b4-grid,.b4-progress .b4-grid{grid-template-columns:repeat(12,minmax(0,1fr));grid-auto-rows:7rem}
    .b4-gallery .b4-card,.b4-progress .b4-card{grid-column:span 5;grid-row:span 3}
    .b4-gallery .b4-card:nth-child(2),.b4-progress .b4-card:nth-child(2){grid-column:span 7;grid-row:span 3}
    .b4-gallery .b4-img,.b4-progress .b4-img{position:absolute;inset:0;height:100%;opacity:1}
    .b4-gallery .b4-copy,.b4-progress .b4-copy{position:relative;z-index:2}

    .b4-reservation .b4-grid,.b4-services .b4-grid,.b4-pathways .b4-grid,.b4-facility .b4-grid,.b4-neighborhoods .b4-grid,.b4-itinerary .b4-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
    .b4-reservation .b4-card,.b4-facility .b4-card{min-height:27rem}
    .b4-reservation .b4-img,.b4-facility .b4-img{position:absolute;inset:0;height:100%}
    .b4-reservation .b4-card:after,.b4-facility .b4-card:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(2,6,23,.86),rgba(2,6,23,.08))}
    .b4-reservation .b4-copy,.b4-facility .b4-copy{position:absolute;z-index:2;left:0;right:0;bottom:0;color:white}
    .b4-reservation .b4-text,.b4-facility .b4-text,.b4-reservation .b4-label,.b4-facility .b4-label{color:rgba(255,255,255,.72)}

        .b4-gallery .b4-copy,.b4-progress .b4-copy{display:flex;min-height:100%;flex-direction:column;justify-content:flex-end;padding:1.75rem;background:linear-gradient(to top,rgba(255,255,255,.98) 0%,rgba(255,255,255,.92) 24%,rgba(255,255,255,.68) 43%,rgba(255,255,255,.24) 58%,rgba(255,255,255,0) 74%)}
    .b4-gallery .b4-copy,.b4-progress .b4-copy{color:#172033}
    .b4-gallery .b4-label,.b4-progress .b4-label{color:#64748b}
    .b4-gallery .b4-text,.b4-progress .b4-text{color:#475569}

    /* Batch 3 parity repair: these breakpoints key off the actual Spark canvas, not the browser viewport. */
    @container cosmic-b4 (max-width:1100px){
      .b4-dishes .b4-grid,.b4-projects .b4-grid,.b4-treatments .b4-grid,.b4-properties .b4-grid,.b4-rooms .b4-grid,.b4-experiences .b4-grid{grid-template-columns:repeat(3,minmax(0,1fr))}
      .b4-story .b4-grid,.b4-capabilities .b4-grid,.b4-featured .b4-grid,.b4-agent .b4-grid,.b4-destination .b4-grid{grid-template-columns:minmax(0,1.12fr) minmax(16rem,.88fr)}
      .b4-reservation .b4-grid,.b4-services .b4-grid,.b4-pathways .b4-grid,.b4-facility .b4-grid,.b4-neighborhoods .b4-grid,.b4-itinerary .b4-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
    }
    @container cosmic-b4 (max-width:900px){
      .cosmic-b4{padding:5rem 1.25rem}
      .cosmic-b4 .b4-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}
      .b4-story .b4-card:first-child,.b4-capabilities .b4-card:first-child,.b4-featured .b4-card:first-child,.b4-agent .b4-card:first-child,.b4-destination .b4-card:first-child{grid-row:auto;height:auto}
      .b4-story .b4-card:first-child .b4-img,.b4-capabilities .b4-card:first-child .b4-img,.b4-featured .b4-card:first-child .b4-img,.b4-agent .b4-card:first-child .b4-img,.b4-destination .b4-card:first-child .b4-img{flex:none;min-height:22rem}
      .b4-gallery .b4-grid,.b4-progress .b4-grid{grid-auto-rows:auto}
      .b4-gallery .b4-card,.b4-progress .b4-card{grid-column:auto;grid-row:auto;min-height:21rem}
    }
    @container cosmic-b4 (max-width:640px){
      .cosmic-b4{padding:4rem 1rem}
      .cosmic-b4 .b4-heading{font-size:clamp(2.2rem,10cqw,3.4rem);overflow-wrap:anywhere}
      .cosmic-b4 .b4-grid{grid-template-columns:1fr!important}
      .b4-story .b4-card:first-child .b4-img,.b4-capabilities .b4-card:first-child .b4-img,.b4-featured .b4-card:first-child .b4-img,.b4-agent .b4-card:first-child .b4-img,.b4-destination .b4-card:first-child .b4-img{min-height:17rem}
    }
@media(max-width:900px){.b4-story .b4-card:first-child,.b4-capabilities .b4-card:first-child,.b4-featured .b4-card:first-child,.b4-agent .b4-card:first-child,.b4-destination .b4-card:first-child{grid-row:auto;height:auto}.b4-story .b4-card:first-child .b4-img,.b4-capabilities .b4-card:first-child .b4-img,.b4-featured .b4-card:first-child .b4-img,.b4-agent .b4-card:first-child .b4-img,.b4-destination .b4-card:first-child .b4-img{flex:none}.cosmic-b4{padding:5rem 1.25rem}.cosmic-b4 .b4-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.b4-gallery .b4-grid,.b4-progress .b4-grid{grid-auto-rows:auto}.b4-gallery .b4-card,.b4-progress .b4-card{grid-column:auto;grid-row:auto;min-height:21rem}}
    @media(max-width:640px){.cosmic-b4{padding:4rem 1rem}.cosmic-b4 .b4-heading{font-size:clamp(2.2rem,12vw,3.4rem)}.cosmic-b4 .b4-grid{grid-template-columns:1fr!important}}
   
    .b4-card,.b4-copy,.b4-img,.b4-grid{min-width:0}.b4-title,.b4-text{overflow-wrap:anywhere}`}</style>
 </section>
};

export const RestaurantSignatureDishesPremiumBlock=(props)=><IndustrySection {...props} variant="dishes" family="restaurant"/>;
export const RestaurantSignatureDishesPremiumSchema={"type":"restaurant_signature_dishes_premium","title":"Restaurant Signature Dishes","description":"Industry-specific restaurant section with a dishes composition and image-led presentation.","defaults":{"type":"restaurant_signature_dishes_premium","theme":"auto","eyebrow":"Taste & atmosphere","heading":"Restaurant Signature Dishes","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Chef's selection","text":"Seasonal dishes with thoughtful ingredients and a strong sense of place.","label":"Signature","image_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=82"},{"title":"Shared plates","text":"Relaxed dishes made for the table and easy conversation.","label":"To share","image_url":"https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=82"},{"title":"House desserts","text":"A simple finish built around familiar flavours.","label":"Sweet","image_url":"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=82"},{"title":"Evening menu","text":"A slower dinner experience with changing seasonal plates.","label":"Dinner","image_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=82"}]}};

export const RestaurantStoryMenuPremiumBlock=(props)=><IndustrySection {...props} variant="story" family="restaurant"/>;
export const RestaurantStoryMenuPremiumSchema={"type":"restaurant_story_menu_premium","title":"Restaurant Story Menu","description":"Industry-specific restaurant section with a story composition and image-led presentation.","defaults":{"type":"restaurant_story_menu_premium","theme":"auto","eyebrow":"Taste & atmosphere","heading":"Restaurant Story Menu","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Chef's selection","text":"Seasonal dishes with thoughtful ingredients and a strong sense of place.","label":"Signature","image_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=82"},{"title":"Shared plates","text":"Relaxed dishes made for the table and easy conversation.","label":"To share","image_url":"https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=82"},{"title":"House desserts","text":"A simple finish built around familiar flavours.","label":"Sweet","image_url":"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=82"},{"title":"Evening menu","text":"A slower dinner experience with changing seasonal plates.","label":"Dinner","image_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=82"}]}};

export const RestaurantAtmosphereGalleryPremiumBlock=(props)=><IndustrySection {...props} variant="gallery" family="restaurant"/>;
export const RestaurantAtmosphereGalleryPremiumSchema={"type":"restaurant_atmosphere_gallery_premium","title":"Restaurant Atmosphere Gallery","description":"Industry-specific restaurant section with a gallery composition and image-led presentation.","defaults":{"type":"restaurant_atmosphere_gallery_premium","theme":"auto","eyebrow":"Taste & atmosphere","heading":"Restaurant Atmosphere Gallery","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Chef's selection","text":"Seasonal dishes with thoughtful ingredients and a strong sense of place.","label":"Signature","image_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=82"},{"title":"Shared plates","text":"Relaxed dishes made for the table and easy conversation.","label":"To share","image_url":"https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=82"},{"title":"House desserts","text":"A simple finish built around familiar flavours.","label":"Sweet","image_url":"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=82"},{"title":"Evening menu","text":"A slower dinner experience with changing seasonal plates.","label":"Dinner","image_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=82"}]}};

export const RestaurantReservationCtaPremiumBlock=(props)=><IndustrySection {...props} variant="reservation" family="restaurant"/>;
export const RestaurantReservationCtaPremiumSchema={"type":"restaurant_reservation_cta_premium","title":"Restaurant Reservation CTA","description":"Industry-specific restaurant section with a reservation composition and image-led presentation.","defaults":{"type":"restaurant_reservation_cta_premium","theme":"auto","eyebrow":"Taste & atmosphere","heading":"Restaurant Reservation CTA","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Chef's selection","text":"Seasonal dishes with thoughtful ingredients and a strong sense of place.","label":"Signature","image_url":"https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=82"},{"title":"Shared plates","text":"Relaxed dishes made for the table and easy conversation.","label":"To share","image_url":"https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=82"},{"title":"House desserts","text":"A simple finish built around familiar flavours.","label":"Sweet","image_url":"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1400&q=82"},{"title":"Evening menu","text":"A slower dinner experience with changing seasonal plates.","label":"Dinner","image_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=82"}]}};

export const ConstructionProjectCardsPremiumBlock=(props)=><IndustrySection {...props} variant="projects" family="construction"/>;
export const ConstructionProjectCardsPremiumSchema={"type":"construction_project_cards_premium","title":"Construction Project Cards","description":"Industry-specific construction section with a projects composition and image-led presentation.","defaults":{"type":"construction_project_cards_premium","theme":"auto","eyebrow":"Built with purpose","heading":"Construction Project Cards","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Residential builds","text":"Well-managed homes with practical detailing and dependable delivery.","label":"Homes","image_url":"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=82"},{"title":"Commercial projects","text":"Flexible delivery for workplaces, retail, and mixed-use spaces.","label":"Commercial","image_url":"https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=82"},{"title":"Renovations","text":"Careful upgrades that respect the existing structure.","label":"Renovation","image_url":"https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1400&q=82"},{"title":"Project management","text":"Clear coordination across trades, milestones, and handover.","label":"Delivery","image_url":"https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1400&q=82"}]}};

export const ConstructionServicePhotosPremiumBlock=(props)=><IndustrySection {...props} variant="services" family="construction"/>;
export const ConstructionServicePhotosPremiumSchema={"type":"construction_service_photos_premium","title":"Construction Service Photos","description":"Industry-specific construction section with a services composition and image-led presentation.","defaults":{"type":"construction_service_photos_premium","theme":"auto","eyebrow":"Built with purpose","heading":"Construction Service Photos","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Residential builds","text":"Well-managed homes with practical detailing and dependable delivery.","label":"Homes","image_url":"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=82"},{"title":"Commercial projects","text":"Flexible delivery for workplaces, retail, and mixed-use spaces.","label":"Commercial","image_url":"https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=82"},{"title":"Renovations","text":"Careful upgrades that respect the existing structure.","label":"Renovation","image_url":"https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1400&q=82"},{"title":"Project management","text":"Clear coordination across trades, milestones, and handover.","label":"Delivery","image_url":"https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1400&q=82"}]}};

export const ConstructionCapabilitySplitPremiumBlock=(props)=><IndustrySection {...props} variant="capabilities" family="construction"/>;
export const ConstructionCapabilitySplitPremiumSchema={"type":"construction_capability_split_premium","title":"Construction Capability Split","description":"Industry-specific construction section with a capabilities composition and image-led presentation.","defaults":{"type":"construction_capability_split_premium","theme":"auto","eyebrow":"Built with purpose","heading":"Construction Capability Split","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Residential builds","text":"Well-managed homes with practical detailing and dependable delivery.","label":"Homes","image_url":"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=82"},{"title":"Commercial projects","text":"Flexible delivery for workplaces, retail, and mixed-use spaces.","label":"Commercial","image_url":"https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=82"},{"title":"Renovations","text":"Careful upgrades that respect the existing structure.","label":"Renovation","image_url":"https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1400&q=82"},{"title":"Project management","text":"Clear coordination across trades, milestones, and handover.","label":"Delivery","image_url":"https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1400&q=82"}]}};

export const ConstructionSiteProgressPremiumBlock=(props)=><IndustrySection {...props} variant="progress" family="construction"/>;
export const ConstructionSiteProgressPremiumSchema={"type":"construction_site_progress_premium","title":"Construction Site Progress","description":"Industry-specific construction section with a progress composition and image-led presentation.","defaults":{"type":"construction_site_progress_premium","theme":"auto","eyebrow":"Built with purpose","heading":"Construction Site Progress","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Residential builds","text":"Well-managed homes with practical detailing and dependable delivery.","label":"Homes","image_url":"https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1400&q=82"},{"title":"Commercial projects","text":"Flexible delivery for workplaces, retail, and mixed-use spaces.","label":"Commercial","image_url":"https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=82"},{"title":"Renovations","text":"Careful upgrades that respect the existing structure.","label":"Renovation","image_url":"https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1400&q=82"},{"title":"Project management","text":"Clear coordination across trades, milestones, and handover.","label":"Delivery","image_url":"https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1400&q=82"}]}};

export const DentalTreatmentCardsPremiumBlock=(props)=><IndustrySection {...props} variant="treatments" family="dental"/>;
export const DentalTreatmentCardsPremiumSchema={"type":"dental_treatment_cards_premium","title":"Dental Treatment Cards","description":"Industry-specific dental section with a treatments composition and image-led presentation.","defaults":{"type":"dental_treatment_cards_premium","theme":"auto","eyebrow":"Care for every smile","heading":"Dental Treatment Cards","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Preventive care","text":"Regular care focused on maintaining healthy teeth and gums.","label":"Everyday care","image_url":"https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1400&q=82"},{"title":"Restorative dentistry","text":"Practical treatment options to restore comfort and function.","label":"Restore","image_url":"https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1400&q=82"},{"title":"Cosmetic dentistry","text":"Considered treatments designed around your goals and smile.","label":"Smile","image_url":"https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1400&q=82"},{"title":"Emergency care","text":"Prompt assessment when something feels urgent or uncomfortable.","label":"Urgent","image_url":"https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1400&q=82"}]}};

export const DentalClinicStoryPremiumBlock=(props)=><IndustrySection {...props} variant="story" family="dental"/>;
export const DentalClinicStoryPremiumSchema={"type":"dental_clinic_story_premium","title":"Dental Clinic Story","description":"Industry-specific dental section with a story composition and image-led presentation.","defaults":{"type":"dental_clinic_story_premium","theme":"auto","eyebrow":"Care for every smile","heading":"Dental Clinic Story","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Preventive care","text":"Regular care focused on maintaining healthy teeth and gums.","label":"Everyday care","image_url":"https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1400&q=82"},{"title":"Restorative dentistry","text":"Practical treatment options to restore comfort and function.","label":"Restore","image_url":"https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1400&q=82"},{"title":"Cosmetic dentistry","text":"Considered treatments designed around your goals and smile.","label":"Smile","image_url":"https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1400&q=82"},{"title":"Emergency care","text":"Prompt assessment when something feels urgent or uncomfortable.","label":"Urgent","image_url":"https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1400&q=82"}]}};

export const MedicalCarePathwaysPremiumBlock=(props)=><IndustrySection {...props} variant="pathways" family="medical"/>;
export const MedicalCarePathwaysPremiumSchema={"type":"medical_care_pathways_premium","title":"Medical Care Pathways","description":"Industry-specific medical section with a pathways composition and image-led presentation.","defaults":{"type":"medical_care_pathways_premium","theme":"auto","eyebrow":"Care pathways","heading":"Medical Care Pathways","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Primary care","text":"Accessible support for everyday health needs and ongoing care.","label":"Care","image_url":"https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1400&q=82"},{"title":"Diagnostics","text":"Clear next steps supported by appropriate testing and review.","label":"Assess","image_url":"https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1400&q=82"},{"title":"Specialist support","text":"Coordinated pathways when more focused care is needed.","label":"Specialist","image_url":"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1400&q=82"},{"title":"Follow-up care","text":"Continuity after treatment with practical ongoing support.","label":"Follow-up","image_url":"https://images.unsplash.com/photo-1516841273335-e39b37888115?auto=format&fit=crop&w=1400&q=82"}]}};

export const MedicalFacilityShowcasePremiumBlock=(props)=><IndustrySection {...props} variant="facility" family="medical"/>;
export const MedicalFacilityShowcasePremiumSchema={"type":"medical_facility_showcase_premium","title":"Medical Facility Showcase","description":"Industry-specific medical section with a facility composition and image-led presentation.","defaults":{"type":"medical_facility_showcase_premium","theme":"auto","eyebrow":"Care pathways","heading":"Medical Facility Showcase","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Primary care","text":"Accessible support for everyday health needs and ongoing care.","label":"Care","image_url":"https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1400&q=82"},{"title":"Diagnostics","text":"Clear next steps supported by appropriate testing and review.","label":"Assess","image_url":"https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1400&q=82"},{"title":"Specialist support","text":"Coordinated pathways when more focused care is needed.","label":"Specialist","image_url":"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1400&q=82"},{"title":"Follow-up care","text":"Continuity after treatment with practical ongoing support.","label":"Follow-up","image_url":"https://images.unsplash.com/photo-1516841273335-e39b37888115?auto=format&fit=crop&w=1400&q=82"}]}};

export const RealestatePropertyGridPremiumBlock=(props)=><IndustrySection {...props} variant="properties" family="realestate"/>;
export const RealestatePropertyGridPremiumSchema={"type":"realestate_property_grid_premium","title":"Real Estate Property Grid","description":"Industry-specific realestate section with a properties composition and image-led presentation.","defaults":{"type":"realestate_property_grid_premium","theme":"auto","eyebrow":"Featured properties","heading":"Real Estate Property Grid","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Modern family home","text":"Light-filled interiors, flexible living, and an easy connection outdoors.","label":"For sale","image_url":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82"},{"title":"City apartment","text":"A well-positioned residence close to dining, transport, and work.","label":"Apartment","image_url":"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=82"},{"title":"Coastal retreat","text":"Relaxed living with open views and generous outdoor space.","label":"Coastal","image_url":"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82"},{"title":"Investment property","text":"A practical property with strong fundamentals and long-term appeal.","label":"Investment","image_url":"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=82"}]}};

export const RealestateFeaturedListingPremiumBlock=(props)=><IndustrySection {...props} variant="featured" family="realestate"/>;
export const RealestateFeaturedListingPremiumSchema={"type":"realestate_featured_listing_premium","title":"Real Estate Featured Listing","description":"Industry-specific realestate section with a featured composition and image-led presentation.","defaults":{"type":"realestate_featured_listing_premium","theme":"auto","eyebrow":"Featured properties","heading":"Real Estate Featured Listing","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Modern family home","text":"Light-filled interiors, flexible living, and an easy connection outdoors.","label":"For sale","image_url":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82"},{"title":"City apartment","text":"A well-positioned residence close to dining, transport, and work.","label":"Apartment","image_url":"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=82"},{"title":"Coastal retreat","text":"Relaxed living with open views and generous outdoor space.","label":"Coastal","image_url":"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82"},{"title":"Investment property","text":"A practical property with strong fundamentals and long-term appeal.","label":"Investment","image_url":"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=82"}]}};

export const RealestateNeighborhoodCardsPremiumBlock=(props)=><IndustrySection {...props} variant="neighborhoods" family="realestate"/>;
export const RealestateNeighborhoodCardsPremiumSchema={"type":"realestate_neighborhood_cards_premium","title":"Real Estate Neighborhood Cards","description":"Industry-specific realestate section with a neighborhoods composition and image-led presentation.","defaults":{"type":"realestate_neighborhood_cards_premium","theme":"auto","eyebrow":"Featured properties","heading":"Real Estate Neighborhood Cards","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Modern family home","text":"Light-filled interiors, flexible living, and an easy connection outdoors.","label":"For sale","image_url":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82"},{"title":"City apartment","text":"A well-positioned residence close to dining, transport, and work.","label":"Apartment","image_url":"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=82"},{"title":"Coastal retreat","text":"Relaxed living with open views and generous outdoor space.","label":"Coastal","image_url":"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82"},{"title":"Investment property","text":"A practical property with strong fundamentals and long-term appeal.","label":"Investment","image_url":"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=82"}]}};

export const RealestateAgentStoryPremiumBlock=(props)=><IndustrySection {...props} variant="agent" family="realestate"/>;
export const RealestateAgentStoryPremiumSchema={"type":"realestate_agent_story_premium","title":"Real Estate Agent Story","description":"Industry-specific realestate section with a agent composition and image-led presentation.","defaults":{"type":"realestate_agent_story_premium","theme":"auto","eyebrow":"Featured properties","heading":"Real Estate Agent Story","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Modern family home","text":"Light-filled interiors, flexible living, and an easy connection outdoors.","label":"For sale","image_url":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=82"},{"title":"City apartment","text":"A well-positioned residence close to dining, transport, and work.","label":"Apartment","image_url":"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=82"},{"title":"Coastal retreat","text":"Relaxed living with open views and generous outdoor space.","label":"Coastal","image_url":"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=82"},{"title":"Investment property","text":"A practical property with strong fundamentals and long-term appeal.","label":"Investment","image_url":"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=82"}]}};

export const HotelRoomCollectionPremiumBlock=(props)=><IndustrySection {...props} variant="rooms" family="hotel"/>;
export const HotelRoomCollectionPremiumSchema={"type":"hotel_room_collection_premium","title":"Hotel Room Collection","description":"Industry-specific hotel section with a rooms composition and image-led presentation.","defaults":{"type":"hotel_room_collection_premium","theme":"auto","eyebrow":"Stay your way","heading":"Hotel Room Collection","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Garden Suite","text":"Quiet comfort with a calm interior and space to unwind.","label":"Suite","image_url":"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=82"},{"title":"City King","text":"A refined room designed for short stays and easy mornings.","label":"Room","image_url":"https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1400&q=82"},{"title":"Family Loft","text":"Flexible space for longer stays and shared travel.","label":"Family","image_url":"https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1400&q=82"},{"title":"Signature Suite","text":"A larger stay with elevated details and a private outlook.","label":"Premium","image_url":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1400&q=82"}]}};

export const HotelExperienceCardsPremiumBlock=(props)=><IndustrySection {...props} variant="experiences" family="hotel"/>;
export const HotelExperienceCardsPremiumSchema={"type":"hotel_experience_cards_premium","title":"Hotel Experience Cards","description":"Industry-specific hotel section with a experiences composition and image-led presentation.","defaults":{"type":"hotel_experience_cards_premium","theme":"auto","eyebrow":"Stay your way","heading":"Hotel Experience Cards","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Garden Suite","text":"Quiet comfort with a calm interior and space to unwind.","label":"Suite","image_url":"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=82"},{"title":"City King","text":"A refined room designed for short stays and easy mornings.","label":"Room","image_url":"https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1400&q=82"},{"title":"Family Loft","text":"Flexible space for longer stays and shared travel.","label":"Family","image_url":"https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1400&q=82"},{"title":"Signature Suite","text":"A larger stay with elevated details and a private outlook.","label":"Premium","image_url":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1400&q=82"}]}};

export const TravelDestinationStoryPremiumBlock=(props)=><IndustrySection {...props} variant="destination" family="travel"/>;
export const TravelDestinationStoryPremiumSchema={"type":"travel_destination_story_premium","title":"Travel Destination Story","description":"Industry-specific travel section with a destination composition and image-led presentation.","defaults":{"type":"travel_destination_story_premium","theme":"auto","eyebrow":"Explore more","heading":"Travel Destination Story","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Island escape","text":"Slow days, clear water, and a relaxed itinerary.","label":"Coast","image_url":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=82"},{"title":"Mountain journey","text":"Scenic routes, cooler air, and memorable viewpoints.","label":"Nature","image_url":"https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=82"},{"title":"City weekend","text":"Food, culture, and neighbourhood discovery in a compact stay.","label":"City","image_url":"https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=82"},{"title":"Road trip","text":"Flexible travel built around local stops and changing scenery.","label":"Journey","image_url":"https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1400&q=82"}]}};

export const TravelItineraryVisualPremiumBlock=(props)=><IndustrySection {...props} variant="itinerary" family="travel"/>;
export const TravelItineraryVisualPremiumSchema={"type":"travel_itinerary_visual_premium","title":"Travel Itinerary Visual","description":"Industry-specific travel section with a itinerary composition and image-led presentation.","defaults":{"type":"travel_itinerary_visual_premium","theme":"auto","eyebrow":"Explore more","heading":"Travel Itinerary Visual","text":"A focused visual section designed to feel immediately relevant to this industry while staying flexible for different brands.","button_label":"Learn more","button_url":"#","secondary_label":"Get in touch","secondary_url":"#","items":[{"title":"Island escape","text":"Slow days, clear water, and a relaxed itinerary.","label":"Coast","image_url":"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=82"},{"title":"Mountain journey","text":"Scenic routes, cooler air, and memorable viewpoints.","label":"Nature","image_url":"https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=82"},{"title":"City weekend","text":"Food, culture, and neighbourhood discovery in a compact stay.","label":"City","image_url":"https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=82"},{"title":"Road trip","text":"Flexible travel built around local stops and changing scenery.","label":"Journey","image_url":"https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1400&q=82"}]}};
