import React from "react";

import { sparkTw } from "../Shared/sparkTailwindRuntime";
const asset=(value)=>String(value||"").trim();
const themeVars=(resolved)=>{
    const primary=String(resolved||"").toLowerCase()==="primary";
    return {
        "--b5-bg":primary?"var(--cosmic-local-bg-primary,var(--cosmic-bg-primary,var(--cosmic-primary,#243447)))":"var(--cosmic-local-bg-surface,var(--cosmic-bg-surface,#ffffff))",
        "--b5-surface":primary?"var(--cosmic-local-bg-primary-surface,var(--cosmic-bg-primary-surface,var(--cosmic-surface,#30475E)))":"var(--cosmic-local-bg-surface,var(--cosmic-bg-surface,#f7f7f5))",
        "--b5-text":primary?"var(--cosmic-local-on-primary,var(--cosmic-on-primary,#f8fafc))":"var(--cosmic-local-on-surface,var(--cosmic-on-surface,#172033))",
        "--b5-muted":primary?"var(--cosmic-local-on-primary-muted,var(--cosmic-on-primary-muted,rgba(248,250,252,.76)))":"var(--cosmic-local-on-surface-muted,var(--cosmic-on-surface-muted,#64748b))",
        "--b5-surface-text":primary?"var(--cosmic-color-on-secondary,var(--cosmic-on-secondary,#172033))":"var(--cosmic-local-on-surface,var(--cosmic-on-surface,#172033))",
        "--b5-surface-muted":primary?"color-mix(in srgb,var(--cosmic-color-on-secondary,var(--cosmic-on-secondary,#172033)) 68%,transparent)":"var(--cosmic-local-on-surface-muted,var(--cosmic-on-surface-muted,#64748b))",
        "--b5-border":primary?"rgba(248,250,252,.18)":"rgba(15,23,42,.12)",
        "--b5-accent":"var(--cosmic-accent,#60A5FA)",
    };
};

const Batch5=({block,variant,family})=>{
    const items=Array.isArray(block?.items)?block.items:[];
    const resolved=block?.resolvedTheme||block?.theme||"light";
    return <section className={sparkTw(block, "auto_1", `group/repeatable-section cosmic-b5 b5-${family} b5-${variant}`)} style={themeVars(resolved)}>
        <div className={sparkTw(block, "auto_2", "b5-shell")}>
            <div className={sparkTw(block, "auto_3", "b5-head")}>
                <span data-cosmic-luna-display="text" data-luna-target="label" className={sparkTw(block, "auto_4", "b5-eyebrow")}>{block?.eyebrow}</span>
                <span data-cosmic-luna-display="text" data-cosmic-type="h2" data-luna-target="heading" className={sparkTw(block, "auto_5", "b5-heading")}>{block?.heading}</span>
                <span data-cosmic-luna-display="text" data-cosmic-type="lead" data-luna-target="text" className={sparkTw(block, "auto_6", "b5-intro")}>{block?.text}</span>
            </div>
            <div className={sparkTw(block, "auto_7", "b5-grid")}>
                {items.map((item,index)=><article className={sparkTw(block, "auto_8", "b5-card group relative")} key={`${item?.title||"item"}-${index}`}>
                    <div data-cosmic-luna-display="image" data-luna-target="image" className={sparkTw(block, "auto_9", "b5-img")}>
                        {asset(item?.image_url)?<img src={asset(item?.image_url)} alt="" className={sparkTw(block, "auto_10", "h-full w-full object-cover pointer-events-none")}/>:<div className={sparkTw(block, "auto_11", "h-full min-h-[16rem] w-full bg-[var(--b5-surface)]")}/>}
                    </div>
                    <div className={sparkTw(block, "auto_12", "b5-copy")}>
                        <span className={sparkTw(block, "auto_13", "b5-label")}>{item?.label || String(index+1).padStart(2,"0")}</span>
                        <span data-cosmic-luna-display="text" data-cosmic-type="card-title" data-luna-target="heading" className={sparkTw(block, "auto_14", "b5-title")}>{item?.title}</span>
                        <span data-cosmic-luna-display="text" data-cosmic-type="card-body" data-luna-target="text" className={sparkTw(block, "auto_15", "b5-text")}>{item?.text}</span>
                    </div>
                </article>)}
            </div>
            <div className={sparkTw(block, "auto_16", "b5-actions")}>
                {block?.button_label&&<a className={sparkTw(block, "auto_17", "b5-primary")} href={block?.button_url||"#"} data-cosmic-luna-display="button" data-luna-target="button">{block.button_label}</a>}
                {block?.secondary_label&&<a className={sparkTw(block, "auto_18", "b5-secondary")} href={block?.secondary_url||"#"} data-cosmic-luna-display="button" data-luna-target="button">{block.secondary_label}</a>}
            </div>
        </div>
        <style>{`
            .cosmic-b5{container-type:inline-size;container-name:cosmic-b5;min-width:0;overflow:hidden;background:var(--b5-bg);color:var(--b5-text);padding:7rem 1.75rem}
            .cosmic-b5 .b5-shell{width:100%;max-width:88rem;margin:0 auto}
            .cosmic-b5 .b5-head{max-width:52rem;margin-bottom:3.5rem}
            .cosmic-b5 .b5-eyebrow{display:block;font-size:.75rem;font-weight:500;letter-spacing:.28em;text-transform:uppercase;color:var(--b5-muted)}
            .cosmic-b5 .b5-heading{display:block;margin-top:1rem;font-size:clamp(2.5rem,5vw,4.8rem);line-height:.96;letter-spacing:-.045em;font-weight:700}
            .cosmic-b5 .b5-intro{display:block;margin-top:1.25rem;max-width:44rem;font-size:1.05rem;line-height:1.8;color:var(--b5-muted)}
            .cosmic-b5 .b5-grid{display:grid;gap:1.25rem}
            .cosmic-b5 .b5-card{position:relative;overflow:hidden;border:1px solid var(--b5-border);background:var(--b5-surface);color:var(--b5-surface-text)!important;-webkit-text-fill-color:var(--b5-surface-text)!important;border-radius:1.75rem}
            .cosmic-b5 .b5-img{overflow:hidden;min-height:16rem}
            .cosmic-b5 .b5-img img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .55s ease}
            .cosmic-b5 .b5-card:hover .b5-img img{transform:scale(1.035)}
            .cosmic-b5 .b5-copy{padding:1.5rem}
            .cosmic-b5 .b5-label{display:block;font-size:.72rem;letter-spacing:.16em;text-transform:uppercase;color:var(--b5-surface-muted)!important;-webkit-text-fill-color:var(--b5-surface-muted)!important;margin-bottom:.75rem}
            .cosmic-b5 .b5-title{display:block;color:var(--b5-surface-text)!important;-webkit-text-fill-color:var(--b5-surface-text)!important;font-size:1.45rem;line-height:1.12;font-weight:700}
            .cosmic-b5 .b5-text{display:block;margin-top:.7rem;line-height:1.7;color:var(--b5-surface-muted)!important;-webkit-text-fill-color:var(--b5-surface-muted)!important}
            .cosmic-b5 .b5-actions{display:flex;gap:.8rem;flex-wrap:wrap;margin-top:2.25rem}
            .cosmic-b5 .b5-primary,.cosmic-b5 .b5-secondary{display:inline-flex;min-height:50px;align-items:center;justify-content:center;border-radius:100px;padding:.75rem 1.5rem;font-weight:700}
            .cosmic-b5 .b5-primary{background:var(--b5-text);color:var(--b5-bg)}
            .cosmic-b5 .b5-secondary{border:1px solid var(--b5-border);color:var(--b5-text)}

            .b5-stack .b5-grid,.b5-ledger .b5-grid{grid-template-columns:1fr}
            .b5-stack .b5-card,.b5-ledger .b5-card{display:grid;grid-template-columns:minmax(18rem,.8fr) 1.2fr;align-items:center}
            .b5-stack .b5-card:nth-child(even),.b5-ledger .b5-card:nth-child(even){grid-template-columns:1.2fr minmax(18rem,.8fr)}
            .b5-stack .b5-card:nth-child(even) .b5-img,.b5-ledger .b5-card:nth-child(even) .b5-img{order:2}

            .b5-asymmetric .b5-grid,.b5-mosaic .b5-grid,.b5-staggered .b5-grid{grid-template-columns:repeat(12,minmax(0,1fr));grid-auto-rows:7rem}
            .b5-asymmetric .b5-card,.b5-mosaic .b5-card,.b5-staggered .b5-card{grid-column:span 5;grid-row:span 3}
            .b5-asymmetric .b5-card:nth-child(2),.b5-mosaic .b5-card:nth-child(2),.b5-staggered .b5-card:nth-child(2){grid-column:span 7;grid-row:span 3}
            .b5-asymmetric .b5-img,.b5-mosaic .b5-img,.b5-staggered .b5-img{position:absolute;inset:0;height:100%;opacity:.38}
            .b5-asymmetric .b5-copy,.b5-mosaic .b5-copy,.b5-staggered .b5-copy{position:relative;z-index:2}

            .b5-manifesto .b5-grid,.b5-quote .b5-grid,.b5-fullbleed .b5-grid,.b5-case .b5-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
            .b5-manifesto .b5-card,.b5-quote .b5-card,.b5-fullbleed .b5-card,.b5-case .b5-card{min-height:28rem}
            .b5-manifesto .b5-img,.b5-quote .b5-img,.b5-fullbleed .b5-img,.b5-case .b5-img{position:absolute;inset:0;height:100%}
            .b5-manifesto .b5-card:after,.b5-quote .b5-card:after,.b5-fullbleed .b5-card:after,.b5-case .b5-card:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(2,6,23,.86),rgba(2,6,23,.06))}
            .b5-manifesto .b5-copy,.b5-quote .b5-copy,.b5-fullbleed .b5-copy,.b5-case .b5-copy{position:absolute;z-index:2;left:0;right:0;bottom:0;color:white!important;-webkit-text-fill-color:white!important}
            .b5-manifesto .b5-title,.b5-quote .b5-title,.b5-fullbleed .b5-title,.b5-case .b5-title{color:white!important;-webkit-text-fill-color:white!important}.b5-manifesto .b5-text,.b5-quote .b5-text,.b5-fullbleed .b5-text,.b5-case .b5-text,.b5-manifesto .b5-label,.b5-quote .b5-label,.b5-fullbleed .b5-label,.b5-case .b5-label{color:rgba(255,255,255,.72)!important;-webkit-text-fill-color:rgba(255,255,255,.72)!important}

            .b5-overlap .b5-grid,.b5-index .b5-grid,.b5-directory .b5-grid,.b5-metrics .b5-grid,.b5-values .b5-grid,.b5-principles .b5-grid{grid-template-columns:repeat(4,minmax(0,1fr))}
            .b5-overlap .b5-grid{align-items:start}.b5-overlap .b5-card:nth-child(even){margin-top:1.5rem}
            .b5-index .b5-img,.b5-directory .b5-img{aspect-ratio:4/5}

            .b5-accordion .b5-grid{grid-template-columns:1fr}.b5-accordion .b5-card{display:grid;grid-template-columns:minmax(15rem,.7fr) 1.3fr;align-items:center}
            .b5-accordion .b5-card:not(:first-child) .b5-img{max-height:13rem}

                .b5-asymmetric .b5-copy,.b5-mosaic .b5-copy,.b5-staggered .b5-copy{display:flex;min-height:100%;flex-direction:column;justify-content:flex-end;padding:1.75rem;background:linear-gradient(to top,color-mix(in srgb,var(--b5-surface,var(--cosmic-bg-primary-surface,#30475E)) 88%,transparent),transparent 78%)}

            /* Batch 3 parity repair: respond to Section Editor / preview canvas width. */
            @container cosmic-b5 (max-width:1100px){
                .b5-overlap .b5-grid,.b5-index .b5-grid,.b5-directory .b5-grid,.b5-metrics .b5-grid,.b5-values .b5-grid,.b5-principles .b5-grid{grid-template-columns:repeat(3,minmax(0,1fr))}
                .b5-stack .b5-card,.b5-ledger .b5-card,.b5-stack .b5-card:nth-child(even),.b5-ledger .b5-card:nth-child(even){grid-template-columns:minmax(14rem,.78fr) minmax(0,1.22fr)}
                .b5-stack .b5-card:nth-child(even),.b5-ledger .b5-card:nth-child(even){grid-template-columns:minmax(0,1.22fr) minmax(14rem,.78fr)}
                .b5-accordion .b5-card{grid-template-columns:minmax(12rem,.7fr) minmax(0,1.3fr)}
            }
            @container cosmic-b5 (max-width:900px){
                .cosmic-b5{padding:5rem 1.25rem}
                .cosmic-b5 .b5-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}
                .b5-asymmetric .b5-grid,.b5-mosaic .b5-grid,.b5-staggered .b5-grid{grid-auto-rows:auto}
                .b5-asymmetric .b5-card,.b5-mosaic .b5-card,.b5-staggered .b5-card{grid-column:auto;grid-row:auto;min-height:21rem}
                .b5-stack .b5-grid,.b5-ledger .b5-grid,.b5-accordion .b5-grid{grid-template-columns:1fr!important}
                .b5-stack .b5-card,.b5-ledger .b5-card,.b5-stack .b5-card:nth-child(even),.b5-ledger .b5-card:nth-child(even),.b5-accordion .b5-card{grid-template-columns:minmax(12rem,.72fr) minmax(0,1.28fr)}
                .b5-stack .b5-card:nth-child(even) .b5-img,.b5-ledger .b5-card:nth-child(even) .b5-img{order:initial}
            }
            @container cosmic-b5 (max-width:640px){
                .cosmic-b5{padding:4rem 1rem}
                .cosmic-b5 .b5-heading{font-size:clamp(2.2rem,10cqw,3.4rem);overflow-wrap:anywhere}
                .cosmic-b5 .b5-grid{grid-template-columns:1fr!important}
                .b5-overlap .b5-card:nth-child(even){margin-top:0;transform:none}
                .b5-stack .b5-card,.b5-ledger .b5-card,.b5-stack .b5-card:nth-child(even),.b5-ledger .b5-card:nth-child(even),.b5-accordion .b5-card{display:block}
            }
@media(max-width:900px){
                .cosmic-b5{padding:5rem 1.25rem}
                .cosmic-b5 .b5-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}
                .b5-asymmetric .b5-grid,.b5-mosaic .b5-grid,.b5-staggered .b5-grid{grid-auto-rows:auto}
                .b5-asymmetric .b5-card,.b5-mosaic .b5-card,.b5-staggered .b5-card{grid-column:auto;grid-row:auto;min-height:21rem}
            }
            @media(max-width:640px){
                .cosmic-b5{padding:4rem 1rem}
                .cosmic-b5 .b5-heading{font-size:clamp(2.2rem,12vw,3.4rem)}
                .cosmic-b5 .b5-grid{grid-template-columns:1fr!important}.b5-overlap .b5-card:nth-child(even){margin-top:0}
                .b5-stack .b5-card,.b5-ledger .b5-card,.b5-stack .b5-card:nth-child(even),.b5-ledger .b5-card:nth-child(even),.b5-accordion .b5-card{display:block}
                .b5-stack .b5-card:nth-child(even) .b5-img,.b5-ledger .b5-card:nth-child(even) .b5-img{order:initial}
                .b5-overlap .b5-card:nth-child(even){transform:none}
            }
        
            .b5-card,.b5-copy,.b5-img,.b5-grid{min-width:0}.b5-title,.b5-text{overflow-wrap:anywhere}`}</style>
    </section>
};

export const ContentEditorialImageStackPremiumBlock=(props)=><Batch5 {...props} variant="stack" family="content"/>;
export const ContentEditorialImageStackPremiumSchema={"type":"content_editorial_image_stack_premium","title":"Editorial Image Stack","description":"Premium content section with a distinct stack image-led composition.","defaults":{"type":"content_editorial_image_stack_premium","theme":"auto","eyebrow":"Editorial content","heading":"Editorial Image Stack","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ContentAsymmetricStoryPremiumBlock=(props)=><Batch5 {...props} variant="asymmetric" family="content"/>;
export const ContentAsymmetricStoryPremiumSchema={"type":"content_asymmetric_story_premium","title":"Asymmetric Story","description":"Premium content section with a distinct asymmetric image-led composition.","defaults":{"type":"content_asymmetric_story_premium","theme":"auto","eyebrow":"Editorial content","heading":"Asymmetric Story","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ContentMediaManifestoPremiumBlock=(props)=><Batch5 {...props} variant="manifesto" family="content"/>;
export const ContentMediaManifestoPremiumSchema={"type":"content_media_manifesto_premium","title":"Media Manifesto","description":"Premium content section with a distinct manifesto image-led composition.","defaults":{"type":"content_media_manifesto_premium","theme":"auto","eyebrow":"Editorial content","heading":"Media Manifesto","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ContentVisualQuotePremiumBlock=(props)=><Batch5 {...props} variant="quote" family="content"/>;
export const ContentVisualQuotePremiumSchema={"type":"content_visual_quote_premium","title":"Visual Quote","description":"Premium content section with a distinct quote image-led composition.","defaults":{"type":"content_visual_quote_premium","theme":"auto","eyebrow":"Editorial content","heading":"Visual Quote","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesOverlapCardsPremiumBlock=(props)=><Batch5 {...props} variant="overlap" family="features"/>;
export const FeaturesOverlapCardsPremiumSchema={"type":"features_overlap_cards_premium","title":"Features Overlap Cards","description":"Premium features section with a distinct overlap image-led composition.","defaults":{"type":"features_overlap_cards_premium","theme":"auto","eyebrow":"Why it works","heading":"Features Overlap Cards","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesFullbleedPanelsPremiumBlock=(props)=><Batch5 {...props} variant="fullbleed" family="features"/>;
export const FeaturesFullbleedPanelsPremiumSchema={"type":"features_fullbleed_panels_premium","title":"Features Full Bleed Panels","description":"Premium features section with a distinct fullbleed image-led composition.","defaults":{"type":"features_fullbleed_panels_premium","theme":"auto","eyebrow":"Why it works","heading":"Features Full Bleed Panels","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesImageIndexPremiumBlock=(props)=><Batch5 {...props} variant="index" family="features"/>;
export const FeaturesImageIndexPremiumSchema={"type":"features_image_index_premium","title":"Features Image Index","description":"Premium features section with a distinct index image-led composition.","defaults":{"type":"features_image_index_premium","theme":"auto","eyebrow":"Why it works","heading":"Features Image Index","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const FeaturesEditorialMosaicPremiumBlock=(props)=><Batch5 {...props} variant="mosaic" family="features"/>;
export const FeaturesEditorialMosaicPremiumSchema={"type":"features_editorial_mosaic_premium","title":"Features Editorial Mosaic","description":"Premium features section with a distinct mosaic image-led composition.","defaults":{"type":"features_editorial_mosaic_premium","theme":"auto","eyebrow":"Why it works","heading":"Features Editorial Mosaic","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesFullbleedOverlayPremiumBlock=(props)=><Batch5 {...props} variant="overlay" family="services"/>;
export const ServicesFullbleedOverlayPremiumSchema={"type":"services_fullbleed_overlay_premium","title":"Services Full Bleed Overlay","description":"Premium services section with a distinct overlay image-led composition.","defaults":{"type":"services_fullbleed_overlay_premium","theme":"auto","eyebrow":"What we do","heading":"Services Full Bleed Overlay","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesStaggeredMediaPremiumBlock=(props)=><Batch5 {...props} variant="staggered" family="services"/>;
export const ServicesStaggeredMediaPremiumSchema={"type":"services_staggered_media_premium","title":"Services Staggered Media","description":"Premium services section with a distinct staggered image-led composition.","defaults":{"type":"services_staggered_media_premium","theme":"auto","eyebrow":"What we do","heading":"Services Staggered Media","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesImageAccordionPremiumBlock=(props)=><Batch5 {...props} variant="accordion" family="services"/>;
export const ServicesImageAccordionPremiumSchema={"type":"services_image_accordion_premium","title":"Services Image Accordion","description":"Premium services section with a distinct accordion image-led composition.","defaults":{"type":"services_image_accordion_premium","theme":"auto","eyebrow":"What we do","heading":"Services Image Accordion","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ServicesVisualDirectoryPremiumBlock=(props)=><Batch5 {...props} variant="directory" family="services"/>;
export const ServicesVisualDirectoryPremiumSchema={"type":"services_visual_directory_premium","title":"Services Visual Directory","description":"Premium services section with a distinct directory image-led composition.","defaults":{"type":"services_visual_directory_premium","theme":"auto","eyebrow":"What we do","heading":"Services Visual Directory","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioFullbleedProjectsPremiumBlock=(props)=><Batch5 {...props} variant="fullbleed" family="portfolio"/>;
export const PortfolioFullbleedProjectsPremiumSchema={"type":"portfolio_fullbleed_projects_premium","title":"Portfolio Full Bleed Projects","description":"Premium portfolio section with a distinct fullbleed image-led composition.","defaults":{"type":"portfolio_fullbleed_projects_premium","theme":"auto","eyebrow":"Selected work","heading":"Portfolio Full Bleed Projects","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioStaggeredGalleryPremiumBlock=(props)=><Batch5 {...props} variant="staggered" family="portfolio"/>;
export const PortfolioStaggeredGalleryPremiumSchema={"type":"portfolio_staggered_gallery_premium","title":"Portfolio Staggered Gallery","description":"Premium portfolio section with a distinct staggered image-led composition.","defaults":{"type":"portfolio_staggered_gallery_premium","theme":"auto","eyebrow":"Selected work","heading":"Portfolio Staggered Gallery","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioStoryIndexPremiumBlock=(props)=><Batch5 {...props} variant="index" family="portfolio"/>;
export const PortfolioStoryIndexPremiumSchema={"type":"portfolio_story_index_premium","title":"Portfolio Story Index","description":"Premium portfolio section with a distinct index image-led composition.","defaults":{"type":"portfolio_story_index_premium","theme":"auto","eyebrow":"Selected work","heading":"Portfolio Story Index","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const PortfolioMediaLedgerPremiumBlock=(props)=><Batch5 {...props} variant="ledger" family="portfolio"/>;
export const PortfolioMediaLedgerPremiumSchema={"type":"portfolio_media_ledger_premium","title":"Portfolio Media Ledger","description":"Premium portfolio section with a distinct ledger image-led composition.","defaults":{"type":"portfolio_media_ledger_premium","theme":"auto","eyebrow":"Selected work","heading":"Portfolio Media Ledger","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ProofCaseStoryPremiumBlock=(props)=><Batch5 {...props} variant="case" family="proof"/>;
export const ProofCaseStoryPremiumSchema={"type":"proof_case_story_premium","title":"Proof Case Story","description":"Premium proof section with a distinct case image-led composition.","defaults":{"type":"proof_case_story_premium","theme":"auto","eyebrow":"Proof in practice","heading":"Proof Case Story","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const ProofMetricGalleryPremiumBlock=(props)=><Batch5 {...props} variant="metrics" family="proof"/>;
export const ProofMetricGalleryPremiumSchema={"type":"proof_metric_gallery_premium","title":"Proof Metric Gallery","description":"Premium proof section with a distinct metrics image-led composition.","defaults":{"type":"proof_metric_gallery_premium","theme":"auto","eyebrow":"Proof in practice","heading":"Proof Metric Gallery","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const BrandValueCardsPremiumBlock=(props)=><Batch5 {...props} variant="values" family="brand"/>;
export const BrandValueCardsPremiumSchema={"type":"brand_value_cards_premium","title":"Brand Value Cards","description":"Premium brand section with a distinct values image-led composition.","defaults":{"type":"brand_value_cards_premium","theme":"auto","eyebrow":"What guides us","heading":"Brand Value Cards","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};

export const BrandVisualPrinciplesPremiumBlock=(props)=><Batch5 {...props} variant="principles" family="brand"/>;
export const BrandVisualPrinciplesPremiumSchema={"type":"brand_visual_principles_premium","title":"Brand Visual Principles","description":"Premium brand section with a distinct principles image-led composition.","defaults":{"type":"brand_visual_principles_premium","theme":"auto","eyebrow":"What guides us","heading":"Brand Visual Principles","text":"A premium visual section designed to give Luna more meaningful alternatives when a user asks for another layout.","button_label":"Learn more","button_url":"#","secondary_label":"View details","secondary_url":"#","items":[{"title":"Clarity first","text":"A strong visual hierarchy keeps the message easy to understand.","label":"01","image_url":"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=82"},{"title":"Useful contrast","text":"Different scales, surfaces, and imagery create rhythm without noise.","label":"02","image_url":"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1400&q=82"},{"title":"Built to adapt","text":"The structure stays flexible as content and priorities evolve.","label":"03","image_url":"https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=82"},{"title":"Designed to last","text":"A thoughtful system makes future updates easier and more consistent.","label":"04","image_url":"https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1400&q=82"}]}};
