<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ $title }} · {{ $website->name }}</title>
    @if($description)<meta name="description" content="{{ $description }}">@endif
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');
        :root{--p:{{ $palette['primary'] }};--a:{{ $palette['accent'] }};--s:{{ $palette['surface'] }};--t:{{ $palette['text'] }};--m:{{ $palette['muted'] }};--b:{{ $palette['border'] }};--bg:{{ $palette['background'] }}}
        *{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,var(--bg),color-mix(in srgb,var(--p) 4%,var(--bg)));color:var(--t);font-family:Manrope,system-ui,sans-serif}.wrap{width:min(1180px,calc(100% - 40px));margin:auto}a{color:inherit;text-decoration:none}img{display:block;max-width:100%}.shell{background:var(--bg)}
        .fallback-header{border-bottom:1px solid var(--b);background:color-mix(in srgb,var(--bg) 94%,transparent);backdrop-filter:blur(12px)}.fallback-header .wrap{display:flex;justify-content:space-between;align-items:center;padding:18px 0}.brand{font-weight:700}.fallback-header nav{display:flex;gap:20px;font-size:14px}.fallback-footer{margin-top:72px;background:color-mix(in srgb,var(--p) 9%,#0f172a);color:#e2e8f0;padding:34px 0}.fallback-footer .wrap{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}
        .content-hero{padding:72px 0 48px;border-bottom:1px solid var(--b);background:linear-gradient(135deg,color-mix(in srgb,var(--p) 14%,var(--bg)),var(--bg) 66%)}.kicker{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.22em;color:var(--p)}h1,h2,h3{font-weight:700;letter-spacing:-.035em}h1{font-size:clamp(40px,6vw,68px);line-height:1.02;margin:14px 0}.hero-copy{max-width:720px;color:var(--m);font-size:17px;line-height:1.75}.filters{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.pill{display:inline-flex;align-items:center;min-height:38px;padding:8px 13px;border:1px solid var(--b);border-radius:999px;background:var(--bg);font-size:13px;font-weight:600}.pill.active{background:var(--p);border-color:var(--p);color:white}
        .archive{padding:44px 0 72px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.card{overflow:hidden;border:1px solid var(--b);border-radius:24px;background:var(--bg);box-shadow:0 16px 45px rgba(15,23,42,.055);transition:.2s}.card:hover{transform:translateY(-3px);box-shadow:0 22px 56px rgba(15,23,42,.09)}.card-media{aspect-ratio:16/10;background:var(--s);overflow:hidden}.card-media img{width:100%;height:100%;object-fit:cover}.card-body{padding:22px}.meta{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.15em;color:var(--p)}.card h2{font-size:22px;line-height:1.18;margin:10px 0}.card p{color:var(--m);font-size:14px;line-height:1.65}.read{display:inline-flex;margin-top:14px;font-size:14px;font-weight:700}.empty{padding:48px;text-align:center;border:1px dashed var(--b);border-radius:24px;color:var(--m)}
        .entry{padding:44px 0 72px}.breadcrumb{display:flex;gap:9px;align-items:center;font-size:13px;color:var(--m);margin-bottom:30px}.entry-head{max-width:880px;margin-bottom:28px}.entry-head h1{font-size:clamp(42px,6vw,72px)}.entry-deck{font-size:19px;line-height:1.7;color:var(--m);max-width:760px}.entry-meta{display:flex;gap:12px;flex-wrap:wrap;margin-top:20px;color:var(--m);font-size:13px}.hero-image{overflow:hidden;border:1px solid var(--b);border-radius:30px;background:var(--s);box-shadow:0 24px 70px rgba(15,23,42,.09);margin:32px 0}.hero-image img{width:100%;max-height:680px;object-fit:cover}.entry-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:54px;align-items:start}.prose{font-size:17px;line-height:1.85;color:color-mix(in srgb,var(--t) 84%,var(--m))}.prose p{margin:0 0 1.35em}.prose h2,.prose h3{color:var(--t);margin:1.7em 0 .65em}.sidebar{position:sticky;top:24px}.info-card{border:1px solid var(--b);border-radius:22px;background:var(--bg);padding:20px;box-shadow:0 12px 36px rgba(15,23,42,.045)}.info-row{padding:11px 0;border-bottom:1px solid var(--b)}.info-row:last-child{border-bottom:0}.info-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.15em;color:var(--m)}.info-value{margin-top:4px;font-size:14px;font-weight:600}.gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:34px}.gallery img{width:100%;height:190px;object-fit:cover;border:1px solid var(--b);border-radius:18px}.related{padding:64px 0;border-top:1px solid var(--b)}.related h2{font-size:34px;margin:0 0 26px}.related .grid{grid-template-columns:repeat(3,minmax(0,1fr))}
        @media(max-width:900px){.grid,.related .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.entry-layout{grid-template-columns:1fr}.sidebar{position:static}.gallery{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.wrap{width:min(100% - 24px,1180px)}.content-hero{padding:50px 0 34px}.archive,.entry{padding-top:30px}.grid,.related .grid{grid-template-columns:1fr}.entry-head h1{font-size:40px}.gallery{grid-template-columns:1fr}.gallery img{height:auto}.fallback-header nav{display:none}}
    </style>
</head>
<body>
@if($useSiteShell)<div class="shell">{!! $siteHeaderHtml !!}</div>@else<header class="fallback-header"><div class="wrap"><a class="brand" href="{{ $archiveUrl($contentType) }}">{{ $website->name }}</a><nav><a href="{{ $archiveUrl($contentType) }}">{{ $contentType->name }}</a></nav></div></header>@endif

@if($viewMode === 'archive')
<section class="content-hero"><div class="wrap"><div class="kicker">{{ $contentType->singular_name }} archive</div><h1>{{ $contentType->name }}</h1><p class="hero-copy">{{ $contentType->description ?: 'Explore the latest '.$contentType->name.'.' }}</p>@if($categories->isNotEmpty() || $tags->isNotEmpty())<div class="filters"><a class="pill {{ !$activeCategory && !$activeTag ? 'active' : '' }}" href="{{ $archiveUrl($contentType) }}">All</a>@foreach($categories as $category)<a class="pill {{ $activeCategory === $category ? 'active' : '' }}" href="{{ $archiveUrl($contentType) }}?category={{ rawurlencode($category) }}">{{ $category }}</a>@endforeach @foreach($tags->take(6) as $tag)<a class="pill {{ $activeTag === $tag ? 'active' : '' }}" href="{{ $archiveUrl($contentType) }}?tag={{ rawurlencode($tag) }}">#{{ $tag }}</a>@endforeach</div>@endif</div></section>
<section class="archive"><div class="wrap">@if($entries->isEmpty())<div class="empty">No published {{ strtolower($contentType->name) }} yet.</div>@else<div class="grid">@foreach($entries as $entry)<article class="card"><a class="card-media" href="{{ $entryUrl($contentType,$entry) }}">@if($entry->featured_image_url)<img src="{{ $assetUrl($entry->featured_image_url) }}" alt="{{ $entry->title }}">@endif</a><div class="card-body"><div class="meta">{{ $entry->category ?: $contentType->singular_name }}@if($entry->is_featured) · Featured @endif</div><h2><a href="{{ $entryUrl($contentType,$entry) }}">{{ $entry->title }}</a></h2><p>{{ $entry->excerpt }}</p><a class="read" href="{{ $entryUrl($contentType,$entry) }}">Read more →</a></div></article>@endforeach</div>@endif</div></section>
@else
<section class="entry"><div class="wrap"><div class="breadcrumb"><a href="{{ $archiveUrl($contentType) }}">{{ $contentType->name }}</a><span>›</span><span>{{ $activeEntry->title }}</span></div><header class="entry-head"><div class="kicker">{{ $activeEntry->category ?: $contentType->singular_name }}@if($activeEntry->is_featured) · Featured @endif</div><h1>{{ $activeEntry->title }}</h1>@if($activeEntry->excerpt)<p class="entry-deck">{{ $activeEntry->excerpt }}</p>@endif<div class="entry-meta">@if($activeEntry->published_at)<span>{{ $activeEntry->published_at->format('M j, Y') }}</span>@endif @foreach(($activeEntry->tags ?: []) as $tag)<span>#{{ $tag }}</span>@endforeach</div></header>@if($activeEntry->featured_image_url)<div class="hero-image"><img src="{{ $assetUrl($activeEntry->featured_image_url) }}" alt="{{ $activeEntry->title }}"></div>@endif<div class="entry-layout"><article class="prose">{!! nl2br(e($activeEntry->content ?: $activeEntry->excerpt)) !!}@if(is_array($activeEntry->gallery) && count($activeEntry->gallery))<div class="gallery">@foreach($activeEntry->gallery as $item)@php($src=is_array($item)?($item['url']??$item['src']??''):$item)@if($src)<img src="{{ $assetUrl($src) }}" alt="{{ is_array($item)?($item['alt']??$activeEntry->title):$activeEntry->title }}">@endif @endforeach</div>@endif</article><aside class="sidebar"><div class="info-card"><div class="meta">{{ $contentType->singular_name }} details</div>@if($activeEntry->category)<div class="info-row"><div class="info-label">Category</div><div class="info-value">{{ $activeEntry->category }}</div></div>@endif @foreach(($contentType->schema ?: []) as $field)@php($value=data_get($activeEntry->custom_fields ?: [],$field['key']??''))@if($value !== null && $value !== '' && $value !== false)<div class="info-row"><div class="info-label">{{ $field['label'] ?? $field['key'] ?? 'Detail' }}</div><div class="info-value">@if(($field['type']??'')==='url')<a href="{{ $value }}" target="_blank" rel="noopener">Open link ↗</a>@elseif(($field['type']??'')==='date'){{ \Illuminate\Support\Carbon::parse($value)->format('M j, Y') }}@elseif(($field['type']??'')==='boolean'){{ $value ? 'Yes' : 'No' }}@else{{ $value }}@endif</div></div>@endif @endforeach</div></aside></div></div></section>
@if($relatedEntries->isNotEmpty())<section class="related"><div class="wrap"><div class="kicker">Keep exploring</div><h2>Related {{ strtolower($contentType->name) }}</h2><div class="grid">@foreach($relatedEntries as $entry)<article class="card"><a class="card-media" href="{{ $entryUrl($contentType,$entry) }}">@if($entry->featured_image_url)<img src="{{ $assetUrl($entry->featured_image_url) }}" alt="{{ $entry->title }}">@endif</a><div class="card-body"><div class="meta">{{ $entry->category ?: $contentType->singular_name }}</div><h3><a href="{{ $entryUrl($contentType,$entry) }}">{{ $entry->title }}</a></h3><p>{{ $entry->excerpt }}</p><a class="read" href="{{ $entryUrl($contentType,$entry) }}">Read next →</a></div></article>@endforeach</div></div></section>@endif
@endif

@if($useSiteShell)<div class="shell">{!! $siteFooterHtml !!}</div>@else<footer class="fallback-footer"><div class="wrap"><strong>{{ $website->name }}</strong><span>Powered by Cosmic CMS</span></div></footer>@endif
</body></html>
