import { useEffect, useMemo, useRef, useState } from "react";
import { usePage } from "@inertiajs/react";
import { EditableText } from "../Shared/EditableText";
import { EditableButton } from "../Shared/EditableButton";
import { EditableImage } from "../Shared/EditableImage";
import { EditableImageGallery } from "../Shared/EditableImageGallery";
import { colorFamilies } from "../../../../theme/colorFamilies";
import { getSectionBackgroundClass } from "../../../../theme/Theme";
import { getHeroThemeState } from "../../../../theme/heroTheme";

import { sparkTw, sparkTwPath } from "../Shared/sparkTailwindRuntime";
const base = {
  eyebrow: "MOTION, WITH PURPOSE",
  heading: "Add depth from the start.",
  text: "Distinct interaction and restrained motion create a memorable opening without overwhelming the message.",
  primary_label: "Start a project", primary_url: "/contact",
  secondary_label: "Explore more", secondary_url: "/about",
  image_url: "/storage/cms-images/background/background-1.avif",
  image_url_2: "/storage/cms-images/background/background-2.avif",
  image_url_3: "/storage/cms-images/background/background-3.avif",
  overlayOpacity: 52,
  motionStrength: 24,
};

function schema(type,title,purpose,aliases,defaults={},fields=[]) { return {
  type,title,category:"Hero",purpose,description:`${title} is a Pro animated hero with lightweight motion and reduced-motion safeguards.`,
  access:"pro",isPremium:true,badge:"PRO",credits:175,tags:["hero","premium","animated","motion",...aliases],aliases:[title.toLowerCase(),...aliases],
  defaults:{...base,...defaults},fields:[
    {type:"text",name:"eyebrow",label:"Eyebrow"},{type:"textarea",name:"heading",label:"Heading"},{type:"textarea",name:"text",label:"Description"},
    {type:"button",name:"primary",label:"Primary Button"},{type:"button",name:"secondary",label:"Secondary Button"},
    {type:"image",name:"image_url",label:"Primary Image"},{type:"image",name:"image_url_2",label:"Secondary Image"},{type:"image",name:"image_url_3",label:"Third Image"},
    {type:"range",name:"overlayOpacity",label:"Overlay Opacity",min:20,max:85,step:5},...fields
  ]
};}

export const HeroImageMaskRevealPremiumSchema=schema("hero_image_mask_reveal_premium","Image Mask Reveal Hero","Reveals the hero image through a moving rounded mask for editorial and premium visual brands.",["image mask reveal","masked hero","image reveal","editorial motion","fashion hero"]);
export const HeroStackedCardsPremiumSchema=schema("hero_stacked_cards_premium","Stacked Cards Hero","Cycles layered image cards with dimensional motion for portfolios, services, and product stories.",["stacked cards","card stack","layered cards","portfolio hero","product cards"]);
export const HeroPerspectiveCarouselPremiumSchema=schema("hero_perspective_carousel_premium","Perspective Carousel Hero","Rotates a three-card visual carousel with subtle perspective depth.",["perspective carousel","3d carousel","image carousel","visual showcase","portfolio slider"]);
export const HeroBeforeAfterPremiumSchema=schema("hero_before_after_premium","Before / After Hero","Adds an interactive draggable before-and-after image comparison for transformation-led businesses.",["before after","comparison slider","image comparison","renovation hero","beauty transformation"],{splitPosition:52},[{type:"range",name:"splitPosition",label:"Initial Split",min:20,max:80,step:1}]);
export const HeroScrollMorphPremiumSchema=schema("hero_scroll_morph_premium","Scroll Morph Hero","Morphs the hero artwork from a compact card into a wide cinematic frame as the page scrolls.",["scroll morph","morphing hero","scroll animation","cinematic frame","interactive editorial"],{motionStrength:28},[{type:"range",name:"motionStrength",label:"Morph Strength",min:10,max:40,step:2}]);
export const HeroGlassOrbPremiumSchema=schema("hero_glass_orb_premium","Glass Orb Hero","Floats translucent glass orbs around a luminous premium hero.",["glass orb","glassmorphism hero","floating orb","luxury tech hero","gradient glass"]);
export const HeroParticleConstellationPremiumSchema=schema("hero_particle_constellation_premium","Particle Constellation Hero","Uses a lightweight canvas constellation behind conversion copy for AI, science, and technology brands.",["particle constellation","particles hero","network hero","ai particles","connected dots"],{particleCount:36},[{type:"range",name:"particleCount",label:"Particle Count",min:18,max:54,step:3}]);

function heroVisualState(block, globalTheme) {
  const state = getHeroThemeState(block, globalTheme);
  const primaryKey = typeof globalTheme === "string" ? globalTheme : (globalTheme?.primary || "midnight");
  const primaryTheme = colorFamilies[primaryKey] || colorFamilies.midnight;
  return { ...state, primaryTheme, sectionClass: state.isLight ? `${state.theme.bg} ${state.theme.text}` : (state.isPrimary ? `${getSectionBackgroundClass(primaryKey, "deep")} ${primaryTheme.text}` : "bg-slate-950 text-white") };
}

function heroGradient(globalTheme) {
  const primaryKey = typeof globalTheme === "string" ? globalTheme : (globalTheme?.primary || "midnight");
  return (colorFamilies[primaryKey] || colorFamilies.midnight)?.gradient || colorFamilies.midnight.gradient;
}

function Copy({data,onUpdate,headingNode,visual,block}) { const v=visual||heroVisualState(data,null); const primary=v.isPrimary?"bg-white text-slate-950 hover:bg-white/90":`${v.primaryTheme.bg} ${v.primaryTheme.text}`; const secondary=v.isLight?`border-slate-300 bg-white/70 ${v.theme.text}`:"border-white/30 bg-white/10 text-white"; return <div className={sparkTw(block, "content", "max-w-3xl")}>
  <EditableText value={data.eyebrow} className={sparkTw(block, "eyebrow", `text-xs font-normal uppercase tracking-[0.32em] ${v.isLight?v.theme.sub:"text-white/70"}`)} onSave={v=>onUpdate({eyebrow:v})}/>
  {headingNode || <EditableText value={data.heading} cosmicType="h1" className={sparkTw(block, "heading", `mt-6 block text-[clamp(3rem,6.2vw,5.75rem)] font-semibold leading-[0.94] tracking-[-0.05em] ${v.isLight?v.theme.text:"text-white"}`)} onSave={v=>onUpdate({heading:v})}/>} 
  <EditableText value={data.text} className={sparkTw(block, "description", `mt-7 block max-w-2xl text-base leading-8 sm:text-lg ${v.isLight?v.theme.sub:"text-white/75"}`)} onSave={v=>onUpdate({text:v})}/>
  <div className={sparkTw(block, "actions", "mt-9 flex flex-wrap gap-3")}><EditableButton label={data.primary_label} url={data.primary_url} onSave={(label,url)=>onUpdate({primary_label:label,primary_url:url})} className={sparkTw(block, "primary_button", `rounded-full px-6 py-3.5 text-sm font-bold ${primary}`)}/><EditableButton label={data.secondary_label} url={data.secondary_url} onSave={(label,url)=>onUpdate({secondary_label:label,secondary_url:url})} className={sparkTw(block, "secondary_button", `rounded-full border px-6 py-3.5 text-sm font-bold backdrop-blur ${secondary}`)}/></div>
</div>; }

const Overlay=({opacity=54,visual,block})=><><div className={sparkTw(block, "overlay_color", "absolute inset-0")} style={{backgroundColor:visual?.isLight?"#ffffff":"#020617",opacity:visual?.isLight ? .92 :Math.max(20,Math.min(85,Number(opacity)||54))/100}}/><div className={sparkTw(block, "overlay", `absolute inset-0 ${visual?.isLight?"bg-gradient-to-r from-white/80 via-white/40 to-white/15":"bg-gradient-to-r from-slate-950/75 via-slate-950/20 to-slate-950/10"}`)}/></>;

export function HeroImageMaskRevealPremiumBlock({block,blockIndex,onUpdate,globalTheme}) {
  const data={...HeroImageMaskRevealPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const {props}=usePage(); const websiteId=props.page?.website_id||props.website?.id; const imageRef=useRef(null);
  const edit=(event)=>{if(event.target.closest("button, a, input, textarea, select, label, [contenteditable='true'], [role='button'], [data-cosmic-edit-control]"))return;imageRef.current?.openEditor();};
  return <section onClick={edit} data-cosmic-editable-hero-media="true" className={sparkTw(block, "section", `relative isolate min-h-[var(--cosmic-hero-fold-height)] cursor-pointer overflow-hidden ${visual.sectionClass}`)} data-cosmic-hero-theme={visual.requestedTheme}><style>{`@keyframes cosmicMaskReveal{0%{clip-path:inset(16% 28% 16% 28% round 36px);transform:scale(1.08)}100%{clip-path:inset(0 0 0 0 round 0);transform:scale(1)}}@media(prefers-reduced-motion:reduce){.cosmic-mask-reveal{animation:none!important;clip-path:none!important}}`}</style><div className={`${sparkTw(block, "media", "absolute inset-0")} cosmic-mask-reveal`.trim()} style={{animation:"cosmicMaskReveal 1.35s cubic-bezier(.22,1,.36,1) both"}}><EditableImage ref={imageRef} websiteId={websiteId} blockIndex={blockIndex} src={data.image_url} showOverlay={false} isBackground blockType={block.type} className={sparkTw(block, "image", "absolute inset-0 h-full w-full")} onSave={v=>onUpdate({image_url:v})}/></div><Overlay block={block} opacity={data.overlayOpacity} visual={visual}/><div className={sparkTw(block, "wrapper", "relative z-10 mx-auto flex min-h-[var(--cosmic-hero-fold-height)] max-w-7xl items-end px-6 py-0 sm:px-10 lg:px-14 lg:py-24")}><Copy block={block} data={data} onUpdate={onUpdate} visual={visual}/></div></section>;
}

export function HeroStackedCardsPremiumBlock({block,blockIndex,onUpdate,globalTheme}) {
  const data={...HeroStackedCardsPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const [active,setActive]=useState(0); const root=useRef(null); const galleryRef=useRef(null); const {props}=usePage(); const websiteId=props.page?.website_id||props.website?.id; const images=[data.image_url,data.image_url_2,data.image_url_3].filter(Boolean);
  useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const el=root.current;if(!el)return;let id=0;const stop=()=>{if(id){clearInterval(id);id=0;}};const start=()=>{if(!id)id=setInterval(()=>setActive(v=>(v+1)%images.length),3200);};const io=new IntersectionObserver(([entry])=>entry?.isIntersecting?start():stop(),{rootMargin:"120px"});io.observe(el);return()=>{stop();io.disconnect();};},[images.length]);
  const saveImages=(next)=>onUpdate({image_url:next[0]||'',image_url_2:next[1]||'',image_url_3:next[2]||''});
  const edit=(event)=>{if(event.target.closest("button, a, input, textarea, select, label, [contenteditable='true'], [role='button'], [data-cosmic-edit-control]"))return;galleryRef.current?.openEditor();};
  return <section ref={root} onClick={edit} data-cosmic-editable-hero-media="true" className={sparkTw(block, "section", `relative overflow-hidden ${visual.sectionClass}`)} data-cosmic-hero-theme={visual.requestedTheme}><div className={sparkTw(block, "wrapper", "mx-auto grid min-h-[var(--cosmic-hero-fold-height)] max-w-7xl items-center gap-14 px-6 py-0 lg:grid-cols-[.9fr_1.1fr] lg:px-14")}><Copy block={block} data={data} onUpdate={onUpdate} visual={visual}/><div className={sparkTw(block, "media_stage", "relative h-[460px] sm:h-[540px]")}>{images.map((src,i)=>{const offset=(i-active+images.length)%images.length;return <div key={i} className={sparkTwPath(block, ["images", i], "card", "absolute inset-x-[8%] top-1/2 overflow-hidden rounded-[30px] border border-white/15 bg-white/10 p-2 shadow-2xl transition-all duration-700")} style={{transform:`translateY(calc(-50% + ${offset*26}px)) translateX(${offset*18}px) scale(${1-offset*.055})`,opacity:1-offset*.22,zIndex:10-offset}}><img src={src} alt="" className={sparkTwPath(block, ["images", i], "image", "aspect-[16/11] w-full rounded-[24px] object-cover")} loading={i?"lazy":"eager"}/></div>})}<div className={sparkTw(block, "progress", "absolute bottom-0 left-1/2 z-20 flex -translate-x-1/2 gap-2")}>{images.map((_,i)=><button key={i} type="button" aria-label={`Show image ${i+1}`} onClick={()=>setActive(i)} className={`${sparkTwPath(block, ["images", i], "dot", "h-2.5 rounded-full transition-all")} ${i===active?'w-8 bg-white':'w-2.5 bg-white/35'}`.trim()}/>)}</div></div></div><EditableImageGallery ref={galleryRef} websiteId={websiteId} images={images} maxItems={3} title="Stacked Cards images" onSave={saveImages}/></section>;
}

export function HeroPerspectiveCarouselPremiumBlock({block,blockIndex,onUpdate,globalTheme}) {
 const data={...HeroPerspectiveCarouselPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const gradient=heroGradient(globalTheme); const [active,setActive]=useState(0); const root=useRef(null); const galleryRef=useRef(null); const {props}=usePage(); const websiteId=props.page?.website_id||props.website?.id; const images=[data.image_url,data.image_url_2,data.image_url_3].filter(Boolean);
 useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const el=root.current;if(!el)return;let id=0;const stop=()=>{if(id){clearInterval(id);id=0;}};const start=()=>{if(!id)id=setInterval(()=>setActive(v=>(v+1)%images.length),3600);};const io=new IntersectionObserver(([entry])=>entry?.isIntersecting?start():stop(),{rootMargin:"120px"});io.observe(el);return()=>{stop();io.disconnect();};},[images.length]);
 const saveImages=(next)=>onUpdate({image_url:next[0]||'',image_url_2:next[1]||'',image_url_3:next[2]||''});
 const edit=(event)=>{if(event.target.closest("button, a, input, textarea, select, label, [contenteditable='true'], [role='button'], [data-cosmic-edit-control]"))return;galleryRef.current?.openEditor();};
 const handleCardClick=(event,index)=>{event.stopPropagation();if(index===active){galleryRef.current?.openEditor();return;}setActive(index);};
 return <section ref={root} onClick={edit} className={sparkTw(block, "section", `relative isolate overflow-hidden ${visual.sectionClass}`)} data-cosmic-hero-theme={visual.requestedTheme}><div className={sparkTw(block, "background_effect", `absolute inset-0 ${visual.isLight?"opacity-20":"opacity-100"}`)} style={{backgroundImage:`radial-gradient(circle at 75% 20%, ${gradient.glowSoft}, transparent 34%)`}}/><div className={sparkTw(block, "wrapper", "relative mx-auto grid min-h-[var(--cosmic-hero-fold-height)] max-w-7xl items-center gap-12 px-6 py-0 lg:grid-cols-[.85fr_1.15fr] lg:px-14")}><Copy block={block} data={data} onUpdate={onUpdate} visual={visual}/><div className={sparkTw(block, "media_stage", "relative h-[470px] [perspective:1200px]")} data-cosmic-editable-hero-media="true">{images.map((src,i)=>{let d=(i-active+images.length)%images.length;if(d===images.length-1)d=-1;return <button type="button" key={i} data-cosmic-edit-control onClick={(event)=>handleCardClick(event,i)} aria-label={i===active?`Edit image ${i+1}`:`Show image ${i+1}`} className={`${sparkTwPath(block, ["images", i], "card", "absolute left-1/2 top-1/2 w-[70%] overflow-hidden rounded-[28px] border border-white/15 bg-slate-900 p-2 shadow-2xl transition-all duration-700")} ${i===active?'cursor-pointer':'cursor-default'}`.trim()} style={{transform:`translate(-50%,-50%) translateX(${d*38}%) translateZ(${d===0?70:-70}px) rotateY(${d*-18}deg) scale(${d===0?1:.82})`,opacity:d===0?1:.55,zIndex:d===0?20:10}}><img src={src} alt="" className={sparkTwPath(block, ["images", i], "image", "aspect-[4/3] w-full rounded-[22px] object-cover")} loading={i?"lazy":"eager"}/></button>})}</div></div><EditableImageGallery ref={galleryRef} websiteId={websiteId} images={images} maxItems={3} title="Perspective Carousel images" onSave={saveImages}/></section>;
}

export function HeroBeforeAfterPremiumBlock({block,blockIndex,onUpdate,globalTheme}) {
 const data={...HeroBeforeAfterPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const root=useRef(null); const galleryRef=useRef(null); const [split,setSplit]=useState(Number(data.splitPosition||52)); const drag=useRef(false); const moved=useRef(false); const startX=useRef(0); const {props}=usePage(); const websiteId=props.page?.website_id||props.website?.id; const images=[data.image_url,data.image_url_2].filter(Boolean); const update=e=>{if(!root.current)return;const r=root.current.getBoundingClientRect();setSplit(Math.max(4,Math.min(96,((e.clientX-r.left)/r.width)*100)));};
 const saveImages=(next)=>onUpdate({image_url:next[0]||'',image_url_2:next[1]||next[0]||''});
 const beginDrag=e=>{drag.current=true;moved.current=false;startX.current=e.clientX;e.currentTarget.setPointerCapture?.(e.pointerId);}; const moveDrag=e=>{if(!drag.current)return;if(Math.abs(e.clientX-startX.current)>4)moved.current=true;update(e);}; const endDrag=()=>{drag.current=false;if(!moved.current)galleryRef.current?.openEditor();};
 return <section className={sparkTw(block, "section", `relative overflow-hidden ${visual.sectionClass}`)} data-cosmic-hero-theme={visual.requestedTheme}><div className={sparkTw(block, "wrapper", "mx-auto grid min-h-[var(--cosmic-hero-fold-height)] max-w-7xl items-center gap-12 px-6 py-0 lg:grid-cols-[.82fr_1.18fr] lg:px-14")}><Copy block={block} data={data} onUpdate={onUpdate} visual={visual}/><div ref={root} data-cosmic-editable-hero-media="true" className={sparkTw(block, "comparison", "relative aspect-[4/3] cursor-ew-resize select-none overflow-hidden rounded-[32px] border border-white/15 shadow-2xl")} onPointerDown={beginDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={()=>{drag.current=false;moved.current=false;}}><img src={data.image_url} alt="Before" className={sparkTw(block, "before_image", "absolute inset-0 h-full w-full object-cover")}/><div className={sparkTw(block, "after_clip", "absolute inset-y-0 left-0 overflow-hidden")} style={{width:`${split}%`}}><img src={data.image_url_2} alt="After" className={sparkTw(block, "after_image", "absolute inset-y-0 left-0 h-full max-w-none object-cover")} style={{width:`${root.current?.clientWidth||760}px`}}/></div><div className={sparkTw(block, "divider", "absolute inset-y-0 w-px bg-white")} style={{left:`${split}%`}}><div className={sparkTw(block, "handle", "absolute left-1/2 top-1/2 grid h-12 w-12 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-white/40 bg-slate-950/80 text-lg shadow-xl backdrop-blur")}>↔</div></div><span className={sparkTw(block, "before_label", "pointer-events-none absolute bottom-4 left-4 rounded-full bg-slate-950/70 px-3 py-1 text-xs font-bold uppercase tracking-wider")}>Before</span><span className={sparkTw(block, "after_label", "pointer-events-none absolute bottom-4 right-4 rounded-full bg-white/90 px-3 py-1 text-xs font-bold uppercase tracking-wider text-slate-950")}>After</span></div></div><EditableImageGallery ref={galleryRef} websiteId={websiteId} images={images} minItems={2} maxItems={2} title="Before / After images" onSave={saveImages}/></section>;
}

export function HeroScrollMorphPremiumBlock({block,blockIndex,onUpdate,globalTheme}) {
 const data={...HeroScrollMorphPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const root=useRef(null); const frame=useRef(null); const {props}=usePage(); const websiteId=props.page?.website_id||props.website?.id; useEffect(()=>{const el=root.current,f=frame.current;if(!el||!f)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');if(reduced.matches)return;let raf=0;const run=()=>{const r=el.getBoundingClientRect();if(r.bottom<0||r.top>window.innerHeight)return;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const p=Math.max(0,Math.min(1,(window.innerHeight-r.top)/(window.innerHeight+r.height*.45)));const s=Number(data.motionStrength||28);f.style.transform=`scale(${.78+p*.22})`;f.style.borderRadius=`${Math.max(0,36-p*s)}px`;});};run();addEventListener('scroll',run,{passive:true});addEventListener('resize',run);return()=>{removeEventListener('scroll',run);removeEventListener('resize',run);cancelAnimationFrame(raf);};},[data.motionStrength]);
 return <section ref={root} className={sparkTw(block, "section", `relative min-h-[110svh] overflow-hidden ${visual.sectionClass}`)} data-cosmic-hero-theme={visual.requestedTheme}><div className={sparkTw(block, "sticky_stage", "sticky top-0 flex min-h-[var(--cosmic-hero-fold-height)] items-center")}><div className={sparkTw(block, "wrapper", "mx-auto grid w-full max-w-7xl items-center gap-12 px-6 py-0 lg:grid-cols-[.82fr_1.18fr] lg:px-14")}><Copy block={block} data={data} onUpdate={onUpdate} visual={visual}/><div ref={frame} className={sparkTw(block, "media_frame", "origin-center overflow-hidden border border-white/15 shadow-2xl will-change-transform")} style={{transform:'scale(.78)',borderRadius:36}}><EditableImage websiteId={websiteId} blockIndex={blockIndex} src={data.image_url} showOverlay={false} blockType={block.type} className={sparkTw(block, "image", "aspect-[4/3] w-full")} onSave={v=>onUpdate({image_url:v})}/></div></div></div></section>;
}

export function HeroGlassOrbPremiumBlock({block,onUpdate,globalTheme}) { const data={...HeroGlassOrbPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const gradient=heroGradient(globalTheme); return <section className={sparkTw(block, "section", `relative isolate min-h-[var(--cosmic-hero-fold-height)] overflow-hidden ${visual.sectionClass}`)} data-cosmic-hero-theme={visual.requestedTheme}><style>{`@keyframes cosmicOrbA{50%{transform:translate3d(30px,-28px,0) scale(1.08)}}@keyframes cosmicOrbB{50%{transform:translate3d(-26px,24px,0) scale(.94)}}@media(prefers-reduced-motion:reduce){.cosmic-glass-orb{animation:none!important}}`}</style><div className={sparkTw(block, "background_effect", `absolute inset-0 ${visual.isLight?"opacity-20":"opacity-100"}`)} style={{backgroundImage:`radial-gradient(circle at 30% 20%, ${gradient.glowSoft}, transparent 30%), radial-gradient(circle at 80% 70%, ${gradient.glowStrong}, transparent 34%)`}}/><div className={`${sparkTw(block, "orb_large", "absolute right-[9%] top-[14%] h-64 w-64 rounded-full border border-white/20 bg-white/10 shadow-[inset_0_0_70px_rgba(255,255,255,.12)] backdrop-blur-2xl")} cosmic-glass-orb`.trim()} style={{animation:'cosmicOrbA 8s ease-in-out infinite'}}/><div className={`${sparkTw(block, "orb_medium", "absolute bottom-[8%] right-[30%] h-40 w-40 rounded-full border border-white/15 shadow-[inset_0_0_50px_rgba(255,255,255,.1)] backdrop-blur-xl")} cosmic-glass-orb`.trim()} style={{animation:'cosmicOrbB 7s ease-in-out infinite',backgroundColor:gradient.glowSoft}}/><div className={`${sparkTw(block, "orb_small", "absolute left-[55%] top-[42%] h-24 w-24 rounded-full border border-white/15 backdrop-blur-xl")} cosmic-glass-orb`.trim()} style={{animation:'cosmicOrbA 6s ease-in-out -1.5s infinite',backgroundColor:gradient.glowSoft}}/><div className={sparkTw(block, "wrapper", "relative z-10 mx-auto flex min-h-[var(--cosmic-hero-fold-height)] w-full max-w-[88rem] items-center px-6 py-14 sm:py-16 lg:px-14 lg:py-20")}><Copy block={block} data={data} onUpdate={onUpdate} visual={visual}/></div></section>; }

export function HeroParticleConstellationPremiumBlock({block,onUpdate,globalTheme}) { const data={...HeroParticleConstellationPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const gradient=heroGradient(globalTheme); const canvasRef=useRef(null); const root=useRef(null); const particles=useMemo(()=>Math.max(18,Math.min(54,Number(data.particleCount||36))),[data.particleCount]); useEffect(()=>{const canvas=canvasRef.current,host=root.current;if(!canvas||!host)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const ctx=canvas.getContext('2d');let raf=0,ro,visible=true;const points=Array.from({length:particles},(_,i)=>({x:(i*73%997)/997,y:(i*137%991)/991,vx:((i%5)-2)*.00008,vy:(((i*3)%5)-2)*.00008}));const draw=()=>{cancelAnimationFrame(raf);const dpr=Math.min(2,devicePixelRatio||1),w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);ctx.fillStyle=visual.isLight?'rgba(71,85,105,.72)':gradient.glow;ctx.strokeStyle=visual.isLight?'rgba(100,116,139,.18)':gradient.glowSoft;for(const p of points){if(!reduced.matches&&visible){p.x=(p.x+p.vx+1)%1;p.y=(p.y+p.vy+1)%1}ctx.beginPath();ctx.arc(p.x*w,p.y*h,1.4,0,Math.PI*2);ctx.fill()}for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const a=points[i],b=points[j],dx=(a.x-b.x)*w,dy=(a.y-b.y)*h,dist=Math.hypot(dx,dy);if(dist<130){ctx.globalAlpha=(1-dist/130)*.75;ctx.beginPath();ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.stroke();ctx.globalAlpha=1}}if(!reduced.matches&&visible)raf=requestAnimationFrame(draw)};const io=new IntersectionObserver(([entry])=>{visible=Boolean(entry?.isIntersecting);if(visible)draw();else cancelAnimationFrame(raf);},{rootMargin:"120px"});io.observe(host);draw();ro=new ResizeObserver(()=>{if(visible||reduced.matches)draw();});ro.observe(canvas);return()=>{cancelAnimationFrame(raf);io.disconnect();ro?.disconnect();};},[particles,visual.isLight,gradient.glow,gradient.glowSoft]); return <section ref={root} className={sparkTw(block, "section", `relative isolate min-h-[var(--cosmic-hero-fold-height)] overflow-hidden ${visual.sectionClass}`)} data-cosmic-hero-theme={visual.requestedTheme}><canvas ref={canvasRef} className={sparkTw(block, "canvas", "absolute inset-0 h-full w-full opacity-80")} aria-hidden="true"/><div className={sparkTw(block, "background_effect", `absolute inset-0 ${visual.isLight?"opacity-20":"opacity-100"}`)} style={{backgroundImage:`radial-gradient(circle at 70% 25%, ${gradient.glowSoft}, transparent 35%)`}}/><div className={sparkTw(block, "wrapper", "relative z-10 mx-auto flex min-h-[var(--cosmic-hero-fold-height)] w-full max-w-[88rem] items-center px-6 py-14 sm:py-16 lg:px-14 lg:py-20")}><Copy block={block} data={data} onUpdate={onUpdate} visual={visual}/></div></section>; }
