import { useEffect, useMemo, useRef, useState } from "react";
import { usePage } from "@inertiajs/react";
import { EditableText } from "../Shared/EditableText";
import { EditableButton } from "../Shared/EditableButton";
import { EditableImage } from "../Shared/EditableImage";
import { colorFamilies } from "../../../../theme/colorFamilies";
import { getHeroThemeState } from "../../../../theme/heroTheme";

const base = {
  eyebrow: "MOTION THAT EARNS ATTENTION",
  heading: "Make the opening feel alive without slowing the page down.",
  text: "Premium interaction, restrained motion, and clear conversion copy work together in one focused hero.",
  primary_label: "Start a project", primary_url: "/contact",
  secondary_label: "Explore more", secondary_url: "/about",
  image_url: "/storage/cms-images/background/background-1.avif",
  image_url_2: "/storage/cms-images/background/background-2.avif",
  image_url_3: "/storage/cms-images/background/background-3.avif",
  overlayOpacity: 54,
  pointerStrength: 14,
  interval: 2800,
  rotating_words: ["faster", "smarter", "beautifully"],
};

function schema(type,title,purpose,aliases,defaults={},fields=[]) { return {
  type,title,category:"Hero",purpose,description:`${title} is a Pro animated hero with lightweight motion and reduced-motion safeguards.`,
  access:"pro",isPremium:true,badge:"PRO",credits:170,tags:["hero","premium","animated","motion",...aliases],aliases:[title.toLowerCase(),...aliases],
  defaults:{...base,...defaults},fields:[
    {type:"text",name:"eyebrow",label:"Eyebrow"},{type:"textarea",name:"heading",label:"Heading"},{type:"textarea",name:"text",label:"Description"},
    {type:"button",name:"primary",label:"Primary Button"},{type:"button",name:"secondary",label:"Secondary Button"},
    {type:"image",name:"image_url",label:"Primary Image"},{type:"image",name:"image_url_2",label:"Secondary Image"},{type:"image",name:"image_url_3",label:"Third Image"},
    {type:"range",name:"overlayOpacity",label:"Overlay Opacity",min:20,max:85,step:5},...fields
  ]
};}

export const HeroSpotlightCursorPremiumSchema=schema("hero_spotlight_cursor_premium","Spotlight Cursor Hero","Adds a soft pointer-following spotlight over a premium dark hero.",["spotlight cursor","mouse glow","interactive hero","cursor glow","saas hero"],{pointerStrength:16},[{type:"range",name:"pointerStrength",label:"Spotlight Strength",min:8,max:28,step:2}]);
export const HeroFloatingCardsMotionPremiumSchema=schema("hero_floating_cards_motion_premium","Floating Cards Motion Hero","Floats layered proof and product cards around conversion copy.",["floating cards","floating ui","dashboard cards","saas motion","product cards"]);
export const Hero3dTiltProductPremiumSchema=schema("hero_3d_tilt_product_premium","3D Tilt Product Hero","Tilts a product or dashboard showcase subtly with pointer movement.",["3d tilt","product tilt","dashboard tilt","cursor perspective","interactive product"],{pointerStrength:12},[{type:"range",name:"pointerStrength",label:"Tilt Strength",min:6,max:20,step:1}]);
export const HeroInfiniteMarqueePremiumSchema=schema("hero_infinite_marquee_premium","Infinite Marquee Hero","Runs large editorial words behind anchored hero copy.",["marquee hero","moving typography","infinite text","agency hero","editorial motion"]);
export const HeroRotatingWordsPremiumSchema=schema("hero_rotating_words_premium","Rotating Words Hero","Rotates a highlighted phrase inside a conversion-led headline.",["rotating words","headline rotation","changing words","saas headline","dynamic headline"],{interval:2600},[{type:"range",name:"interval",label:"Word Interval",min:1600,max:5000,step:200}]);
export const HeroTypewriterPremiumSchema=schema("hero_typewriter_premium","Typewriter Premium Hero","Types and replaces a highlighted phrase for product, AI, and developer launches.",["typewriter hero","typing headline","developer hero","ai hero","dynamic text"],{interval:2200},[{type:"range",name:"interval",label:"Phrase Hold",min:1400,max:4200,step:200}]);
export const HeroCurtainRevealPremiumSchema=schema("hero_curtain_reveal_premium","Curtain Reveal Hero","Opens two cinematic panels to reveal the image and message beneath.",["curtain reveal","panel reveal","cinematic intro","luxury hero","launch reveal"]);

function heroVisualState(block, globalTheme) {
  const state = getHeroThemeState(block, globalTheme);
  const primaryKey = typeof globalTheme === "string" ? globalTheme : (globalTheme?.primary || "midnight");
  const primaryTheme = colorFamilies[primaryKey] || colorFamilies.midnight;
  return { ...state, primaryTheme, sectionClass: state.isLight ? `${state.theme.bg} ${state.theme.text}` : (state.isPrimary ? `${primaryTheme.bg} ${primaryTheme.text}` : "bg-slate-950 text-white") };
}

function heroGradient(globalTheme) {
  const primaryKey = typeof globalTheme === "string" ? globalTheme : (globalTheme?.primary || "midnight");
  return (colorFamilies[primaryKey] || colorFamilies.midnight)?.gradient || colorFamilies.midnight.gradient;
}

function Copy({data,onUpdate,headingNode,visual}) { const v=visual||heroVisualState(data,null); const primary=v.isPrimary?"bg-white text-slate-950 hover:bg-white/90":`${v.primaryTheme.bg} ${v.primaryTheme.text}`; const secondary=v.isLight?`border-slate-300 bg-white/70 ${v.theme.text}`:"border-white/30 bg-white/10 text-white"; return <div className="max-w-3xl">
  <EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[0.32em] ${v.isLight?v.theme.sub:"text-white/70"}`} onSave={v=>onUpdate({eyebrow:v})}/>
  {headingNode || <EditableText value={data.heading} className={`mt-6 block text-5xl font-semibold leading-[0.95] tracking-[-0.045em] sm:text-6xl lg:text-7xl ${v.isLight?v.theme.text:"text-white"}`} onSave={v=>onUpdate({heading:v})}/>} 
  <EditableText value={data.text} className={`mt-7 block max-w-2xl text-base leading-8 sm:text-lg ${v.isLight?v.theme.sub:"text-white/75"}`} onSave={v=>onUpdate({text:v})}/>
  <div className="mt-9 flex flex-wrap gap-3"><EditableButton label={data.primary_label} url={data.primary_url} onSave={(label,url)=>onUpdate({primary_label:label,primary_url:url})} className={`rounded-full px-6 py-3.5 text-sm font-bold ${primary}`}/><EditableButton label={data.secondary_label} url={data.secondary_url} onSave={(label,url)=>onUpdate({secondary_label:label,secondary_url:url})} className={`rounded-full border px-6 py-3.5 text-sm font-bold backdrop-blur ${secondary}`}/></div>
</div>; }

const Overlay=({opacity=54,visual})=><><div className="absolute inset-0" style={{backgroundColor:visual?.isLight?"#ffffff":"#020617",opacity:visual?.isLight ? .92 :Math.max(20,Math.min(85,Number(opacity)||54))/100}}/><div className={`absolute inset-0 ${visual?.isLight?"bg-gradient-to-r from-white/80 via-white/40 to-white/15":"bg-gradient-to-r from-slate-950/75 via-slate-950/20 to-slate-950/10"}`}/></>;

export function HeroSpotlightCursorPremiumBlock({block,onUpdate,globalTheme}) { const data={...HeroSpotlightCursorPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const gradient=heroGradient(globalTheme); const root=useRef(null); const glow=useRef(null);
  useEffect(()=>{const el=root.current,g=glow.current;if(!el||!g)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)");let raf;const move=e=>{if(reduced.matches)return;const r=el.getBoundingClientRect();if(raf)cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{g.style.left=`${e.clientX-r.left}px`;g.style.top=`${e.clientY-r.top}px`;});};el.addEventListener("pointermove",move);return()=>{el.removeEventListener("pointermove",move);if(raf)cancelAnimationFrame(raf);};},[]);
  return <section ref={root} className={`relative isolate min-h-[86svh] overflow-hidden ${visual.sectionClass}`} data-cosmic-hero-theme={visual.requestedTheme}><div className={`absolute inset-0 ${visual.isLight?"opacity-20":"opacity-100"}`} style={{backgroundImage:`radial-gradient(circle at 20% 20%, ${gradient.glowSoft}, transparent 32%), radial-gradient(circle at 85% 70%, ${gradient.glowStrong}, transparent 30%)`}}/><div ref={glow} className="pointer-events-none absolute h-72 w-72 -translate-x-1/2 -translate-y-1/2 rounded-full blur-3xl" style={{backgroundColor:gradient.glowSoft}}/><div className="relative z-10 mx-auto flex min-h-[86svh] max-w-7xl items-center px-6 py-24 sm:px-10 lg:px-14"><Copy data={data} onUpdate={onUpdate} visual={visual}/></div></section>; }

export function HeroFloatingCardsMotionPremiumBlock({block,blockIndex,onUpdate,globalTheme}) { const data={...HeroFloatingCardsMotionPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const {props}=usePage();const websiteId=props.page?.website_id||props.website?.id;return <section className={`relative isolate min-h-[86svh] overflow-hidden ${visual.sectionClass}`} data-cosmic-hero-theme={visual.requestedTheme}><style>{`@keyframes cosmicFloatCard{0%,100%{transform:translate3d(0,0,0) rotate(-2deg)}50%{transform:translate3d(0,-18px,0) rotate(2deg)}}@media(prefers-reduced-motion:reduce){.cosmic-float-card{animation:none!important}}`}</style><div className="absolute inset-0 opacity-45"><EditableImage websiteId={websiteId} blockIndex={blockIndex} src={data.image_url} showOverlay={false} isBackground blockType={block.type} className="absolute inset-0 h-full w-full" onSave={v=>onUpdate({image_url:v})}/></div><Overlay opacity={data.overlayOpacity} visual={visual}/><div className="relative z-10 mx-auto grid min-h-[86svh] max-w-7xl items-center gap-12 px-6 py-24 lg:grid-cols-[1fr_.85fr] lg:px-14"><Copy data={data} onUpdate={onUpdate} visual={visual}/><div className="relative hidden h-[520px] lg:block">{[0,1,2].map((i)=><div key={i} className="cosmic-float-card absolute w-[72%] overflow-hidden rounded-[28px] border border-white/15 bg-white/10 p-3 shadow-2xl backdrop-blur-xl" style={{left:`${i*11}%`,top:`${i*82}px`,animation:`cosmicFloatCard ${6+i*1.4}s ease-in-out ${i*.45}s infinite`}}><img src={[data.image_url,data.image_url_2,data.image_url_3][i]} alt="" className="aspect-[16/10] w-full rounded-[20px] object-cover" loading={i?"lazy":"eager"}/><div className="p-4"><div className="h-2 w-24 rounded-full bg-white/35"/><div className="mt-3 h-2 w-40 rounded-full bg-white/15"/></div></div>)}</div></div></section>; }

export function Hero3dTiltProductPremiumBlock({block,blockIndex,onUpdate,globalTheme}) { const data={...Hero3dTiltProductPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme); const {props}=usePage();const websiteId=props.page?.website_id||props.website?.id;const root=useRef(null),card=useRef(null);useEffect(()=>{const el=root.current,c=card.current;if(!el||!c)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)");let raf;const move=e=>{if(reduced.matches)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5,s=Number(data.pointerStrength||12);if(raf)cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>c.style.transform=`perspective(1200px) rotateX(${-y*s}deg) rotateY(${x*s}deg) translateZ(18px)`);};const leave=()=>{c.style.transform="perspective(1200px) rotateX(0) rotateY(0)";};el.addEventListener("pointermove",move);el.addEventListener("pointerleave",leave);return()=>{el.removeEventListener("pointermove",move);el.removeEventListener("pointerleave",leave);if(raf)cancelAnimationFrame(raf);};},[data.pointerStrength]);return <section ref={root} className={`relative overflow-hidden ${visual.sectionClass}`} data-cosmic-hero-theme={visual.requestedTheme}><div className="mx-auto grid min-h-[86svh] max-w-7xl items-center gap-14 px-6 py-24 lg:grid-cols-2 lg:px-14"><Copy data={data} onUpdate={onUpdate} visual={visual}/><div className="relative [perspective:1200px]"><div ref={card} className="overflow-hidden rounded-[32px] border border-white/15 bg-white/10 p-3 shadow-2xl transition-transform duration-200 will-change-transform"><EditableImage websiteId={websiteId} blockIndex={blockIndex} src={data.image_url} showOverlay={false} blockType={block.type} className="aspect-[16/10] w-full overflow-hidden rounded-[24px]" onSave={v=>onUpdate({image_url:v})}/><div className="grid grid-cols-3 gap-3 p-4">{["98.4%","2.4x","24/7"].map(v=><div key={v} className="rounded-2xl bg-white/10 p-4"><div className="text-xl font-bold">{v}</div><div className="mt-1 text-xs text-white/50">Live metric</div></div>)}</div></div></div></div></section>; }

export function HeroInfiniteMarqueePremiumBlock({block,onUpdate,globalTheme}) { const data={...HeroInfiniteMarqueePremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme);return <section className={`relative isolate min-h-[86svh] overflow-hidden ${visual.sectionClass}`} data-cosmic-hero-theme={visual.requestedTheme}><style>{`@keyframes cosmicMarqueeHero{to{transform:translateX(-50%)}}@media(prefers-reduced-motion:reduce){.cosmic-marquee-track{animation:none!important}}`}</style><div className="absolute inset-0 flex flex-col justify-center gap-8 opacity-[.09]" aria-hidden="true">{["BUILD • LAUNCH • GROW • ","DESIGN • MOTION • STORY • ","IDEAS • PRODUCTS • PEOPLE • "].map((t,i)=><div key={i} className="overflow-hidden whitespace-nowrap text-[clamp(5rem,14vw,13rem)] font-black uppercase tracking-[-.06em]"><div className="cosmic-marquee-track inline-block min-w-max" style={{animation:`cosmicMarqueeHero ${22+i*5}s linear infinite ${i%2?"reverse":"normal"}`}}>{t.repeat(4)}</div></div>)}</div><div className="relative z-10 mx-auto flex min-h-[86svh] max-w-7xl items-center px-6 py-24 lg:px-14"><Copy data={data} onUpdate={onUpdate} visual={visual}/></div></section>; }

function words(data){const raw=data.rotating_words; if(Array.isArray(raw)&&raw.length)return raw.filter(Boolean).slice(0,6); if(typeof raw==="string")return raw.split(",").map(v=>v.trim()).filter(Boolean).slice(0,6); return base.rotating_words;}
export function HeroRotatingWordsPremiumBlock({block,onUpdate,globalTheme}) {const data={...HeroRotatingWordsPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme);const gradient=heroGradient(globalTheme);const list=useMemo(()=>words(data),[data.rotating_words]);const [idx,setIdx]=useState(0);const root=useRef(null);useEffect(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const el=root.current;if(!el)return;let id=0;const stop=()=>{if(id){clearInterval(id);id=0;}};const start=()=>{if(!id)id=setInterval(()=>setIdx(v=>(v+1)%list.length),Math.max(1600,Number(data.interval)||2600));};const io=new IntersectionObserver(([entry])=>entry?.isIntersecting?start():stop(),{rootMargin:"120px"});io.observe(el);return()=>{stop();io.disconnect();};},[list,data.interval]);const heading=<div className={`mt-6 text-5xl font-semibold leading-[.95] tracking-[-.045em] sm:text-6xl lg:text-7xl ${visual.isLight?visual.theme.text:"text-white"}`}><EditableText value={data.heading} className="inline" onSave={v=>onUpdate({heading:v})}/> <span className="inline-grid overflow-hidden align-bottom" style={{color:gradient.glow}}><span key={list[idx]} className="animate-[fadeIn_.35s_ease]">{list[idx]}</span></span></div>;return <section ref={root} className={`relative min-h-[86svh] overflow-hidden ${visual.sectionClass}`} data-cosmic-hero-theme={visual.requestedTheme}><div className={`absolute inset-0 ${visual.isLight?"opacity-20":"opacity-100"}`} style={{backgroundImage:`radial-gradient(circle at 80% 20%, ${gradient.glowSoft}, transparent 32%)`}}/><div className="relative z-10 mx-auto flex min-h-[86svh] max-w-7xl items-center px-6 py-24 lg:px-14"><Copy data={data} onUpdate={onUpdate} headingNode={heading} visual={visual}/></div></section>;}

export function HeroTypewriterPremiumBlock({block,onUpdate,globalTheme}) {const data={...HeroTypewriterPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme);const gradient=heroGradient(globalTheme);const list=useMemo(()=>words(data),[data.rotating_words]);const [idx,setIdx]=useState(0),[shown,setShown]=useState("");const [deleting,setDeleting]=useState(false),[visible,setVisible]=useState(true);const root=useRef(null);useEffect(()=>{const el=root.current;if(!el)return;const io=new IntersectionObserver(([entry])=>setVisible(Boolean(entry?.isIntersecting)),{rootMargin:"120px"});io.observe(el);return()=>io.disconnect();},[]);useEffect(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches){setShown(list[0]||"");return;}if(!visible)return;const word=list[idx]||"";const done=!deleting&&shown===word,empty=deleting&&shown==="";const delay=done?Math.max(1200,Number(data.interval)||2200):empty?250:deleting?45:70;const id=setTimeout(()=>{if(done)setDeleting(true);else if(empty){setDeleting(false);setIdx(v=>(v+1)%list.length);}else setShown(word.slice(0,shown.length+(deleting?-1:1)));},delay);return()=>clearTimeout(id);},[shown,deleting,idx,list,data.interval,visible]);const heading=<div className={`mt-6 text-5xl font-semibold leading-[.95] tracking-[-.045em] sm:text-6xl lg:text-7xl ${visual.isLight?visual.theme.text:"text-white"}`}><EditableText value={data.heading} className="inline" onSave={v=>onUpdate({heading:v})}/> <span style={{color:gradient.glow}}>{shown}<span className="ml-1 inline-block h-[.9em] w-[3px] animate-pulse align-middle" style={{backgroundColor:gradient.glow}}/></span></div>;return <section ref={root} className={`relative min-h-[86svh] overflow-hidden ${visual.sectionClass}`} data-cosmic-hero-theme={visual.requestedTheme}><div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] bg-[size:48px_48px]"/><div className="relative z-10 mx-auto flex min-h-[86svh] max-w-7xl items-center px-6 py-24 lg:px-14"><Copy data={data} onUpdate={onUpdate} headingNode={heading} visual={visual}/></div></section>;}

export function HeroCurtainRevealPremiumBlock({block,blockIndex,onUpdate,globalTheme}) {const data={...HeroCurtainRevealPremiumSchema.defaults,...block}; const visual=heroVisualState(block,globalTheme);const {props}=usePage();const websiteId=props.page?.website_id||props.website?.id;return <section className={`group relative isolate min-h-[86svh] overflow-hidden ${visual.sectionClass}`} data-cosmic-hero-theme={visual.requestedTheme}><style>{`@keyframes cosmicCurtainLeft{from{transform:translateX(0)}to{transform:translateX(-102%)}}@keyframes cosmicCurtainRight{from{transform:translateX(0)}to{transform:translateX(102%)}}@media(prefers-reduced-motion:reduce){.cosmic-curtain-left,.cosmic-curtain-right{animation:none!important;display:none}}`}</style><div className="absolute inset-0"><EditableImage websiteId={websiteId} blockIndex={blockIndex} src={data.image_url} showOverlay={false} isBackground blockType={block.type} className="absolute inset-0 h-full w-full" onSave={v=>onUpdate({image_url:v})}/></div><Overlay opacity={data.overlayOpacity} visual={visual}/><div className="relative z-10 mx-auto flex min-h-[86svh] max-w-7xl items-center px-6 py-24 lg:px-14"><Copy data={data} onUpdate={onUpdate} visual={visual}/></div><div className={`cosmic-curtain-left pointer-events-none absolute inset-y-0 left-0 z-20 w-1/2 ${visual.isLight?"bg-white":"bg-slate-950"}`} style={{animation:"cosmicCurtainLeft 1.25s cubic-bezier(.76,0,.24,1) .15s both"}}/><div className={`cosmic-curtain-right pointer-events-none absolute inset-y-0 right-0 z-20 w-1/2 ${visual.isLight?"bg-white":"bg-slate-950"}`} style={{animation:"cosmicCurtainRight 1.25s cubic-bezier(.76,0,.24,1) .15s both"}}/></section>;}
