import { EditableButton } from "../Shared/EditableButton";
import { EditableText } from "../Shared/EditableText";
import { getEffectiveTheme } from "../../../../theme/Theme";
import { colorFamilies } from "../../../../theme/colorFamilies";
import { RepeatableControls, RepeatableRemoveButton } from "../Shared/RepeatableControls";

const base = (block, globalTheme, defaults) => {
    const theme = getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme);
    const primary = colorFamilies[globalTheme?.primary] || colorFamilies.emerald;
    const isPrimary = (block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme) === "primary";
    return {
        data: { ...defaults, ...block }, theme, primary, isPrimary,
        muted: isPrimary ? "text-white/70" : theme.sub,
        card: isPrimary ? "border-white/20 bg-white/10 text-white" : `${theme.border} ${theme.surface} ${theme.text}`,
        soft: isPrimary ? "border-white/20 bg-black/10 text-white" : `${primary.border || theme.border} ${primary.card || primary.bg} ${primary.text}`,
        softMuted: isPrimary ? "text-white/70" : primary.sub,
        button: isPrimary ? "bg-white text-slate-950" : `${primary.bg} ${primary.text}`,
    };
};

export const AboutTimelineStorySchema = {
    type: "about_timeline_story", title: "Timeline Story", category: "About",
    purpose: "Tell a company story through a premium chronological timeline.",
    description: "A Pro-only editorial timeline for milestones, growth stages, launches, or brand history.",
    tags: ["about","timeline","story","history","premium","pro"],
    defaults: { eyebrow:"OUR STORY", heading:"Built one meaningful chapter at a time.", text:"Show how the business evolved without turning the About page into a wall of copy.", primary_label:"Meet the team", primary_url:"#", year_one:"2018", title_one:"The beginning", text_one:"A focused idea became a practical service built around real customer needs.", year_two:"2021", title_two:"Growing with purpose", text_two:"The team expanded its capabilities while keeping the experience personal and clear.", year_three:"2024", title_three:"A stronger platform", text_three:"New systems, sharper positioning, and broader expertise created room for the next stage.", year_four:"Today", title_four:"What comes next", text_four:"We continue to improve the work, the process, and the value we create for every client." }
};
export function AboutTimelineStoryBlock({ block, onUpdate, globalTheme }) {
    const {data,theme,muted,card,button} = base(block,globalTheme,AboutTimelineStorySchema.defaults);
    const save=(k)=>(v)=>onUpdate({[k]:v});const itemCount=Math.min(4,Math.max(1,Number(data.about_timeline_count||4)));
    const items=["one","two","three","four"];
    return <section className={`group/repeatable-section relative overflow-hidden px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:gap-16"><div className="lg:sticky lg:top-24 lg:self-start"><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl ${theme.text}`} onSave={save("heading")}/><EditableText value={data.text} isTextArea className={`mt-5 block text-base leading-7 ${muted}`} onSave={save("text")}/><EditableButton label={data.primary_label} url={data.primary_url} className={`mt-7 inline-flex min-h-[48px] items-center rounded-full px-7 text-sm font-bold ${button}`} onSave={(label,url)=>onUpdate({primary_label:label,primary_url:url})}/></div><div className="relative"><div className={`absolute bottom-0 left-[31px] top-0 w-px ${block.resolvedTheme === 'primary' ? 'bg-white/20' : 'bg-slate-200'}`}/><div className="space-y-5">{items.slice(0,itemCount).map((w,i)=><article key={w} className={`group relative ml-16 rounded-[1.75rem] border p-6 sm:p-7 ${card}`}><RepeatableRemoveButton hoverScope="card" overlay label="Remove timeline item" disabled={itemCount<=1} onRemove={()=>onUpdate({about_timeline_count:itemCount-1})}/><span className={`absolute -left-[49px] top-7 flex h-9 w-9 items-center justify-center rounded-full border text-xs font-black ${card}`}>{i+1}</span><EditableText value={data[`year_${w}`]} className={`text-xs font-black uppercase tracking-[.18em] ${muted}`} onSave={save(`year_${w}`)}/><EditableText value={data[`title_${w}`]} className="mt-3 block text-2xl font-semibold tracking-[-.03em]" onSave={save(`title_${w}`)}/><EditableText value={data[`text_${w}`]} isTextArea className={`mt-3 block text-sm leading-6 ${muted}`} onSave={save(`text_${w}`)}/></article>)}</div></div></div></div></section>;
}

export const AboutFounderStorySchema = {
    type:"about_founder_story", title:"Founder Story", category:"About", purpose:"Introduce the founder with a premium editorial narrative.", description:"A Pro-only founder profile with quote, principles, and an image-led editorial layout.", tags:["about","founder","story","editorial","premium","pro"],
    defaults:{eyebrow:"FOUNDER STORY",heading:"Built from a belief that better work starts with better listening.",text:"Use this space for the human reason behind the business—the problem the founder wanted to solve and the standard they wanted to set.",quote:"Do the useful work first. Make it beautiful second. Then keep improving both.",founder_name:"Alex Morgan",founder_role:"Founder & Creative Director",principle_one:"Clarity over complexity",principle_two:"Craft with purpose",principle_three:"Long-term partnerships",image_url:"/storage/cms-images/background/background-1.avif",primary_label:"Our approach",primary_url:"#"}
};
export function AboutFounderStoryBlock({block,onUpdate,globalTheme}){const {data,theme,muted,card,button}=base(block,globalTheme,AboutFounderStorySchema.defaults);const save=(k)=>(v)=>onUpdate({[k]:v});return <section className={`group/repeatable-section px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-12 lg:items-stretch"><div className="relative min-h-[460px] overflow-hidden rounded-[2rem] lg:col-span-5"><img src={data.image_url} alt="" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent"/><div className="absolute bottom-0 p-7 text-white"><EditableText value={data.founder_name} className="block text-2xl font-semibold" onSave={save("founder_name")}/><EditableText value={data.founder_role} className="mt-1 block text-sm text-white/70" onSave={save("founder_role")}/></div></div><div className="lg:col-span-7 lg:py-4"><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl ${theme.text}`} onSave={save("heading")}/><EditableText value={data.text} isTextArea className={`mt-6 block text-base leading-7 sm:text-lg ${muted}`} onSave={save("text")}/><blockquote className={`mt-8 rounded-[1.75rem] border p-6 text-xl font-medium leading-8 sm:p-8 ${card}`}><EditableText value={data.quote} isTextArea className="block" onSave={save("quote")}/></blockquote><div className="mt-6 grid gap-3 sm:grid-cols-3">{["one","two","three"].map(w=><div key={w} className={`group relative rounded-2xl border p-4 text-sm font-semibold ${card}`}><EditableText value={data[`principle_${w}`]} onSave={save(`principle_${w}`)}/></div>)}</div><EditableButton label={data.primary_label} url={data.primary_url} className={`mt-7 inline-flex min-h-[48px] items-center rounded-full px-7 text-sm font-bold ${button}`} onSave={(label,url)=>onUpdate({primary_label:label,primary_url:url})}/></div></div></section>}

export const AboutMissionGridSchema={type:"about_mission_grid",title:"Mission Grid",category:"About",purpose:"Explain mission, vision, and values in a premium modular grid.",description:"A Pro-only About section combining purpose, vision, values, and operating principles in an asymmetrical grid.",tags:["about","mission","vision","values","bento","premium","pro"],defaults:{eyebrow:"WHY WE EXIST",heading:"A clear mission, translated into everyday decisions.",text:"Make the purpose of the company concrete by connecting the big idea to the way the team actually works.",mission_label:"MISSION",mission_title:"Make complex things feel simple.",mission_text:"Create useful experiences that remove friction and help people move forward with confidence.",vision_label:"VISION",vision_title:"Raise the standard",vision_text:"Build a business known for thoughtful work, dependable delivery, and relationships that last.",value_one_title:"Stay curious",value_one_text:"Ask better questions before reaching for familiar answers.",value_two_title:"Own the outcome",value_two_text:"Take responsibility for the result, not just the task.",value_three_title:"Keep it human",value_three_text:"Communicate clearly, listen carefully, and respect people’s time."}};
export function AboutMissionGridBlock({block,onUpdate,globalTheme}){const {data,theme,muted,card,soft,softMuted}=base(block,globalTheme,AboutMissionGridSchema.defaults);const save=(k)=>(v)=>onUpdate({[k]:v});return <section className={`group/repeatable-section px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="max-w-4xl"><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl lg:text-6xl ${theme.text}`} onSave={save("heading")}/><EditableText value={data.text} isTextArea className={`mt-5 block max-w-2xl text-base leading-7 ${muted}`} onSave={save("text")}/></div><div className="mt-12 grid gap-4 lg:grid-cols-12"><article className={`group relative rounded-[2rem] border p-7 sm:p-9 lg:col-span-7 ${card}`}><EditableText value={data.mission_label} className={`text-xs font-black tracking-[.2em] ${muted}`} onSave={save("mission_label")}/><EditableText value={data.mission_title} className="mt-12 block text-3xl font-semibold tracking-[-.035em] sm:text-4xl" onSave={save("mission_title")}/><EditableText value={data.mission_text} isTextArea className={`mt-4 block max-w-xl leading-7 ${muted}`} onSave={save("mission_text")}/></article><article className={`group relative rounded-[2rem] border p-7 sm:p-9 lg:col-span-5 ${soft}`}><EditableText value={data.vision_label} className={`text-xs font-black tracking-[.2em] ${softMuted}`} onSave={save("vision_label")}/><EditableText value={data.vision_title} className="mt-12 block text-3xl font-semibold tracking-[-.035em]" onSave={save("vision_title")}/><EditableText value={data.vision_text} isTextArea className={`mt-4 block leading-7 ${softMuted}`} onSave={save("vision_text")}/></article>{["one","two","three"].map(w=><article key={w} className={`group relative rounded-[2rem] border p-6 lg:col-span-4 ${card}`}><EditableText value={data[`value_${w}_title`]} className="block text-xl font-semibold" onSave={save(`value_${w}_title`)}/><EditableText value={data[`value_${w}_text`]} isTextArea className={`mt-3 block text-sm leading-6 ${muted}`} onSave={save(`value_${w}_text`)}/></article>)}</div></div></section>}

export const AboutInteractiveStatsSchema={type:"about_interactive_stats",title:"Interactive Company Stats",category:"About",purpose:"Show company scale and proof through premium interactive metric cards.",description:"A Pro-only company statistics section with four large metrics and contextual supporting copy.",tags:["about","stats","metrics","interactive","premium","pro"],defaults:{eyebrow:"THE COMPANY IN NUMBERS",heading:"Proof that the work has momentum behind it.",text:"Use meaningful company metrics to give visitors a quick sense of scale, experience, reach, or progress.",stat_one_value:"12+",stat_one_label:"Years building",stat_one_text:"Experience shaped across changing markets and technologies.",stat_two_value:"48",stat_two_label:"Projects this year",stat_two_text:"Focused engagements delivered across strategy, design, and technology.",stat_three_value:"6",stat_three_label:"Core disciplines",stat_three_text:"A connected team covering the work from direction through delivery.",stat_four_value:"4",stat_four_label:"Markets served",stat_four_text:"Local understanding combined with a broader point of view.",footnote:"Replace starter metrics with verified company data before publishing."}};
export function AboutInteractiveStatsBlock({block,onUpdate,globalTheme}){const {data,theme,muted,card,primary}=base(block,globalTheme,AboutInteractiveStatsSchema.defaults);const save=(k)=>(v)=>onUpdate({[k]:v});const itemCount=Math.min(4,Math.max(1,Number(data.about_stats_count||4)));return <section className={`group/repeatable-section px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl ${theme.text}`} onSave={save("heading")}/></div><EditableText value={data.text} isTextArea className={`block max-w-2xl text-base leading-7 sm:text-lg ${muted}`} onSave={save("text")}/></div><div className="mt-12 grid gap-4 md:grid-cols-2">{["one","two","three","four"].slice(0,itemCount).map((w,i)=><article key={w} className={`group relative overflow-hidden rounded-[2rem] border p-7 transition duration-300 hover:-translate-y-1 hover:shadow-xl sm:p-8 ${card}`}><RepeatableRemoveButton hoverScope="card" overlay label="Remove stat" disabled={itemCount<=1} onRemove={()=>onUpdate({about_stats_count:itemCount-1})}/><span className={`absolute right-6 top-6 h-2.5 w-2.5 rounded-full ${(block.theme && block.theme !== 'auto' ? block.theme : block.resolvedTheme)==='primary'?'bg-white':primary.bg}`}/><EditableText value={data[`stat_${w}_value`]} className="block text-5xl font-semibold tracking-[-.055em] sm:text-6xl" onSave={save(`stat_${w}_value`)}/><EditableText value={data[`stat_${w}_label`]} className="mt-6 block text-lg font-semibold" onSave={save(`stat_${w}_label`)}/><EditableText value={data[`stat_${w}_text`]} isTextArea className={`mt-3 block text-sm leading-6 ${muted}`} onSave={save(`stat_${w}_text`)}/><div className={`mt-7 h-1 rounded-full opacity-30 ${(block.theme && block.theme !== 'auto' ? block.theme : block.resolvedTheme)==='primary'?'bg-white':primary.bg}`}><div className="h-full rounded-full bg-current transition-all duration-500 group-hover:w-full" style={{width:`${55+i*12}%`}}/></div></article>)}</div><EditableText value={data.footnote} className={`mt-5 block text-xs ${muted}`} onSave={save("footnote")}/><RepeatableControls onAdd={()=>onUpdate({about_stats_count:Math.min(4,itemCount+1)})} canAdd={itemCount<4} showRemove={false} addLabel="Add stat" removeLabel="Remove last stat"/></div></section>}


export const AboutBrandJourneySchema={type:"about_brand_journey",title:"Brand Journey",category:"About",purpose:"Show how the brand evolved through distinct eras, pivots, and identity milestones.",description:"A Pro-only editorial brand journey with a large narrative rail and four visual chapters.",tags:["about","brand","journey","history","editorial","premium","pro"],defaults:{eyebrow:"BRAND JOURNEY",heading:"How the brand became what it is today.",text:"Connect the moments that shaped the identity, the offer, and the way customers experience the business.",chapter_one_label:"ORIGIN",chapter_one_title:"Start with the problem",chapter_one_text:"The brand began with a simple observation: customers deserved a clearer, more thoughtful option.",chapter_two_label:"REFINEMENT",chapter_two_title:"Find the point of view",chapter_two_text:"The offer became sharper, the language more confident, and the experience more recognisable.",chapter_three_label:"EXPANSION",chapter_three_title:"Grow without losing focus",chapter_three_text:"New capabilities were added while the core promise stayed consistent.",chapter_four_label:"NOW",chapter_four_title:"Build the next chapter",chapter_four_text:"The brand keeps evolving around what customers value most.",primary_label:"See our work",primary_url:"#"}};
export function AboutBrandJourneyBlock({block,onUpdate,globalTheme}){const {data,theme,muted,card,button}=base(block,globalTheme,AboutBrandJourneySchema.defaults);const save=(k)=>(v)=>onUpdate({[k]:v});const itemCount=Math.min(4,Math.max(1,Number(data.about_journey_count||4)));const chapters=["one","two","three","four"];return <section className={`group/repeatable-section px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl lg:text-6xl ${theme.text}`} onSave={save("heading")}/><EditableText value={data.text} isTextArea className={`mt-6 block max-w-xl text-base leading-7 ${muted}`} onSave={save("text")}/><EditableButton label={data.primary_label} url={data.primary_url} className={`mt-7 inline-flex min-h-[48px] items-center rounded-full px-7 text-sm font-bold ${button}`} onSave={(label,url)=>onUpdate({primary_label:label,primary_url:url})}/></div><div className="grid gap-4 sm:grid-cols-2">{chapters.slice(0,itemCount).map((w,i)=><article key={w} className={`group relative rounded-[2rem] border p-6 sm:p-7 ${card}`}><RepeatableRemoveButton hoverScope="card" overlay label="Remove journey card" disabled={itemCount<=1} onRemove={()=>onUpdate({about_journey_count:itemCount-1})}/><div className="flex items-center justify-between"><EditableText value={data[`chapter_${w}_label`]} className={`text-xs font-black tracking-[.2em] ${muted}`} onSave={save(`chapter_${w}_label`)}/><span className={`text-sm font-bold ${muted}`}>0{i+1}</span></div><EditableText value={data[`chapter_${w}_title`]} className="mt-12 block text-2xl font-semibold tracking-[-.03em]" onSave={save(`chapter_${w}_title`)}/><EditableText value={data[`chapter_${w}_text`]} isTextArea className={`mt-4 block text-sm leading-6 ${muted}`} onSave={save(`chapter_${w}_text`)}/></article>)}</div></div><RepeatableControls onAdd={()=>onUpdate({about_journey_count:Math.min(4,itemCount+1)})} canAdd={itemCount<4} showRemove={false} addLabel="Add journey card" removeLabel="Remove last journey card"/></div></section>}

export const AboutAwardsTimelineSchema={type:"about_awards_timeline",title:"Awards Timeline",category:"About",purpose:"Present awards and recognition in a premium chronological layout.",description:"A Pro-only awards timeline designed for verified recognitions, shortlistings, and milestones.",tags:["about","awards","recognition","timeline","premium","pro"],defaults:{eyebrow:"RECOGNITION",heading:"Selected recognition along the way.",text:"Use this section only for awards, shortlistings, certifications, or recognitions the business can verify.",award_one_year:"2022",award_one_title:"Industry Award",award_one_org:"Awarding organisation",award_two_year:"2023",award_two_title:"Design Recognition",award_two_org:"Awarding organisation",award_three_year:"2024",award_three_title:"Customer Experience Award",award_three_org:"Awarding organisation",award_four_year:"2025",award_four_title:"Innovation Recognition",award_four_org:"Awarding organisation",footnote:"Replace all starter entries with verified recognition before publishing."}};
export function AboutAwardsTimelineBlock({block,onUpdate,globalTheme}){const {data,theme,muted,card}=base(block,globalTheme,AboutAwardsTimelineSchema.defaults);const save=(k)=>(v)=>onUpdate({[k]:v});const itemCount=Math.min(4,Math.max(1,Number(data.about_awards_count||4)));const items=["one","two","three","four"];return <section className={`group/repeatable-section px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold tracking-[-.045em] sm:text-5xl ${theme.text}`} onSave={save("heading")}/><EditableText value={data.text} isTextArea className={`mt-5 block text-base leading-7 ${muted}`} onSave={save("text")}/></div><div className="mt-12 divide-y divide-current/10 border-y border-current/10">{items.slice(0,itemCount).map((w,i)=><article key={w} className="group relative grid gap-4 py-6 pr-12 sm:grid-cols-[120px_1fr_auto] sm:items-center"><RepeatableRemoveButton hoverScope="item" overlay placement="row" label="Remove award" disabled={itemCount<=1} onRemove={()=>onUpdate({about_awards_count:itemCount-1})}/><EditableText value={data[`award_${w}_year`]} className={`text-sm font-black ${muted}`} onSave={save(`award_${w}_year`)}/><EditableText value={data[`award_${w}_title`]} className={`text-2xl font-semibold tracking-[-.03em] ${theme.text}`} onSave={save(`award_${w}_title`)}/><div className={`rounded-full border px-4 py-2 text-xs font-bold ${card}`}><EditableText value={data[`award_${w}_org`]} onSave={save(`award_${w}_org`)}/></div></article>)}</div><EditableText value={data.footnote} isTextArea className={`mt-5 block text-xs ${muted}`} onSave={save("footnote")}/><RepeatableControls onAdd={()=>onUpdate({about_awards_count:Math.min(4,itemCount+1)})} canAdd={itemCount<4} showRemove={false} addLabel="Add award" removeLabel="Remove last award"/></div></section>}

export const AboutCultureSectionSchema={type:"about_culture_section",title:"Culture Section",category:"About",purpose:"Explain the working culture through principles, behaviours, and team expectations.",description:"A Pro-only culture section with an editorial intro and four culture pillars.",tags:["about","culture","team","values","premium","pro"],defaults:{eyebrow:"HOW WE WORK",heading:"A culture built around useful work and good people.",text:"Show the behaviours that shape everyday decisions, collaboration, and the experience of working with the team.",pillar_one_title:"Be clear",pillar_one_text:"Say what matters, remove ambiguity, and make the next step easy to understand.",pillar_two_title:"Stay curious",pillar_two_text:"Ask better questions and keep learning instead of defaulting to familiar answers.",pillar_three_title:"Own the outcome",pillar_three_text:"Take responsibility for the result and help the whole team move forward.",pillar_four_title:"Respect the craft",pillar_four_text:"Care about the details without losing sight of the customer or the goal.",closing_line:"The best culture is visible in the work, not just written on the wall."}};
export function AboutCultureSectionBlock({block,onUpdate,globalTheme}){const {data,theme,muted,card,soft,softMuted}=base(block,globalTheme,AboutCultureSectionSchema.defaults);const save=(k)=>(v)=>onUpdate({[k]:v});const itemCount=Math.min(4,Math.max(1,Number(data.about_culture_count||4)));const p=["one","two","three","four"];return <section className={`group/repeatable-section px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-5xl ${theme.text}`} onSave={save("heading")}/><EditableText value={data.text} isTextArea className={`mt-5 block text-base leading-7 ${muted}`} onSave={save("text")}/></div><div className="grid gap-4 sm:grid-cols-2 lg:col-span-7">{p.slice(0,itemCount).map((w,i)=>{const itemMuted=i===0?softMuted:muted;return <article key={w} className={`group relative rounded-[2rem] border p-7 ${i===0?soft:card}`}><RepeatableRemoveButton hoverScope="card" overlay label="Remove culture pillar" disabled={itemCount<=1} onRemove={()=>onUpdate({about_culture_count:itemCount-1})}/><span className={`text-xs font-black ${itemMuted}`}>0{i+1}</span><EditableText value={data[`pillar_${w}_title`]} className="mt-10 block text-2xl font-semibold tracking-[-.03em]" onSave={save(`pillar_${w}_title`)}/><EditableText value={data[`pillar_${w}_text`]} isTextArea className={`mt-4 block text-sm leading-6 ${itemMuted}`} onSave={save(`pillar_${w}_text`)}/></article>})}</div></div><div className={`mt-5 rounded-[2rem] border px-6 py-5 text-center text-sm font-semibold ${card}`}><EditableText value={data.closing_line} onSave={save("closing_line")}/></div><RepeatableControls onAdd={()=>onUpdate({about_culture_count:Math.min(4,itemCount+1)})} canAdd={itemCount<4} showRemove={false} addLabel="Add culture pillar" removeLabel="Remove last culture pillar"/></div></section>}

export const AboutOfficeGallerySchema={type:"about_office_gallery",title:"Office Gallery",category:"About",purpose:"Show the workspace, studio, venue, or team environment in a premium gallery.",description:"A Pro-only asymmetrical office gallery with editable captions and three image slots.",tags:["about","office","gallery","workspace","studio","premium","pro"],defaults:{eyebrow:"INSIDE THE STUDIO",heading:"A place designed for focused work and good collaboration.",text:"Use real workplace, studio, venue, clinic, showroom, or team-environment photography to make the business feel tangible.",image_one_url:"/storage/cms-images/background/background-1.avif",image_one_caption:"Main workspace",image_two_url:"/storage/cms-images/background/background-2.avif",image_two_caption:"Collaboration space",image_three_url:"/storage/cms-images/background/background-3.avif",image_three_caption:"Details that make it ours"}};
export function AboutOfficeGalleryBlock({block,onUpdate,globalTheme}){const {data,theme,muted,card}=base(block,globalTheme,AboutOfficeGallerySchema.defaults);const save=(k)=>(v)=>onUpdate({[k]:v});return <section className={`group/repeatable-section px-6 py-16 sm:px-10 sm:py-20 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><EditableText value={data.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${muted}`} onSave={save("eyebrow")}/><EditableText value={data.heading} className={`mt-5 block text-4xl font-semibold tracking-[-.045em] sm:text-5xl ${theme.text}`} onSave={save("heading")}/><EditableText value={data.text} isTextArea className={`mt-5 block text-base leading-7 ${muted}`} onSave={save("text")}/></div><div className="mt-12 grid gap-4 lg:grid-cols-12"><figure className="relative min-h-[520px] overflow-hidden rounded-[2rem] lg:col-span-7"><img src={data.image_one_url} alt="" className="absolute inset-0 h-full w-full object-cover"/><figcaption className="absolute bottom-4 left-4 rounded-full bg-black/65 px-4 py-2 text-xs font-bold text-white"><EditableText value={data.image_one_caption} onSave={save("image_one_caption")}/></figcaption></figure><div className="grid gap-4 lg:col-span-5"><figure className="relative min-h-[250px] overflow-hidden rounded-[2rem]"><img src={data.image_two_url} alt="" className="absolute inset-0 h-full w-full object-cover"/><figcaption className="absolute bottom-4 left-4 rounded-full bg-black/65 px-4 py-2 text-xs font-bold text-white"><EditableText value={data.image_two_caption} onSave={save("image_two_caption")}/></figcaption></figure><figure className={`relative min-h-[250px] overflow-hidden rounded-[2rem] border ${card}`}><img src={data.image_three_url} alt="" className="absolute inset-0 h-full w-full object-cover"/><figcaption className="absolute bottom-4 left-4 rounded-full bg-black/65 px-4 py-2 text-xs font-bold text-white"><EditableText value={data.image_three_caption} onSave={save("image_three_caption")}/></figcaption></figure></div></div></div></section>}
