import { useEffect, useMemo, useState } from "react";
import { EditableButton } from "../Shared/EditableButton";
import { EditableText } from "../Shared/EditableText";
import { getEffectiveTheme } from "../../../../theme/Theme";
import { colorFamilies } from "../../../../theme/colorFamilies";

const shared=(type,title,purpose,description,defaults)=>({type,title,category:"CTA",purpose,description,tags:["cta","premium","pro"],defaults});
const base={eyebrow:"NEXT STEP",heading:"Ready to move forward?",text:"Give visitors one clear action with confident, concise supporting copy.",primary_label:"Get started",primary_url:"https://example.com",secondary_label:"Learn more",secondary_url:"https://example.com"};
export const CtaGlassPremiumSchema=shared("cta_glass_premium","Glass CTA","Create a premium frosted-glass call to action.","Layered glass card CTA with two editable actions.",{...base,eyebrow:"READY WHEN YOU ARE",heading:"Turn the next step into an easy yes."});
export const CtaGradientPremiumSchema=shared("cta_gradient_premium","Gradient CTA","Create a bold premium gradient call to action.","High-impact gradient CTA with strong hierarchy and two actions.",{...base,eyebrow:"LET’S BUILD WHAT’S NEXT",heading:"Make your next move impossible to miss."});
export const CtaNewsletterPremiumSchema=shared("cta_newsletter_premium","Newsletter CTA","Capture newsletter interest with a premium signup layout.","Newsletter CTA with email field visual and privacy note.",{...base,eyebrow:"STAY IN THE LOOP",heading:"Useful updates, without the noise.",primary_label:"Subscribe",primary_url:"https://example.com/newsletter",input_placeholder:"Email address",privacy_note:"Add your real privacy and email-frequency details before publishing."});
export const CtaBookDemoPremiumSchema=shared("cta_book_demo_premium","Book Demo CTA","Invite qualified visitors to schedule a demo.","Sales-oriented demo CTA with scheduling details and two actions.",{...base,eyebrow:"SEE IT IN ACTION",heading:"Book a focused product walkthrough.",primary_label:"Book a demo",secondary_label:"View features",detail_one:"30-minute walkthrough",detail_two:"Questions welcome",detail_three:"No commitment"});
export const CtaCalendlyPremiumSchema=shared("cta_calendly_premium","Calendly CTA","Create a scheduling CTA that can link to a Calendly or other booking page.","Calendar-style booking card with editable scheduling URL and availability note.",{...base,eyebrow:"PICK A TIME",heading:"Schedule a conversation that works for you.",primary_label:"Open calendar",booking_url:"https://calendly.com/example/30min",availability_note:"Connect your real scheduling link before publishing.",duration_label:"Choose a meeting time"});
export const CtaFreeTrialPremiumSchema=shared("cta_free_trial_premium","Free Trial CTA","Invite visitors to start a product trial with clear expectation-setting.","Premium trial CTA with benefit chips and transparent trial note.",{...base,eyebrow:"TRY IT YOURSELF",heading:"Start exploring before you commit.",primary_label:"Start free trial",primary_url:"/start",trial_note:"Add your real trial length, billing, and cancellation terms before publishing.",benefit_one:"Explore the product",benefit_two:"Build at your pace",benefit_three:"Upgrade when ready"});
export const CtaCountdownPremiumSchema=shared("cta_countdown_premium","Countdown CTA","Create a time-sensitive CTA without inventing urgency.","Countdown-style campaign CTA driven by an editable deadline and a functional demo timer fallback.",{...base,eyebrow:"UPCOMING",heading:"A key moment is getting closer.",primary_label:"Learn more",countdown_deadline:"demo:+7d",countdown_days:"00",countdown_hours:"00",countdown_minutes:"00",countdown_seconds:"00",deadline_note:"Demo countdown shown. Replace demo:+7d with a real ISO deadline before publishing."});
export const CtaLimitedOfferPremiumSchema=shared("cta_limited_offer_premium","Limited Offer CTA","Present a genuine limited promotion with transparent terms.","Premium offer card with offer badge, supporting terms, and conversion action.",{...base,eyebrow:"LIMITED OFFER",heading:"Give visitors a clear reason to act now.",primary_label:"Claim offer",primary_url:"https://example.com/offer",offer_badge:"Special offer",offer_detail:"Add the real offer value or benefit.",terms_note:"Add genuine eligibility, expiry, and offer terms before publishing."});

function Shell({block,onUpdate,globalTheme,variant,children}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme);const primary=colorFamilies[globalTheme?.primary]||colorFamilies.emerald;const save=k=>v=>onUpdate({[k]:v});const isGradient=variant==='gradient';const gradient=primary.gradient||colorFamilies.midnight?.gradient||{};const gradientStyle=isGradient?{background:`linear-gradient(${Number(gradient.angle||120)}deg, ${gradient.from||'#071426'}, ${gradient.via||'#111936'}, ${gradient.to||'#28164D'})`}:undefined;return <section style={gradientStyle} className={`relative overflow-hidden px-6 py-20 sm:px-8 lg:py-24 ${isGradient?'text-white':theme.bg}`}><div className="pointer-events-none absolute inset-0" style={isGradient?{background:`radial-gradient(circle at 78% 18%, ${gradient.glowSoft||'rgba(124, 58, 237, 0.20)'}, transparent 34%)`}:undefined}/><div className="relative mx-auto max-w-6xl">{children({theme,primary,save})}</div></section>}
function Header({d,theme,save,light=false}){return <><EditableText value={d.eyebrow} onSave={save('eyebrow')} className={`text-xs font-bold uppercase tracking-[.26em] ${light?'text-white/70':theme.sub}`}/><EditableText value={d.heading} onSave={save('heading')} className={`mt-5 block max-w-4xl text-4xl font-bold tracking-tight sm:text-5xl ${light?'text-white':theme.text}`}/><EditableText value={d.text} isTextArea onSave={save('text')} className={`mt-5 block max-w-2xl text-base leading-7 ${light?'text-white/75':theme.sub}`}/></>}
function Actions({d,theme,primary,save,light=false}){return <div className="mt-8 flex flex-wrap gap-3"><EditableButton label={d.primary_label} url={d.primary_url} onLabelSave={save('primary_label')} onUrlSave={save('primary_url')} className={`rounded-full px-6 py-3 text-sm font-bold ${light?'bg-white text-slate-950':`${primary.bg} ${primary.text}`}`}/><EditableButton label={d.secondary_label} url={d.secondary_url} onLabelSave={save('secondary_label')} onUrlSave={save('secondary_url')} className={`rounded-full border px-6 py-3 text-sm font-bold ${light?'border-white/30 text-white':`${theme.border} ${theme.text}`}`}/></div>}
export function CtaGlassPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaGlassPremiumSchema.defaults,...block};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme}>{({theme,primary,save})=><div className={`relative rounded-[2.25rem] border p-8 shadow-2xl backdrop-blur-xl sm:p-12 ${theme.border} ${theme.card}`}><div className="absolute -right-16 -top-20 h-48 w-48 rounded-full bg-current opacity-5 blur-3xl"/><Header d={d} theme={theme} save={save}/><Actions d={d} theme={theme} primary={primary} save={save}/></div>}</Shell>}
export function CtaGradientPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaGradientPremiumSchema.defaults,...block};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme} variant="gradient">{({theme,primary,save})=><div className="grid items-end gap-8 rounded-[2.25rem] border border-white/15 bg-white/5 p-8 shadow-2xl backdrop-blur sm:p-12 lg:grid-cols-[1fr_auto]"><div><Header d={d} theme={theme} save={save} light/></div><Actions d={d} theme={theme} primary={primary} save={save} light/></div>}</Shell>}
export function CtaNewsletterPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaNewsletterPremiumSchema.defaults,...block};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme}>{({theme,primary,save})=><div className={`grid gap-8 rounded-[2.25rem] border p-8 sm:p-12 lg:grid-cols-[1fr_.8fr] lg:items-center ${theme.border} ${theme.card}`}><div><Header d={d} theme={theme} save={save}/></div><div><div className={`flex gap-2 rounded-2xl border p-2 ${theme.border} ${theme.bg}`}><EditableText value={d.input_placeholder} onSave={save('input_placeholder')} className={`flex-1 px-3 py-2 text-sm ${theme.sub}`}/><EditableButton label={d.primary_label} url={d.primary_url} onLabelSave={save('primary_label')} onUrlSave={save('primary_url')} className={`rounded-xl px-5 py-3 text-sm font-bold ${primary.bg} ${primary.text}`}/></div><EditableText value={d.privacy_note} onSave={save('privacy_note')} className={`mt-3 block text-xs ${theme.sub}`}/></div></div>}</Shell>}
export function CtaBookDemoPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaBookDemoPremiumSchema.defaults,...block};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme}>{({theme,primary,save})=><div className="grid gap-8 lg:grid-cols-[1fr_.72fr] lg:items-center"><div><Header d={d} theme={theme} save={save}/><Actions d={d} theme={theme} primary={primary} save={save}/></div><div className={`rounded-[2rem] border p-7 ${theme.border} ${theme.card}`}><span className={`text-xs font-bold uppercase tracking-[.2em] ${theme.sub}`}>Demo details</span>{['one','two','three'].map(i=><div key={i} className={`mt-4 rounded-2xl border p-4 text-sm font-semibold ${theme.border} ${theme.text}`}><EditableText value={d[`detail_${i}`]} onSave={save(`detail_${i}`)}/></div>)}</div></div>}</Shell>}


export function CtaCalendlyPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaCalendlyPremiumSchema.defaults,...block};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme}>{({theme,primary,save})=><div data-cosmic-calendly className="grid gap-8 lg:grid-cols-[1fr_.75fr] lg:items-center"><div><Header d={d} theme={theme} save={save}/><div className="mt-8"><EditableButton label={d.primary_label} url={d.booking_url} onLabelSave={save('primary_label')} onUrlSave={save('booking_url')} className={`cosmic-calendly-cta inline-flex min-h-[48px] items-center justify-center rounded-full px-6 py-3 text-sm font-bold ${primary.bg} ${primary.text}`}/></div></div><div className={`rounded-[2rem] border p-6 ${theme.border} ${theme.card}`}><div className={`grid grid-cols-7 gap-2 text-center text-[10px] font-bold uppercase ${theme.sub}`}>{['M','T','W','T','F','S','S'].map((x,i)=><span key={i}>{x}</span>)}</div><div className="mt-3 grid grid-cols-7 gap-2">{Array.from({length:21},(_,i)=><span key={i} className={`aspect-square rounded-lg border ${i===10?`${primary.bg} ${primary.text}`:`${theme.border} ${theme.bg}`} flex items-center justify-center text-xs`}>{i+1}</span>)}</div><EditableText value={d.duration_label} onSave={save('duration_label')} className={`mt-5 block text-sm font-semibold ${theme.text}`}/><EditableText value={d.availability_note} onSave={save('availability_note')} className={`mt-2 block text-xs ${theme.sub}`}/></div></div>}</Shell>}
export function CtaFreeTrialPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaFreeTrialPremiumSchema.defaults,...block};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme}>{({theme,primary,save})=><div className={`grid gap-8 rounded-[2rem] border p-8 sm:p-12 lg:grid-cols-[1fr_.8fr] ${theme.border} ${theme.card}`}><div><Header d={d} theme={theme} save={save}/><div className="mt-8"><EditableButton label={d.primary_label} url={d.primary_url} onLabelSave={save('primary_label')} onUrlSave={save('primary_url')} className={`rounded-full px-6 py-3 text-sm font-bold ${primary.bg} ${primary.text}`}/></div></div><div className="space-y-3">{['one','two','three'].map(i=><div key={i} className={`rounded-2xl border p-4 ${theme.border} ${theme.bg}`}><EditableText value={d[`benefit_${i}`]} onSave={save(`benefit_${i}`)} className={`text-sm font-semibold ${theme.text}`}/></div>)}<EditableText value={d.trial_note} onSave={save('trial_note')} className={`block pt-2 text-xs leading-5 ${theme.sub}`}/></div></div>}</Shell>}
export function CtaCountdownPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaCountdownPremiumSchema.defaults,...block};const [now,setNow]=useState(()=>Date.now());const demoTarget=useMemo(()=>Date.now()+(7*24*60*60*1000),[]);useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);const deadline=String(d.countdown_deadline||'demo:+7d').trim();const parsedTarget=deadline.toLowerCase()==='demo:+7d'?demoTarget:Date.parse(deadline);const remaining=Number.isFinite(parsedTarget)?Math.max(0,parsedTarget-now):0;const values={days:String(Math.floor(remaining/86400000)).padStart(2,'0'),hours:String(Math.floor((remaining%86400000)/3600000)).padStart(2,'0'),minutes:String(Math.floor((remaining%3600000)/60000)).padStart(2,'0'),seconds:String(Math.floor((remaining%60000)/1000)).padStart(2,'0')};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme}>{({theme,primary,save})=><div className={`rounded-[2rem] border p-8 text-center sm:p-12 ${theme.border} ${theme.card}`}><div className="mx-auto max-w-3xl"><Header d={d} theme={theme} save={save}/></div><div className="mx-auto mt-8 grid max-w-2xl grid-cols-2 gap-3 sm:grid-cols-4">{[['days','Days'],['hours','Hours'],['minutes','Minutes'],['seconds','Seconds']].map(([k,l])=><div key={k} className={`rounded-2xl border p-4 ${theme.border} ${theme.bg}`}><strong className={`block text-3xl font-bold tabular-nums ${theme.text}`}>{values[k]}</strong><span className={`mt-1 block text-[10px] uppercase tracking-widest ${theme.sub}`}>{l}</span></div>)}</div><div className={`mx-auto mt-5 max-w-xl rounded-xl border px-4 py-3 text-left ${theme.border} ${theme.bg}`}><span className={`block text-[10px] font-bold uppercase tracking-widest ${theme.sub}`}>Deadline</span><EditableText value={d.countdown_deadline} onSave={save('countdown_deadline')} className={`mt-1 block text-sm font-semibold ${theme.text}`}/></div><div className="mt-8 flex justify-center"><EditableButton label={d.primary_label} url={d.primary_url} onLabelSave={save('primary_label')} onUrlSave={save('primary_url')} className={`rounded-full px-6 py-3 text-sm font-bold ${primary.bg} ${primary.text}`}/></div><EditableText value={d.deadline_note} onSave={save('deadline_note')} className={`mx-auto mt-4 block max-w-xl text-xs ${theme.sub}`}/></div>}</Shell>}
export function CtaLimitedOfferPremiumBlock({block,onUpdate,globalTheme}){const d={...CtaLimitedOfferPremiumSchema.defaults,...block};return <Shell block={d} onUpdate={onUpdate} globalTheme={globalTheme}>{({theme,primary,save})=><div className={`relative overflow-hidden rounded-[2rem] border p-8 sm:p-12 ${theme.border} ${theme.card}`}><div className={`absolute right-0 top-0 rounded-bl-2xl px-5 py-3 text-xs font-bold uppercase tracking-widest ${primary.bg} ${primary.text}`}><EditableText value={d.offer_badge} onSave={save('offer_badge')}/></div><div className="max-w-3xl"><Header d={d} theme={theme} save={save}/><EditableText value={d.offer_detail} onSave={save('offer_detail')} className={`mt-6 block text-xl font-semibold ${theme.text}`}/><div className="mt-8"><EditableButton label={d.primary_label} url={d.primary_url} onLabelSave={save('primary_label')} onUrlSave={save('primary_url')} className={`rounded-full px-6 py-3 text-sm font-bold ${primary.bg} ${primary.text}`}/></div><EditableText value={d.terms_note} onSave={save('terms_note')} className={`mt-4 block text-xs leading-5 ${theme.sub}`}/></div></div>}</Shell>}
