import { EditableText } from "../Shared/EditableText";
import { EditableButton } from "../Shared/EditableButton";
import { getEffectiveTheme } from "../../../../theme/Theme";
import { useMemo, useState } from "react";
import { RepeatableControls, RepeatableRemoveButton } from "../Shared/RepeatableControls";
import { FormFieldsEditor, FormField, normalizeContactFields } from "./ContactFormModernBlock";


const premiumDefaultFields = [
  { id:"name", name:"name", type:"text", label:"Name", placeholder:"Your name", required:true },
  { id:"email", name:"email", type:"email", label:"Email", placeholder:"you@example.com", required:true },
  { id:"message", name:"message", type:"textarea", label:"Message", placeholder:"Tell us what you need", required:true },
];

function PremiumEditableForm({ fields, onSave, submitLabel, theme, compact=false }) {
  const [editing,setEditing]=useState(false);
  const normalized=useMemo(()=>normalizeContactFields(fields?.length?fields:premiumDefaultFields),[fields]);
  const inputClass=`w-full rounded-xl border bg-transparent px-4 py-3 text-sm outline-none ${theme.border} ${theme.text}`;
  return <>
    <div className="group/form relative">
      <button type="button" data-cosmic-edit-control onClick={()=>setEditing(true)} className="absolute right-3 top-3 z-20 rounded-lg border border-white/15 bg-slate-950/80 px-3 py-1.5 text-xs font-bold text-white opacity-0 shadow-lg transition group-hover/form:opacity-100 focus:opacity-100">✎ Edit form</button>
      <div className={compact?"space-y-4":"space-y-5"}>
        {normalized.map(field=><FormField key={field.id} field={field} inputClass={inputClass} theme={theme} nativeColorScheme="light" accentColor="#475569"/>)}
      </div>
      <button type="button" className="mt-5 w-full rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">{submitLabel}</button>
    </div>
    {editing?<FormFieldsEditor fields={normalized} onSave={onSave} onClose={()=>setEditing(false)}/>:null}
  </>;
}

function PremiumMultiStepForm({ fields, onSave, submitLabel, theme, step, setStep }) {
  const [editing,setEditing]=useState(false);
  const normalized=useMemo(()=>normalizeContactFields(fields?.length?fields:premiumDefaultFields).slice(0,3),[fields]);
  const field=normalized[Math.min(step,normalized.length-1)] || normalized[0];
  const inputClass=`w-full rounded-xl border bg-transparent px-4 py-3 text-sm outline-none ${theme.border} ${theme.text}`;
  return <>
    <div className="group/form relative">
      <button type="button" data-cosmic-edit-control onClick={()=>setEditing(true)} className="absolute right-0 -top-10 z-20 rounded-lg border border-white/15 bg-slate-950/80 px-3 py-1.5 text-xs font-bold text-white opacity-0 shadow-lg transition group-hover/form:opacity-100 focus:opacity-100">✎ Edit form</button>
      {field?<FormField field={field} inputClass={inputClass} theme={theme} nativeColorScheme="light" accentColor="#475569"/>:null}
      <div className="mt-5 flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} className={`rounded-xl border px-4 py-3 text-sm font-semibold disabled:opacity-40 ${theme.border} ${theme.text}`}>Back</button>{step<normalized.length-1?<button type="button" onClick={()=>setStep(Math.min(normalized.length-1,step+1))} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Continue</button>:<button type="button" className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">{submitLabel}</button>}</div>
    </div>
    {editing?<FormFieldsEditor fields={normalized} onSave={onSave} onClose={()=>setEditing(false)}/>:null}
  </>;
}

const shared=(type,title,purpose,description,defaults)=>({type,title,category:"Contact",purpose,description,tags:["contact","premium","pro"],defaults});
const base={eyebrow:"CONTACT",heading:"Let’s make the next step simple.",text:"Choose the contact option that fits your needs.",email:"hello@example.com",phone:"+1 (555) 010-0200",address:"Available by appointment",primary_label:"Send inquiry",primary_url:"#"};
export const ContactSplitPremiumSchema=shared("contact_split_premium","Split Contact","Create a premium split contact section.","Contact details paired with a polished inquiry form.",{...base,eyebrow:"START A CONVERSATION",heading:"Tell us what you’re planning.",fields:premiumDefaultFields});
export const ContactMapPremiumSchema=shared("contact_map_premium","Map Contact","Create a location-first premium contact section.","Map-style location panel with editable address and directions link.",{...base,eyebrow:"FIND US",heading:"Visit, call, or send a message.",map_label:"Map preview",directions_label:"Get directions",directions_url:"https://www.google.com/maps/search/?api=1&query=Your+Business+Location"});
export const ContactAppointmentPremiumSchema=shared("contact_appointment_premium","Appointment Booking","Create an appointment-oriented contact section without inventing availability.","Scheduling CTA with editable appointment note and booking URL.",{...base,eyebrow:"BOOK A TIME",heading:"Choose the right way to connect.",primary_label:"Book appointment",booking_url:"https://calendly.com/",appointment_note:"Connect your real booking link and availability before publishing.",duration_label:"Appointment length varies"});
export const ContactSupportCenterPremiumSchema=shared("contact_support_center_premium","Support Center","Create a premium support contact hub.","Support channels and help topics with clear escalation paths.",{...base,eyebrow:"SUPPORT CENTER",heading:"Help is easy to find.",support_one_title:"General support",support_one_text:"Questions about your account or service.",support_two_title:"Technical help",support_two_text:"Get help with setup or troubleshooting.",support_three_title:"Billing",support_three_text:"Questions about invoices or plan details."});
export const ContactFaqPremiumSchema=shared("contact_faq_premium","FAQ + Contact","Create a premium FAQ and contact section.","Common questions paired with a focused inquiry form.",{...base,eyebrow:"QUESTIONS, ANSWERED",heading:"Get clarity before you get in touch.",fields:premiumDefaultFields,faq_one_question:"What should I include in my inquiry?",faq_one_answer:"Share the goal, timing, and any useful context so the conversation can start clearly.",faq_two_question:"What happens after I contact you?",faq_two_answer:"Use this space to explain your real follow-up process before publishing.",faq_three_question:"Can I ask about a custom requirement?",faq_three_answer:"Yes—replace this placeholder with the real options your business supports."});
export const ContactMultiStepPremiumSchema=shared("contact_multistep_premium","Multi-step Contact","Create a premium staged inquiry section.","A focused multi-step form experience with a readable static fallback.",{...base,eyebrow:"START YOUR INQUIRY",heading:"A few details. One clear next step.",fields:premiumDefaultFields,step_one_title:"About you",step_one_text:"Start with the essentials.",step_two_title:"Your request",step_two_text:"Add the context that matters.",step_three_title:"Contact details",step_three_text:"Tell us how to reach you.",submit_label:"Send inquiry"});
export const ContactLiveChatPremiumSchema=shared("contact_live_chat_premium","Live Chat CTA","Create a premium chat-entry contact section.","A polished live-chat call to action without fabricated online status.",{...base,eyebrow:"CHAT WITH US",heading:"Prefer a quick conversation?",text:"Connect your real chat or messaging destination before publishing.",primary_label:"Start chat",chat_url:"https://www.messenger.com/",chat_note:"Chat availability depends on your connected support channel.",secondary_label:"Send an email",secondary_url:"mailto:hello@example.com"});


const slotWords=["one","two","three"];

function Header({d,theme,save}){return <><EditableText value={d.eyebrow} onSave={save('eyebrow')} className={`block text-xs font-semibold uppercase tracking-[0.24em] ${theme.sub}`}/><EditableText value={d.heading} onSave={save('heading')} className={`mt-4 block text-4xl font-bold leading-tight sm:text-5xl ${theme.text}`}/><EditableText value={d.text} isTextArea onSave={save('text')} className={`mt-5 block text-base leading-7 ${theme.sub}`}/></>}
function Shell({block,onUpdate,globalTheme,schema,children}){const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme,globalTheme);const d={...schema.defaults,...block};const save=(key)=>(value)=>onUpdate({[key]:value});return children({d,theme,save});}
function Field({label,placeholder,theme}){return <label className="block"><span className={`mb-2 block text-xs font-semibold uppercase tracking-[0.16em] ${theme.sub}`}>{label}</span><input placeholder={placeholder} className={`w-full rounded-xl border bg-transparent px-4 py-3 text-sm ${theme.border} ${theme.text}`}/></label>}
export function ContactSplitPremiumBlock(p){return <Shell {...p} schema={ContactSplitPremiumSchema}>{({d,theme,save})=><section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><Header d={d} theme={theme} save={save}/><div className={`mt-8 space-y-3 border-t pt-6 ${theme.border}`}><EditableText value={d.email} onSave={save('email')} className={`block font-semibold ${theme.text}`}/><EditableText value={d.phone} onSave={save('phone')} className={`block font-semibold ${theme.text}`}/><EditableText value={d.address} onSave={save('address')} className={`block ${theme.sub}`}/></div></div><div className={`rounded-[2rem] border p-6 sm:p-8 ${theme.card} ${theme.border}`}><PremiumEditableForm fields={d.fields} onSave={(fields)=>p.onUpdate({fields})} submitLabel={d.primary_label} theme={theme}/></div></div></section>}</Shell>}
export function ContactMapPremiumBlock(p){return <Shell {...p} schema={ContactMapPremiumSchema}>{({d,theme,save})=><section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><Header d={d} theme={theme} save={save}/><div className="mt-8 space-y-3"><EditableText value={d.address} onSave={save('address')} className={`block text-lg font-semibold ${theme.text}`}/><EditableText value={d.phone} onSave={save('phone')} className={`block ${theme.sub}`}/><EditableText value={d.email} onSave={save('email')} className={`block ${theme.sub}`}/></div><div className="mt-6"><EditableButton label={d.directions_label} url={d.directions_url} onSave={(label,url)=>p.onUpdate({directions_label:label,directions_url:url})} className="rounded-full bg-slate-900 px-5 py-3 text-sm font-bold text-white"/></div></div><div className={`grid min-h-80 place-items-center overflow-hidden rounded-[2rem] border ${theme.card} ${theme.border}`}><div className="text-center"><div className={`mx-auto mb-4 grid h-16 w-16 place-items-center rounded-full border ${theme.border} ${theme.bg}`}>⌖</div><EditableText value={d.map_label} onSave={save('map_label')} className={`block text-sm font-semibold ${theme.text}`}/><p className={`mt-2 text-xs ${theme.sub}`}>Connect a real map or directions URL before publishing.</p></div></div></div></section>}</Shell>}
export function ContactAppointmentPremiumBlock(p){return <Shell {...p} schema={ContactAppointmentPremiumSchema}>{({d,theme,save})=><section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className={`mx-auto max-w-5xl rounded-[2rem] border p-7 sm:p-10 ${theme.card} ${theme.border}`}><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><Header d={d} theme={theme} save={save}/><EditableText value={d.appointment_note} onSave={save('appointment_note')} className={`mt-6 block text-sm ${theme.sub}`}/></div><div className={`rounded-2xl border p-6 ${theme.bg} ${theme.border}`}><EditableText value={d.duration_label} onSave={save('duration_label')} className={`block text-sm font-semibold ${theme.text}`}/><div className="mt-5"><EditableButton label={d.primary_label} url={d.booking_url} onSave={(label,url)=>p.onUpdate({primary_label:label,booking_url:url})} className="w-full rounded-xl bg-slate-900 px-5 py-3 text-center text-sm font-bold text-white"/></div><p className={`mt-4 text-xs ${theme.sub}`}>Availability is not generated by Cosmic AI.</p></div></div></div></section>}</Shell>}
export function ContactSupportCenterPremiumBlock(p){return <Shell {...p} schema={ContactSupportCenterPremiumSchema}>{({d,theme,save})=>{const count=Math.max(1,Math.min(3,Number(d.support_count)||3));return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><Header d={d} theme={theme} save={save}/></div><div className="mt-10 grid gap-5 md:grid-cols-3">{slotWords.slice(0,count).map((n,i)=><article key={n} className={`group relative rounded-2xl border p-6 ${theme.card} ${theme.border}`}><RepeatableRemoveButton hoverScope="card" overlay label="Remove support card" disabled={count<=1} onRemove={()=>p.onUpdate((()=>{const patch={support_count:Math.max(1,count-1)};for(let x=i;x<count-1;x++){const from=slotWords[x+1],to=slotWords[x];patch[`support_${to}_title`]=d[`support_${from}_title`]??"";patch[`support_${to}_text`]=d[`support_${from}_text`]??"";}return patch;})())}/><EditableText value={d[`support_${n}_title`]} onSave={save(`support_${n}_title`)} className={`block text-lg font-bold ${theme.text}`}/><EditableText value={d[`support_${n}_text`]} isTextArea onSave={save(`support_${n}_text`)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/></article>)}</div><RepeatableControls onAdd={()=>p.onUpdate((()=>{if(count>=3)return {};const from=slotWords[Math.max(0,count-1)],to=slotWords[count];return {support_count:count+1,[`support_${to}_title`]:d[`support_${from}_title`]??"",[`support_${to}_text`]:d[`support_${from}_text`]??""};})())} canAdd={count<3} canRemove={count>1} addLabel="Add support card" showRemove={false}/><div className={`mt-8 flex flex-wrap gap-4 border-t pt-6 ${theme.border}`}><EditableText value={d.email} onSave={save('email')} className={`block font-semibold ${theme.text}`}/><EditableText value={d.phone} onSave={save('phone')} className={`block ${theme.sub}`}/></div></div></section>}}</Shell>}

export function ContactFaqPremiumBlock(p){return <Shell {...p} schema={ContactFaqPremiumSchema}>{({d,theme,save})=>{const count=Math.max(1,Math.min(3,Number(d.faq_count)||3));return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><Header d={d} theme={theme} save={save}/><div className="mt-8 space-y-3">{slotWords.slice(0,count).map((n,i)=><details key={n} className={`group relative rounded-2xl border p-5 ${theme.card} ${theme.border}`} defaultOpen={i===0}><RepeatableRemoveButton hoverScope="card" overlay label="Remove FAQ" disabled={count<=1} onRemove={()=>p.onUpdate((()=>{const patch={faq_count:Math.max(1,count-1)};for(let x=i;x<count-1;x++){const from=slotWords[x+1],to=slotWords[x];patch[`faq_${to}_question`]=d[`faq_${from}_question`]??"";patch[`faq_${to}_answer`]=d[`faq_${from}_answer`]??"";}return patch;})())}/><summary className={`cursor-pointer list-none pr-10 font-semibold ${theme.text}`}><EditableText value={d[`faq_${n}_question`]} onSave={save(`faq_${n}_question`)} className="block"/></summary><EditableText value={d[`faq_${n}_answer`]} isTextArea onSave={save(`faq_${n}_answer`)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/></details>)}</div><RepeatableControls onAdd={()=>p.onUpdate((()=>{if(count>=3)return {};const from=slotWords[Math.max(0,count-1)],to=slotWords[count];return {faq_count:count+1,[`faq_${to}_question`]:d[`faq_${from}_question`]??"",[`faq_${to}_answer`]:d[`faq_${from}_answer`]??""};})())} canAdd={count<3} canRemove={count>1} addLabel="Add FAQ" showRemove={false}/></div><div className={`rounded-[2rem] border p-6 sm:p-8 ${theme.card} ${theme.border}`}><PremiumEditableForm fields={d.fields} onSave={(fields)=>p.onUpdate({fields})} submitLabel={d.primary_label} theme={theme}/><div className={`mt-6 border-t pt-5 text-sm ${theme.border} ${theme.sub}`}><EditableText value={d.email} onSave={save('email')} className="block"/><EditableText value={d.phone} onSave={save('phone')} className="mt-1 block"/></div></div></div></section>}}</Shell>}

export function ContactMultiStepPremiumBlock(p){const [step,setStep]=useState(0);return <Shell {...p} schema={ContactMultiStepPremiumSchema}>{({d,theme,save})=>{const steps=[['one','Name','Your name'],['two','Request','Tell us what you need'],['three','Email','you@example.com']];const [n,label,placeholder]=steps[step];return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-5xl"><div className="max-w-2xl"><Header d={d} theme={theme} save={save}/></div><div className={`mt-10 overflow-hidden rounded-[2rem] border ${theme.card} ${theme.border}`}><div className={`grid border-b sm:grid-cols-3 ${theme.border}`}>{steps.map(([key],i)=><button key={key} type="button" onClick={()=>setStep(i)} className={`px-5 py-4 text-left text-sm font-semibold ${i===step?theme.text:theme.sub} ${i===step?'bg-black/5 dark:bg-white/5':''}`}>0{i+1} · {d[`step_${key}_title`]}</button>)}</div><div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[.75fr_1.25fr]"><div><EditableText value={d[`step_${n}_title`]} onSave={save(`step_${n}_title`)} className={`block text-2xl font-bold ${theme.text}`}/><EditableText value={d[`step_${n}_text`]} isTextArea onSave={save(`step_${n}_text`)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/></div><div><PremiumMultiStepForm fields={d.fields} onSave={(fields)=>p.onUpdate({fields})} submitLabel={d.submit_label} theme={theme} step={step} setStep={setStep}/></div></div></div></div></section>}}</Shell>}

export function ContactLiveChatPremiumBlock(p){return <Shell {...p} schema={ContactLiveChatPremiumSchema}>{({d,theme,save})=><section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className={`mx-auto grid max-w-6xl gap-8 rounded-[2rem] border p-7 sm:p-10 lg:grid-cols-[1fr_.72fr] lg:items-center ${theme.card} ${theme.border}`}><div><Header d={d} theme={theme} save={save}/><div className="mt-7 flex flex-wrap gap-3"><EditableButton label={d.primary_label} url={d.chat_url} onSave={(label,url)=>p.onUpdate({primary_label:label,chat_url:url})} className="rounded-full bg-slate-900 px-6 py-3 text-sm font-bold text-white"/><EditableButton label={d.secondary_label} url={d.secondary_url} onSave={(label,url)=>p.onUpdate({secondary_label:label,secondary_url:url})} className={`rounded-full border px-6 py-3 text-sm font-bold ${theme.border} ${theme.text}`}/></div></div><div className={`rounded-2xl border p-6 ${theme.bg} ${theme.border}`}><div className="flex items-start gap-4"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-full border ${theme.border}`}>✦</div><div><p className={`font-semibold ${theme.text}`}>Connected chat</p><EditableText value={d.chat_note} isTextArea onSave={save('chat_note')} className={`mt-2 block text-sm leading-6 ${theme.sub}`}/></div></div><p className={`mt-5 text-xs ${theme.sub}`}>Cosmic AI does not generate live availability or presence claims.</p></div></div></section>}</Shell>}

