import { EditableText } from "../Shared/EditableText";
import { EditableButton } from "../Shared/EditableButton";
import { getEffectiveTheme } from "../../../../theme/Theme";
import { useState } from "react";

const shared=(type,title,purpose,description,defaults)=>({type,title,category:"Contact",purpose,description,tags:["contact","premium","pro"],defaults});
const base={eyebrow:"CONTACT",heading:"Let’s make the next step simple.",text:"Choose the contact option that fits your needs.",email:"hello@example.com",phone:"+1 (555) 010-0200",address:"Available by appointment",primary_label:"Send inquiry",primary_url:"#"};
export const ContactSplitPremiumSchema=shared("contact_split_premium","Split Contact","Create a premium split contact section.","Contact details paired with a polished inquiry form.",{...base,eyebrow:"START A CONVERSATION",heading:"Tell us what you’re planning."});
export const ContactMapPremiumSchema=shared("contact_map_premium","Map Contact","Create a location-first premium contact section.","Map-style location panel with editable address and directions link.",{...base,eyebrow:"FIND US",heading:"Visit, call, or send a message.",map_label:"Map preview",directions_label:"Get directions",directions_url:"#"});
export const ContactAppointmentPremiumSchema=shared("contact_appointment_premium","Appointment Booking","Create an appointment-oriented contact section without inventing availability.","Scheduling CTA with editable appointment note and booking URL.",{...base,eyebrow:"BOOK A TIME",heading:"Choose the right way to connect.",primary_label:"Book appointment",booking_url:"#",appointment_note:"Connect your real booking link and availability before publishing.",duration_label:"Appointment length varies"});
export const ContactSupportCenterPremiumSchema=shared("contact_support_center_premium","Support Center","Create a premium support contact hub.","Support channels and help topics with clear escalation paths.",{...base,eyebrow:"SUPPORT CENTER",heading:"Help is easy to find.",support_one_title:"General support",support_one_text:"Questions about your account or service.",support_two_title:"Technical help",support_two_text:"Get help with setup or troubleshooting.",support_three_title:"Billing",support_three_text:"Questions about invoices or plan details."});
export const ContactFaqPremiumSchema=shared("contact_faq_premium","FAQ + Contact","Create a premium FAQ and contact section.","Common questions paired with a focused inquiry form.",{...base,eyebrow:"QUESTIONS, ANSWERED",heading:"Get clarity before you get in touch.",faq_one_question:"What should I include in my inquiry?",faq_one_answer:"Share the goal, timing, and any useful context so the conversation can start clearly.",faq_two_question:"What happens after I contact you?",faq_two_answer:"Use this space to explain your real follow-up process before publishing.",faq_three_question:"Can I ask about a custom requirement?",faq_three_answer:"Yes—replace this placeholder with the real options your business supports."});
export const ContactMultiStepPremiumSchema=shared("contact_multistep_premium","Multi-step Contact","Create a premium staged inquiry section.","A focused multi-step form experience with a readable static fallback.",{...base,eyebrow:"START YOUR INQUIRY",heading:"A few details. One clear next step.",step_one_title:"About you",step_one_text:"Start with the essentials.",step_two_title:"Your request",step_two_text:"Add the context that matters.",step_three_title:"Contact details",step_three_text:"Tell us how to reach you.",submit_label:"Send inquiry"});
export const ContactLiveChatPremiumSchema=shared("contact_live_chat_premium","Live Chat CTA","Create a premium chat-entry contact section.","A polished live-chat call to action without fabricated online status.",{...base,eyebrow:"CHAT WITH US",heading:"Prefer a quick conversation?",text:"Connect your real chat or messaging destination before publishing.",primary_label:"Start chat",chat_url:"#",chat_note:"Chat availability depends on your connected support channel.",secondary_label:"Send an email",secondary_url:"mailto:hello@example.com"});

function Header({d,theme,save}){return <><EditableText value={d.eyebrow} onSave={save('eyebrow')} className={`block text-xs font-semibold uppercase tracking-[0.24em] ${theme.sub}`}/><EditableText value={d.heading} onSave={save('heading')} className={`mt-4 block text-4xl font-bold leading-tight sm:text-5xl ${theme.text}`}/><EditableText value={d.text} isTextArea onSave={save('text')} className={`mt-5 block text-base leading-7 ${theme.sub}`}/></>}
function Shell({block,onUpdate,globalTheme,schema,children}){const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const d={...schema.defaults,...block};const save=(key)=>(value)=>onUpdate({[key]:value});return children({d,theme,save});}
function Field({label,placeholder,theme}){return <label className="block"><span className={`mb-2 block text-xs font-semibold uppercase tracking-[0.16em] ${theme.sub}`}>{label}</span><input placeholder={placeholder} className={`w-full rounded-xl border bg-transparent px-4 py-3 text-sm ${theme.border} ${theme.text}`}/></label>}
export function ContactSplitPremiumBlock(p){return <Shell {...p} schema={ContactSplitPremiumSchema}>{({d,theme,save})=><section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><Header d={d} theme={theme} save={save}/><div className={`mt-8 space-y-3 border-t pt-6 ${theme.border}`}><EditableText value={d.email} onSave={save('email')} className={`block font-semibold ${theme.text}`}/><EditableText value={d.phone} onSave={save('phone')} className={`block font-semibold ${theme.text}`}/><EditableText value={d.address} onSave={save('address')} className={`block ${theme.sub}`}/></div></div><div className={`rounded-[2rem] border p-6 sm:p-8 ${theme.card} ${theme.border}`}><div className="grid gap-4 sm:grid-cols-2"><Field label="Name" placeholder="Your name" theme={theme}/><Field label="Email" placeholder="you@example.com" theme={theme}/></div><div className="mt-4"><Field label="Message" placeholder="Tell us what you need" theme={theme}/></div><button type="button" className="mt-5 w-full rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">{d.primary_label}</button></div></div></section>}</Shell>}
export function ContactMapPremiumBlock(p){return <Shell {...p} schema={ContactMapPremiumSchema}>{({d,theme,save})=><section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><Header d={d} theme={theme} save={save}/><div className="mt-8 space-y-3"><EditableText value={d.address} onSave={save('address')} className={`block text-lg font-semibold ${theme.text}`}/><EditableText value={d.phone} onSave={save('phone')} className={`block ${theme.sub}`}/><EditableText value={d.email} onSave={save('email')} className={`block ${theme.sub}`}/></div><div className="mt-6"><EditableButton label={d.directions_label} url={d.directions_url} onLabelSave={save('directions_label')} onUrlSave={save('directions_url')} className="rounded-full bg-slate-900 px-5 py-3 text-sm font-bold text-white"/></div></div><div className={`grid min-h-80 place-items-center overflow-hidden rounded-[2rem] border ${theme.card} ${theme.border}`}><div className="text-center"><div className={`mx-auto mb-4 grid h-16 w-16 place-items-center rounded-full border ${theme.border} ${theme.bg}`}>⌖</div><EditableText value={d.map_label} onSave={save('map_label')} className={`block text-sm font-semibold ${theme.text}`}/><p className={`mt-2 text-xs ${theme.sub}`}>Connect a real map or directions URL before publishing.</p></div></div></div></section>}</Shell>}
export function ContactAppointmentPremiumBlock(p){return <Shell {...p} schema={ContactAppointmentPremiumSchema}>{({d,theme,save})=><section className={`px-6 py-20 ${theme.bg}`}><div className={`mx-auto max-w-5xl rounded-[2rem] border p-7 sm:p-10 ${theme.card} ${theme.border}`}><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><Header d={d} theme={theme} save={save}/><EditableText value={d.appointment_note} onSave={save('appointment_note')} className={`mt-6 block text-sm ${theme.sub}`}/></div><div className={`rounded-2xl border p-6 ${theme.bg} ${theme.border}`}><EditableText value={d.duration_label} onSave={save('duration_label')} className={`block text-sm font-semibold ${theme.text}`}/><div className="mt-5"><EditableButton label={d.primary_label} url={d.booking_url} onLabelSave={save('primary_label')} onUrlSave={save('booking_url')} className="w-full rounded-xl bg-slate-900 px-5 py-3 text-center text-sm font-bold text-white"/></div><p className={`mt-4 text-xs ${theme.sub}`}>Availability is not generated by Cosmic AI.</p></div></div></div></section>}</Shell>}
export function ContactSupportCenterPremiumBlock(p){return <Shell {...p} schema={ContactSupportCenterPremiumSchema}>{({d,theme,save})=><section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><Header d={d} theme={theme} save={save}/></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[1,2,3].map(i=><article key={i} className={`rounded-2xl border p-6 ${theme.card} ${theme.border}`}><EditableText value={d[`support_${['one','two','three'][i-1]}_title`]} onSave={save(`support_${['one','two','three'][i-1]}_title`)} className={`block text-lg font-bold ${theme.text}`}/><EditableText value={d[`support_${['one','two','three'][i-1]}_text`]} isTextArea onSave={save(`support_${['one','two','three'][i-1]}_text`)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/></article>)}</div><div className={`mt-8 flex flex-wrap gap-4 border-t pt-6 ${theme.border}`}><EditableText value={d.email} onSave={save('email')} className={`block font-semibold ${theme.text}`}/><EditableText value={d.phone} onSave={save('phone')} className={`block ${theme.sub}`}/></div></div></section>}</Shell>}

export function ContactFaqPremiumBlock(p){return <Shell {...p} schema={ContactFaqPremiumSchema}>{({d,theme,save})=><section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><Header d={d} theme={theme} save={save}/><div className="mt-8 space-y-3">{[1,2,3].map((i)=>{const n=['one','two','three'][i-1];return <details key={n} className={`group rounded-2xl border p-5 ${theme.card} ${theme.border}`} open={i===1}><summary className={`cursor-pointer list-none font-semibold ${theme.text}`}><EditableText value={d[`faq_${n}_question`]} onSave={save(`faq_${n}_question`)} className="block"/></summary><EditableText value={d[`faq_${n}_answer`]} isTextArea onSave={save(`faq_${n}_answer`)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/></details>})}</div></div><div className={`rounded-[2rem] border p-6 sm:p-8 ${theme.card} ${theme.border}`}><div className="grid gap-4 sm:grid-cols-2"><Field label="Name" placeholder="Your name" theme={theme}/><Field label="Email" placeholder="you@example.com" theme={theme}/></div><div className="mt-4"><Field label="Message" placeholder="How can we help?" theme={theme}/></div><button type="button" className="mt-5 w-full rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">{d.primary_label}</button><div className={`mt-6 border-t pt-5 text-sm ${theme.border} ${theme.sub}`}><EditableText value={d.email} onSave={save('email')} className="block"/><EditableText value={d.phone} onSave={save('phone')} className="mt-1 block"/></div></div></div></section>}</Shell>}

export function ContactMultiStepPremiumBlock(p){const [step,setStep]=useState(0);return <Shell {...p} schema={ContactMultiStepPremiumSchema}>{({d,theme,save})=>{const steps=[['one','Name','Your name'],['two','Request','Tell us what you need'],['three','Email','you@example.com']];const [n,label,placeholder]=steps[step];return <section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-5xl"><div className="max-w-2xl"><Header d={d} theme={theme} save={save}/></div><div className={`mt-10 overflow-hidden rounded-[2rem] border ${theme.card} ${theme.border}`}><div className={`grid border-b sm:grid-cols-3 ${theme.border}`}>{steps.map(([key],i)=><button key={key} type="button" onClick={()=>setStep(i)} className={`px-5 py-4 text-left text-sm font-semibold ${i===step?theme.text:theme.sub} ${i===step?'bg-black/5 dark:bg-white/5':''}`}>0{i+1} · {d[`step_${key}_title`]}</button>)}</div><div className="grid gap-8 p-6 sm:p-8 lg:grid-cols-[.75fr_1.25fr]"><div><EditableText value={d[`step_${n}_title`]} onSave={save(`step_${n}_title`)} className={`block text-2xl font-bold ${theme.text}`}/><EditableText value={d[`step_${n}_text`]} isTextArea onSave={save(`step_${n}_text`)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/></div><div><Field label={label} placeholder={placeholder} theme={theme}/><div className="mt-5 flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} className={`rounded-xl border px-4 py-3 text-sm font-semibold disabled:opacity-40 ${theme.border} ${theme.text}`}>Back</button>{step<2?<button type="button" onClick={()=>setStep(step+1)} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Continue</button>:<button type="button" className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">{d.submit_label}</button>}</div></div></div></div></div></section>}}</Shell>}

export function ContactLiveChatPremiumBlock(p){return <Shell {...p} schema={ContactLiveChatPremiumSchema}>{({d,theme,save})=><section className={`px-6 py-20 ${theme.bg}`}><div className={`mx-auto grid max-w-6xl gap-8 rounded-[2rem] border p-7 sm:p-10 lg:grid-cols-[1fr_.72fr] lg:items-center ${theme.card} ${theme.border}`}><div><Header d={d} theme={theme} save={save}/><div className="mt-7 flex flex-wrap gap-3"><EditableButton label={d.primary_label} url={d.chat_url} onLabelSave={save('primary_label')} onUrlSave={save('chat_url')} className="rounded-full bg-slate-900 px-6 py-3 text-sm font-bold text-white"/><EditableButton label={d.secondary_label} url={d.secondary_url} onLabelSave={save('secondary_label')} onUrlSave={save('secondary_url')} className={`rounded-full border px-6 py-3 text-sm font-bold ${theme.border} ${theme.text}`}/></div></div><div className={`rounded-2xl border p-6 ${theme.bg} ${theme.border}`}><div className="flex items-start gap-4"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-full border ${theme.border}`}>✦</div><div><p className={`font-semibold ${theme.text}`}>Connected chat</p><EditableText value={d.chat_note} isTextArea onSave={save('chat_note')} className={`mt-2 block text-sm leading-6 ${theme.sub}`}/></div></div><p className={`mt-5 text-xs ${theme.sub}`}>Cosmic AI does not generate live availability or presence claims.</p></div></div></section>}</Shell>}

