import { EditableText } from "../Shared/EditableText";
import { RepeatableControls, RepeatableRemoveButton } from "../Shared/RepeatableControls";
import { getEffectiveTheme } from "../../../../theme/Theme";
import { sparkTw } from "../Shared/sparkTailwindRuntime";

const EVENT_PRESETS = [
    { month: "OCT", day: "12", title: "A practical session for your next move", date: "October 12 · 10:00 AM", location: "Online", description: "A focused conversation with useful ideas you can put into action right away.", button_label: "Reserve a place" },
    { month: "NOV", day: "04", title: "Meet the people behind the work", date: "November 4 · 6:00 PM", location: "Our studio", description: "An informal evening to connect, exchange ideas, and see how we approach the work.", button_label: "Save your seat" },
    { month: "DEC", day: "08", title: "Plan a stronger year ahead", date: "December 8 · 1:00 PM", location: "Online", description: "A guided planning session for teams ready to set clearer priorities for what is next.", button_label: "Join the session" },
];

export const EventsGridSchema = {
    type: "events_grid", title: "Events Grid", category: "Events", purpose: "Promote upcoming events with clear dates and simple actions.",
    description: "Display three editable events in a clean, professional grid.", tags: ["events", "workshops", "webinars", "community"],
    defaults: { eyebrow: "Upcoming events", heading: "Useful conversations, coming up.", text: "Join practical sessions, thoughtful gatherings, and opportunities to connect with our team.", events: EVENT_PRESETS },
};

export function EventsGridBlock({ block, onUpdate, globalTheme }) {
    const theme = getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme, globalTheme);
    const data = { ...EventsGridSchema.defaults, ...block, events: Array.isArray(block.events) && block.events.length ? block.events : EventsGridSchema.defaults.events };
    const updateEvent = (index, field, value) => onUpdate({ events: data.events.map((event, eventIndex) => eventIndex === index ? { ...event, [field]: value } : event) });
    const addEvent = () => onUpdate({ events: [...data.events, { ...EVENT_PRESETS[data.events.length % EVENT_PRESETS.length] }] });
    const removeEvent = (index) => { if (data.events.length > 1) onUpdate({ events: data.events.filter((_, eventIndex) => eventIndex !== index) }); };
    return <section className={sparkTw(block, "b10_1", `group/repeatable-section px-6 py-16 sm:px-8 lg:py-20 ${theme.bg} transition-colors duration-500`)}><div className={sparkTw(block, "b10_2", "mx-auto max-w-7xl")}><div className={sparkTw(block, "b10_3", "mb-10 max-w-2xl space-y-4 sm:mb-12")}>{data.eyebrow && <EditableText value={data.eyebrow} className={sparkTw(block, "b10_4", `block text-xs font-semibold uppercase tracking-[0.22em] ${theme.sub}`)} onSave={(eyebrow) => onUpdate({ eyebrow })} />}<EditableText value={data.heading} cosmicType="h2" className={sparkTw(block, "b10_5", `block text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl lg:text-[3.75rem] ${theme.text}`)} onSave={(heading) => onUpdate({ heading })} />{data.text && <EditableText value={data.text} isTextArea className={sparkTw(block, "b10_6", `block max-w-xl text-base leading-7 ${theme.sub}`)} onSave={(text) => onUpdate({ text })} />}</div><div className={sparkTw(block, "b10_7", "grid gap-5 md:grid-cols-3")}>{data.events.map((event, index) => <article key={index} className={sparkTw(block, "b10_8", `group relative flex min-h-full flex-col rounded-2xl border p-6 ${theme.border} ${theme.card}`)}><div className={sparkTw(block, "b10_9", "flex items-start gap-4")}><div className={sparkTw(block, "b10_10", `grid h-16 w-16 shrink-0 place-items-center rounded-xl border text-center ${theme.border}`)}><EditableText value={event.month} className={sparkTw(block, "b10_11", `block text-[10px] font-bold tracking-[0.18em] ${theme.sub}`)} onSave={(month) => updateEvent(index, "month", month)} /><EditableText value={event.day} className={sparkTw(block, "b10_12", `block text-2xl font-bold leading-none ${theme.text}`)} onSave={(day) => updateEvent(index, "day", day)} /></div><div><EditableText value={event.date} className={sparkTw(block, "b10_13", `block text-xs font-semibold ${theme.sub}`)} onSave={(date) => updateEvent(index, "date", date)} /><EditableText value={event.location} className={sparkTw(block, "b10_14", `mt-1 block text-xs ${theme.sub}`)} onSave={(location) => updateEvent(index, "location", location)} /></div></div><EditableText value={event.title} className={sparkTw(block, "b10_15", `mt-7 block text-xl font-bold leading-tight ${theme.text}`)} onSave={(title) => updateEvent(index, "title", title)} /><EditableText value={event.description} isTextArea className={sparkTw(block, "b10_16", `mt-3 block text-sm leading-6 ${theme.sub}`)} onSave={(description) => updateEvent(index, "description", description)} /><EditableText value={event.button_label} className={sparkTw(block, "b10_17", `mt-6 block text-sm font-semibold ${theme.text}`)} onSave={(button_label) => updateEvent(index, "button_label", button_label)} /><RepeatableRemoveButton hoverScope="card" overlay label="Remove event" disabled={data.events.length <= 1} onRemove={() => removeEvent(index)} /></article>)}</div><RepeatableControls onAdd={addEvent} showRemove={false} addLabel="Add event" hoverScope="section" /></div></section>;
}
