import { EditableText } from "../Shared/EditableText";
import { getEffectiveTheme } from "../../../../theme/Theme";

const EVENT_PRESETS = [
    { month: "OCT", day: "12", title: "A practical session for your next move", date: "October 12 · 10:00 AM", location: "Online", description: "A focused conversation with useful ideas you can put into action right away.", button_label: "Reserve a place" },
    { month: "NOV", day: "04", title: "Meet the people behind the work", date: "November 4 · 6:00 PM", location: "Our studio", description: "An informal evening to connect, exchange ideas, and see how we approach the work.", button_label: "Save your seat" },
    { month: "DEC", day: "08", title: "Plan a stronger year ahead", date: "December 8 · 1:00 PM", location: "Online", description: "A guided planning session for teams ready to set clearer priorities for what is next.", button_label: "Join the session" },
];

export const EventsGridSchema = {
    type: "events_grid", title: "Events Grid", category: "Events", purpose: "Promote upcoming events with clear dates and simple actions.",
    description: "Display three editable events in a clean, professional grid.", tags: ["events", "workshops", "webinars", "community"],
    defaults: { eyebrow: "Upcoming events", heading: "Useful conversations, coming up.", text: "Join practical sessions, thoughtful gatherings, and opportunities to connect with our team.", events: EVENT_PRESETS },
};

export function EventsGridBlock({ block, onUpdate, globalTheme }) {
    const theme = getEffectiveTheme(block.resolvedTheme, globalTheme);
    const data = { ...EventsGridSchema.defaults, ...block, events: Array.isArray(block.events) && block.events.length ? block.events : EventsGridSchema.defaults.events };
    const updateEvent = (index, field, value) => onUpdate({ events: data.events.map((event, eventIndex) => eventIndex === index ? { ...event, [field]: value } : event) });
    const addEvent = () => onUpdate({ events: [...data.events, { ...EVENT_PRESETS[data.events.length % EVENT_PRESETS.length] }] });
    const removeEvent = (index) => { if (data.events.length > 1) onUpdate({ events: data.events.filter((_, eventIndex) => eventIndex !== index) }); };
    return <section className={`px-6 py-16 sm:px-8 lg:py-20 ${theme.bg} transition-colors duration-500`}><div className="mx-auto max-w-7xl"><div className="mb-10 max-w-2xl space-y-4 sm:mb-12">{data.eyebrow && <EditableText value={data.eyebrow} className={`block text-xs font-semibold uppercase tracking-[0.22em] ${theme.sub}`} onSave={(eyebrow) => onUpdate({ eyebrow })} />}<EditableText value={data.heading} className={`block text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl lg:text-[3.75rem] ${theme.text}`} onSave={(heading) => onUpdate({ heading })} />{data.text && <EditableText value={data.text} isTextArea className={`block max-w-xl text-base leading-7 ${theme.sub}`} onSave={(text) => onUpdate({ text })} />}</div><div className="grid gap-5 md:grid-cols-3">{data.events.map((event, index) => <article key={index} className={`flex min-h-full flex-col rounded-2xl border p-6 ${theme.border} ${theme.card}`}><div className="flex items-start gap-4"><div className={`grid h-16 w-16 shrink-0 place-items-center rounded-xl border text-center ${theme.border}`}><EditableText value={event.month} className={`block text-[10px] font-bold tracking-[0.18em] ${theme.sub}`} onSave={(month) => updateEvent(index, "month", month)} /><EditableText value={event.day} className={`block text-2xl font-bold leading-none ${theme.text}`} onSave={(day) => updateEvent(index, "day", day)} /></div><div><EditableText value={event.date} className={`block text-xs font-semibold ${theme.sub}`} onSave={(date) => updateEvent(index, "date", date)} /><EditableText value={event.location} className={`mt-1 block text-xs ${theme.sub}`} onSave={(location) => updateEvent(index, "location", location)} /></div></div><EditableText value={event.title} className={`mt-7 block text-xl font-bold leading-tight ${theme.text}`} onSave={(title) => updateEvent(index, "title", title)} /><EditableText value={event.description} isTextArea className={`mt-3 block text-sm leading-6 ${theme.sub}`} onSave={(description) => updateEvent(index, "description", description)} /><EditableText value={event.button_label} className={`mt-6 block text-sm font-semibold ${theme.text}`} onSave={(button_label) => updateEvent(index, "button_label", button_label)} /><button type="button" onClick={() => removeEvent(index)} disabled={data.events.length <= 1} className="cosmic-spark-custom-remove mt-4 inline-flex min-h-9 w-fit items-center justify-center rounded-lg border border-rose-500 bg-rose-600 px-3 py-2 text-xs font-bold !text-white shadow-sm transition hover:bg-rose-500 disabled:cursor-not-allowed disabled:border-slate-400 disabled:bg-slate-300 disabled:!text-slate-600 disabled:opacity-80">Remove event</button></article>)}</div><button type="button" onClick={addEvent} className="cosmic-spark-custom-add mt-6 inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold !text-slate-900 shadow-sm transition hover:bg-slate-100">+ Add event</button></div></section>;
}
