import { useState } from "react";

function TemplatePreview({ template, large = false }) {
    return <div className={`relative overflow-hidden rounded-xl border border-white/10 bg-gradient-to-br ${template.thumbnail} ${large ? "h-32" : "h-24"}`}><div className="absolute inset-x-4 top-4 h-2 rounded-full bg-white/40" /><div className="absolute inset-x-4 top-8 h-7 rounded-md bg-white/25" /><div className="absolute inset-x-4 top-[4.25rem] grid grid-cols-3 gap-1.5"><span className="h-8 rounded bg-white/20" /><span className="h-8 rounded bg-white/20" /><span className="h-8 rounded bg-white/20" /></div></div>;
}

export function FeaturedTemplateCard({ template, onPreview, onUse }) {
    return <article className="flex flex-col gap-4 rounded-2xl border border-violet-400/20 bg-gradient-to-br from-violet-500/[0.10] to-white/[0.035] p-4 sm:flex-row"><div className="sm:w-56"><TemplatePreview template={template} large /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="rounded-full bg-violet-400/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-violet-200">Featured</span><span className="text-xs text-slate-400">{template.category}</span></div><h2 className="mt-2 text-lg font-semibold tracking-tight text-white">{template.name}</h2><p className="mt-1 text-sm text-slate-400">{template.description}</p><p className="mt-3 text-xs text-slate-500">{template.pageCount} pages · {template.industry}</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => onPreview(template)} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 transition hover:bg-white/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-violet-400">Preview</button><button type="button" onClick={() => onUse(template)} className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-950 transition hover:bg-slate-200 focus:outline-none focus:ring-2 focus:ring-violet-400">Use Template</button></div></div></article>;
}

export default function TemplateCard({ template, onPreview, onUse, onSave, onDuplicate }) {
    const [menuOpen, setMenuOpen] = useState(false);
    return <article className="group relative rounded-2xl border border-white/10 bg-white/[0.035] p-3 transition hover:-translate-y-0.5 hover:border-violet-400/35 hover:bg-white/[0.055] hover:shadow-xl hover:shadow-black/20 focus-within:border-violet-400/55"><TemplatePreview template={template} /><div className="mt-3 flex items-start gap-2"><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><h2 className="truncate text-sm font-semibold text-white">{template.name}</h2>{template.isNew && <span className="rounded-full bg-cyan-400/10 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-cyan-200">New</span>}{template.featured && <span className="rounded-full bg-violet-400/10 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wide text-violet-200">Featured</span>}</div><p className="mt-1 text-xs text-slate-500">{template.category} · {template.pageCount} pages</p></div><button type="button" aria-label={`More actions for ${template.name}`} aria-expanded={menuOpen} onClick={() => setMenuOpen((value) => !value)} className="rounded-lg p-1 text-slate-500 transition hover:bg-white/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-violet-400">•••</button></div><div className="mt-3 flex gap-2"><button type="button" onClick={() => onPreview(template)} className="flex-1 rounded-lg border border-white/10 py-1.5 text-xs font-semibold text-slate-300 transition hover:bg-white/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-violet-400">Preview</button><button type="button" onClick={() => onUse(template)} className="flex-1 rounded-lg bg-white py-1.5 text-xs font-semibold text-slate-950 transition hover:bg-slate-200 focus:outline-none focus:ring-2 focus:ring-violet-400">Use</button></div>{menuOpen && <div className="absolute right-3 top-32 z-10 w-32 rounded-xl border border-white/10 bg-[#1a1a1d] p-1 shadow-2xl shadow-black/40"><button type="button" onClick={() => { onSave(template); setMenuOpen(false); }} className="w-full rounded-lg px-3 py-2 text-left text-xs font-medium text-slate-200 transition hover:bg-white/10 focus:bg-white/10 focus:outline-none">Save</button><button type="button" onClick={() => { onDuplicate(template); setMenuOpen(false); }} className="w-full rounded-lg px-3 py-2 text-left text-xs font-medium text-slate-200 transition hover:bg-white/10 focus:bg-white/10 focus:outline-none">Duplicate</button></div>}</article>;
}
