import { useEffect, useState } from 'react';
import axios from 'axios';

const labels = { website_admin: 'Website Admin', website_editor: 'Website Editor' };
export default function WebsiteAccessModal({ open, website, onClose }) {
    const [members, setMembers] = useState([]); const [email, setEmail] = useState(''); const [role, setRole] = useState('website_editor'); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
    const load = async () => { if (!website) return; setLoading(true); setError(''); try { const r=await axios.get(route('websites.access.index', website.id)); setMembers(r.data.members || []); } catch(e){ setError(e.response?.data?.message || 'Could not load access.'); } finally { setLoading(false); } };
    useEffect(()=>{ if(open){ setEmail(''); setRole('website_editor'); load(); } },[open, website?.id]);
    if(!open || !website) return null;
    const add = async (e)=>{ e.preventDefault(); if(!email.trim()) return; setLoading(true); setError(''); try { await axios.post(route('websites.access.store',website.id),{email:email.trim(),role}); setEmail(''); await load(); } catch(e){ setError(e.response?.data?.errors?.email?.[0] || e.response?.data?.message || 'Could not add access.'); setLoading(false);} };
    const changeRole = async (member,next)=>{ setLoading(true); try { await axios.patch(route('websites.access.update',[website.id,member.id]),{role:next}); await load(); } catch(e){ setError(e.response?.data?.message || 'Could not update role.'); setLoading(false);} };
    const remove = async (member)=>{ setLoading(true); try { await axios.delete(route('websites.access.destroy',[website.id,member.id])); await load(); } catch(e){ setError(e.response?.data?.message || 'Could not remove access.'); setLoading(false);} };
    return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><div className="w-full max-w-2xl rounded-3xl border border-white/10 bg-[#111114] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-300">Website access</p><h2 className="mt-2 text-xl font-semibold text-white">Manage access · {website.name}</h2><p className="mt-2 text-sm text-slate-400">Admins manage website content. Editors stay inside the Builder and can edit existing text, images, buttons and publish.</p></div><button onClick={onClose} className="rounded-lg px-2 py-1 text-slate-400 hover:bg-white/10 hover:text-white">✕</button></div>
    <form onSubmit={add} className="mt-6 grid gap-2 sm:grid-cols-[1fr_170px_auto]"><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="Cosmic account email" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-sm text-white outline-none focus:border-violet-400"/><select value={role} onChange={(e)=>setRole(e.target.value)} className="rounded-xl border border-white/10 bg-[#18181c] px-3 py-3 text-sm text-white"><option value="website_editor">Website Editor</option><option value="website_admin">Website Admin</option></select><button disabled={loading||!email.trim()} className="rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">Add user</button></form>
    {error&&<p className="mt-2 text-xs text-rose-300">{error}</p>}
    <div className="mt-6 space-y-2">{members.map(m=><div key={m.id} className="flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-white">{m.name}</p><p className="text-xs text-slate-500">{m.email}</p></div><div className="flex items-center gap-2"><select disabled={loading} value={m.role} onChange={(e)=>changeRole(m,e.target.value)} className="rounded-lg border border-white/10 bg-[#18181c] px-3 py-2 text-xs text-white"><option value="website_editor">Website Editor</option><option value="website_admin">Website Admin</option></select><button disabled={loading} onClick={()=>remove(m)} className="rounded-lg border border-rose-400/20 px-3 py-2 text-xs font-semibold text-rose-300">Remove</button></div></div>)}{!loading&&members.length===0&&<div className="rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-slate-500">No additional users have access to this website.</div>}</div>
    <div className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-4 text-xs text-slate-400"><strong className="text-slate-200">Website Admin:</strong> pages, blog/content, commerce, media, Builder and publish. <span className="mx-2 text-slate-600">•</span><strong className="text-slate-200">Website Editor:</strong> Builder-only editing and publish; no AI generation, Sparks, theme changes or structural controls.</div></div></div>;
}
