import { EditableButton } from "../Shared/EditableButton";
import { EditableImage } from "../Shared/EditableImage";
import { EditableText } from "../Shared/EditableText";

const F = (key, type = "text", label = null) => ({ key, type, label: label || key.replaceAll("_", " ") });
const Text = ({ value, className = "", fieldPath, cosmicType, area = false, style }) => <EditableText value={value} className={className} fieldPath={fieldPath} cosmicType={cosmicType} isTextArea={area} style={style} />;
const Button = ({ label, url = "#", className = "", fieldPath, style }) => <EditableButton label={label} url={url} className={className} fieldPath={fieldPath} style={style} />;
const Image = ({ src, className = "", fieldPath, background = false, style }) => <EditableImage src={src} className={className} fieldPath={fieldPath} isBackground={background} style={style} />;

const DENTAL = {
    ink: "#17304a", navy: "#10263b", blue: "#2f86a6", blue2: "#54a9c2", mint: "#dff1ed",
    mist: "#eef7f8", paper: "#fbfdfd", white: "#ffffff", line: "#d9e8eb", muted: "#667d88", peach: "#f5e5dc",
};
const STONE = {
    ink: "#17191b", black: "#0f1112", charcoal: "#24282b", graphite: "#343a3d", orange: "#e66b2f",
    orange2: "#f48a4d", sand: "#efe9df", paper: "#f6f3ed", line: "#cfc8bd", muted: "#74716b", white: "#ffffff",
};

const dentalTreatments = [
    { icon: "01", title: "General Dentistry", text: "Check-ups, cleans, fillings, and preventive care for healthy smiles at every age." },
    { icon: "02", title: "Cosmetic Dentistry", text: "Whitening, veneers, and tailored smile improvements with a natural, considered approach." },
    { icon: "03", title: "Emergency Dental", text: "Prompt support for pain, swelling, broken teeth, and urgent dental concerns." },
    { icon: "04", title: "Preventive Care", text: "Practical routines and regular care designed to protect your long-term oral health." },
];

export const MarketplaceDentalHeroSchema = {
    type: "marketplace_dental_hero", title: "Brightline Airy Clinic Hero", category: "Marketplace",
    defaults: {
        eyebrow: "MODERN DENTISTRY · GENTLE CARE", heading: "Dental care that feels", accent_heading: "clear, calm, and personal.",
        text: "Thoughtful dentistry, modern technology, and a team that takes the time to make every visit feel easier.",
        primary_label: "Book an Appointment", primary_url: "/contact", secondary_label: "Explore Treatments", secondary_url: "/treatments",
        image_url: "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1800&q=88",
        trust_label: "New patients welcome", trust_text: "Same-week appointments available",
    },
    fields: [F("eyebrow"), F("heading"), F("accent_heading"), F("text", "textarea"), F("primary_label"), F("primary_url"), F("secondary_label"), F("secondary_url"), F("image_url", "image"), F("trust_label"), F("trust_text")],
};
export function MarketplaceDentalHeroBlock({ block }) {
    const d = { ...MarketplaceDentalHeroSchema.defaults, ...block };
    return <section className="overflow-hidden px-4 py-5 sm:px-6 lg:px-8" style={{ background: DENTAL.paper, color: DENTAL.ink }}>
        <div className="relative mx-auto min-h-[650px] max-w-[1500px] overflow-hidden rounded-[42px] lg:min-h-[720px]" style={{ background: DENTAL.mist }}>
            <div className="absolute -left-20 -top-24 h-72 w-72 rounded-full blur-3xl" style={{ background: DENTAL.mint, opacity: .9 }} />
            <div className="absolute bottom-[-100px] left-[36%] h-72 w-72 rounded-full blur-3xl" style={{ background: DENTAL.peach, opacity: .6 }} />
            <div className="relative grid min-h-[650px] lg:min-h-[720px] lg:grid-cols-[.92fr_1.08fr]">
                <div className="z-10 flex items-center px-7 py-16 sm:px-12 lg:px-16 xl:px-20">
                    <div className="max-w-[650px]">
                        <div className="mb-7 inline-flex items-center gap-3 rounded-full border bg-white/75 px-4 py-2 shadow-sm backdrop-blur" style={{ borderColor: DENTAL.line }}><span className="h-2 w-2 rounded-full" style={{ background: DENTAL.blue2 }} /><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.2em]" style={{ color: DENTAL.blue }} /></div>
                        <Text value={d.heading} fieldPath="heading" cosmicType="h1" className="block text-[clamp(3.25rem,6vw,6.15rem)] font-black leading-[.92] tracking-[-.06em]" />
                        <Text value={d.accent_heading} fieldPath="accent_heading" className="mt-1 block font-serif text-[clamp(3rem,5.6vw,5.7rem)] italic leading-[.95] tracking-[-.05em]" style={{ color: DENTAL.blue }} />
                        <Text value={d.text} fieldPath="text" area className="mt-8 block max-w-xl text-base leading-8 sm:text-lg" style={{ color: DENTAL.muted }} />
                        <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button label={d.primary_label} url={d.primary_url} fieldPath="primary_label" className="inline-flex min-h-12 items-center justify-center rounded-full px-7 text-sm font-black text-white shadow-lg" style={{ background: DENTAL.navy }} /><Button label={d.secondary_label} url={d.secondary_url} fieldPath="secondary_label" className="inline-flex min-h-12 items-center justify-center rounded-full border bg-white px-7 text-sm font-black" style={{ borderColor: DENTAL.line, color: DENTAL.ink }} /></div>
                    </div>
                </div>
                <div className="relative min-h-[430px] lg:min-h-0">
                    <div className="absolute inset-5 overflow-hidden rounded-[34px] lg:inset-y-5 lg:left-2 lg:right-5"><Image src={d.image_url} fieldPath="image_url" className="h-full w-full" /></div>
                    <div className="absolute bottom-9 left-9 max-w-[270px] rounded-[22px] border bg-white/90 p-5 shadow-[0_24px_70px_rgba(23,48,74,.18)] backdrop-blur-xl lg:left-[-34px]" style={{ borderColor: DENTAL.line }}><Text value={d.trust_label} fieldPath="trust_label" className="block text-xs font-black uppercase tracking-[.12em]" style={{ color: DENTAL.blue }} /><Text value={d.trust_text} fieldPath="trust_text" className="mt-2 block text-sm font-bold leading-6" /></div>
                </div>
            </div>
        </div>
    </section>;
}

export const MarketplaceDentalTreatmentsSchema = {
    type: "marketplace_dental_treatments", title: "Brightline Treatment Cards", category: "Marketplace",
    defaults: { eyebrow: "TREATMENTS", heading: "Everything you need for a healthier, more confident smile.", text: "From everyday preventive care to cosmetic and urgent dentistry, treatment is explained clearly and tailored to you.", items: dentalTreatments },
    fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("items", "repeater")],
};
export function MarketplaceDentalTreatmentsBlock({ block }) {
    const d = { ...MarketplaceDentalTreatmentsSchema.defaults, ...block }; const items = Array.isArray(d.items) && d.items.length ? d.items : dentalTreatments;
    return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{ background: DENTAL.white, color: DENTAL.ink }}><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[1.1fr_.7fr] lg:items-end"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-4xl text-4xl font-black leading-[1.01] tracking-[-.05em] sm:text-5xl lg:text-6xl" /></div><Text value={d.text} fieldPath="text" area className="block max-w-xl text-base leading-8" style={{ color: DENTAL.muted }} /></div><div className="mt-14 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{items.slice(0, 6).map((it, i) => <article key={i} className="group min-h-[330px] rounded-[28px] border p-7 transition duration-300 hover:-translate-y-1" style={{ borderColor: DENTAL.line, background: i % 2 ? DENTAL.paper : DENTAL.mist }}><Text value={it.icon || String(i + 1).padStart(2, "0")} fieldPath={`items.${i}.icon`} className="block text-xs font-black tracking-[.16em]" style={{ color: DENTAL.blue }} /><div className="mt-24"><Text value={it.title} fieldPath={`items.${i}.title`} cosmicType="h3" className="block text-2xl font-black tracking-[-.025em]" /><Text value={it.text} fieldPath={`items.${i}.text`} area className="mt-4 block text-sm leading-7" style={{ color: DENTAL.muted }} /></div></article>)}</div></div></section>;
}

export const MarketplaceDentalComfortSchema = {
    type: "marketplace_dental_comfort", title: "Brightline Comfort Story", category: "Marketplace",
    defaults: { eyebrow: "A CALMER DENTAL EXPERIENCE", heading: "Good dentistry starts with feeling understood.", text: "We explain your options without pressure, use modern technology to make treatment more comfortable, and keep every step clear from first visit to follow-up.", image_url: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1500&q=88", quote: "No rushed appointments. No confusing treatment plans. Just clear care built around you." },
    fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("image_url", "image"), F("quote")],
};
export function MarketplaceDentalComfortBlock({ block }) { const d = { ...MarketplaceDentalComfortSchema.defaults, ...block }; return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{ background: DENTAL.mist, color: DENTAL.ink }}><div className="mx-auto grid max-w-[1380px] gap-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:gap-20"><div className="relative"><div className="overflow-hidden rounded-[180px_34px_34px_34px]"><Image src={d.image_url} fieldPath="image_url" className="aspect-[6/5] w-full" /></div><div className="absolute -bottom-8 right-4 max-w-[350px] rounded-[24px] border bg-white p-6 shadow-xl" style={{ borderColor: DENTAL.line }}><Text value={d.quote} fieldPath="quote" className="block font-serif text-xl italic leading-8" style={{ color: DENTAL.navy }} /></div></div><div className="pt-6 lg:pt-0"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl lg:text-6xl" /><Text value={d.text} fieldPath="text" area className="mt-7 block text-base leading-8" style={{ color: DENTAL.muted }} /><div className="mt-9 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-5"><span className="text-2xl">◎</span><div className="mt-3 text-sm font-black">Modern technology</div></div><div className="rounded-2xl bg-white p-5"><span className="text-2xl">♡</span><div className="mt-3 text-sm font-black">Gentle approach</div></div></div></div></div></section>; }

export const MarketplaceDentalProcessSchema = {
    type: "marketplace_dental_process", title: "Brightline Patient Journey", category: "Marketplace",
    defaults: { eyebrow: "WHAT TO EXPECT", heading: "A simple path from first visit to feeling better.", steps: [{ number: "01", title: "Book", text: "Choose a suitable appointment and tell us what you need." }, { number: "02", title: "Understand", text: "We listen, assess, explain, and answer your questions." }, { number: "03", title: "Plan", text: "Receive a clear treatment plan with options and costs." }, { number: "04", title: "Care", text: "Move forward at a pace that feels comfortable for you." }] },
    fields: [F("eyebrow"), F("heading"), F("steps", "repeater")],
};
export function MarketplaceDentalProcessBlock({ block }) { const d = { ...MarketplaceDentalProcessSchema.defaults, ...block }; const steps = Array.isArray(d.steps) ? d.steps : MarketplaceDentalProcessSchema.defaults.steps; return <section className="px-6 py-24 lg:px-8" style={{ background: DENTAL.navy, color: "white" }}><div className="mx-auto max-w-[1380px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: "#8fd2df" }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-4xl text-4xl font-black leading-[1.01] tracking-[-.05em] sm:text-5xl lg:text-6xl" /><div className="mt-14 grid gap-px overflow-hidden rounded-[28px] border md:grid-cols-2 lg:grid-cols-4" style={{ borderColor: "rgba(255,255,255,.13)", background: "rgba(255,255,255,.13)" }}>{steps.slice(0, 6).map((s, i) => <article key={i} className="min-h-[280px] p-7 lg:p-8" style={{ background: DENTAL.navy }}><Text value={s.number || String(i + 1).padStart(2, "0")} fieldPath={`steps.${i}.number`} className="text-xs font-black tracking-[.18em]" style={{ color: "#8fd2df" }} /><Text value={s.title} fieldPath={`steps.${i}.title`} cosmicType="h3" className="mt-20 block text-2xl font-black" /><Text value={s.text} fieldPath={`steps.${i}.text`} area className="mt-3 block text-sm leading-7 text-white/60" /></article>)}</div></div></section>; }

export const MarketplaceDentalTeamSchema = {
    type: "marketplace_dental_team", title: "Brightline Team Profiles", category: "Marketplace",
    defaults: { eyebrow: "MEET THE TEAM", heading: "Experienced clinicians. Warm, human care.", text: "A team that combines clinical precision with the kind of communication that helps patients feel comfortable and informed.", members: [{ name: "Dr. Emily Hart", role: "Principal Dentist", image_url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=86" }, { name: "Dr. Daniel Cho", role: "Dentist", image_url: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=900&q=86" }, { name: "Sophie Lane", role: "Oral Health Therapist", image_url: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=900&q=86" }] },
    fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("members", "repeater")],
};
export function MarketplaceDentalTeamBlock({ block }) { const d = { ...MarketplaceDentalTeamSchema.defaults, ...block }; const members = Array.isArray(d.members) && d.members.length ? d.members : MarketplaceDentalTeamSchema.defaults.members; return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{ background: DENTAL.paper, color: DENTAL.ink }}><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[1fr_.72fr]"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-4xl text-4xl font-black leading-[1.01] tracking-[-.05em] sm:text-5xl lg:text-6xl" /></div><Text value={d.text} fieldPath="text" area className="self-end text-base leading-8" style={{ color: DENTAL.muted }} /></div><div className="mt-14 grid gap-5 md:grid-cols-3">{members.slice(0, 4).map((m, i) => <article key={i}><div className={`overflow-hidden ${i === 1 ? "rounded-[34px_120px_34px_34px]" : "rounded-[120px_34px_34px_34px]"}`}><Image src={m.image_url} fieldPath={`members.${i}.image_url`} className="aspect-[4/5] w-full" /></div><Text value={m.name} fieldPath={`members.${i}.name`} cosmicType="h3" className="mt-5 block text-xl font-black" /><Text value={m.role} fieldPath={`members.${i}.role`} className="mt-1 block text-sm" style={{ color: DENTAL.blue }} /></article>)}</div></div></section>; }

export const MarketplaceDentalProofSchema = {
    type: "marketplace_dental_proof", title: "Brightline Patient Proof", category: "Marketplace",
    defaults: { eyebrow: "PATIENT CONFIDENCE", heading: "Care measured in trust, not just treatment.", stats: [{ value: "4.9/5", label: "Patient rating" }, { value: "2,500+", label: "Smiles cared for" }, { value: "98%", label: "Would recommend" }], quote: "I finally understood what was happening and why. The whole visit felt calm, clear, and genuinely caring.", name: "Ava M.", role: "Brightline patient" },
    fields: [F("eyebrow"), F("heading"), F("stats", "repeater"), F("quote", "textarea"), F("name"), F("role")],
};
export function MarketplaceDentalProofBlock({ block }) { const d = { ...MarketplaceDentalProofSchema.defaults, ...block }; const stats = Array.isArray(d.stats) ? d.stats : MarketplaceDentalProofSchema.defaults.stats; return <section className="px-6 py-24 lg:px-8" style={{ background: DENTAL.white, color: DENTAL.ink }}><div className="mx-auto grid max-w-[1380px] gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-[32px] p-8 sm:p-12" style={{ background: DENTAL.mint }}><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl" /><div className="mt-10 grid gap-3 sm:grid-cols-3">{stats.slice(0, 3).map((s, i) => <div key={i} className="rounded-2xl bg-white/65 p-5"><Text value={s.value} fieldPath={`stats.${i}.value`} className="block text-2xl font-black" /><Text value={s.label} fieldPath={`stats.${i}.label`} className="mt-1 block text-xs" style={{ color: DENTAL.muted }} /></div>)}</div></div><figure className="flex min-h-[430px] flex-col justify-between rounded-[32px] p-8 sm:p-12" style={{ background: DENTAL.navy, color: "white" }}><div className="text-4xl" style={{ color: "#8fd2df" }}>“</div><Text value={d.quote} fieldPath="quote" area className="block max-w-3xl font-serif text-3xl italic leading-[1.3] sm:text-4xl" /><figcaption><Text value={d.name} fieldPath="name" className="block text-sm font-black" /><Text value={d.role} fieldPath="role" className="mt-1 block text-xs text-white/50" /></figcaption></figure></div></section>; }

export const MarketplaceDentalInfoSchema = {
    type: "marketplace_dental_info", title: "Brightline Patient Information", category: "Marketplace",
    defaults: { eyebrow: "PATIENT INFORMATION", heading: "Know what to expect before you arrive.", items: [{ title: "First visits", text: "Allow time for a full history, examination, and discussion of your goals." }, { title: "Payment & fees", text: "Clear estimates before treatment, with payment options explained upfront." }, { title: "Dental anxiety", text: "Tell us what helps. We can slow things down and explain each step as we go." }, { title: "Aftercare", text: "Simple take-home guidance and a clear plan for follow-up when needed." }] },
    fields: [F("eyebrow"), F("heading"), F("items", "repeater")],
};
export function MarketplaceDentalInfoBlock({ block }) { const d = { ...MarketplaceDentalInfoSchema.defaults, ...block }; const items = Array.isArray(d.items) ? d.items : MarketplaceDentalInfoSchema.defaults.items; return <section className="px-6 py-24 lg:px-8" style={{ background: DENTAL.mist, color: DENTAL.ink }}><div className="mx-auto max-w-[1280px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-4xl text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl" /><div className="mt-12 divide-y rounded-[28px] border bg-white px-7 sm:px-10" style={{ borderColor: DENTAL.line }}>{items.slice(0, 6).map((it, i) => <article key={i} className="grid gap-4 py-7 md:grid-cols-[56px_.55fr_1fr] md:items-start"><span className="grid h-11 w-11 place-items-center rounded-full text-xs font-black" style={{ background: DENTAL.mint, color: DENTAL.blue }}>{String(i + 1).padStart(2, "0")}</span><Text value={it.title} fieldPath={`items.${i}.title`} cosmicType="h3" className="block text-xl font-black" /><Text value={it.text} fieldPath={`items.${i}.text`} area className="block text-sm leading-7" style={{ color: DENTAL.muted }} /></article>)}</div></div></section>; }

export const MarketplaceDentalFaqSchema = {
    type: "marketplace_dental_faq", title: "Brightline FAQ", category: "Marketplace",
    defaults: { eyebrow: "COMMON QUESTIONS", heading: "Answers that make the next step easier.", questions: [{ q: "Do you accept new patients?", a: "Yes. New patients are welcome and we can help you choose the right appointment type." }, { q: "What if I am nervous about dental treatment?", a: "Tell us when you book. We can allow extra time, explain each step, and move at a pace that feels comfortable." }, { q: "Can I get an urgent appointment?", a: "We reserve capacity for urgent dental concerns. Contact the clinic as early as possible." }, { q: "Will I know the cost before treatment?", a: "Yes. Once we understand what you need, we explain options and provide a clear estimate before proceeding." }] },
    fields: [F("eyebrow"), F("heading"), F("questions", "repeater")],
};
export function MarketplaceDentalFaqBlock({ block }) { const d = { ...MarketplaceDentalFaqSchema.defaults, ...block }; const qs = Array.isArray(d.questions) ? d.questions : MarketplaceDentalFaqSchema.defaults.questions; return <section className="px-6 py-24 lg:px-8" style={{ background: DENTAL.paper, color: DENTAL.ink }}><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl" /></div><div className="divide-y border-y" style={{ borderColor: DENTAL.line }}>{qs.slice(0, 8).map((q, i) => <article key={i} className="py-7"><div className="grid grid-cols-[1fr_auto] gap-6"><Text value={q.q || q.question} fieldPath={`questions.${i}.q`} cosmicType="h3" className="block text-xl font-black" /><span className="text-xl" style={{ color: DENTAL.blue }}>+</span></div><Text value={q.a || q.answer} fieldPath={`questions.${i}.a`} area className="mt-3 block max-w-3xl text-sm leading-7" style={{ color: DENTAL.muted }} /></article>)}</div></div></section>; }

export const MarketplaceDentalContactSchema = {
    type: "marketplace_dental_contact", title: "Brightline Booking Panel", category: "Marketplace",
    defaults: { eyebrow: "BOOK AN APPOINTMENT", heading: "Ready for a dental visit that feels easier?", text: "Request an appointment and our team will help you find the right time and type of visit.", phone: "(02) 5550 0226", email: "hello@brightlinedental.example", address: "Suite 4 · 86 Harbour Road · Sydney NSW", hours: "Mon–Fri 8am–6pm · Sat 8am–1pm", button_label: "Request Appointment", button_url: "mailto:hello@brightlinedental.example", image_url: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1400&q=88" },
    fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("phone"), F("email"), F("address"), F("hours"), F("button_label"), F("button_url"), F("image_url", "image")],
};
export function MarketplaceDentalContactBlock({ block }) { const d = { ...MarketplaceDentalContactSchema.defaults, ...block }; return <section className="px-6 py-24 lg:px-8" style={{ background: DENTAL.white, color: DENTAL.ink }}><div className="mx-auto grid max-w-[1380px] overflow-hidden rounded-[34px] lg:grid-cols-[.95fr_1.05fr]" style={{ background: DENTAL.navy }}><div className="p-8 text-white sm:p-12 lg:p-14"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: "#8fd2df" }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl" /><Text value={d.text} fieldPath="text" area className="mt-6 block text-base leading-8 text-white/65" /><div className="mt-9 grid gap-3 border-t border-white/10 pt-7 text-sm"><Text value={d.phone} fieldPath="phone" className="font-bold" /><Text value={d.email} fieldPath="email" className="font-bold" /><Text value={d.address} fieldPath="address" className="text-white/55" /><Text value={d.hours} fieldPath="hours" className="text-white/55" /></div><Button label={d.button_label} url={d.button_url} fieldPath="button_label" className="mt-9 inline-flex min-h-12 items-center rounded-full px-7 text-sm font-black" style={{ background: "#8fd2df", color: DENTAL.navy }} /></div><Image src={d.image_url} fieldPath="image_url" className="min-h-[520px] w-full" /></div></section>; }

export const MarketplaceDentalCtaSchema = { type: "marketplace_dental_cta", title: "Brightline Appointment CTA", category: "Marketplace", defaults: { eyebrow: "NEW PATIENTS WELCOME", heading: "A healthier smile can start with one easy appointment.", text: "Book your first visit or talk to our team about the right next step.", button_label: "Book an Appointment", button_url: "/contact" }, fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("button_label"), F("button_url")] };
export function MarketplaceDentalCtaBlock({ block }) { const d = { ...MarketplaceDentalCtaSchema.defaults, ...block }; return <section className="px-6 py-16 lg:px-8" style={{ background: DENTAL.paper }}><div className="mx-auto grid max-w-[1380px] gap-8 rounded-[34px] px-8 py-12 sm:px-12 lg:grid-cols-[1fr_auto] lg:items-end lg:px-16" style={{ background: DENTAL.mint, color: DENTAL.ink }}><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-4 block max-w-4xl text-4xl font-black leading-[1.02] tracking-[-.05em] sm:text-5xl" /><Text value={d.text} fieldPath="text" area className="mt-4 block text-base" style={{ color: DENTAL.muted }} /></div><Button label={d.button_label} url={d.button_url} fieldPath="button_label" className="inline-flex min-h-12 items-center rounded-full px-7 text-sm font-black text-white" style={{ background: DENTAL.navy }} /></div></section>; }

export const MarketplaceDentalPageHeroSchema = { type: "marketplace_dental_page_hero", title: "Brightline Page Hero", category: "Marketplace", defaults: { eyebrow: "BRIGHTLINE DENTAL", heading: "Dental care designed around people.", text: "Clear information, gentle care, and treatment tailored to what you need." }, fields: [F("eyebrow"), F("heading"), F("text", "textarea")] };
export function MarketplaceDentalPageHeroBlock({ block }) { const d = { ...MarketplaceDentalPageHeroSchema.defaults, ...block }; return <section className="overflow-hidden px-6 py-20 lg:px-8 lg:py-28" style={{ background: DENTAL.mist, color: DENTAL.ink }}><div className="relative mx-auto max-w-[1380px]"><div className="absolute right-0 top-[-100px] h-72 w-72 rounded-full blur-3xl" style={{ background: DENTAL.mint }} /><Text value={d.eyebrow} fieldPath="eyebrow" className="relative text-[10px] font-black uppercase tracking-[.22em]" style={{ color: DENTAL.blue }} /><Text value={d.heading} fieldPath="heading" cosmicType="h1" className="relative mt-5 block max-w-5xl text-[clamp(3.5rem,7vw,7rem)] font-black leading-[.9] tracking-[-.06em]" /><Text value={d.text} fieldPath="text" area className="relative mt-7 block max-w-2xl text-base leading-8 sm:text-lg" style={{ color: DENTAL.muted }} /></div></section>; }

// Stonebridge — architectural, high-contrast, construction-specific visual language.
const stoneCapabilities = [
    { number: "01", title: "Commercial Construction", text: "Structured delivery for workplaces, retail, industrial, and mixed-use environments." },
    { number: "02", title: "Residential Construction", text: "Considered new builds and renovations where detail, coordination, and finish matter." },
    { number: "03", title: "Fit-outs", text: "Fast-moving commercial fit-outs and refurbishments with strong site coordination." },
    { number: "04", title: "Project Management", text: "Planning, procurement, programme control, communication, and accountable delivery." },
];

export const MarketplaceStoneHeroSchema = {
    type: "marketplace_stone_hero", title: "Stonebridge Architectural Hero", category: "Marketplace",
    defaults: { eyebrow: "BUILT WITH INTENT · DELIVERED WITH DISCIPLINE", heading: "We build places", accent_heading: "made to perform.", text: "Commercial, residential, and fit-out projects delivered with disciplined planning, clear communication, and uncompromising attention to detail.", primary_label: "Start a Project", primary_url: "/contact", secondary_label: "View Projects", secondary_url: "/projects", image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1900&q=88", badge: "EST. 2008 · SYDNEY" },
    fields: [F("eyebrow"), F("heading"), F("accent_heading"), F("text", "textarea"), F("primary_label"), F("primary_url"), F("secondary_label"), F("secondary_url"), F("image_url", "image"), F("badge")],
};
export function MarketplaceStoneHeroBlock({ block }) { const d = { ...MarketplaceStoneHeroSchema.defaults, ...block }; return <section className="px-4 py-4 sm:px-6 lg:px-8" style={{ background: STONE.black }}><div className="relative mx-auto min-h-[720px] max-w-[1540px] overflow-hidden border" style={{ borderColor: "#383b3d" }}><Image src={d.image_url} fieldPath="image_url" background className="absolute inset-0 h-full w-full" /><div className="absolute inset-0" style={{ background: "linear-gradient(90deg,rgba(15,17,18,.98) 0%,rgba(15,17,18,.92) 43%,rgba(15,17,18,.44) 70%,rgba(15,17,18,.08) 100%)" }} /><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.14) 1px,transparent 1px)", backgroundSize: "80px 80px" }} /><div className="relative z-10 flex min-h-[720px] items-center px-7 py-20 sm:px-12 lg:px-20 xl:px-24"><div className="max-w-[880px] text-white"><div className="flex items-center gap-4"><span className="h-3 w-3" style={{ background: STONE.orange }} /><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em] text-white/60" /></div><Text value={d.heading} fieldPath="heading" cosmicType="h1" className="mt-7 block text-[clamp(4rem,8vw,8.3rem)] font-black uppercase leading-[.8] tracking-[-.07em]" /><Text value={d.accent_heading} fieldPath="accent_heading" className="mt-3 block text-[clamp(3rem,6vw,6.4rem)] font-black uppercase leading-[.84] tracking-[-.065em]" style={{ color: STONE.orange2 }} /><Text value={d.text} fieldPath="text" area className="mt-8 block max-w-2xl text-base leading-8 text-white/65 sm:text-lg" /><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button label={d.primary_label} url={d.primary_url} fieldPath="primary_label" className="inline-flex min-h-12 items-center justify-center px-7 text-sm font-black uppercase tracking-[.08em] text-white" style={{ background: STONE.orange }} /><Button label={d.secondary_label} url={d.secondary_url} fieldPath="secondary_label" className="inline-flex min-h-12 items-center justify-center border px-7 text-sm font-black uppercase tracking-[.08em] text-white" style={{ borderColor: "rgba(255,255,255,.35)" }} /></div></div></div><div className="absolute bottom-0 right-0 z-20 border-l border-t px-7 py-5 text-[10px] font-black uppercase tracking-[.2em] text-white/70" style={{ borderColor: "rgba(255,255,255,.2)", background: "rgba(15,17,18,.8)" }}><Text value={d.badge} fieldPath="badge" /></div></div></section>; }

export const MarketplaceStoneCapabilitiesSchema = { type: "marketplace_stone_capabilities", title: "Stonebridge Capabilities", category: "Marketplace", defaults: { eyebrow: "CAPABILITIES", heading: "Built for complexity. Managed for certainty.", text: "We bring planning, people, procurement, and site delivery together under one accountable team.", items: stoneCapabilities }, fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("items", "repeater")] };
export function MarketplaceStoneCapabilitiesBlock({ block }) { const d = { ...MarketplaceStoneCapabilitiesSchema.defaults, ...block }; const items = Array.isArray(d.items) && d.items.length ? d.items : stoneCapabilities; return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{ background: STONE.paper, color: STONE.ink }}><div className="mx-auto max-w-[1420px]"><div className="grid gap-8 lg:grid-cols-[1.15fr_.7fr] lg:items-end"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-5xl text-5xl font-black uppercase leading-[.9] tracking-[-.055em] sm:text-6xl lg:text-7xl" /></div><Text value={d.text} fieldPath="text" area className="block text-base leading-8" style={{ color: STONE.muted }} /></div><div className="mt-14 grid border-l border-t md:grid-cols-2 xl:grid-cols-4" style={{ borderColor: STONE.line }}>{items.slice(0, 6).map((it, i) => <article key={i} className="min-h-[340px] border-b border-r p-7" style={{ borderColor: STONE.line }}><Text value={it.number || String(i + 1).padStart(2, "0")} fieldPath={`items.${i}.number`} className="text-xs font-black tracking-[.18em]" style={{ color: STONE.orange }} /><Text value={it.title} fieldPath={`items.${i}.title`} cosmicType="h3" className="mt-24 block text-2xl font-black uppercase leading-[1.05] tracking-[-.03em]" /><Text value={it.text} fieldPath={`items.${i}.text`} area className="mt-4 block text-sm leading-7" style={{ color: STONE.muted }} /></article>)}</div></div></section>; }

export const MarketplaceStoneManifestoSchema = { type: "marketplace_stone_manifesto", title: "Stonebridge Manifesto", category: "Marketplace", defaults: { eyebrow: "HOW WE WORK", heading: "Good construction is decided long before concrete is poured.", text: "We reduce uncertainty early: interrogating scope, coordinating teams, planning procurement, and communicating clearly so the project stays controlled from pre-construction through handover.", image_url: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1600&q=88", quote: "Plan hard. Communicate early. Build once." }, fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("image_url", "image"), F("quote")] };
export function MarketplaceStoneManifestoBlock({ block }) { const d = { ...MarketplaceStoneManifestoSchema.defaults, ...block }; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.black, color: "white" }}><div className="mx-auto grid max-w-[1420px] gap-0 border lg:grid-cols-2" style={{ borderColor: "#363a3c" }}><Image src={d.image_url} fieldPath="image_url" className="min-h-[560px] w-full" /><div className="flex flex-col justify-between p-8 sm:p-12 lg:p-14"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange2 }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-6 block text-4xl font-black uppercase leading-[.92] tracking-[-.05em] sm:text-5xl lg:text-6xl" /><Text value={d.text} fieldPath="text" area className="mt-7 block text-base leading-8 text-white/55" /></div><div className="mt-12 border-l-4 pl-6" style={{ borderColor: STONE.orange }}><Text value={d.quote} fieldPath="quote" className="block text-2xl font-black uppercase leading-tight tracking-[-.03em]" /></div></div></div></section>; }

export const MarketplaceStoneProjectsSchema = { type: "marketplace_stone_projects", title: "Stonebridge Project Grid", category: "Marketplace", defaults: { eyebrow: "SELECTED WORK", heading: "Projects that prove the process.", projects: [{ title: "Harbour Workplace", category: "Commercial · Sydney", image_url: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=86" }, { title: "North Shore Residence", category: "Residential · Mosman", image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=86" }, { title: "Foundry Fit-out", category: "Fit-out · Alexandria", image_url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=86" }, { title: "Civic Upgrade", category: "Public · Inner West", image_url: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1200&q=86" }] }, fields: [F("eyebrow"), F("heading"), F("projects", "repeater")] };
export function MarketplaceStoneProjectsBlock({ block }) { const d = { ...MarketplaceStoneProjectsSchema.defaults, ...block }; const projects = Array.isArray(d.projects) && d.projects.length ? d.projects : MarketplaceStoneProjectsSchema.defaults.projects; return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{ background: STONE.sand, color: STONE.ink }}><div className="mx-auto max-w-[1480px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-5xl text-5xl font-black uppercase leading-[.9] tracking-[-.055em] sm:text-6xl lg:text-7xl" /><div className="mt-14 grid gap-4 md:grid-cols-12">{projects.slice(0, 6).map((p, i) => <article key={i} className={`${i % 4 === 0 || i % 4 === 3 ? "md:col-span-7" : "md:col-span-5"}`}><div className="overflow-hidden"><Image src={p.image_url} fieldPath={`projects.${i}.image_url`} className={`${i % 4 === 0 || i % 4 === 3 ? "aspect-[16/10]" : "aspect-[5/6]"} w-full`} /></div><div className="grid grid-cols-[1fr_auto] gap-4 border-x border-b p-5" style={{ borderColor: STONE.line }}><Text value={p.title} fieldPath={`projects.${i}.title`} cosmicType="h3" className="block text-xl font-black uppercase tracking-[-.025em]" /><Text value={p.category} fieldPath={`projects.${i}.category`} className="text-[10px] font-black uppercase tracking-[.12em]" style={{ color: STONE.muted }} /></div></article>)}</div></div></section>; }

export const MarketplaceStoneProcessSchema = { type: "marketplace_stone_process", title: "Stonebridge Delivery Process", category: "Marketplace", defaults: { eyebrow: "DELIVERY METHOD", heading: "A controlled path from brief to handover.", steps: [{ number: "01", title: "Define", text: "Brief, constraints, risk, programme, and commercial priorities." }, { number: "02", title: "Coordinate", text: "Design resolution, consultants, procurement, and buildability." }, { number: "03", title: "Construct", text: "Disciplined site management, quality control, and communication." }, { number: "04", title: "Handover", text: "Commissioning, documentation, defects management, and support." }] }, fields: [F("eyebrow"), F("heading"), F("steps", "repeater")] };
export function MarketplaceStoneProcessBlock({ block }) { const d = { ...MarketplaceStoneProcessSchema.defaults, ...block }; const steps = Array.isArray(d.steps) ? d.steps : MarketplaceStoneProcessSchema.defaults.steps; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.charcoal, color: "white" }}><div className="mx-auto max-w-[1420px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange2 }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-5xl text-5xl font-black uppercase leading-[.9] tracking-[-.055em] sm:text-6xl lg:text-7xl" /><div className="mt-14 border-t" style={{ borderColor: "rgba(255,255,255,.18)" }}>{steps.slice(0, 6).map((s, i) => <article key={i} className="grid gap-5 border-b py-8 md:grid-cols-[100px_.7fr_1fr] md:items-start" style={{ borderColor: "rgba(255,255,255,.18)" }}><Text value={s.number || String(i + 1).padStart(2, "0")} fieldPath={`steps.${i}.number`} className="text-sm font-black tracking-[.18em]" style={{ color: STONE.orange2 }} /><Text value={s.title} fieldPath={`steps.${i}.title`} cosmicType="h3" className="block text-2xl font-black uppercase tracking-[-.03em]" /><Text value={s.text} fieldPath={`steps.${i}.text`} area className="block text-sm leading-7 text-white/55" /></article>)}</div></div></section>; }

export const MarketplaceStoneMetricsSchema = { type: "marketplace_stone_metrics", title: "Stonebridge Project Metrics", category: "Marketplace", defaults: { eyebrow: "PROOF IN DELIVERY", heading: "Performance you can measure.", stats: [{ value: "18+", label: "Years building" }, { value: "$240M", label: "Projects delivered" }, { value: "92%", label: "Repeat & referral work" }, { value: "0", label: "Compromise on safety" }] }, fields: [F("eyebrow"), F("heading"), F("stats", "repeater")] };
export function MarketplaceStoneMetricsBlock({ block }) { const d = { ...MarketplaceStoneMetricsSchema.defaults, ...block }; const stats = Array.isArray(d.stats) ? d.stats : MarketplaceStoneMetricsSchema.defaults.stats; return <section className="px-6 py-20 lg:px-8" style={{ background: STONE.orange, color: "white" }}><div className="mx-auto max-w-[1420px]"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em] text-white/65" /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black uppercase leading-[.92] tracking-[-.05em] sm:text-5xl" /></div><div className="grid grid-cols-2 gap-px bg-white/25">{stats.slice(0, 4).map((s, i) => <div key={i} className="p-6 sm:p-8" style={{ background: STONE.orange }}><Text value={s.value} fieldPath={`stats.${i}.value`} className="block text-4xl font-black tracking-[-.05em] sm:text-5xl" /><Text value={s.label} fieldPath={`stats.${i}.label`} className="mt-2 block text-[10px] font-black uppercase tracking-[.12em] text-white/65" /></div>)}</div></div></div></section>; }

export const MarketplaceStoneCaseStudySchema = { type: "marketplace_stone_case_study", title: "Stonebridge Case Study", category: "Marketplace", defaults: { eyebrow: "FEATURED PROJECT", heading: "Harbour Workplace — built around a live business.", text: "A staged commercial refurbishment delivered in an occupied building, requiring tight logistics, after-hours works, stakeholder coordination, and zero interruption to critical operations.", image_url: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=88", facts: [{ label: "TYPE", value: "Commercial fit-out" }, { label: "PROGRAMME", value: "18 weeks" }, { label: "AREA", value: "3,200 sqm" }, { label: "DELIVERY", value: "Staged / live environment" }] }, fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("image_url", "image"), F("facts", "repeater")] };
export function MarketplaceStoneCaseStudyBlock({ block }) { const d = { ...MarketplaceStoneCaseStudySchema.defaults, ...block }; const facts = Array.isArray(d.facts) ? d.facts : MarketplaceStoneCaseStudySchema.defaults.facts; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.paper, color: STONE.ink }}><div className="mx-auto max-w-[1420px]"><div className="grid gap-10 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black uppercase leading-[.92] tracking-[-.05em] sm:text-5xl lg:text-6xl" /><Text value={d.text} fieldPath="text" area className="mt-6 block text-base leading-8" style={{ color: STONE.muted }} /></div><Image src={d.image_url} fieldPath="image_url" className="aspect-[16/10] w-full" /></div><div className="mt-8 grid border-l border-t sm:grid-cols-2 lg:grid-cols-4" style={{ borderColor: STONE.line }}>{facts.slice(0, 6).map((f, i) => <div key={i} className="border-b border-r p-6" style={{ borderColor: STONE.line }}><Text value={f.label} fieldPath={`facts.${i}.label`} className="block text-[9px] font-black uppercase tracking-[.18em]" style={{ color: STONE.orange }} /><Text value={f.value} fieldPath={`facts.${i}.value`} className="mt-3 block text-lg font-black uppercase" /></div>)}</div></div></section>; }

export const MarketplaceStoneTeamSchema = { type: "marketplace_stone_team", title: "Stonebridge Team", category: "Marketplace", defaults: { eyebrow: "PEOPLE BEHIND THE WORK", heading: "Experienced enough to anticipate. Close enough to stay accountable.", members: [{ name: "Mark Stone", role: "Managing Director", image_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=900&q=86" }, { name: "Olivia Reed", role: "Construction Manager", image_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=900&q=86" }, { name: "Daniel Brooks", role: "Project Director", image_url: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=900&q=86" }] }, fields: [F("eyebrow"), F("heading"), F("members", "repeater")] };
export function MarketplaceStoneTeamBlock({ block }) { const d = { ...MarketplaceStoneTeamSchema.defaults, ...block }; const members = Array.isArray(d.members) && d.members.length ? d.members : MarketplaceStoneTeamSchema.defaults.members; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.sand, color: STONE.ink }}><div className="mx-auto max-w-[1420px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-5xl text-5xl font-black uppercase leading-[.9] tracking-[-.055em] sm:text-6xl" /><div className="mt-14 grid gap-4 md:grid-cols-3">{members.slice(0, 4).map((m, i) => <article key={i}><Image src={m.image_url} fieldPath={`members.${i}.image_url`} className="aspect-[4/5] w-full grayscale" /><div className="border-x border-b p-5" style={{ borderColor: STONE.line }}><Text value={m.name} fieldPath={`members.${i}.name`} cosmicType="h3" className="block text-xl font-black uppercase" /><Text value={m.role} fieldPath={`members.${i}.role`} className="mt-1 block text-[10px] font-black uppercase tracking-[.12em]" style={{ color: STONE.orange }} /></div></article>)}</div></div></section>; }

export const MarketplaceStoneSafetySchema = { type: "marketplace_stone_safety", title: "Stonebridge Safety & Quality", category: "Marketplace", defaults: { eyebrow: "SAFETY · QUALITY · CONTROL", heading: "Systems that protect people, programme, and finish.", text: "Safety and quality are built into planning, procurement, site routines, verification, and handover — not added at the end.", items: [{ title: "Site safety", text: "Project-specific controls, inductions, supervision, and transparent reporting." }, { title: "Quality assurance", text: "Inspection points, samples, documentation, and disciplined close-out." }, { title: "Environmental care", text: "Waste, noise, dust, logistics, and neighbour impacts actively managed." }, { title: "Accountability", text: "Clear ownership of issues and rapid escalation before they become delays." }] }, fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("items", "repeater")] };
export function MarketplaceStoneSafetyBlock({ block }) { const d = { ...MarketplaceStoneSafetySchema.defaults, ...block }; const items = Array.isArray(d.items) ? d.items : MarketplaceStoneSafetySchema.defaults.items; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.black, color: "white" }}><div className="mx-auto max-w-[1420px]"><div className="grid gap-8 lg:grid-cols-[1fr_.7fr]"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange2 }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-5xl text-5xl font-black uppercase leading-[.9] tracking-[-.055em] sm:text-6xl" /></div><Text value={d.text} fieldPath="text" area className="self-end text-base leading-8 text-white/55" /></div><div className="mt-14 grid border-l border-t md:grid-cols-2" style={{ borderColor: "rgba(255,255,255,.16)" }}>{items.slice(0, 6).map((it, i) => <article key={i} className="min-h-[260px] border-b border-r p-7" style={{ borderColor: "rgba(255,255,255,.16)" }}><span className="text-3xl font-black" style={{ color: STONE.orange }}>{String(i + 1).padStart(2, "0")}</span><Text value={it.title} fieldPath={`items.${i}.title`} cosmicType="h3" className="mt-12 block text-2xl font-black uppercase" /><Text value={it.text} fieldPath={`items.${i}.text`} area className="mt-3 block text-sm leading-7 text-white/50" /></article>)}</div></div></section>; }

export const MarketplaceStoneTestimonialSchema = { type: "marketplace_stone_testimonial", title: "Stonebridge Client Proof", category: "Marketplace", defaults: { eyebrow: "CLIENT PERSPECTIVE", quote: "Stonebridge gave us certainty. Issues were raised early, decisions were documented, and the site team stayed ahead of the programme from day one.", name: "James Caldwell", role: "Development Director · Arcstone Property", stat: "3", stat_label: "repeat projects delivered together" }, fields: [F("eyebrow"), F("quote", "textarea"), F("name"), F("role"), F("stat"), F("stat_label")] };
export function MarketplaceStoneTestimonialBlock({ block }) { const d = { ...MarketplaceStoneTestimonialSchema.defaults, ...block }; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.paper, color: STONE.ink }}><div className="mx-auto grid max-w-[1320px] gap-5 lg:grid-cols-[1.2fr_.55fr]"><figure className="border p-8 sm:p-12" style={{ borderColor: STONE.line }}><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange }} /><div className="mt-8 text-5xl font-black" style={{ color: STONE.orange }}>“</div><Text value={d.quote} fieldPath="quote" area className="mt-4 block text-3xl font-black uppercase leading-[1.08] tracking-[-.04em] sm:text-4xl" /><figcaption className="mt-10 border-t pt-6" style={{ borderColor: STONE.line }}><Text value={d.name} fieldPath="name" className="block text-sm font-black uppercase" /><Text value={d.role} fieldPath="role" className="mt-1 block text-xs" style={{ color: STONE.muted }} /></figcaption></figure><div className="flex flex-col justify-end p-8 text-white sm:p-10" style={{ background: STONE.orange }}><Text value={d.stat} fieldPath="stat" className="block text-7xl font-black tracking-[-.07em]" /><Text value={d.stat_label} fieldPath="stat_label" className="mt-3 block max-w-[220px] text-xs font-black uppercase leading-5 tracking-[.12em] text-white/70" /></div></div></section>; }

export const MarketplaceStoneFaqSchema = { type: "marketplace_stone_faq", title: "Stonebridge Project FAQ", category: "Marketplace", defaults: { eyebrow: "BEFORE WE START", heading: "Straight answers before the first site meeting.", questions: [{ q: "When should we involve a builder?", a: "Early involvement usually improves buildability, programme certainty, procurement planning, and cost visibility before documentation is locked." }, { q: "Can you work with our architect and consultants?", a: "Yes. We regularly coordinate with client-appointed design teams, engineers, certifiers, and specialist consultants." }, { q: "How are variations managed?", a: "Scope changes are documented, priced, and communicated before work proceeds wherever possible, so commercial decisions remain visible." }, { q: "How do you manage programme risk?", a: "We track design inputs, procurement lead times, approvals, site constraints, and critical-path activities through structured project controls." }] }, fields: [F("eyebrow"), F("heading"), F("questions", "repeater")] };
export function MarketplaceStoneFaqBlock({ block }) { const d = { ...MarketplaceStoneFaqSchema.defaults, ...block }; const qs = Array.isArray(d.questions) ? d.questions : MarketplaceStoneFaqSchema.defaults.questions; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.paper, color: STONE.ink }}><div className="mx-auto grid max-w-[1320px] gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black uppercase leading-[.92] tracking-[-.05em] sm:text-5xl" /></div><div className="border-t" style={{ borderColor: STONE.line }}>{qs.slice(0, 8).map((q, i) => <article key={i} className="grid gap-4 border-b py-7 md:grid-cols-[56px_.7fr_1fr]" style={{ borderColor: STONE.line }}><Text value={String(i + 1).padStart(2, "0")} className="text-xs font-black" style={{ color: STONE.orange }} /><Text value={q.q || q.question} fieldPath={`questions.${i}.q`} cosmicType="h3" className="block text-xl font-black uppercase leading-tight" /><Text value={q.a || q.answer} fieldPath={`questions.${i}.a`} area className="block text-sm leading-7" style={{ color: STONE.muted }} /></article>)}</div></div></section>; }

export const MarketplaceStoneContactSchema = { type: "marketplace_stone_contact", title: "Stonebridge Project Enquiry", category: "Marketplace", defaults: { eyebrow: "START A PROJECT", heading: "Bring us the brief. We’ll help make the path clear.", text: "Tell us what you are planning, where the project is, and the timing you are working toward. Our team will come back with the right next step.", phone: "(02) 5550 0418", email: "projects@stonebridge.example", address: "14 Foundry Street · Alexandria NSW", button_label: "Request a Project Call", button_url: "mailto:projects@stonebridge.example", image_url: "https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1500&q=88" }, fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("phone"), F("email"), F("address"), F("button_label"), F("button_url"), F("image_url", "image")] };
export function MarketplaceStoneContactBlock({ block }) { const d = { ...MarketplaceStoneContactSchema.defaults, ...block }; return <section className="px-6 py-24 lg:px-8" style={{ background: STONE.sand, color: STONE.ink }}><div className="mx-auto grid max-w-[1420px] border lg:grid-cols-[.9fr_1.1fr]" style={{ borderColor: STONE.line, background: STONE.paper }}><div className="p-8 sm:p-12 lg:p-14"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black uppercase leading-[.92] tracking-[-.05em] sm:text-5xl lg:text-6xl" /><Text value={d.text} fieldPath="text" area className="mt-6 block text-base leading-8" style={{ color: STONE.muted }} /><div className="mt-9 grid gap-2 border-t pt-6 text-sm" style={{ borderColor: STONE.line }}><Text value={d.phone} fieldPath="phone" className="font-black" /><Text value={d.email} fieldPath="email" className="font-black" /><Text value={d.address} fieldPath="address" className="text-sm" style={{ color: STONE.muted }} /></div><Button label={d.button_label} url={d.button_url} fieldPath="button_label" className="mt-9 inline-flex min-h-12 items-center px-7 text-sm font-black uppercase tracking-[.08em] text-white" style={{ background: STONE.orange }} /></div><Image src={d.image_url} fieldPath="image_url" className="min-h-[560px] w-full" /></div></section>; }

export const MarketplaceStoneCtaSchema = { type: "marketplace_stone_cta", title: "Stonebridge Project CTA", category: "Marketplace", defaults: { eyebrow: "READY TO BUILD?", heading: "Start with a better plan.", text: "Bring us your project goals, constraints, and timing. We’ll help define the next step.", button_label: "Request a Quote", button_url: "/contact" }, fields: [F("eyebrow"), F("heading"), F("text", "textarea"), F("button_label"), F("button_url")] };
export function MarketplaceStoneCtaBlock({ block }) { const d = { ...MarketplaceStoneCtaSchema.defaults, ...block }; return <section className="px-6 py-16 lg:px-8" style={{ background: STONE.black }}><div className="mx-auto grid max-w-[1420px] gap-8 border px-8 py-12 sm:px-12 lg:grid-cols-[1fr_auto] lg:items-end lg:px-16" style={{ borderColor: "#3b3e40", color: "white" }}><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em]" style={{ color: STONE.orange2 }} /><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-4 block max-w-5xl text-5xl font-black uppercase leading-[.88] tracking-[-.055em] sm:text-6xl" /><Text value={d.text} fieldPath="text" area className="mt-5 block text-base text-white/55" /></div><Button label={d.button_label} url={d.button_url} fieldPath="button_label" className="inline-flex min-h-12 items-center px-7 text-sm font-black uppercase tracking-[.08em] text-white" style={{ background: STONE.orange }} /></div></section>; }

export const MarketplaceStonePageHeroSchema = { type: "marketplace_stone_page_hero", title: "Stonebridge Page Hero", category: "Marketplace", defaults: { eyebrow: "STONEBRIDGE CONSTRUCTION", heading: "Built around the work that matters.", text: "Disciplined planning, experienced teams, and accountable delivery from brief to handover." }, fields: [F("eyebrow"), F("heading"), F("text", "textarea")] };
export function MarketplaceStonePageHeroBlock({ block }) { const d = { ...MarketplaceStonePageHeroSchema.defaults, ...block }; return <section className="relative overflow-hidden px-6 py-20 lg:px-8 lg:py-28" style={{ background: STONE.charcoal, color: "white" }}><div className="absolute inset-0 opacity-15" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.18) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.18) 1px,transparent 1px)", backgroundSize: "72px 72px" }} /><div className="relative mx-auto max-w-[1420px]"><div className="flex items-center gap-4"><span className="h-3 w-3" style={{ background: STONE.orange }} /><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.25em] text-white/55" /></div><Text value={d.heading} fieldPath="heading" cosmicType="h1" className="mt-7 block max-w-6xl text-[clamp(3.8rem,8vw,8rem)] font-black uppercase leading-[.82] tracking-[-.07em]" /><Text value={d.text} fieldPath="text" area className="mt-8 block max-w-2xl text-base leading-8 text-white/55 sm:text-lg" /></div></section>; }
