import { EditableButton } from "../Shared/EditableButton";
import { EditableImage } from "../Shared/EditableImage";
import { EditableText } from "../Shared/EditableText";

const F=(key,type='text',label=null)=>({key,type,label:label||key.replaceAll('_',' ')});
const Text=({value,className='',fieldPath,cosmicType,area=false,style})=><EditableText value={value} className={className} fieldPath={fieldPath} cosmicType={cosmicType} isTextArea={area} style={style}/>;
const Button=({label,url='#',className='',fieldPath,style})=><EditableButton label={label} url={url} className={className} fieldPath={fieldPath} style={style}/>;
const Image=({src,className='',fieldPath,style})=><EditableImage src={src} className={className} fieldPath={fieldPath} style={style}/>;

const LAW={burgundy:'#6f1d2b',burgundy2:'#8c2d3f',ink:'#171819',paper:'#f7f4ee',ivory:'#fffdf8',sand:'#e9e0d2',line:'#d8cfc1',muted:'#6d6861',gold:'#b28a53',white:'#fff'};
const practice=[
 {number:'01',title:'Business Law',text:'Practical advice for contracts, structures, transactions, and day-to-day commercial decisions.'},
 {number:'02',title:'Property Law',text:'Clear support for acquisitions, sales, leasing, due diligence, and property agreements.'},
 {number:'03',title:'Estate Planning',text:'Thoughtful wills, powers of attorney, succession planning, and estate administration.'},
 {number:'04',title:'Dispute Resolution',text:'Strategic advice focused on proportionate, commercially sensible paths through disputes.'},
];
const steps=[
 {number:'01',title:'Listen',text:'We start with the facts, priorities, timing, and what a useful outcome looks like.'},
 {number:'02',title:'Clarify',text:'We explain the legal position, risks, options, and likely next steps in plain language.'},
 {number:'03',title:'Advise',text:'You receive a practical recommendation shaped around your circumstances and objectives.'},
 {number:'04',title:'Act',text:'We move the matter forward with clear communication and disciplined follow-through.'},
];

export const MarketplaceNorthfieldHeroSchema={type:'marketplace_northfield_hero',title:'Northfield Editorial Legal Hero',category:'Marketplace',defaults:{eyebrow:'NORTHFIELD LEGAL · PRACTICAL COUNSEL',heading:'Clear advice for',accent_heading:'important decisions.',text:'Calm, commercially aware legal guidance for businesses, property matters, families, and estates.',primary_label:'Request a Consultation',primary_url:'/contact',secondary_label:'Explore Practice Areas',secondary_url:'/services',image_url:'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1800&q=88',trust_label:'Confidential consultations',trust_text:'Clear scope · Practical next steps'},fields:[F('eyebrow'),F('heading'),F('accent_heading'),F('text','textarea'),F('primary_label'),F('primary_url'),F('secondary_label'),F('secondary_url'),F('image_url','image'),F('trust_label'),F('trust_text')]};
export function MarketplaceNorthfieldHeroBlock({block}){const d={...MarketplaceNorthfieldHeroSchema.defaults,...block};return <section className="px-4 py-4 sm:px-6 lg:px-8" style={{background:LAW.paper,color:LAW.ink}}><div className="relative mx-auto grid min-h-[690px] max-w-[1540px] overflow-hidden lg:grid-cols-[1.05fr_.95fr]" style={{background:LAW.ivory,border:`1px solid ${LAW.line}`}}><div className="flex items-center px-7 py-16 sm:px-12 lg:px-16 xl:px-20"><div className="max-w-[760px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:LAW.burgundy}}/><Text value={d.heading} fieldPath="heading" cosmicType="h1" className="mt-7 block text-[clamp(3.6rem,6.8vw,7.4rem)] font-black leading-[.86] tracking-[-.065em]"/><Text value={d.accent_heading} fieldPath="accent_heading" className="mt-2 block font-serif text-[clamp(3rem,5.4vw,5.8rem)] italic leading-[.94] tracking-[-.045em]" style={{color:LAW.burgundy}}/><Text value={d.text} fieldPath="text" area className="mt-8 block max-w-2xl text-base leading-8 sm:text-lg" style={{color:LAW.muted}}/><div className="mt-9 flex flex-wrap gap-3"><Button label={d.primary_label} url={d.primary_url} fieldPath="primary_label" className="inline-flex min-h-12 items-center justify-center px-7 text-sm font-black text-white" style={{background:LAW.burgundy}}/><Button label={d.secondary_label} url={d.secondary_url} fieldPath="secondary_label" className="inline-flex min-h-12 items-center justify-center border px-7 text-sm font-black" style={{borderColor:LAW.line}}/></div></div></div><div className="relative min-h-[460px] lg:min-h-0"><Image src={d.image_url} fieldPath="image_url" className="h-full w-full"/><div className="absolute inset-0" style={{background:'linear-gradient(180deg,transparent 55%,rgba(23,24,25,.55))'}}/><div className="absolute bottom-8 left-8 right-8 border bg-white/95 p-5 backdrop-blur" style={{borderColor:LAW.line}}><Text value={d.trust_label} fieldPath="trust_label" className="block text-[10px] font-black uppercase tracking-[.18em]" style={{color:LAW.burgundy}}/><Text value={d.trust_text} fieldPath="trust_text" className="mt-2 block text-sm font-bold"/></div></div></div></section>}

export const MarketplaceNorthfieldPracticeSchema={type:'marketplace_northfield_practice',title:'Northfield Practice Areas',category:'Marketplace',defaults:{eyebrow:'PRACTICE AREAS',heading:'Legal support that stays focused on the decision in front of you.',text:'Straightforward advice, careful preparation, and a clear path forward.',items:practice},fields:[F('eyebrow'),F('heading'),F('text','textarea'),F('items','repeater')]};
export function MarketplaceNorthfieldPracticeBlock({block}){const d={...MarketplaceNorthfieldPracticeSchema.defaults,...block};const items=Array.isArray(d.items)&&d.items.length?d.items:practice;return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{background:LAW.ivory,color:LAW.ink}}><div className="mx-auto max-w-[1400px]"><div className="grid gap-8 lg:grid-cols-[1.1fr_.7fr] lg:items-end"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:LAW.burgundy}}/><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-5xl text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl"/></div><Text value={d.text} fieldPath="text" area className="block text-base leading-8" style={{color:LAW.muted}}/></div><div className="mt-14 grid border-l border-t md:grid-cols-2 xl:grid-cols-4" style={{borderColor:LAW.line}}>{items.slice(0,6).map((it,i)=><article key={i} className="min-h-[340px] border-b border-r p-7" style={{borderColor:LAW.line,background:i%2?LAW.paper:LAW.ivory}}><Text value={it.number||String(i+1).padStart(2,'0')} fieldPath={`items.${i}.number`} className="text-xs font-black" style={{color:LAW.gold}}/><div className="mt-24"><Text value={it.title} fieldPath={`items.${i}.title`} cosmicType="h3" className="block text-2xl font-black tracking-[-.025em]"/><Text value={it.text} fieldPath={`items.${i}.text`} area className="mt-4 block text-sm leading-7" style={{color:LAW.muted}}/></div></article>)}</div></div></section>}

export const MarketplaceNorthfieldAuthoritySchema={type:'marketplace_northfield_authority',title:'Northfield Authority Story',category:'Marketplace',defaults:{eyebrow:'THE NORTHFIELD APPROACH',heading:'Measured advice. Clear communication. No unnecessary theatre.',text:'Good legal work starts by understanding what matters, then giving you a practical view of risk, options, and next steps.',quote:'Our role is to make complex matters easier to understand and easier to act on.',image_url:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1600&q=88'},fields:[F('eyebrow'),F('heading'),F('text','textarea'),F('quote'),F('image_url','image')]};
export function MarketplaceNorthfieldAuthorityBlock({block}){const d={...MarketplaceNorthfieldAuthoritySchema.defaults,...block};return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{background:LAW.paper,color:LAW.ink}}><div className="mx-auto grid max-w-[1400px] gap-14 lg:grid-cols-2 lg:items-center"><div className="min-h-[560px]"><Image src={d.image_url} fieldPath="image_url" className="h-full min-h-[560px] w-full"/></div><div className="lg:px-8"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:LAW.burgundy}}/><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl"/><Text value={d.text} fieldPath="text" area className="mt-7 block text-base leading-8" style={{color:LAW.muted}}/><div className="mt-9 border-l-2 pl-6" style={{borderColor:LAW.gold}}><Text value={d.quote} fieldPath="quote" className="block font-serif text-2xl italic leading-9" style={{color:LAW.burgundy}}/></div></div></div></section>}

export const MarketplaceNorthfieldProcessSchema={type:'marketplace_northfield_process',title:'Northfield Legal Process',category:'Marketplace',defaults:{eyebrow:'HOW WE WORK',heading:'A clear process from first conversation to next step.',items:steps},fields:[F('eyebrow'),F('heading'),F('items','repeater')]};
export function MarketplaceNorthfieldProcessBlock({block}){const d={...MarketplaceNorthfieldProcessSchema.defaults,...block};const items=Array.isArray(d.items)&&d.items.length?d.items:steps;return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{background:LAW.ink,color:LAW.white}}><div className="mx-auto max-w-[1400px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:'#d9b47d'}}/><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block max-w-5xl text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl"/><div className="mt-14 grid border-l border-t md:grid-cols-2 xl:grid-cols-4" style={{borderColor:'rgba(255,255,255,.16)'}}>{items.slice(0,6).map((it,i)=><article key={i} className="min-h-[300px] border-b border-r p-7" style={{borderColor:'rgba(255,255,255,.16)'}}><Text value={it.number||String(i+1).padStart(2,'0')} fieldPath={`items.${i}.number`} className="text-xs font-black" style={{color:'#d9b47d'}}/><Text value={it.title} fieldPath={`items.${i}.title`} cosmicType="h3" className="mt-16 block text-2xl font-black"/><Text value={it.text} fieldPath={`items.${i}.text`} area className="mt-4 block text-sm leading-7 text-white/55"/></article>)}</div></div></section>}

export const MarketplaceNorthfieldProofSchema={type:'marketplace_northfield_proof',title:'Northfield Credibility Proof',category:'Marketplace',defaults:{eyebrow:'CLIENT CONFIDENCE',heading:'Advice built around clarity, discretion, and practical outcomes.',quote:'Northfield made a complicated matter feel manageable from the first meeting.',name:'Client testimonial',role:'Commercial matter',stats:[{value:'Plain',label:'language first'},{value:'Clear',label:'scope & fees'},{value:'Direct',label:'lawyer access'}]},fields:[F('eyebrow'),F('heading'),F('quote'),F('name'),F('role'),F('stats','repeater')]};
export function MarketplaceNorthfieldProofBlock({block}){const d={...MarketplaceNorthfieldProofSchema.defaults,...block};const stats=Array.isArray(d.stats)&&d.stats.length?d.stats:MarketplaceNorthfieldProofSchema.defaults.stats;return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{background:LAW.burgundy,color:LAW.white}}><div className="mx-auto grid max-w-[1400px] gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em] text-white/65"/><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl"/><div className="mt-10 grid grid-cols-3 border-l border-t" style={{borderColor:'rgba(255,255,255,.22)'}}>{stats.slice(0,3).map((s,i)=><div key={i} className="border-b border-r p-5" style={{borderColor:'rgba(255,255,255,.22)'}}><Text value={s.value} fieldPath={`stats.${i}.value`} className="block text-xl font-black"/><Text value={s.label} fieldPath={`stats.${i}.label`} className="mt-2 block text-[10px] font-bold uppercase tracking-[.14em] text-white/55"/></div>)}</div></div><figure className="border p-8 sm:p-10" style={{borderColor:'rgba(255,255,255,.24)',background:'rgba(255,255,255,.06)'}}><Text value={d.quote} fieldPath="quote" className="block font-serif text-3xl italic leading-[1.35]"/><figcaption className="mt-8 border-t pt-6" style={{borderColor:'rgba(255,255,255,.2)'}}><Text value={d.name} fieldPath="name" className="font-black"/><Text value={d.role} fieldPath="role" className="mt-1 block text-xs text-white/55"/></figcaption></figure></div></section>}

export const MarketplaceNorthfieldFaqSchema={type:'marketplace_northfield_faq',title:'Northfield Legal FAQ',category:'Marketplace',defaults:{eyebrow:'COMMON QUESTIONS',heading:'Useful answers before we get started.',questions:[{q:'What happens in the first consultation?',a:'We discuss the matter, your priorities, immediate risks, and what the next useful step may be.'},{q:'Will I know the likely costs?',a:'We explain scope, billing approach, and known cost drivers as clearly as possible before substantial work begins.'},{q:'Is my enquiry confidential?',a:'We treat enquiries discreetly and explain any formal conflict or engagement requirements before acting.'}]},fields:[F('eyebrow'),F('heading'),F('questions','repeater')]};
export function MarketplaceNorthfieldFaqBlock({block}){const d={...MarketplaceNorthfieldFaqSchema.defaults,...block};const qs=Array.isArray(d.questions)&&d.questions.length?d.questions:MarketplaceNorthfieldFaqSchema.defaults.questions;return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{background:LAW.ivory,color:LAW.ink}}><div className="mx-auto grid max-w-[1400px] gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:LAW.burgundy}}/><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl"/></div><div className="border-t" style={{borderColor:LAW.line}}>{qs.slice(0,8).map((q,i)=><article key={i} className="grid gap-4 border-b py-7 sm:grid-cols-[50px_.8fr_1fr]" style={{borderColor:LAW.line}}><span className="text-xs font-black" style={{color:LAW.gold}}>{String(i+1).padStart(2,'0')}</span><Text value={q.q||q.question} fieldPath={`questions.${i}.q`} cosmicType="h3" className="text-lg font-black"/><Text value={q.a||q.answer} fieldPath={`questions.${i}.a`} area className="text-sm leading-7" style={{color:LAW.muted}}/></article>)}</div></div></section>}

export const MarketplaceNorthfieldContactSchema={type:'marketplace_northfield_contact',title:'Northfield Consultation Contact',category:'Marketplace',defaults:{eyebrow:'CONFIDENTIAL CONSULTATION',heading:'Start with a clear conversation.',text:'Tell us briefly what you need help with and we will explain the most useful next step.',phone:'(02) 5550 0196',email:'hello@northfieldlegal.example',address:'Level 8 · 65 King Street · Sydney NSW',button_label:'Request a Consultation',button_url:'mailto:hello@northfieldlegal.example',image_url:'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1500&q=88'},fields:[F('eyebrow'),F('heading'),F('text','textarea'),F('phone'),F('email'),F('address'),F('button_label'),F('button_url'),F('image_url','image')]};
export function MarketplaceNorthfieldContactBlock({block}){const d={...MarketplaceNorthfieldContactSchema.defaults,...block};return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{background:LAW.sand,color:LAW.ink}}><div className="mx-auto grid max-w-[1400px] border lg:grid-cols-[.9fr_1.1fr]" style={{borderColor:LAW.line,background:LAW.ivory}}><div className="p-8 sm:p-12 lg:p-14"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:LAW.burgundy}}/><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-5 block text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl"/><Text value={d.text} fieldPath="text" area className="mt-6 block text-base leading-8" style={{color:LAW.muted}}/><div className="mt-8 grid gap-2 border-t pt-6 text-sm" style={{borderColor:LAW.line}}><Text value={d.phone} fieldPath="phone" className="font-black"/><Text value={d.email} fieldPath="email" className="font-black"/><Text value={d.address} fieldPath="address" className="text-sm" style={{color:LAW.muted}}/></div><Button label={d.button_label} url={d.button_url} fieldPath="button_label" className="mt-8 inline-flex min-h-12 items-center px-7 text-sm font-black text-white" style={{background:LAW.burgundy}}/></div><Image src={d.image_url} fieldPath="image_url" className="min-h-[560px] w-full"/></div></section>}

export const MarketplaceNorthfieldCtaSchema={type:'marketplace_northfield_cta',title:'Northfield Consultation CTA',category:'Marketplace',defaults:{eyebrow:'READY WHEN YOU ARE',heading:'Make the next legal step clearer.',text:'A useful legal relationship starts with a focused conversation about what matters now.',button_label:'Request a Consultation',button_url:'/contact'},fields:[F('eyebrow'),F('heading'),F('text','textarea'),F('button_label'),F('button_url')]};
export function MarketplaceNorthfieldCtaBlock({block}){const d={...MarketplaceNorthfieldCtaSchema.defaults,...block};return <section className="px-6 py-16 lg:px-8" style={{background:LAW.ink,color:LAW.white}}><div className="mx-auto grid max-w-[1400px] gap-8 border px-8 py-12 sm:px-12 lg:grid-cols-[1fr_auto] lg:items-end lg:px-16" style={{borderColor:'rgba(255,255,255,.18)'}}><div><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:'#d9b47d'}}/><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="mt-4 block max-w-5xl text-4xl font-black leading-[.96] tracking-[-.045em] sm:text-6xl"/><Text value={d.text} fieldPath="text" area className="mt-5 block max-w-2xl text-base text-white/55"/></div><Button label={d.button_label} url={d.button_url} fieldPath="button_label" className="inline-flex min-h-12 items-center px-7 text-sm font-black text-white" style={{background:LAW.burgundy2}}/></div></section>}

export const MarketplaceNorthfieldPageHeroSchema={type:'marketplace_northfield_page_hero',title:'Northfield Page Hero',category:'Marketplace',defaults:{eyebrow:'NORTHFIELD LEGAL',heading:'Clear legal advice when the decision matters.',text:'Practical guidance, disciplined preparation, and straightforward communication.'},fields:[F('eyebrow'),F('heading'),F('text','textarea')]};
export function MarketplaceNorthfieldPageHeroBlock({block}){const d={...MarketplaceNorthfieldPageHeroSchema.defaults,...block};return <section className="px-6 py-20 lg:px-8 lg:py-28" style={{background:LAW.burgundy,color:LAW.white}}><div className="mx-auto max-w-[1400px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em] text-white/60"/><Text value={d.heading} fieldPath="heading" cosmicType="h1" className="mt-7 block max-w-6xl text-[clamp(3.8rem,7vw,7.4rem)] font-black leading-[.86] tracking-[-.065em]"/><Text value={d.text} fieldPath="text" area className="mt-7 block max-w-2xl text-base leading-8 text-white/65 sm:text-lg"/></div></section>}

export const MarketplaceNorthfieldTeamSchema={type:'marketplace_northfield_team',title:'Northfield Legal Team',category:'Marketplace',defaults:{eyebrow:'OUR LAWYERS',heading:'Experienced counsel, accessible when it matters.',text:'A small, senior team focused on practical advice and direct client communication.',items:[{name:'Alex Northfield',role:'Principal · Commercial & Property'},{name:'Maya Bennett',role:'Senior Lawyer · Estates & Succession'},{name:'Daniel Cho',role:'Lawyer · Disputes & Advisory'}]},fields:[F('eyebrow'),F('heading'),F('text','textarea'),F('items','repeater')]};
export function MarketplaceNorthfieldTeamBlock({block}){const d={...MarketplaceNorthfieldTeamSchema.defaults,...block};const items=Array.isArray(d.items)&&d.items.length?d.items:MarketplaceNorthfieldTeamSchema.defaults.items;return <section className="px-6 py-24 lg:px-8 lg:py-32" style={{background:LAW.paper,color:LAW.ink}}><div className="mx-auto max-w-[1400px]"><Text value={d.eyebrow} fieldPath="eyebrow" className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:LAW.burgundy}}/><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end"><Text value={d.heading} fieldPath="heading" cosmicType="h2" className="block text-4xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl"/><Text value={d.text} fieldPath="text" area className="block text-base leading-8" style={{color:LAW.muted}}/></div><div className="mt-12 grid gap-4 md:grid-cols-3">{items.slice(0,6).map((it,i)=><article key={i} className="border p-7" style={{borderColor:LAW.line,background:LAW.ivory}}><span className="text-xs font-black" style={{color:LAW.gold}}>{String(i+1).padStart(2,'0')}</span><Text value={it.name} fieldPath={`items.${i}.name`} cosmicType="h3" className="mt-20 block text-2xl font-black"/><Text value={it.role} fieldPath={`items.${i}.role`} className="mt-3 block text-sm" style={{color:LAW.muted}}/></article>)}</div></div></section>}
