import { EditableText } from "../Shared/EditableText";
import { RepeatableControls, RepeatableRemoveButton, cloneLast, removeAt } from "../Shared/RepeatableControls";
import { getEffectiveTheme } from "../../../../theme/Theme";

import { sparkTw, sparkTwPath } from "../Shared/sparkTailwindRuntime";
const base=[{key:"eyebrow",type:"text",label:"Eyebrow"},{key:"heading",type:"text",label:"Heading"},{key:"text",type:"textarea",label:"Text"}];
const item=[{key:"title",type:"text",label:"Title"},{key:"text",type:"textarea",label:"Text"}];
const defs={
 ai_prompt_showcase_premium:{title:"AI Prompt Showcase",eyebrow:"FROM PROMPT TO PAGE",heading:"Show the prompts that shape the experience.",text:"Present safe example prompts or real supplied use cases without implying unsupported AI capabilities.",items:[{title:"Describe the goal",text:"Example: Build a clean service page for a local business."},{title:"Add the details",text:"Example: Include services, trust signals, and a clear contact action."},{title:"Refine the direction",text:"Example: Make the tone more editorial and concise."}]},
 ai_workflow_premium:{title:"AI Workflow",eyebrow:"AI WORKFLOW",heading:"Make the generation process easy to understand.",text:"Explain the real AI-assisted workflow in clear stages without claiming autonomous actions that are not available.",items:[{title:"Understand",text:"Collect the real brief, business context, and requested page intent."},{title:"Create",text:"Generate content and layout choices from supported inputs."},{title:"Review",text:"Let the user review, edit, and publish the result."}]},
 ai_assistant_premium:{title:"AI Assistant",eyebrow:"AI ASSISTANT",heading:"Turn a complex request into a guided conversation.",text:"Show an assistant-style interaction using example copy, not fabricated customer conversations or unsupported actions.",items:[{title:"You",text:"I need a modern landing page for a growing service business."},{title:"Assistant",text:"I can structure the page around the offer, proof, services, and next action."},{title:"Next prompt",text:"Ask for a change in tone, layout, or content priority."}]},
 ai_timeline_premium:{title:"AI Timeline",eyebrow:"GENERATION JOURNEY",heading:"Show how an idea becomes a finished page.",text:"Use a timeline to explain supported AI generation stages without fake processing times or guarantees.",items:[{title:"01 · Brief",text:"Capture the prompt, brand direction, and page goal."},{title:"02 · Generate",text:"Create supported content and section recommendations."},{title:"03 · Refine",text:"Review, edit, and prepare the page for publishing."}]},
 ai_builder_premium:{title:"AI Builder",eyebrow:"AI BUILDER",heading:"Show how AI helps shape a page without hiding the controls.",text:"Present the real builder workflow with editable stages and supported actions only.",items:[{title:"Describe",text:"Start from a real goal, page type, and brand direction."},{title:"Build",text:"Generate supported sections and content into the visual builder."},{title:"Refine",text:"Review, edit, rearrange, and prepare the page for publishing."}]},
 ai_automation_premium:{title:"Automation",eyebrow:"AUTOMATION",heading:"Explain the repetitive work the product can genuinely simplify.",text:"Show only real supported automations or clearly labelled planned workflows.",items:[{title:"Trigger",text:"A supported user action starts the workflow."},{title:"Process",text:"The product performs the real configured steps."},{title:"Review",text:"Keep a clear human review or next-action point where applicable."}]},
 ai_credits_dashboard_premium:{title:"Credits Dashboard",eyebrow:"AI CREDITS",heading:"Make AI usage easy to understand at a glance.",text:"Show supplied credit balances, usage rules, or editable sample values without fabricating account data.",items:[{title:"Available",text:"Display the real available credit balance when supplied."},{title:"Usage",text:"Explain how supported AI actions consume credits."},{title:"Top up",text:"Show a real purchase or plan path only when it exists."}]},
 ai_generation_process_premium:{title:"Generation Process",eyebrow:"GENERATION PROCESS",heading:"Turn generation into a clear sequence users can follow.",text:"Explain supported generation stages without fake progress, background work, or completion times.",items:[{title:"Understand",text:"Read the supplied prompt and page context."},{title:"Generate",text:"Create supported content and section choices."},{title:"Prepare",text:"Return the result for review, editing, and publishing."}]},
 ai_statistics_premium:{title:"AI Statistics",eyebrow:"AI STATISTICS",heading:"Explain AI usage with numbers you can actually support.",text:"Present supplied usage, generation, adoption, or efficiency metrics without fabricated performance claims.",items:[{title:"Generations",text:"Add a real supplied usage total or leave this as editable sample copy."},{title:"Adoption",text:"Show a verified adoption or usage metric only when available."},{title:"Efficiency",text:"Use a supplied time or workflow metric without implying guaranteed savings."}]},
 ai_prompt_examples_premium:{title:"Prompt Examples",eyebrow:"PROMPT EXAMPLES",heading:"Give visitors practical ways to start with AI.",text:"Show clearly illustrative prompt examples tied to supported capabilities, not promises of unsupported results.",items:[{title:"Landing page",text:"Create a concise landing page for a local service business with services, proof, and a contact CTA."},{title:"Rewrite",text:"Rewrite this section in a confident, clear tone while keeping the supplied facts unchanged."},{title:"Structure",text:"Suggest a page structure for this goal using only supported section types."}]}
};
function schema(type){const d=defs[type];return {type,title:d.title,category:"AI",purpose:d.text,description:d.text,tags:["ai","premium","pro"],defaults:d,fields:[...base,{key:"items",type:"repeater",label:"Items",fields:item},{key:"note",type:"textarea",label:"Note"}]};}
export const AiPromptShowcasePremiumSchema=schema("ai_prompt_showcase_premium");
export const AiWorkflowPremiumSchema=schema("ai_workflow_premium");
export const AiAssistantPremiumSchema=schema("ai_assistant_premium");
export const AiTimelinePremiumSchema=schema("ai_timeline_premium");
export const AiBuilderPremiumSchema=schema("ai_builder_premium");
export const AiAutomationPremiumSchema=schema("ai_automation_premium");
export const AiCreditsDashboardPremiumSchema=schema("ai_credits_dashboard_premium");
export const AiGenerationProcessPremiumSchema=schema("ai_generation_process_premium");
export const AiStatisticsPremiumSchema=schema("ai_statistics_premium");
export const AiPromptExamplesPremiumSchema=schema("ai_prompt_examples_premium");

function AiBlock({block,onUpdate,globalTheme,schema}){
 const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme,globalTheme); const d={...schema.defaults,...block}; const items=d.items||[];
 const useHoverTrash = true;
 return <section className={sparkTw(block, "section_1", `group/repeatable-section relative overflow-hidden px-6 py-20 sm:py-24 ${theme.bg}`)}><div className={sparkTw(block, "element_2", "pointer-events-none absolute inset-0 opacity-[.05]")} style={{backgroundImage:"radial-gradient(currentColor 1px, transparent 1px)",backgroundSize:"24px 24px"}}/><div className={sparkTw(block, "wrapper_3", "relative mx-auto max-w-7xl")}><div className={sparkTw(block, "element_4", "max-w-3xl")}><EditableText value={d.eyebrow} onSave={eyebrow=>onUpdate({eyebrow})} className={sparkTw(block, "eyebrow_5", `text-xs font-bold uppercase tracking-[.24em] ${theme.sub}`)}/><EditableText value={d.heading} onSave={heading=>onUpdate({heading})} className={sparkTw(block, "heading_6", `mt-4 block text-4xl font-black tracking-tight sm:text-5xl ${theme.text}`)}/><EditableText value={d.text} isTextArea onSave={text=>onUpdate({text})} className={sparkTw(block, "element_7", `mt-5 block max-w-2xl leading-7 ${theme.sub}`)}/></div><div className={sparkTw(block, "grid_8", "mt-10 grid gap-4 lg:grid-cols-3")}>{items.slice(0,6).map((x,i)=><article key={i} className={sparkTwPath(block, ["items", i], "card", `${useHoverTrash ? "group relative" : ""} rounded-[1.75rem] border p-6 backdrop-blur ${theme.border} ${theme.card}`)}><div className={sparkTwPath(block, ["items", i], "index", `mb-5 inline-flex h-9 w-9 items-center justify-center rounded-xl border text-xs font-black ${theme.border} ${theme.text}`)}>{i+1}</div><EditableText value={x.title} onSave={v=>{const next=[...items];next[i]={...next[i],title:v};onUpdate({items:next})}} className={sparkTwPath(block, ["items", i], "title", `block text-lg font-bold ${theme.text}`)}/><EditableText value={x.text} isTextArea onSave={v=>{const next=[...items];next[i]={...next[i],text:v};onUpdate({items:next})}} className={sparkTwPath(block, ["items", i], "desc", `mt-3 block text-sm leading-6 ${theme.sub}`)}/><RepeatableRemoveButton hoverScope="card" overlay={useHoverTrash} disabled={items.length<=1} onRemove={()=>onUpdate({items:removeAt(items,i,1)})}/></article>)}</div><RepeatableControls addLabel="Add AI item" showRemove={!useHoverTrash} canAdd={items.length<6} canRemove={items.length>1} onAdd={()=>items.length<6&&onUpdate({items:cloneLast(items,{title:"New item",text:"Describe this item."})})} onRemove={()=>items.length>1&&onUpdate({items:items.slice(0,-1)})}/></div></section>
}
export const AiPromptShowcasePremiumBlock=p=><AiBlock {...p} schema={AiPromptShowcasePremiumSchema}/>;
export const AiWorkflowPremiumBlock=p=><AiBlock {...p} schema={AiWorkflowPremiumSchema}/>;
export const AiAssistantPremiumBlock=p=><AiBlock {...p} schema={AiAssistantPremiumSchema}/>;
export const AiTimelinePremiumBlock=p=><AiBlock {...p} schema={AiTimelinePremiumSchema}/>;
export const AiBuilderPremiumBlock=p=><AiBlock {...p} schema={AiBuilderPremiumSchema}/>;
export const AiAutomationPremiumBlock=p=><AiBlock {...p} schema={AiAutomationPremiumSchema}/>;
export const AiCreditsDashboardPremiumBlock=p=><AiBlock {...p} schema={AiCreditsDashboardPremiumSchema}/>;
export const AiGenerationProcessPremiumBlock=p=><AiBlock {...p} schema={AiGenerationProcessPremiumSchema}/>;
export const AiStatisticsPremiumBlock=p=><AiBlock {...p} schema={AiStatisticsPremiumSchema}/>;
export const AiPromptExamplesPremiumBlock=p=><AiBlock {...p} schema={AiPromptExamplesPremiumSchema}/>;
