import { EditableText } from "../Shared/EditableText";
import { getEffectiveTheme } from "../../../../theme/Theme";

const metricFields=[{key:"value",type:"text",label:"Value"},{key:"label",type:"text",label:"Label"},{key:"description",type:"textarea",label:"Description"}];
const baseFields=[{key:"eyebrow",type:"text",label:"Eyebrow"},{key:"heading",type:"text",label:"Heading"},{key:"text",type:"textarea",label:"Supporting text"}];
const verifiedMetrics=[
 {value:"12+",label:"Years in market",description:"Replace with a verified business metric."},
 {value:"48",label:"Projects delivered",description:"Replace with verified company data."},
 {value:"6",label:"Core capabilities",description:"Use a factual count from the business."},
 {value:"4",label:"Markets served",description:"Publish only when this can be verified."},
];
export const StatsAnimatedCountersPremiumSchema={type:"stats_animated_counters_premium",title:"Animated Counters",category:"Statistics",purpose:"Present verified business numbers with premium counter styling.",description:"Large metric counters with supporting labels and editorial hierarchy.",tags:["statistics","counters","metrics","proof","premium","pro"],defaults:{eyebrow:"BY THE NUMBERS",heading:"A clear view of the progress behind the work.",text:"Replace the sample values with verified company metrics before publishing.",metrics:verifiedMetrics},fields:[...baseFields,{key:"metrics",type:"repeater",label:"Metrics",fields:metricFields}]};
export const StatsRevenueDashboardPremiumSchema={type:"stats_revenue_dashboard_premium",title:"Revenue Dashboard",category:"Statistics",purpose:"Show supplied financial or commercial metrics in a premium dashboard layout.",description:"A restrained executive dashboard for verified revenue or commercial data.",tags:["statistics","revenue","dashboard","metrics","premium","pro"],defaults:{eyebrow:"PERFORMANCE SNAPSHOT",heading:"Commercial performance at a glance.",text:"Use only supplied and verified financial figures. Sample values are placeholders.",period_label:"Selected period",metrics:[{value:"—",label:"Revenue",description:"Add verified revenue."},{value:"—",label:"Recurring revenue",description:"Add verified recurring revenue."},{value:"—",label:"Average order",description:"Add a verified average."},{value:"—",label:"Active accounts",description:"Add a verified count."}]},fields:[...baseFields,{key:"period_label",type:"text",label:"Period label"},{key:"metrics",type:"repeater",label:"Dashboard metrics",fields:metricFields}]};
export const StatsGrowthChartsPremiumSchema={type:"stats_growth_charts_premium",title:"Growth Charts",category:"Statistics",purpose:"Visualize supplied trend data without external chart libraries.",description:"Lightweight CSS bar chart plus key figures for verified growth data.",tags:["statistics","growth","charts","trend","premium","pro"],defaults:{eyebrow:"GROWTH",heading:"See the direction, not just the headline.",text:"Replace the sample trend with verified values before publishing.",chart_label:"Six-period trend",series:[{label:"P1",value:28},{label:"P2",value:38},{label:"P3",value:46},{label:"P4",value:58},{label:"P5",value:72},{label:"P6",value:84}],metrics:[{value:"—",label:"Growth rate",description:"Add a verified rate."},{value:"—",label:"New customers",description:"Add a verified count."},{value:"—",label:"Retention",description:"Add a verified rate."}]},fields:[...baseFields,{key:"chart_label",type:"text",label:"Chart label"},{key:"series",type:"repeater",label:"Chart series",fields:[{key:"label",type:"text",label:"Label"},{key:"value",type:"number",label:"Value 0-100"}]},{key:"metrics",type:"repeater",label:"Summary metrics",fields:metricFields}]};
export const StatsAchievementsPremiumSchema={type:"stats_achievements_premium",title:"Achievements",category:"Statistics",purpose:"Present real milestones, recognitions, or achievements with premium editorial hierarchy.",description:"A four-item achievement grid with year/badge support.",tags:["statistics","achievements","milestones","proof","premium","pro"],defaults:{eyebrow:"MILESTONES",heading:"Moments worth marking.",text:"Use real milestones or clearly editable placeholders until verified.",achievements:[{year:"20XX",badge:"Milestone",title:"Company milestone",text:"Replace with a verified achievement."},{year:"20XX",badge:"Recognition",title:"Recognition or award",text:"Publish only when supplied and verified."},{year:"20XX",badge:"Growth",title:"Growth milestone",text:"Use factual company history."},{year:"20XX",badge:"Impact",title:"Impact milestone",text:"Avoid unsupported performance claims."}]},fields:[...baseFields,{key:"achievements",type:"repeater",label:"Achievements",fields:[{key:"year",type:"text",label:"Year"},{key:"badge",type:"text",label:"Badge"},{key:"title",type:"text",label:"Title"},{key:"text",type:"textarea",label:"Description"}]}]};

function Head({data,onUpdate,theme}){return <div className="mb-10 max-w-3xl"><EditableText value={data.eyebrow} className={`block text-xs font-bold uppercase tracking-[.22em] ${theme.sub}`} onSave={eyebrow=>onUpdate({eyebrow})}/><EditableText value={data.heading} className={`mt-4 block text-4xl font-semibold tracking-tight sm:text-5xl ${theme.text}`} onSave={heading=>onUpdate({heading})}/><EditableText value={data.text} isTextArea className={`mt-4 block max-w-2xl text-base leading-7 ${theme.sub}`} onSave={text=>onUpdate({text})}/></div>}
function useData(schema,block){return {...schema.defaults,...block};}
function updateArray(onUpdate,data,key,index,field,value){onUpdate({[key]:(data[key]||[]).map((x,i)=>i===index?{...x,[field]:value}:x)});}

export function StatsAnimatedCountersPremiumBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.resolvedTheme,globalTheme),data=useData(StatsAnimatedCountersPremiumSchema,block),metrics=Array.isArray(data.metrics)&&data.metrics.length?data.metrics:verifiedMetrics;return <section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Head data={data} onUpdate={onUpdate} theme={theme}/><div className={`grid overflow-hidden rounded-3xl border ${theme.border} sm:grid-cols-2 lg:grid-cols-4`}>{metrics.slice(0,4).map((m,i)=><article key={i} className={`min-h-56 border-b p-7 sm:border-r lg:border-b-0 ${theme.border} ${theme.card}`}><span className={`text-xs font-bold ${theme.sub}`}>0{i+1}</span><EditableText value={m.value} className={`mt-8 block text-5xl font-black tracking-tight ${theme.text}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"value",v)}/><EditableText value={m.label} className={`mt-3 block font-semibold ${theme.text}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"label",v)}/><EditableText value={m.description} isTextArea className={`mt-3 block text-sm leading-6 ${theme.sub}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"description",v)}/></article>)}</div></div></section>}

export function StatsRevenueDashboardPremiumBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.resolvedTheme,globalTheme),data=useData(StatsRevenueDashboardPremiumSchema,block),metrics=Array.isArray(data.metrics)&&data.metrics.length?data.metrics:StatsRevenueDashboardPremiumSchema.defaults.metrics;return <section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Head data={data} onUpdate={onUpdate} theme={theme}/><div className={`rounded-3xl border p-5 sm:p-7 ${theme.border} ${theme.card}`}><div className="mb-6 flex items-center justify-between gap-4"><span className={`text-xs font-bold uppercase tracking-wider ${theme.sub}`}>Dashboard</span><EditableText value={data.period_label} className={`text-sm ${theme.sub}`} onSave={period_label=>onUpdate({period_label})}/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.slice(0,4).map((m,i)=><article key={i} className={`rounded-2xl border p-5 ${theme.border}`}><EditableText value={m.label} className={`block text-sm font-medium ${theme.sub}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"label",v)}/><EditableText value={m.value} className={`mt-5 block text-3xl font-bold ${theme.text}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"value",v)}/><EditableText value={m.description} isTextArea className={`mt-3 block text-xs leading-5 ${theme.sub}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"description",v)}/></article>)}</div></div></div></section>}

export function StatsGrowthChartsPremiumBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.resolvedTheme,globalTheme),data=useData(StatsGrowthChartsPremiumSchema,block),series=Array.isArray(data.series)&&data.series.length?data.series:StatsGrowthChartsPremiumSchema.defaults.series,metrics=Array.isArray(data.metrics)&&data.metrics.length?data.metrics:StatsGrowthChartsPremiumSchema.defaults.metrics;return <section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Head data={data} onUpdate={onUpdate} theme={theme}/><div className="grid gap-6 lg:grid-cols-[1.5fr_.8fr]"><div className={`rounded-3xl border p-6 ${theme.border} ${theme.card}`}><EditableText value={data.chart_label} className={`block text-sm font-semibold ${theme.text}`} onSave={chart_label=>onUpdate({chart_label})}/><div className="mt-8 flex h-64 items-end gap-3">{series.slice(0,6).map((point,i)=>{const value=Math.max(8,Math.min(100,Number(point.value)||0));return <div key={i} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-3"><div className="flex h-48 w-full items-end"><div className="w-full rounded-t-xl bg-current opacity-20" style={{height:`${value}%`}}/></div><EditableText value={point.label} className={`block text-xs ${theme.sub}`} onSave={v=>updateArray(onUpdate,{...data,series},"series",i,"label",v)}/></div>})}</div></div><div className="grid gap-3">{metrics.slice(0,3).map((m,i)=><article key={i} className={`rounded-3xl border p-5 ${theme.border} ${theme.card}`}><EditableText value={m.value} className={`block text-3xl font-bold ${theme.text}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"value",v)}/><EditableText value={m.label} className={`mt-2 block font-semibold ${theme.text}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"label",v)}/><EditableText value={m.description} isTextArea className={`mt-2 block text-xs leading-5 ${theme.sub}`} onSave={v=>updateArray(onUpdate,{...data,metrics},"metrics",i,"description",v)}/></article>)}</div></div></div></section>}

export function StatsAchievementsPremiumBlock({block,onUpdate,globalTheme}){const theme=getEffectiveTheme(block.resolvedTheme,globalTheme),data=useData(StatsAchievementsPremiumSchema,block),items=Array.isArray(data.achievements)&&data.achievements.length?data.achievements:StatsAchievementsPremiumSchema.defaults.achievements;return <section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Head data={data} onUpdate={onUpdate} theme={theme}/><div className="grid gap-px overflow-hidden rounded-3xl border sm:grid-cols-2 ${theme.border}">{items.slice(0,4).map((a,i)=><article key={i} className={`min-h-64 p-7 ${theme.card}`}><div className="flex items-center justify-between gap-3"><EditableText value={a.year} className={`text-sm font-bold ${theme.text}`} onSave={v=>updateArray(onUpdate,{...data,achievements:items},"achievements",i,"year",v)}/><EditableText value={a.badge} className={`rounded-full border px-3 py-1 text-xs ${theme.border} ${theme.sub}`} onSave={v=>updateArray(onUpdate,{...data,achievements:items},"achievements",i,"badge",v)}/></div><EditableText value={a.title} className={`mt-12 block text-2xl font-semibold ${theme.text}`} onSave={v=>updateArray(onUpdate,{...data,achievements:items},"achievements",i,"title",v)}/><EditableText value={a.text} isTextArea className={`mt-3 block text-sm leading-6 ${theme.sub}`} onSave={v=>updateArray(onUpdate,{...data,achievements:items},"achievements",i,"text",v)}/></article>)}</div></div></section>}
