<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><?php echo e($title); ?> · <?php echo e($website->name); ?></title>
    <script src="https://cdn.tailwindcss.com"></script>
    <?php if($description): ?><meta name="description" content="<?php echo e($description); ?>"><?php endif; ?>
    <meta property="og:type" content="<?php echo e($viewMode === 'entry' ? 'article' : 'website'); ?>">
    <meta property="og:title" content="<?php echo e($title); ?> · <?php echo e($website->name); ?>">
    <?php if($description): ?><meta property="og:description" content="<?php echo e($description); ?>"><?php endif; ?>
    <?php if($viewMode === 'entry' && $activeEntry?->og_image_url): ?><meta property="og:image" content="<?php echo e($assetUrl($activeEntry->og_image_url)); ?>"><?php elseif($viewMode === 'entry' && $activeEntry?->featured_image_url): ?><meta property="og:image" content="<?php echo e($assetUrl($activeEntry->featured_image_url)); ?>"><?php endif; ?>
    <?php if($viewMode === 'entry' && $activeEntry?->published_at): ?><meta property="article:published_time" content="<?php echo e($activeEntry->published_at->toISOString()); ?>"><?php endif; ?>
    <?php if($viewMode === 'entry' && $activeEntry?->updated_at): ?><meta property="article:modified_time" content="<?php echo e($activeEntry->updated_at->toISOString()); ?>"><?php endif; ?>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');
        :root{--p:<?php echo e($palette['primary']); ?>;--a:<?php echo e($palette['accent']); ?>;--s:<?php echo e($palette['surface']); ?>;--t:<?php echo e($palette['text']); ?>;--m:<?php echo e($palette['muted']); ?>;--b:<?php echo e($palette['border']); ?>;--bg:<?php echo e($palette['background']); ?>;--ink:#0f172a;--sub:#475569}
        *{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,var(--bg),color-mix(in srgb,var(--p) 4%,var(--bg)));color:var(--t);font-family:Manrope,system-ui,sans-serif}.wrap{width:min(1180px,calc(100% - 40px));margin:auto}a{color:inherit;text-decoration:none}img{display:block;max-width:100%}.shell{background:var(--bg)}
        .fallback-header{border-bottom:1px solid var(--b);background:color-mix(in srgb,var(--bg) 94%,transparent);backdrop-filter:blur(12px)}.fallback-header .wrap{display:flex;justify-content:space-between;align-items:center;padding:18px 0}.brand{font-weight:700}.fallback-header nav{display:flex;gap:20px;font-size:14px}.fallback-footer{margin-top:72px;background:color-mix(in srgb,var(--p) 9%,#0f172a);color:#e2e8f0;padding:34px 0}.fallback-footer .wrap{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}
        .content-hero{padding:72px 0 48px;border-bottom:1px solid var(--b);background:linear-gradient(135deg,color-mix(in srgb,var(--p) 10%,var(--bg)),var(--bg) 70%)}.kicker{font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.22em;color:var(--t);opacity:.72}h1,h2,h3{font-weight:700;letter-spacing:-.035em;color:var(--t)}h1{font-size:clamp(40px,6vw,68px);line-height:1.02;margin:14px 0}.hero-copy{max-width:720px;color:var(--m);font-size:17px;line-height:1.75}.filters{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.pill{display:inline-flex;align-items:center;min-height:38px;padding:8px 13px;border:1px solid var(--b);border-radius:999px;background:var(--bg);color:var(--t);font-size:13px;font-weight:700;box-shadow:0 1px 2px rgba(15,23,42,.04)}.pill:hover{border-color:color-mix(in srgb,var(--t) 28%,var(--b));background:var(--s)}.pill.active{background:var(--t);border-color:var(--t);color:var(--bg)}
        .archive{padding:52px 0 80px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px}.card{overflow:hidden;border:1px solid var(--b);border-radius:24px;background:var(--bg);color:var(--t);box-shadow:0 16px 45px rgba(15,23,42,.07);transition:.2s}.card:hover{transform:translateY(-3px);box-shadow:0 22px 56px rgba(15,23,42,.11)}.card-media{aspect-ratio:16/10;background:var(--s);overflow:hidden}.card-media img{width:100%;height:100%;object-fit:cover}.card-body{padding:24px}.meta{font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.15em;color:var(--m)}.card h2{font-size:22px;line-height:1.18;margin:10px 0;color:var(--t)}.card h2 a,.read{color:var(--t)}.card p{color:var(--m);font-size:14px;line-height:1.7}.read{display:inline-flex;margin-top:14px;font-size:14px;font-weight:800}.empty{padding:48px;text-align:center;border:1px dashed var(--b);border-radius:24px;color:var(--m)}
        .entry{padding:44px 0 72px}.breadcrumb{display:flex;gap:9px;align-items:center;font-size:13px;color:var(--m);margin-bottom:30px}.entry-head{max-width:880px;margin-bottom:28px}.entry-head h1{font-size:clamp(42px,6vw,72px)}.entry-deck{font-size:19px;line-height:1.7;color:var(--m);max-width:760px}.entry-meta{display:flex;gap:12px;flex-wrap:wrap;margin-top:20px;color:var(--m);font-size:13px}.hero-image{overflow:hidden;border:1px solid var(--b);border-radius:30px;background:var(--s);box-shadow:0 24px 70px rgba(15,23,42,.09);margin:32px 0}.hero-image img{width:100%;max-height:680px;object-fit:cover}.entry-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:54px;align-items:start}.prose{font-size:17px;line-height:1.85;color:color-mix(in srgb,var(--t) 84%,var(--m))}.prose p{margin:0 0 1.35em}.prose h2,.prose h3{color:var(--t);margin:1.7em 0 .65em}.sidebar{position:sticky;top:24px}.info-card{border:1px solid var(--b);border-radius:22px;background:var(--bg);padding:20px;box-shadow:0 12px 36px rgba(15,23,42,.045)}.info-row{padding:11px 0;border-bottom:1px solid var(--b)}.info-row:last-child{border-bottom:0}.info-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.15em;color:var(--m)}.info-value{margin-top:4px;font-size:14px;font-weight:600}.gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:34px}.gallery img{width:100%;height:190px;object-fit:cover;border:1px solid var(--b);border-radius:18px}.related{padding:64px 0;border-top:1px solid var(--b)}.related h2{font-size:34px;margin:0 0 26px}.related .grid{grid-template-columns:repeat(3,minmax(0,1fr))}
        [data-cosmic-dynamic-single]{width:100%;overflow:hidden}[data-cosmic-dynamic-single] [data-cosmic-richtext]{font-size:1.0625rem;line-height:1.88;text-wrap:pretty}[data-cosmic-dynamic-single] [data-cosmic-richtext]>:first-child{margin-top:0}[data-cosmic-dynamic-single] [data-cosmic-richtext]>:last-child{margin-bottom:0}[data-cosmic-dynamic-single] [data-cosmic-richtext] p{margin:0 0 1.35em}[data-cosmic-dynamic-single] [data-cosmic-richtext] h2{font-size:clamp(1.75rem,3vw,2.35rem);line-height:1.15;margin:1.8em 0 .65em;letter-spacing:-.035em}[data-cosmic-dynamic-single] [data-cosmic-richtext] h3{font-size:clamp(1.35rem,2.4vw,1.75rem);line-height:1.22;margin:1.6em 0 .6em;letter-spacing:-.025em}[data-cosmic-dynamic-single] [data-cosmic-richtext] ul,[data-cosmic-dynamic-single] [data-cosmic-richtext] ol{margin:1.2em 0;padding-left:1.4em}[data-cosmic-dynamic-single] [data-cosmic-richtext] li{margin:.45em 0}[data-cosmic-dynamic-single] [data-cosmic-richtext] blockquote{margin:1.6em 0;padding:1rem 1.25rem;border-left:4px solid var(--p);border-radius:0 1rem 1rem 0;background:color-mix(in srgb,var(--p) 7%,var(--bg));font-size:1.08em;font-weight:500}[data-cosmic-dynamic-single] [data-cosmic-richtext] a{text-decoration:underline;text-decoration-thickness:.08em;text-underline-offset:.18em}[data-cosmic-dynamic-single] [data-cosmic-richtext] img{height:auto;border-radius:1.25rem;margin:1.6rem auto}[data-cosmic-dynamic-single] [data-cosmic-richtext] figcaption{margin-top:.65rem;text-align:center;font-size:.82rem;color:var(--m)}[data-cosmic-dynamic-single] [data-cosmic-richtext] pre{overflow:auto;border-radius:1rem;padding:1rem 1.1rem;background:#0f172a;color:#e2e8f0;font-size:.9rem;line-height:1.7}[data-cosmic-dynamic-single] [data-cosmic-richtext] table{display:block;width:100%;overflow-x:auto;border-collapse:collapse;margin:1.7rem 0}[data-cosmic-dynamic-single] [data-cosmic-richtext] th,[data-cosmic-dynamic-single] [data-cosmic-richtext] td{padding:.8rem .9rem;border:1px solid var(--b);text-align:left}[data-cosmic-gallery] figure{aspect-ratio:4/3}[data-cosmic-gallery] img{width:100%;height:100%;object-fit:cover;transition:transform .35s ease}[data-cosmic-gallery] figure:hover img{transform:scale(1.025)}
        @media(max-width:900px){.grid,.related .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.entry-layout{grid-template-columns:1fr}.sidebar{position:static}.gallery{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.wrap{width:min(100% - 24px,1180px)}.content-hero{padding:50px 0 34px}.archive,.entry{padding-top:30px}.grid,.related .grid{grid-template-columns:1fr}.entry-head h1{font-size:40px}.gallery{grid-template-columns:1fr}.gallery img{height:auto}.fallback-header nav{display:none}}
    </style>
</head>
<body>
<?php if($useSiteShell): ?><div class="shell"><?php echo $siteHeaderHtml; ?></div><?php else: ?><header class="fallback-header"><div class="wrap"><a class="brand" href="<?php echo e($archiveUrl($contentType)); ?>"><?php echo e($website->name); ?></a><nav><a href="<?php echo e($archiveUrl($contentType)); ?>"><?php echo e($contentType->name); ?></a></nav></div></header><?php endif; ?>

<?php if($viewMode === 'archive'): ?>
<section class="content-hero"><div class="wrap"><div class="kicker"><?php echo e($contentType->singular_name); ?> archive</div><h1><?php echo e($contentType->name); ?></h1><p class="hero-copy"><?php echo e($contentType->description ?: 'Explore the latest '.$contentType->name.'.'); ?></p><?php if($categories->isNotEmpty() || $tags->isNotEmpty()): ?><div class="filters"><a class="pill <?php echo e(!$activeCategory && !$activeTag ? 'active' : ''); ?>" href="<?php echo e($archiveUrl($contentType)); ?>">All</a><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="pill <?php echo e($activeCategory === $category ? 'active' : ''); ?>" href="<?php echo e($archiveUrl($contentType)); ?>?category=<?php echo e(rawurlencode($category)); ?>"><?php echo e($category); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php $__currentLoopData = $tags->take(6); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $tag): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="pill <?php echo e($activeTag === $tag ? 'active' : ''); ?>" href="<?php echo e($archiveUrl($contentType)); ?>?tag=<?php echo e(rawurlencode($tag)); ?>">#<?php echo e($tag); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?></div></section>
<section class="archive"><div class="wrap"><?php if($entries->isEmpty()): ?><div class="empty">No published <?php echo e(strtolower($contentType->name)); ?> yet.</div><?php else: ?><div class="grid"><?php $__currentLoopData = $entries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $entry): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="card"><a class="card-media" href="<?php echo e($entryUrl($contentType,$entry)); ?>"><?php if($entry->featured_image_url): ?><img src="<?php echo e($assetUrl($entry->featured_image_url)); ?>" alt="<?php echo e($entry->title); ?>"><?php endif; ?></a><div class="card-body"><div class="meta"><?php echo e($entry->category ?: $contentType->singular_name); ?><?php if($entry->is_featured): ?> · Featured <?php endif; ?></div><h2><a href="<?php echo e($entryUrl($contentType,$entry)); ?>"><?php echo e($entry->title); ?></a></h2><p><?php echo e($entry->excerpt); ?></p><a class="read" href="<?php echo e($entryUrl($contentType,$entry)); ?>">Read more →</a></div></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?></div></section>
<?php else: ?>
<section class="entry-template-runtime"><?php echo $renderedTemplateMarkup ?? ''; ?></section>
<?php endif; ?>

<?php if($useSiteShell): ?><div class="shell"><?php echo $siteFooterHtml; ?></div><?php else: ?><footer class="fallback-footer"><div class="wrap"><strong><?php echo e($website->name); ?></strong><span>Powered by Cosmic CMS</span></div></footer><?php endif; ?>
</body></html>
<?php /**PATH C:\xampp\htdocs\my-custom-cms\resources\views/content/storefront.blade.php ENDPATH**/ ?>