import { Link } from "@inertiajs/react";

const formatLastEdited = (value) => { if (!value) return "Not yet edited"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Recently updated" : `Edited ${date.toLocaleDateString(undefined, { month: "short", day: "numeric" })}`; };

export default function PageListRow({ page, depth = 0, onDelete, onAddChild }) {
    const status = page.status === "published" || page.status === "Published" ? "Published" : "Draft";
    const pageType = page.page_type === "blog" ? "Posts & updates" : "Standard page";
    const childAction = depth === 0 ? 'Add child page' : 'Add nested page';
    return <article className="flex flex-col gap-3 px-4 py-3.5 transition hover:bg-white/[0.04] sm:flex-row sm:items-center"><div className={`min-w-0 flex-1 ${depth ? 'border-l border-violet-400/35 pl-3' : ''}`} style={depth ? { marginLeft: `${Math.min(depth, 2) * 20}px` } : undefined}><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-semibold text-white">{page.title || "Untitled Page"}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${status === "Published" ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-300/10 text-amber-200"}`}>{status}</span><span className="rounded-full bg-violet-400/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-violet-200">{pageType}</span>{depth > 0 && <span className="text-[10px] font-medium uppercase tracking-wide text-slate-500">Level {depth + 1}</span>}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500"><span>/{page.slug || "untitled"}</span><span>{formatLastEdited(page.updated_at)}</span></div></div><div className="flex shrink-0 flex-wrap items-center gap-1.5">{depth < 2 && <button type="button" onClick={() => onAddChild(page)} className="inline-flex h-8 items-center justify-center rounded-lg px-2.5 text-xs font-semibold text-violet-200 transition hover:bg-violet-400/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-violet-400">{childAction}</button>}<button type="button" onClick={() => onDelete(page)} className="inline-flex h-8 items-center justify-center rounded-lg px-2.5 text-xs font-semibold text-rose-300 transition hover:bg-rose-400/10 hover:text-rose-200 focus:outline-none focus:ring-2 focus:ring-rose-400">Delete</button><Link href={route("pages.builder", page.id)} className="inline-flex h-8 items-center justify-center rounded-lg bg-white px-3 text-xs font-semibold text-slate-950 transition hover:bg-slate-200 focus:outline-none focus:ring-2 focus:ring-violet-400">Open Builder</Link></div></article>;
}
