import { useMemo, useState } from "react";
import { EditableButton } from "../Shared/EditableButton";
import { EditableText } from "../Shared/EditableText";
import { getEffectiveTheme } from "../../../../theme/Theme";
import { colorFamilies } from "../../../../theme/colorFamilies";

const shared = (type,title,purpose,description,defaults)=>({type,title,category:"Pricing",purpose,description,tags:["pricing","premium","pro"],defaults});
const baseDefaults={eyebrow:"SIMPLE, FLEXIBLE PRICING",heading:"Choose the plan that fits your next stage.",text:"Clear options designed to make comparison easier without hiding the details."};
const planDefaults={
  plan_one_name:"Starter",plan_one_monthly:"$29",plan_one_yearly:"$290",plan_one_description:"For focused projects and smaller teams.",plan_one_button_label:"Choose Starter",plan_one_button_url:"#",
  plan_two_name:"Growth",plan_two_monthly:"$79",plan_two_yearly:"$790",plan_two_description:"For growing teams that need more capability.",plan_two_button_label:"Choose Growth",plan_two_button_url:"#",plan_two_badge:"MOST POPULAR",
  plan_three_name:"Pro",plan_three_monthly:"$149",plan_three_yearly:"$1,490",plan_three_description:"For advanced teams and larger operations.",plan_three_button_label:"Choose Pro",plan_three_button_url:"#",
};
export const PricingComparisonPremiumSchema=shared("pricing_comparison_premium","Comparison Table","Compare plans in a premium feature matrix.","Pro-only comparison table with three plans and six editable feature rows.",{...baseDefaults,...planDefaults,
  feature_one:"Projects",one_one:"3",two_one:"Unlimited",three_one:"Unlimited",
  feature_two:"Team members",one_two:"1",two_two:"5",three_two:"Unlimited",
  feature_three:"Priority support",one_three:"Standard",two_three:"Priority",three_three:"Dedicated",
  feature_four:"Analytics",one_four:"Basic",two_four:"Advanced",three_four:"Advanced + exports",
  feature_five:"Custom branding",one_five:"—",two_five:"Included",three_five:"Included",
  feature_six:"Best for",one_six:"Individuals",two_six:"Growing teams",three_six:"Agencies & scale",
  footnote:"Pricing and inclusions are editable placeholders and should be replaced with your actual offer details."
});
export const PricingTogglePremiumSchema=shared("pricing_toggle_premium","Toggle Monthly/Yearly","Switch pricing presentation between monthly and yearly values.","Interactive premium pricing cards with a monthly/yearly toggle and static export fallback.",{...baseDefaults,...planDefaults,monthly_label:"Monthly",yearly_label:"Yearly",yearly_note:"Save with annual billing"});
export const PricingEnterprisePremiumSchema=shared("pricing_enterprise_premium","Enterprise Pricing","Present enterprise pricing with a consultative premium layout.","Enterprise-focused pricing section with custom scope, proof points, and sales CTA.",{...baseDefaults,heading:"Pricing built around the complexity of your organisation.",text:"Create a tailored enterprise package around your team size, workflow, support, security, and rollout needs.",price_label:"CUSTOM PRICING",price_text:"Talk to sales",primary_label:"Book a consultation",primary_url:"#",secondary_label:"View capabilities",secondary_url:"#",point_one:"Tailored onboarding",point_two:"Priority support",point_three:"Flexible permissions",point_four:"Custom rollout planning",note:"Only publish claims and service levels that your business can actually provide."});
export const PricingCalculatorPremiumSchema=shared("pricing_calculator_premium","Pricing Calculator","Estimate pricing from a simple configurable quantity.","Lightweight premium pricing estimator without an external dependency.",{...baseDefaults,heading:"Estimate your plan in seconds.",text:"Adjust the quantity to preview a simple estimate. Replace the placeholder rate with your real pricing before publishing.",unit_label:"Seats",base_price:"49",currency:"$",minimum_units:"1",maximum_units:"20",primary_label:"Get a custom quote",primary_url:"#",note:"Estimate only. Final pricing may vary based on scope and requirements."});

export const PricingCreditPremiumSchema=shared("pricing_credit_premium","Credit Pricing","Sell usage credits in clear premium packs.","Pro-only credit-pack pricing for AI, usage, tokens, or prepaid service units.",{...baseDefaults,eyebrow:"FLEXIBLE CREDITS",heading:"Buy credits when you need them.",text:"Simple prepaid packs for teams that prefer flexible usage without changing plans.",pack_one_name:"Starter Pack",pack_one_credits:"1,000 credits",pack_one_price:"$19",pack_one_description:"A lightweight top-up for occasional usage.",pack_one_button_label:"Choose Starter",pack_one_button_url:"#",pack_two_name:"Growth Pack",pack_two_credits:"5,000 credits",pack_two_price:"$79",pack_two_description:"More room for regular campaigns and production work.",pack_two_button_label:"Choose Growth",pack_two_button_url:"#",pack_two_badge:"POPULAR",pack_three_name:"Scale Pack",pack_three_credits:"15,000 credits",pack_three_price:"$199",pack_three_description:"A larger prepaid pool for high-volume teams.",pack_three_button_label:"Choose Scale",pack_three_button_url:"#",note:"Replace placeholder pack sizes and prices with your actual credit policy before publishing."});
export const PricingAgencyPremiumSchema=shared("pricing_agency_premium","Agency Pricing","Present scalable packages for agencies and multi-client teams.","Pro-only agency pricing with client/site capacity, collaboration, and support positioning.",{...baseDefaults,eyebrow:"BUILT FOR AGENCIES",heading:"Pricing that grows with your client roster.",text:"Choose a package around the number of client websites, collaborators, and support your agency needs.",plan_one_name:"Studio",plan_one_price:"$99",plan_one_period:"/month",plan_one_capacity:"Up to 5 client sites",plan_one_description:"For small studios managing a focused client roster.",plan_one_button_label:"Choose Studio",plan_one_button_url:"#",plan_two_name:"Agency",plan_two_price:"$199",plan_two_period:"/month",plan_two_capacity:"Up to 20 client sites",plan_two_description:"For growing agencies that need more capacity and collaboration.",plan_two_button_label:"Choose Agency",plan_two_button_url:"#",plan_two_badge:"MOST POPULAR",plan_three_name:"Partner",plan_three_price:"Custom",plan_three_period:"",plan_three_capacity:"Custom client capacity",plan_three_description:"For larger teams that need a tailored rollout and support model.",plan_three_button_label:"Talk to sales",plan_three_button_url:"#",feature_one:"Team collaboration",feature_two:"Client workspaces",feature_three:"Priority support",note:"Use only real limits, prices, and service levels that your agency actually offers."});
export const PricingFeatureMatrixPremiumSchema=shared("pricing_feature_matrix_premium","Feature Matrix","Show detailed capability differences between plans.","Pro-only grouped feature matrix for detailed package evaluation.",{...baseDefaults,eyebrow:"FEATURE MATRIX",heading:"Everything included, clearly mapped.",text:"Give buyers a detailed view of the capabilities available at each level.",plan_one_name:"Starter",plan_two_name:"Growth",plan_three_name:"Pro",group_one:"Core",feature_one:"Projects",one_one:"3",two_one:"Unlimited",three_one:"Unlimited",feature_two:"Team members",one_two:"1",two_two:"5",three_two:"Unlimited",group_two:"Workflow",feature_three:"Automations",one_three:"Basic",two_three:"Advanced",three_three:"Advanced",feature_four:"Approvals",one_four:"—",two_four:"Included",three_four:"Included",group_three:"Support",feature_five:"Support",one_five:"Standard",two_five:"Priority",three_five:"Dedicated",feature_six:"Reporting",one_six:"Basic",two_six:"Advanced",three_six:"Custom exports",note:"Replace placeholder capabilities with your actual plan inclusions before publishing."});

function Shell({block,onUpdate,globalTheme,children}){const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});return <section className={`px-6 py-16 sm:px-10 lg:px-14 lg:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><EditableText value={block.eyebrow} className={`text-xs font-bold uppercase tracking-[.28em] ${theme.sub}`} onSave={save("eyebrow")}/><EditableText value={block.heading} className={`mt-5 block text-4xl font-semibold tracking-[-.045em] sm:text-5xl lg:text-6xl ${theme.text}`} onSave={save("heading")}/><EditableText value={block.text} isTextArea className={`mt-5 block max-w-2xl text-base leading-7 ${theme.sub}`} onSave={save("text")}/></div>{children(theme,save)}</div></section>}

function PlanCard({data,prefix,theme,save,featured=false,showYearly=false}){const primary=colorFamilies.emerald;return <article className={`rounded-[2rem] border p-7 ${theme.border} ${theme.card} ${featured?"ring-2 ring-current":""}`}>{featured&&<EditableText value={data.plan_two_badge} className="mb-5 inline-flex rounded-full bg-slate-900 px-3 py-1 text-[10px] font-black tracking-[.16em] text-white" onSave={save("plan_two_badge")}/>}<EditableText value={data[`${prefix}_name`]} className={`block text-xl font-semibold ${theme.text}`} onSave={save(`${prefix}_name`)}/><div className="mt-4 flex items-end gap-2"><EditableText value={showYearly?data[`${prefix}_yearly`]:data[`${prefix}_monthly`]} className={`text-4xl font-semibold ${theme.text}`} onSave={save(showYearly?`${prefix}_yearly`:`${prefix}_monthly`)}/><span className={`mb-1 text-xs ${theme.sub}`}>{showYearly?"/year":"/month"}</span></div><EditableText value={data[`${prefix}_description`]} isTextArea className={`mt-4 block text-sm leading-6 ${theme.sub}`} onSave={save(`${prefix}_description`)}/><EditableButton label={data[`${prefix}_button_label`]} url={data[`${prefix}_button_url`]} className="mt-6 inline-flex min-h-[46px] w-full items-center justify-center rounded-full bg-slate-900 px-5 text-sm font-bold text-white" onSave={(label,url)=>save(`${prefix}_button_label`)(label)||onUpdate}/></article>}

export function PricingComparisonPremiumBlock({block,onUpdate,globalTheme}){const data={...PricingComparisonPremiumSchema.defaults,...block};const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});const rows=["one","two","three","four","five","six"];return <Shell block={data} onUpdate={onUpdate} globalTheme={globalTheme}>{()=> <div className={`mt-12 overflow-hidden rounded-[2rem] border ${theme.border}`}><div className="grid lg:grid-cols-4"><div className={`hidden p-6 lg:block ${theme.card}`}>Compare plans</div>{[1,2,3].map((i)=><div key={i} className={`p-6 ${theme.card}`}><EditableText value={data[`plan_${["one","two","three"][i-1]}_name`]} className={`text-lg font-semibold ${theme.text}`} onSave={save(`plan_${["one","two","three"][i-1]}_name`)}/></div>)}{rows.map((r,idx)=><div className="contents" key={r}><div className={`border-t p-5 text-sm font-semibold ${theme.border} ${theme.card} ${theme.text}`}><EditableText value={data[`feature_${r}`]} onSave={save(`feature_${r}`)}/></div>{["one","two","three"].map(p=><div key={p} className={`border-t p-5 text-sm ${theme.border} ${theme.card} ${theme.text}`}><EditableText value={data[`${p}_${r}`]} onSave={save(`${p}_${r}`)}/></div>)}</div>)}</div><EditableText value={data.footnote} isTextArea className={`block p-5 text-xs ${theme.sub}`} onSave={save("footnote")}/></div>}</Shell>}

export function PricingTogglePremiumBlock({block,onUpdate,globalTheme}){const data={...PricingTogglePremiumSchema.defaults,...block};const [yearly,setYearly]=useState(false);const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});return <Shell block={data} onUpdate={onUpdate} globalTheme={globalTheme}>{()=> <><div className={`mt-8 inline-flex rounded-full border p-1 ${theme.border} ${theme.card}`}><button type="button" onClick={()=>setYearly(false)} className={`rounded-full px-5 py-2 text-sm font-semibold ${!yearly?"bg-slate-900 text-white":theme.text}`}>{data.monthly_label}</button><button type="button" onClick={()=>setYearly(true)} className={`rounded-full px-5 py-2 text-sm font-semibold ${yearly?"bg-slate-900 text-white":theme.text}`}>{data.yearly_label}</button></div><div className="mt-8 grid gap-5 lg:grid-cols-3">{["plan_one","plan_two","plan_three"].map((p,i)=><article key={p} className={`rounded-[2rem] border p-7 ${theme.border} ${theme.card}`}><EditableText value={data[`${p}_name`]} className={`text-xl font-semibold ${theme.text}`} onSave={save(`${p}_name`)}/><div className={`mt-4 text-4xl font-semibold ${theme.text}`}>{yearly?data[`${p}_yearly`]:data[`${p}_monthly`]}<span className={`ml-2 text-xs font-normal ${theme.sub}`}>{yearly?"/year":"/month"}</span></div><EditableText value={data[`${p}_description`]} isTextArea className={`mt-4 block text-sm leading-6 ${theme.sub}`} onSave={save(`${p}_description`)}/><EditableButton label={data[`${p}_button_label`]} url={data[`${p}_button_url`]} className="mt-6 inline-flex min-h-[46px] w-full items-center justify-center rounded-full bg-slate-900 px-5 text-sm font-bold text-white" onSave={(label,url)=>onUpdate({[`${p}_button_label`]:label,[`${p}_button_url`]:url})}/></article>)}</div><EditableText value={data.yearly_note} className={`mt-5 block text-sm ${theme.sub}`} onSave={save("yearly_note")}/></>}</Shell>}

export function PricingEnterprisePremiumBlock({block,onUpdate,globalTheme}){const data={...PricingEnterprisePremiumSchema.defaults,...block};const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});return <Shell block={data} onUpdate={onUpdate} globalTheme={globalTheme}>{()=> <div className="mt-12 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className={`rounded-[2rem] border p-8 ${theme.border} ${theme.card}`}><EditableText value={data.price_label} className={`text-xs font-bold uppercase tracking-[.24em] ${theme.sub}`} onSave={save("price_label")}/><EditableText value={data.price_text} className={`mt-4 block text-5xl font-semibold ${theme.text}`} onSave={save("price_text")}/><div className="mt-8 flex flex-wrap gap-3"><EditableButton label={data.primary_label} url={data.primary_url} className="rounded-full bg-slate-900 px-6 py-3 text-sm font-bold text-white" onSave={(label,url)=>onUpdate({primary_label:label,primary_url:url})}/><EditableButton label={data.secondary_label} url={data.secondary_url} className={`rounded-full border px-6 py-3 text-sm font-bold ${theme.border} ${theme.text}`} onSave={(label,url)=>onUpdate({secondary_label:label,secondary_url:url})}/></div></div><div className="grid gap-3">{[1,2,3,4].map((n)=><div key={n} className={`rounded-2xl border p-5 ${theme.border} ${theme.card}`}><EditableText value={data[`point_${["one","two","three","four"][n-1]}`]} className={`font-semibold ${theme.text}`} onSave={save(`point_${["one","two","three","four"][n-1]}`)}/></div>)}<EditableText value={data.note} isTextArea className={`mt-2 block text-xs leading-5 ${theme.sub}`} onSave={save("note")}/></div></div>}</Shell>}

export function PricingCalculatorPremiumBlock({block,onUpdate,globalTheme}){const data={...PricingCalculatorPremiumSchema.defaults,...block};const min=Number(data.minimum_units)||1,max=Number(data.maximum_units)||20;const [units,setUnits]=useState(min);const rate=Number(data.base_price)||0;const total=useMemo(()=>units*rate,[units,rate]);const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});return <Shell block={data} onUpdate={onUpdate} globalTheme={globalTheme}>{()=> <div className={`mt-12 grid gap-8 rounded-[2rem] border p-7 lg:grid-cols-2 lg:p-10 ${theme.border} ${theme.card}`}><div><EditableText value={data.unit_label} className={`font-semibold ${theme.text}`} onSave={save("unit_label")}/><div className="mt-5 flex items-center gap-4"><button type="button" onClick={()=>setUnits(Math.max(min,units-1))} className={`h-11 w-11 rounded-full border ${theme.border} ${theme.text}`}>−</button><div className={`min-w-16 text-center text-3xl font-semibold ${theme.text}`}>{units}</div><button type="button" onClick={()=>setUnits(Math.min(max,units+1))} className={`h-11 w-11 rounded-full border ${theme.border} ${theme.text}`}>+</button></div><p className={`mt-4 text-sm ${theme.sub}`}>Rate: {data.currency}{data.base_price} per {data.unit_label.toLowerCase()}</p></div><div><div className={`text-xs font-bold uppercase tracking-[.22em] ${theme.sub}`}>Estimated total</div><div className={`mt-3 text-5xl font-semibold ${theme.text}`}>{data.currency}{total.toLocaleString()}</div><EditableButton label={data.primary_label} url={data.primary_url} className="mt-6 inline-flex rounded-full bg-slate-900 px-6 py-3 text-sm font-bold text-white" onSave={(label,url)=>onUpdate({primary_label:label,primary_url:url})}/><EditableText value={data.note} isTextArea className={`mt-4 block text-xs leading-5 ${theme.sub}`} onSave={save("note")}/></div></div>}</Shell>}


export function PricingCreditPremiumBlock({block,onUpdate,globalTheme}){const data={...PricingCreditPremiumSchema.defaults,...block};const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});return <Shell block={data} onUpdate={onUpdate} globalTheme={globalTheme}>{()=> <><div className="mt-12 grid gap-5 lg:grid-cols-3">{["one","two","three"].map((i,idx)=><article key={i} className={`relative rounded-[2rem] border p-7 ${theme.border} ${theme.card} ${idx===1?"ring-2 ring-current":""}`}>{idx===1&&<EditableText value={data.pack_two_badge} className="mb-5 inline-flex rounded-full bg-slate-900 px-3 py-1 text-[10px] font-black tracking-[.16em] text-white" onSave={save("pack_two_badge")}/>}<EditableText value={data[`pack_${i}_name`]} className={`block text-xl font-semibold ${theme.text}`} onSave={save(`pack_${i}_name`)}/><EditableText value={data[`pack_${i}_credits`]} className={`mt-5 block text-3xl font-semibold ${theme.text}`} onSave={save(`pack_${i}_credits`)}/><EditableText value={data[`pack_${i}_price`]} className={`mt-2 block text-lg font-semibold ${theme.sub}`} onSave={save(`pack_${i}_price`)}/><EditableText value={data[`pack_${i}_description`]} isTextArea className={`mt-4 block text-sm leading-6 ${theme.sub}`} onSave={save(`pack_${i}_description`)}/><EditableButton label={data[`pack_${i}_button_label`]} url={data[`pack_${i}_button_url`]} className="mt-6 inline-flex min-h-[46px] w-full items-center justify-center rounded-full bg-slate-900 px-5 text-sm font-bold text-white" onSave={(label,url)=>onUpdate({[`pack_${i}_button_label`]:label,[`pack_${i}_button_url`]:url})}/></article>)}</div><EditableText value={data.note} isTextArea className={`mt-5 block text-xs ${theme.sub}`} onSave={save("note")}/></>}</Shell>}

export function PricingAgencyPremiumBlock({block,onUpdate,globalTheme}){const data={...PricingAgencyPremiumSchema.defaults,...block};const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});return <Shell block={data} onUpdate={onUpdate} globalTheme={globalTheme}>{()=> <><div className="mt-12 grid gap-5 lg:grid-cols-3">{["one","two","three"].map((i,idx)=><article key={i} className={`rounded-[2rem] border p-7 ${theme.border} ${theme.card} ${idx===1?"ring-2 ring-current":""}`}>{idx===1&&<EditableText value={data.plan_two_badge} className="mb-5 inline-flex rounded-full bg-slate-900 px-3 py-1 text-[10px] font-black tracking-[.16em] text-white" onSave={save("plan_two_badge")}/>}<EditableText value={data[`plan_${i}_name`]} className={`block text-xl font-semibold ${theme.text}`} onSave={save(`plan_${i}_name`)}/><div className="mt-4 flex items-end gap-1"><EditableText value={data[`plan_${i}_price`]} className={`text-4xl font-semibold ${theme.text}`} onSave={save(`plan_${i}_price`)}/><EditableText value={data[`plan_${i}_period`]} className={`mb-1 text-xs ${theme.sub}`} onSave={save(`plan_${i}_period`)}/></div><EditableText value={data[`plan_${i}_capacity`]} className={`mt-4 block text-sm font-semibold ${theme.text}`} onSave={save(`plan_${i}_capacity`)}/><EditableText value={data[`plan_${i}_description`]} isTextArea className={`mt-3 block text-sm leading-6 ${theme.sub}`} onSave={save(`plan_${i}_description`)}/><div className="mt-5 space-y-2">{["one","two","three"].map(f=><div key={f} className={`text-sm ${theme.sub}`}>✓ <EditableText value={data[`feature_${f}`]} onSave={save(`feature_${f}`)}/></div>)}</div><EditableButton label={data[`plan_${i}_button_label`]} url={data[`plan_${i}_button_url`]} className="mt-6 inline-flex min-h-[46px] w-full items-center justify-center rounded-full bg-slate-900 px-5 text-sm font-bold text-white" onSave={(label,url)=>onUpdate({[`plan_${i}_button_label`]:label,[`plan_${i}_button_url`]:url})}/></article>)}</div><EditableText value={data.note} isTextArea className={`mt-5 block text-xs ${theme.sub}`} onSave={save("note")}/></>}</Shell>}

export function PricingFeatureMatrixPremiumBlock({block,onUpdate,globalTheme}){const data={...PricingFeatureMatrixPremiumSchema.defaults,...block};const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const save=(k)=>(v)=>onUpdate({[k]:v});const groups=[{label:"group_one",rows:["one","two"]},{label:"group_two",rows:["three","four"]},{label:"group_three",rows:["five","six"]}];return <Shell block={data} onUpdate={onUpdate} globalTheme={globalTheme}>{()=> <div className={`mt-12 overflow-hidden rounded-[2rem] border ${theme.border}`}><div className="grid grid-cols-[1.25fr_repeat(3,minmax(0,1fr))]"><div className={`p-5 ${theme.card}`}/>{["one","two","three"].map(i=><div key={i} className={`p-5 text-sm font-bold ${theme.card} ${theme.text}`}><EditableText value={data[`plan_${i}_name`]} onSave={save(`plan_${i}_name`)}/></div>)}{groups.map(g=><div className="contents" key={g.label}><div className={`col-span-4 border-t px-5 py-3 text-xs font-black uppercase tracking-[.18em] ${theme.border} ${theme.card} ${theme.sub}`}><EditableText value={data[g.label]} onSave={save(g.label)}/></div>{g.rows.map(r=><div className="contents" key={r}><div className={`border-t p-5 text-sm font-semibold ${theme.border} ${theme.card} ${theme.text}`}><EditableText value={data[`feature_${r}`]} onSave={save(`feature_${r}`)}/></div>{["one","two","three"].map(p=><div key={p} className={`border-t p-5 text-sm ${theme.border} ${theme.card} ${theme.text}`}><EditableText value={data[`${p}_${r}`]} onSave={save(`${p}_${r}`)}/></div>)}</div>)}</div>)}</div><EditableText value={data.note} isTextArea className={`block p-5 text-xs ${theme.sub}`} onSave={save("note")}/></div>}</Shell>}
