import { usePage } from "@inertiajs/react";
import { EditableImage } from "../Shared/EditableImage";
import { EditableText } from "../Shared/EditableText";
import { RepeatableControls, RepeatableRemoveButton, cloneLast, removeAt } from "../Shared/RepeatableControls";
import { getEffectiveTheme } from "../../../../theme/Theme";

const avatars=[1,2,3,4].map(n=>`/storage/cms-images/avatars/avatar-${n}.jpg`);
const members=[
 {name:"Alex Morgan",role:"Founder & Director",bio:"Guides the team with a clear, client-first approach.",image_url:avatars[0],level:"Leadership"},
 {name:"Jordan Lee",role:"Client Experience Lead",bio:"Keeps projects organized, responsive, and easy to navigate.",image_url:avatars[1],level:"Leadership"},
 {name:"Taylor Brooks",role:"Creative Lead",bio:"Turns ideas into polished, useful digital experiences.",image_url:avatars[2],level:"Team"},
 {name:"Casey Rivera",role:"Operations Manager",bio:"Coordinates quality and momentum from start to finish.",image_url:avatars[3],level:"Team"},
];
const shared=(type,title,purpose,description,extra={})=>({type,title,category:"Team",purpose,description,tags:["team","people","leadership","premium","pro"],defaults:{eyebrow:"MEET THE TEAM",heading:"People who make the work happen.",text:"A focused team built around clear thinking, dependable delivery, and thoughtful service.",members,...extra}});
export const TeamCardsPremiumSchema=shared("team_cards_premium","Team Cards","Create a premium editorial team card grid.","Large portrait cards with stronger hierarchy, role details, and polished editorial spacing.");
export const TeamTimelinePremiumSchema=shared("team_timeline_premium","Team Timeline","Create a premium people timeline.","A chronological people story that connects team members to milestones or stages.",{timeline_label:"How the team grew"});
export const TeamOrgChartPremiumSchema=shared("team_org_chart_premium","Organization Chart","Create a premium organization chart.","A lightweight responsive organization hierarchy using supplied people and role levels only.",{chart_label:"How we work together"});
export const TeamLeadershipPremiumSchema=shared("team_leadership_premium","Leadership","Create a premium leadership section.","A focused leadership spotlight with larger profiles and concise biographies.",{lead_label:"Leadership"});
export const TeamCulturePremiumSchema={type:"team_culture_premium",title:"Culture",category:"Team",purpose:"Create a premium team culture section.",description:"Editorial culture principles with four editable values and concise supporting copy.",tags:["team","culture","values","premium","pro"],defaults:{eyebrow:"OUR CULTURE",heading:"How we work together.",text:"A practical set of principles that shape how the team collaborates, decides, and delivers.",culture_label:"What guides us",values:[{title:"Clear communication",text:"Share context early and keep decisions understandable."},{title:"Thoughtful craft",text:"Care about the details that improve the final experience."},{title:"Shared ownership",text:"Take responsibility for outcomes, not just assigned tasks."},{title:"Keep improving",text:"Learn from feedback and refine the way the team works."}]}};
export const TeamOpenPositionsPremiumSchema={type:"team_open_positions_premium",title:"Open Positions",category:"Team",purpose:"Create a premium open positions section.",description:"A polished careers section with four editable roles and a clear application CTA.",tags:["team","careers","jobs","hiring","premium","pro"],defaults:{eyebrow:"JOIN THE TEAM",heading:"Open roles for people who care about the work.",text:"Explore current opportunities and find the role that best matches your strengths.",positions_label:"Current openings",primary_label:"View all opportunities",primary_url:"#",positions:[{title:"Product Designer",meta:"Design · Full-time",location:"Flexible / Hybrid",summary:"Shape useful product experiences from early concepts through polished delivery."},{title:"Frontend Developer",meta:"Engineering · Full-time",location:"Flexible / Hybrid",summary:"Build responsive interfaces with strong attention to accessibility and performance."},{title:"Client Success Lead",meta:"Client Experience · Full-time",location:"Flexible / Hybrid",summary:"Help customers move from questions to confident outcomes with clear guidance."},{title:"Content Strategist",meta:"Marketing · Contract",location:"Remote",summary:"Turn complex ideas into concise, useful content across product and campaign touchpoints."}]}};

function useData({block,globalTheme}){const requestedTheme=block.theme&&block.theme!=="auto"?block.theme:block.resolvedTheme;return {theme:getEffectiveTheme(requestedTheme,globalTheme),data:{...members,...block,members:Array.isArray(block.members)&&block.members.length?block.members:members}}}
function Header({data,theme,onUpdate}){return <div className="mb-10 max-w-3xl"><EditableText value={data.eyebrow} onSave={eyebrow=>onUpdate({eyebrow})} className={`text-xs font-bold uppercase tracking-[.24em] ${theme.sub}`}/><EditableText value={data.heading} onSave={heading=>onUpdate({heading})} className={`mt-4 block text-4xl font-semibold tracking-[-.04em] sm:text-5xl ${theme.text}`}/><EditableText value={data.text} isTextArea onSave={text=>onUpdate({text})} className={`mt-4 block max-w-2xl leading-7 ${theme.sub}`}/></div>}
function Person({member,index,theme,websiteId,blockIndex,onUpdate,large=false}){const save=(key,value)=>onUpdate({members:onUpdate.members.map((m,i)=>i===index?{...m,[key]:value}:m)});return <article className={`group relative overflow-hidden rounded-3xl border ${theme.border} ${theme.card}`}><EditableImage websiteId={websiteId} blockIndex={blockIndex} src={member.image_url||avatars[index%4]} className={`${large?'aspect-[5/4]':'aspect-[4/3]'} w-full`} onSave={v=>save('image_url',v)}/><div className={large?'p-7':'p-5'}><EditableText value={member.name} onSave={v=>save('name',v)} className={`${large?'text-2xl':'text-lg'} font-semibold ${theme.text}`}/><EditableText value={member.role} onSave={v=>save('role',v)} className={`mt-1 block text-sm font-medium ${theme.sub}`}/><EditableText value={member.bio} isTextArea onSave={v=>save('bio',v)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/></div></article>}
function memberUpdater(data,onUpdate){const fn=(patch)=>onUpdate(patch);fn.members=data.members;return fn}

export function TeamCardsPremiumBlock({block,blockIndex,onUpdate,globalTheme}){const {website}=usePage().props;const {theme,data}=useData({block,globalTheme});const updater=memberUpdater(data,onUpdate);const items=data.members.slice(0,8);return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={data} theme={theme} onUpdate={onUpdate}/><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{items.map((m,i)=><div key={i} className="group relative"><Person member={m} index={i} theme={theme} websiteId={website?.id} blockIndex={blockIndex} onUpdate={updater}/><RepeatableRemoveButton hoverScope="card" onRemove={()=>onUpdate({members:removeAt(items,i,1)})} disabled={items.length<=1} label="Remove member" overlay/></div>)}</div><RepeatableControls onAdd={()=>items.length<8&&onUpdate({members:cloneLast(items,members[0])})} canAdd={items.length<8} addLabel="Add member" showRemove={false}/></div></section>}

export function TeamTimelinePremiumBlock({block,blockIndex,onUpdate,globalTheme}){const {theme,data}=useData({block,globalTheme});const updater=memberUpdater(data,onUpdate);const items=data.members.slice(0,4);return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-6xl"><Header data={data} theme={theme} onUpdate={onUpdate}/><EditableText value={data.timeline_label||"How the team grew"} onSave={timeline_label=>onUpdate({timeline_label})} className={`mb-6 block text-sm font-semibold ${theme.text}`}/><div className={`border-l ${theme.border}`}>{items.map((m,i)=><div key={i} className="group relative grid gap-4 py-6 pl-8 md:grid-cols-[80px_1fr_2fr_auto] md:items-start"><span className={`absolute -left-1.5 top-8 h-3 w-3 rounded-full ${theme.text} bg-current`}/><span className={`text-xs font-bold ${theme.sub}`}>{String(i+1).padStart(2,'0')}</span><EditableText value={m.name} onSave={v=>updater({members:items.map((x,j)=>j===i?{...x,name:v}:x)})} className={`font-semibold ${theme.text}`}/><div><EditableText value={m.role} onSave={v=>updater({members:items.map((x,j)=>j===i?{...x,role:v}:x)})} className={`text-sm font-medium ${theme.text}`}/><EditableText value={m.bio} isTextArea onSave={v=>updater({members:items.map((x,j)=>j===i?{...x,bio:v}:x)})} className={`mt-2 block text-sm leading-6 ${theme.sub}`}/></div><RepeatableRemoveButton hoverScope="card" onRemove={()=>onUpdate({members:removeAt(items,i,1)})} disabled={items.length<=1} label="Remove member" overlay/></div>)}</div><RepeatableControls onAdd={()=>items.length<4&&onUpdate({members:cloneLast(items,members[0])})} canAdd={items.length<4} addLabel="Add timeline member" showRemove={false}/></div></section>}

export function TeamOrgChartPremiumBlock({block,blockIndex,onUpdate,globalTheme}){const {website}=usePage().props;const {theme,data}=useData({block,globalTheme});const updater=memberUpdater(data,onUpdate);const first=data.members[0],rest=data.members.slice(1,4);return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-6xl"><Header data={data} theme={theme} onUpdate={onUpdate}/><EditableText value={data.chart_label||"How we work together"} onSave={chart_label=>onUpdate({chart_label})} className={`mb-8 block text-center text-sm font-semibold ${theme.sub}`}/>{first&&<div className="mx-auto max-w-sm"><Person member={first} index={0} theme={theme} websiteId={website?.id} blockIndex={blockIndex} onUpdate={updater}/></div>}<div className={`mx-auto h-10 w-px ${theme.border} border-l`}/><div className="grid gap-5 md:grid-cols-3">{rest.map((m,i)=><Person key={i} member={m} index={i+1} theme={theme} websiteId={website?.id} blockIndex={blockIndex} onUpdate={updater}/>)}</div></div></section>}

export function TeamLeadershipPremiumBlock({block,blockIndex,onUpdate,globalTheme}){const {website}=usePage().props;const {theme,data}=useData({block,globalTheme});const updater=memberUpdater(data,onUpdate);return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={data} theme={theme} onUpdate={onUpdate}/><div className="grid gap-7 lg:grid-cols-2">{data.members.slice(0,2).map((m,i)=><Person key={i} member={m} index={i} theme={theme} websiteId={website?.id} blockIndex={blockIndex} onUpdate={updater} large/>)}</div><div className={`mt-8 grid gap-4 border-t pt-7 sm:grid-cols-2 ${theme.border}`}>{data.members.slice(2,4).map((m,i)=><div key={i} className="group relative flex items-center gap-4"><img src={m.image_url||avatars[(i+2)%4]} alt="" className="h-14 w-14 rounded-2xl object-cover"/><div><EditableText value={m.name} onSave={v=>updater({members:data.members.map((x,j)=>j===i+2?{...x,name:v}:x)})} className={`font-semibold ${theme.text}`}/><EditableText value={m.role} onSave={v=>updater({members:data.members.map((x,j)=>j===i+2?{...x,role:v}:x)})} className={`block text-sm ${theme.sub}`}/></div></div>)}</div></div></section>}


export function TeamCulturePremiumBlock({block,onUpdate,globalTheme}){const requestedTheme=block.theme&&block.theme!=="auto"?block.theme:block.resolvedTheme;const theme=getEffectiveTheme(requestedTheme,globalTheme);const values=Array.isArray(block.values)&&block.values.length?block.values:TeamCulturePremiumSchema.defaults.values;const save=(i,key,value)=>onUpdate({values:values.map((v,j)=>j===i?{...v,[key]:value}:v)});return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><Header data={{...TeamCulturePremiumSchema.defaults,...block}} theme={theme} onUpdate={onUpdate}/><div className="mb-7 flex items-end justify-between gap-5"><EditableText value={block.culture_label||"What guides us"} onSave={culture_label=>onUpdate({culture_label})} className={`text-sm font-semibold ${theme.text}`}/><span className={`text-xs uppercase tracking-[.2em] ${theme.sub}`}>{String(values.length).padStart(2,'0')} principles</span></div><div className="grid gap-px overflow-hidden rounded-3xl border sm:grid-cols-2 lg:grid-cols-4"><>{values.slice(0,8).map((v,i)=><article key={i} className={`group relative min-h-52 p-6 ${theme.card}`}><span className={`text-xs font-bold ${theme.sub}`}>{String(i+1).padStart(2,'0')}</span><EditableText value={v.title} onSave={x=>save(i,'title',x)} className={`mt-10 block text-xl font-semibold ${theme.text}`}/><EditableText value={v.text} isTextArea onSave={x=>save(i,'text',x)} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/><RepeatableRemoveButton hoverScope="card" onRemove={()=>onUpdate({values:removeAt(values,i,1)})} disabled={values.length<=1}/></article>)}</></div><RepeatableControls onAdd={()=>values.length<8&&onUpdate({values:cloneLast(values)})} onRemove={()=>onUpdate({values:removeAt(values,values.length-1,1)})} canRemove={values.length>1} addLabel="Add principle" removeLabel="Remove last"/></div></section>}

export function TeamOpenPositionsPremiumBlock({block,onUpdate,globalTheme}){const requestedTheme=block.theme&&block.theme!=="auto"?block.theme:block.resolvedTheme;const theme=getEffectiveTheme(requestedTheme,globalTheme);const data={...TeamOpenPositionsPremiumSchema.defaults,...block};const positions=Array.isArray(block.positions)&&block.positions.length?block.positions:TeamOpenPositionsPremiumSchema.defaults.positions;const save=(i,key,value)=>onUpdate({positions:positions.map((v,j)=>j===i?{...v,[key]:value}:v)});return <section className={`group/repeatable-section px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-6xl"><Header data={data} theme={theme} onUpdate={onUpdate}/><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><EditableText value={data.positions_label} onSave={positions_label=>onUpdate({positions_label})} className={`text-sm font-semibold ${theme.text}`}/><a href={data.primary_url||"#"} className={`rounded-full border px-4 py-2 text-sm font-semibold ${theme.border} ${theme.text}`}><EditableText value={data.primary_label} onSave={primary_label=>onUpdate({primary_label})}/></a></div><div className={`divide-y rounded-3xl border ${theme.border} ${theme.card}`}>{positions.slice(0,8).map((job,i)=><article key={i} className="group relative grid gap-4 p-6 md:grid-cols-[1.2fr_.8fr_2fr_auto] md:items-center"><div><EditableText value={job.title} onSave={x=>save(i,'title',x)} className={`text-lg font-semibold ${theme.text}`}/><EditableText value={job.meta} onSave={x=>save(i,'meta',x)} className={`mt-1 block text-sm ${theme.sub}`}/></div><EditableText value={job.location} onSave={x=>save(i,'location',x)} className={`text-sm font-medium ${theme.text}`}/><EditableText value={job.summary} isTextArea onSave={x=>save(i,'summary',x)} className={`text-sm leading-6 ${theme.sub}`}/><div><span className={`text-sm font-semibold ${theme.text}`}>Explore →</span><RepeatableRemoveButton hoverScope="card" onRemove={()=>onUpdate({positions:removeAt(positions,i,1)})} disabled={positions.length<=1}/></div></article>)}</div><RepeatableControls onAdd={()=>positions.length<8&&onUpdate({positions:cloneLast(positions)})} onRemove={()=>onUpdate({positions:removeAt(positions,positions.length-1,1)})} canRemove={positions.length>1} addLabel="Add position" removeLabel="Remove last"/></div></section>}
