import { EditableText } from "../Shared/EditableText";
import { RepeatableControls, RepeatableRemoveButton, cloneLast, removeAt } from "../Shared/RepeatableControls";
import { getEffectiveTheme } from "../../../../theme/Theme";

const base=[{key:"eyebrow",type:"text",label:"Eyebrow"},{key:"heading",type:"text",label:"Heading"},{key:"text",type:"textarea",label:"Text"}];
const item=[{key:"title",type:"text",label:"Title"},{key:"text",type:"textarea",label:"Text"}];
const defs={
 agency_dashboard_preview_premium:{title:"Agency Dashboard Preview",eyebrow:"AGENCY OVERVIEW",heading:"One clear view across the work you manage.",text:"Present real supplied agency metrics, workflows, or website status without fabricated numbers.",items:[{title:"Websites",text:"Show a real supplied site count or use an editable placeholder."},{title:"Activity",text:"Summarise a real workflow or management signal."},{title:"Reporting",text:"Describe an actually available reporting capability."}]},
 agency_client_portal_premium:{title:"Client Portal",eyebrow:"CLIENT EXPERIENCE",heading:"Give clients a polished place to stay aligned.",text:"Show only client portal capabilities the agency or product genuinely provides.",items:[{title:"Approvals",text:"Describe a real approval or feedback workflow."},{title:"Updates",text:"Describe how clients actually receive project or website updates."},{title:"Assets",text:"Describe real files, reports, or resources clients can access."}]},
 agency_white_label_showcase_premium:{title:"White Label Showcase",eyebrow:"YOUR BRAND, FRONT AND CENTRE",heading:"Present the experience under the agency brand.",text:"Show only white-label controls and branding options that are genuinely available.",items:[{title:"Branding",text:"Describe real logo, colour, domain, or identity controls."},{title:"Client-facing",text:"Describe real branded client experiences."},{title:"Handoff",text:"Describe a real delivery or ownership workflow."}]},
 agency_website_management_premium:{title:"Website Management",eyebrow:"MANAGE AT SCALE",heading:"Keep multiple websites organised without losing the details.",text:"Show real website management workflows, controls, and visibility available to the agency.",items:[{title:"Portfolio view",text:"Describe how managed websites are actually organised."},{title:"Updates",text:"Describe a real publishing, maintenance, or update workflow."},{title:"Oversight",text:"Describe real status, access, or reporting controls."}]},
 agency_maintenance_plans_premium:{title:"Maintenance Plans",eyebrow:"ONGOING CARE",heading:"Keep websites healthy after launch.",text:"Present real maintenance scope, cadence, and inclusions without invented guarantees or response times.",items:[{title:"Routine care",text:"Describe a real recurring maintenance task or service."},{title:"Updates",text:"Describe real update, patching, or content support included."},{title:"Reporting",text:"Describe real maintenance reporting or review provided."}]},
 agency_support_plans_premium:{title:"Support Plans",eyebrow:"SUPPORT THAT FITS",heading:"Make support options easy to understand.",text:"Show only real support channels, coverage, and plan differences supplied by the agency.",items:[{title:"Channels",text:"Describe actual support channels offered."},{title:"Coverage",text:"Describe real support scope or availability without invented SLA claims."},{title:"Escalation",text:"Describe a real escalation or handoff path."}]},
 agency_workflow_premium:{title:"Agency Workflow",eyebrow:"HOW WE WORK",heading:"Turn a complex project into a clear sequence.",text:"Show the agency's real delivery workflow without fabricated timing or guarantees.",items:[{title:"Discover",text:"Describe a real discovery, brief, or planning stage."},{title:"Create",text:"Describe a real design, build, or review stage."},{title:"Deliver",text:"Describe a real launch, handoff, or ongoing-support stage."}]},
 agency_project_pipeline_premium:{title:"Project Pipeline",eyebrow:"PROJECT PIPELINE",heading:"Show how work moves from idea to delivery.",text:"Present real project stages or an editable process example without invented client status or deadlines.",items:[{title:"Planned",text:"Describe what belongs in the planning stage."},{title:"In progress",text:"Describe a real active-work stage without fake status data."},{title:"Ready",text:"Describe a real review, launch, or completion stage."}]},
 agency_client_reviews_premium:{title:"Client Reviews",eyebrow:"CLIENT FEEDBACK",heading:"Let verified client experiences speak for the work.",text:"Present only genuine supplied client feedback, with editable placeholders when real reviews are not available.",items:[{title:"Client name or role",text:"Add a verified client quote here, or keep this clearly editable as a placeholder."},{title:"Client name or role",text:"Add another verified client quote without inventing ratings or outcomes."},{title:"Client name or role",text:"Use supplied feedback only; avoid fabricated endorsements."}]},
 agency_website_reports_premium:{title:"Website Reports",eyebrow:"CLEAR REPORTING",heading:"Turn website activity into a client-friendly update.",text:"Show only reporting views, metrics, and insights the agency genuinely provides.",items:[{title:"Performance",text:"Describe real supplied website performance reporting or an editable report module."},{title:"Activity",text:"Describe real update, maintenance, publishing, or workflow reporting."},{title:"Next actions",text:"Describe real recommendations or follow-up items included in reporting."}]}
};
function schema(type){const d=defs[type];return {type,title:d.title,category:"Agency",purpose:d.text,description:d.text,tags:["agency","premium","pro"],defaults:d,fields:[...base,{key:"items",type:"repeater",label:"Items",fields:item},{key:"note",type:"textarea",label:"Note"}]};}
export const AgencyDashboardPreviewPremiumSchema=schema("agency_dashboard_preview_premium");
export const AgencyClientPortalPremiumSchema=schema("agency_client_portal_premium");
export const AgencyWhiteLabelShowcasePremiumSchema=schema("agency_white_label_showcase_premium");
export const AgencyWebsiteManagementPremiumSchema=schema("agency_website_management_premium");
export const AgencyMaintenancePlansPremiumSchema=schema("agency_maintenance_plans_premium");
export const AgencySupportPlansPremiumSchema=schema("agency_support_plans_premium");
export const AgencyWorkflowPremiumSchema=schema("agency_workflow_premium");
export const AgencyProjectPipelinePremiumSchema=schema("agency_project_pipeline_premium");
export const AgencyClientReviewsPremiumSchema=schema("agency_client_reviews_premium");
export const AgencyWebsiteReportsPremiumSchema=schema("agency_website_reports_premium");

function AgencyBlock({block,onUpdate,globalTheme,schema}){
 const theme=getEffectiveTheme(block.theme && block.theme !== "auto" ? block.theme : block.resolvedTheme,globalTheme); const d={...schema.defaults,...block}; const items=d.items||[];
 return <section className={`px-6 py-20 sm:py-24 ${theme.bg}`}><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><EditableText value={d.eyebrow} onSave={eyebrow=>onUpdate({eyebrow})} className={`text-xs font-bold uppercase tracking-[.24em] ${theme.sub}`}/><EditableText value={d.heading} onSave={heading=>onUpdate({heading})} className={`mt-4 block text-4xl font-black tracking-tight sm:text-5xl ${theme.text}`}/></div><EditableText value={d.text} isTextArea onSave={text=>onUpdate({text})} className={`block max-w-2xl leading-7 lg:justify-self-end ${theme.sub}`}/></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{items.slice(0,6).map((x,i)=><article key={i} className={`group relative overflow-hidden rounded-[2rem] border p-6 ${theme.border} ${theme.card}`}><div className={`absolute right-5 top-4 text-4xl font-black opacity-10 ${theme.text}`}>0{i+1}</div><EditableText value={x.title} onSave={v=>{const next=[...items];next[i]={...next[i],title:v};onUpdate({items:next})}} className={`block pr-10 text-lg font-bold ${theme.text}`}/><EditableText value={x.text} isTextArea onSave={v=>{const next=[...items];next[i]={...next[i],text:v};onUpdate({items:next})}} className={`mt-4 block text-sm leading-6 ${theme.sub}`}/><div className={`mt-8 h-1.5 rounded-full ${theme.border} border`}><div className={`h-full rounded-full ${theme.text} opacity-20`} style={{width:`${Math.min(100,48+i*12)}%`}}/></div><RepeatableRemoveButton overlay disabled={items.length<=1} onRemove={()=>onUpdate({items:removeAt(items,i,1)})}/></article>)}</div><RepeatableControls addLabel="Add agency item" showRemove={false} canAdd={items.length<6} canRemove={items.length>1} onAdd={()=>items.length<6&&onUpdate({items:cloneLast(items,{title:"New item",text:"Describe this item."})})} onRemove={()=>items.length>1&&onUpdate({items:items.slice(0,-1)})}/></div></section>
}
export const AgencyDashboardPreviewPremiumBlock=p=><AgencyBlock {...p} schema={AgencyDashboardPreviewPremiumSchema}/>;
export const AgencyClientPortalPremiumBlock=p=><AgencyBlock {...p} schema={AgencyClientPortalPremiumSchema}/>;
export const AgencyWhiteLabelShowcasePremiumBlock=p=><AgencyBlock {...p} schema={AgencyWhiteLabelShowcasePremiumSchema}/>;
export const AgencyWebsiteManagementPremiumBlock=p=><AgencyBlock {...p} schema={AgencyWebsiteManagementPremiumSchema}/>;
export const AgencyMaintenancePlansPremiumBlock=p=><AgencyBlock {...p} schema={AgencyMaintenancePlansPremiumSchema}/>;
export const AgencySupportPlansPremiumBlock=p=><AgencyBlock {...p} schema={AgencySupportPlansPremiumSchema}/>;
export const AgencyWorkflowPremiumBlock=p=><AgencyBlock {...p} schema={AgencyWorkflowPremiumSchema}/>;
export const AgencyProjectPipelinePremiumBlock=p=><AgencyBlock {...p} schema={AgencyProjectPipelinePremiumSchema}/>;
export const AgencyClientReviewsPremiumBlock=p=><AgencyBlock {...p} schema={AgencyClientReviewsPremiumSchema}/>;
export const AgencyWebsiteReportsPremiumBlock=p=><AgencyBlock {...p} schema={AgencyWebsiteReportsPremiumSchema}/>;
