<?php

return [
    'access_levels' => [
        'starter' => 10,
        'growth' => 20,
        'pro' => 30,
        'agency_starter' => 110,
        'agency_growth' => 120,
        'agency_pro' => 130,
        'all' => PHP_INT_MAX,
    ],


    'agency_collections' => [
        'agency_starter' => [
            'label' => 'Agency Essentials',
            'description' => 'Three versatile client-ready foundations for solo freelancers and small agencies.',
            'minimum_plan' => 'agency_starter',
            'templates' => ['aurora-agency', 'summit-consulting', 'nova-startup'],
        ],
        'agency_growth' => [
            'label' => 'Agency Growth Collection',
            'description' => 'Ten curated templates covering business, hospitality, construction, and startup clients.',
            'minimum_plan' => 'agency_growth',
            'templates' => ['aurora-agency', 'summit-consulting', 'nova-startup', 'midnight-studio', 'table-tide', 'ember-kitchen', 'olive-hearth', 'morning-brew', 'roast-lab', 'buildcore'],
        ],
        'agency_pro' => [
            'label' => 'Agency Pro Library',
            'description' => 'The complete Cosmic template catalog for agencies serving any supported industry.',
            'minimum_plan' => 'agency_pro',
            'templates' => ['*'],
        ],
    ],

    'templates' => [
        'aurora-agency' => [
            'minimum_plan' => 'starter',
            'industry' => 'Creative agency',
            'theme_family' => 'violet',
            'page_count' => 1,
            'spark_collection' => 'aurora-agency-starter',
            'is_featured' => true,
            'is_premium' => false,
            'collection' => 'personal',
        ],
        'summit-consulting' => [
            'minimum_plan' => 'starter',
            'industry' => 'Business consulting',
            'theme_family' => 'navy',
            'page_count' => 1,
            'spark_collection' => 'summit-consulting-starter',
            'is_featured' => false,
            'is_premium' => false,
            'collection' => 'personal',
        ],
        'nova-startup' => [
            'minimum_plan' => 'starter',
            'industry' => 'Startup',
            'theme_family' => 'indigo',
            'page_count' => 1,
            'spark_collection' => 'nova-startup-starter',
            'is_featured' => false,
            'is_premium' => false,
            'collection' => 'personal',
        ],
        'midnight-studio' => [
            'minimum_plan' => 'starter',
            'industry' => 'Professional studio',
            'theme_family' => 'midnight',
            'page_count' => 1,
            'spark_collection' => 'midnight-studio-starter',
            'is_featured' => false,
            'is_premium' => false,
            'collection' => 'personal',
        ],
        'table-tide' => [
            'minimum_plan' => 'starter',
            'industry' => 'Restaurant',
            'theme_family' => 'terracotta',
            'page_count' => 1,
            'spark_collection' => 'table-tide-starter',
            'is_featured' => true,
            'is_premium' => false,
            'collection' => 'personal',
        ],
        'ember-kitchen' => [
            'minimum_plan' => 'growth',
            'industry' => 'Modern dining',
            'theme_family' => 'espresso',
            'page_count' => 1,
            'spark_collection' => 'ember-kitchen-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'olive-hearth' => [
            'minimum_plan' => 'growth',
            'industry' => 'Mediterranean restaurant',
            'theme_family' => 'olive',
            'page_count' => 1,
            'spark_collection' => 'olive-hearth-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'morning-brew' => [
            'minimum_plan' => 'growth',
            'industry' => 'Coffee shop',
            'theme_family' => 'coffee',
            'page_count' => 1,
            'spark_collection' => 'morning-brew-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'roast-lab' => [
            'minimum_plan' => 'growth',
            'industry' => 'Coffee roaster',
            'theme_family' => 'espresso',
            'page_count' => 1,
            'spark_collection' => 'roast-lab-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'buildcore' => [
            'minimum_plan' => 'growth',
            'industry' => 'Construction',
            'theme_family' => 'asphalt',
            'page_count' => 1,
            'spark_collection' => 'buildcore-starter',
            'is_featured' => true,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'skyline-builders' => [
            'minimum_plan' => 'pro',
            'industry' => 'Residential builder',
            'theme_family' => 'stone',
            'page_count' => 1,
            'spark_collection' => 'skyline-builders-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'forge-works' => [
            'minimum_plan' => 'pro',
            'industry' => 'Industrial services',
            'theme_family' => 'charcoal',
            'page_count' => 1,
            'spark_collection' => 'forge-works-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'carepoint' => [
            'minimum_plan' => 'pro',
            'industry' => 'Medical clinic',
            'theme_family' => 'ocean',
            'page_count' => 1,
            'spark_collection' => 'carepoint-starter',
            'is_featured' => true,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'mednova' => [
            'minimum_plan' => 'pro',
            'industry' => 'Specialist practice',
            'theme_family' => 'teal',
            'page_count' => 1,
            'spark_collection' => 'mednova-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'smile-studio' => [
            'minimum_plan' => 'pro',
            'industry' => 'Dental clinic',
            'theme_family' => 'sapphire',
            'page_count' => 1,
            'spark_collection' => 'smile-studio-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'iron-gym' => [
            'minimum_plan' => 'pro',
            'industry' => 'Gym',
            'theme_family' => 'ruby',
            'page_count' => 1,
            'spark_collection' => 'iron-gym-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'motion-studio' => [
            'minimum_plan' => 'pro',
            'industry' => 'Boutique fitness',
            'theme_family' => 'plum',
            'page_count' => 1,
            'spark_collection' => 'motion-studio-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'haven-estates' => [
            'minimum_plan' => 'pro',
            'industry' => 'Real estate agency',
            'theme_family' => 'emerald',
            'page_count' => 1,
            'spark_collection' => 'haven-estates-starter',
            'is_featured' => true,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'prime-homes' => [
            'minimum_plan' => 'pro',
            'industry' => 'Property sales',
            'theme_family' => 'forest',
            'page_count' => 1,
            'spark_collection' => 'prime-homes-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'learnhub' => [
            'minimum_plan' => 'pro',
            'industry' => 'Online education',
            'theme_family' => 'indigo',
            'page_count' => 1,
            'spark_collection' => 'learnhub-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'bright-academy' => [
            'minimum_plan' => 'pro',
            'industry' => 'School or academy',
            'theme_family' => 'amber',
            'page_count' => 1,
            'spark_collection' => 'bright-academy-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'cloudtech' => [
            'minimum_plan' => 'pro',
            'industry' => 'Technology services',
            'theme_family' => 'sapphire',
            'page_count' => 1,
            'spark_collection' => 'cloudtech-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'orbit-launch' => [
            'minimum_plan' => 'pro',
            'industry' => 'SaaS',
            'theme_family' => 'violet',
            'page_count' => 1,
            'spark_collection' => 'orbit-launch-starter',
            'is_featured' => true,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'horizon-travel' => [
            'minimum_plan' => 'pro',
            'industry' => 'Travel agency',
            'theme_family' => 'teal',
            'page_count' => 1,
            'spark_collection' => 'horizon-travel-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'atlas-escape' => [
            'minimum_plan' => 'pro',
            'industry' => 'Luxury travel',
            'theme_family' => 'navy',
            'page_count' => 1,
            'spark_collection' => 'atlas-escape-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'legacy-law' => [
            'minimum_plan' => 'pro',
            'industry' => 'Law firm',
            'theme_family' => 'navy',
            'page_count' => 1,
            'spark_collection' => 'legacy-law-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'justice-partners' => [
            'minimum_plan' => 'pro',
            'industry' => 'Legal practice',
            'theme_family' => 'charcoal',
            'page_count' => 1,
            'spark_collection' => 'justice-partners-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'obsidian-atelier' => [
            'minimum_plan' => 'pro',
            'industry' => 'Luxury brand',
            'theme_family' => 'obsidian',
            'page_count' => 1,
            'spark_collection' => 'obsidian-atelier-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
        'form-function' => [
            'minimum_plan' => 'pro',
            'industry' => 'Design portfolio',
            'theme_family' => 'slate',
            'page_count' => 1,
            'spark_collection' => 'form-function-starter',
            'is_featured' => false,
            'is_premium' => true,
            'collection' => 'personal',
        ],
    ],
];
