<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Canonical Spark access hierarchy
    |--------------------------------------------------------------------------
    |
    | These ranks are the single source of truth for Spark entitlement checks.
    | Agency tiers are intentionally separate from Personal tiers.
    |
    */
    'access_levels' => [
        'free' => ['rank' => 0, 'label' => 'Free'],
        'starter' => ['rank' => 10, 'label' => 'Starter'],
        'growth' => ['rank' => 20, 'label' => 'Growth'],
        'pro' => ['rank' => 30, 'label' => 'Pro'],
        'agency_starter' => ['rank' => 110, 'label' => 'Starter Agency'],
        'agency_growth' => ['rank' => 120, 'label' => 'Growth Agency'],
        'agency_pro' => ['rank' => 130, 'label' => 'Pro Agency'],
        'all' => ['rank' => PHP_INT_MAX, 'label' => 'All Sparks'],
    ],

    /*
    | Map the existing pricing collections to official entitlement levels.
    | Individual Spark overrides may be added later without changing services.
    */
    'collections' => [
        'core' => [
            'label' => 'Core Collection',
            'access_level' => 'free',
            'description' => 'Essential reusable sections available to every paid Cosmic plan.',
        ],
        'growth' => [
            'label' => 'Growth Collection',
            'access_level' => 'growth',
            'description' => 'Marketing-focused layouts for Growth and higher plans.',
        ],
        'signature' => [
            'label' => 'Signature Collection',
            'access_level' => 'pro',
            'description' => 'Premium visual and motion sections for Pro and higher plans.',
        ],
    ],

    'overrides' => [
        // Metadata is derived automatically from every Spark key. Add only special
        // semantic aliases here when a Spark's name cannot fully describe its use.
        'hero_slider_premium' => [
            'aliases' => ['hero slider','banner slider','homepage carousel','rotating hero'],
            'media' => 'slider',
            'position_fit' => ['top'],
            'capabilities' => ['supports-slider','supports-multiple-images','overlay-header-safe'],
        ],
        'testimonials_carousel' => [
            'aliases' => ['review slider','testimonial slider','client carousel','customer stories'],
            'media' => 'slider',
            'intent' => ['proof'],
        ],
        'case_studies_grid' => [
            'aliases' => ['portfolio','selected work','projects','work showcase'],
            'intent' => ['showcase','proof'],
        ],
        'blog_mini_hero' => [
            'aliases' => ['blog mini hero', 'blog header', 'posts intro', 'updates header', 'resources intro'],
            'layout' => ['compact', 'editorial'],
            'intent' => ['storytelling', 'content discovery'],
            'capabilities' => ['theme-aware', 'layout-swap-safe'],
        ],
        'commerce_cart_classic' => [
            'aliases' => ['classic cart', 'shopping cart', 'cart page'],
            'layout' => ['classic'],
            'intent' => ['commerce', 'checkout preparation'],
            'capabilities' => ['commerce-runtime', 'theme-aware', 'transaction-data-protected'],
        ],
        'commerce_cart_compact' => [
            'aliases' => ['compact cart', 'dense cart', 'cart summary'],
            'layout' => ['compact'],
            'intent' => ['commerce', 'checkout preparation'],
            'capabilities' => ['commerce-runtime', 'theme-aware', 'transaction-data-protected'],
        ],
        'commerce_cart_split' => [
            'aliases' => ['split cart', 'two column cart', 'cart with summary'],
            'layout' => ['split'],
            'intent' => ['commerce', 'checkout preparation'],
            'capabilities' => ['commerce-runtime', 'theme-aware', 'transaction-data-protected'],
        ],

        'commerce_catalog_compact' => [
            'aliases' => ['commerce catalog compact', 'catalog compact'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_catalog_editorial' => [
            'aliases' => ['commerce catalog editorial', 'catalog editorial'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_catalog_grid' => [
            'aliases' => ['commerce catalog grid', 'catalog grid'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_categories' => [
            'aliases' => ['commerce categories', 'categories'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_checkout_classic' => [
            'aliases' => ['commerce checkout classic', 'checkout classic'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_checkout_express' => [
            'aliases' => ['commerce checkout express', 'checkout express'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_checkout_split' => [
            'aliases' => ['commerce checkout split', 'checkout split'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_featured_collection' => [
            'aliases' => ['commerce featured collection', 'featured collection'],
            'media' => 'image',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_featured_products' => [
            'aliases' => ['commerce featured products', 'featured products'],
            'media' => 'image',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_mini_cart' => [
            'aliases' => ['commerce mini cart', 'mini cart'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_price' => [
            'aliases' => ['commerce price', 'price'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_product_gallery' => [
            'aliases' => ['commerce product gallery', 'product gallery'],
            'media' => 'image',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_promo_split' => [
            'aliases' => ['commerce promo split', 'promo split'],
            'media' => 'image',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_related_products' => [
            'aliases' => ['commerce related products', 'related products'],
            'media' => 'image',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'commerce_variation_selector' => [
            'aliases' => ['commerce variation selector', 'variation selector'],
            'media' => 'none',
            'intent' => ['commerce','conversion'],
            'capabilities' => ['commerce-runtime','theme-aware','transaction-data-protected','layout-swap-safe'],
        ],
        'content_events_grid' => [
            'aliases' => ['content events grid', 'events grid'],
            'media' => 'none',
            'intent' => ['content discovery','editorial'],
            'capabilities' => ['content-runtime','theme-aware','layout-swap-safe'],
        ],
        'content_featured_entry' => [
            'aliases' => ['content featured entry', 'featured entry'],
            'media' => 'none',
            'intent' => ['content discovery','editorial'],
            'capabilities' => ['content-runtime','theme-aware','layout-swap-safe'],
        ],
        'content_grid_classic' => [
            'aliases' => ['content grid classic', 'grid classic'],
            'media' => 'none',
            'intent' => ['content discovery','editorial'],
            'capabilities' => ['content-runtime','theme-aware','layout-swap-safe'],
        ],
        'content_grid_compact' => [
            'aliases' => ['content grid compact', 'grid compact'],
            'media' => 'none',
            'intent' => ['content discovery','editorial'],
            'capabilities' => ['content-runtime','theme-aware','layout-swap-safe'],
        ],
        'content_grid_editorial' => [
            'aliases' => ['content grid editorial', 'grid editorial'],
            'media' => 'none',
            'intent' => ['content discovery','editorial'],
            'capabilities' => ['content-runtime','theme-aware','layout-swap-safe'],
        ],
        'content_latest_entries' => [
            'aliases' => ['content latest entries', 'latest entries'],
            'media' => 'none',
            'intent' => ['content discovery','editorial'],
            'capabilities' => ['content-runtime','theme-aware','layout-swap-safe'],
        ],

        'mini_hero_minimal' => [
            'aliases' => ['minimal mini hero', 'internal page hero', 'simple page header'],
            'media' => 'none',
            'layout' => ['minimal'],
            'intent' => ['page introduction'],
            'capabilities' => ['theme-aware','layout-swap-safe'],
        ],
        'mini_hero_promo' => [
            'aliases' => ['promo mini hero', 'promotional page header', 'internal promo hero'],
            'media' => 'image',
            'layout' => ['promo'],
            'intent' => ['page introduction','conversion'],
            'capabilities' => ['supports-image','theme-aware','layout-swap-safe'],
        ],
        'mini_hero_split' => [
            'aliases' => ['split mini hero', 'internal split hero', 'image page header'],
            'media' => 'image',
            'layout' => ['split'],
            'intent' => ['page introduction'],
            'capabilities' => ['supports-image','theme-aware','layout-swap-safe'],
        ],
        'newsletter_cta' => [
            'aliases' => ['newsletter signup', 'email signup', 'subscribe cta'],
            'media' => 'none',
            'layout' => ['cta'],
            'intent' => ['newsletter signup','conversion'],
            'capabilities' => ['form-runtime','theme-aware','layout-swap-safe'],
        ],

        // 'spark_key' => ['access_level' => 'pro'],
        'services_image_trio_premium' => [
            'aliases' => ['services image trio', 'services image layout', 'services trio layout', 'visual services section'],
            'media' => 'image',
            'layout' => 'trio',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'services_overlay_grid_premium' => [
            'aliases' => ['services overlay grid', 'services image layout', 'services overlay layout', 'visual services section'],
            'media' => 'image',
            'layout' => 'overlay',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'services_editorial_rows_premium' => [
            'aliases' => ['services editorial rows', 'services image layout', 'services rows layout', 'visual services section'],
            'media' => 'image',
            'layout' => 'rows',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'services_horizontal_media_premium' => [
            'aliases' => ['services horizontal media', 'services image layout', 'services horizontal layout', 'visual services section'],
            'media' => 'image',
            'layout' => 'horizontal',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'services_numbered_images_premium' => [
            'aliases' => ['services numbered images', 'services image layout', 'services numbered layout', 'visual services section'],
            'media' => 'image',
            'layout' => 'numbered',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'services_mosaic_media_premium' => [
            'aliases' => ['services mosaic media', 'services image layout', 'services mosaic layout', 'visual services section'],
            'media' => 'image',
            'layout' => 'mosaic',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'features_visual_split_premium' => [
            'aliases' => ['features visual split', 'features image layout', 'features split layout', 'visual features section'],
            'media' => 'image',
            'layout' => 'split',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'features_image_stack_premium' => [
            'aliases' => ['features image stack', 'features image layout', 'features stack layout', 'visual features section'],
            'media' => 'image',
            'layout' => 'stack',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'features_spotlight_cards_premium' => [
            'aliases' => ['features spotlight cards', 'features image layout', 'features spotlight layout', 'visual features section'],
            'media' => 'image',
            'layout' => 'spotlight',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'features_media_steps_premium' => [
            'aliases' => ['features media steps', 'features image layout', 'features steps layout', 'visual features section'],
            'media' => 'image',
            'layout' => 'steps',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'features_asymmetric_media_premium' => [
            'aliases' => ['features asymmetric media', 'features image layout', 'features asymmetric layout', 'visual features section'],
            'media' => 'image',
            'layout' => 'asymmetric',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'portfolio_cinematic_grid_premium' => [
            'aliases' => ['portfolio cinematic grid', 'portfolio image layout', 'portfolio cinematic layout', 'visual portfolio section'],
            'media' => 'image',
            'layout' => 'cinematic',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'portfolio_editorial_cards_premium' => [
            'aliases' => ['portfolio editorial cards', 'portfolio image layout', 'portfolio editorial layout', 'visual portfolio section'],
            'media' => 'image',
            'layout' => 'editorial',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'portfolio_project_panels_premium' => [
            'aliases' => ['portfolio project panels', 'portfolio image layout', 'portfolio panels layout', 'visual portfolio section'],
            'media' => 'image',
            'layout' => 'panels',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'portfolio_image_index_premium' => [
            'aliases' => ['portfolio image index', 'portfolio image layout', 'portfolio index layout', 'visual portfolio section'],
            'media' => 'image',
            'layout' => 'index',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'portfolio_split_showcase_premium' => [
            'aliases' => ['portfolio split showcase', 'portfolio image layout', 'portfolio showcase layout', 'visual portfolio section'],
            'media' => 'image',
            'layout' => 'showcase',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'about_story_collage_premium' => [
            'aliases' => ['about story collage', 'about image layout', 'about collage layout', 'visual about section'],
            'media' => 'image',
            'layout' => 'collage',
            'intent' => ['about'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'about_image_manifesto_premium' => [
            'aliases' => ['about image manifesto', 'about image layout', 'about manifesto layout', 'visual about section'],
            'media' => 'image',
            'layout' => 'manifesto',
            'intent' => ['about'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'about_founder_visual_premium' => [
            'aliases' => ['about founder visual', 'about image layout', 'about founder layout', 'visual about section'],
            'media' => 'image',
            'layout' => 'founder',
            'intent' => ['about'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'about_journey_gallery_premium' => [
            'aliases' => ['about journey gallery', 'about image layout', 'about journey layout', 'visual about section'],
            'media' => 'image',
            'layout' => 'journey',
            'intent' => ['about'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'team_portrait_editorial_premium' => [
            'aliases' => ['team portrait editorial', 'team image layout', 'team portrait layout', 'visual team section'],
            'media' => 'image',
            'layout' => 'portrait',
            'intent' => ['team'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'team_image_grid_premium' => [
            'aliases' => ['team image grid', 'team image layout', 'team grid layout', 'visual team section'],
            'media' => 'image',
            'layout' => 'grid',
            'intent' => ['team'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'team_leadership_split_premium' => [
            'aliases' => ['team leadership split', 'team image layout', 'team split layout', 'visual team section'],
            'media' => 'image',
            'layout' => 'split',
            'intent' => ['team'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'team_profile_overlay_premium' => [
            'aliases' => ['team profile overlay', 'team image layout', 'team overlay layout', 'visual team section'],
            'media' => 'image',
            'layout' => 'overlay',
            'intent' => ['team'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'team_people_mosaic_premium' => [
            'aliases' => ['team people mosaic', 'team image layout', 'team mosaic layout', 'visual team section'],
            'media' => 'image',
            'layout' => 'mosaic',
            'intent' => ['team'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'testimonials_portrait_cards_premium' => [
            'aliases' => ['testimonials portrait cards', 'testimonials image layout', 'testimonials portrait layout', 'visual testimonials section'],
            'media' => 'image',
            'layout' => 'portrait',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'testimonials_featured_story_premium' => [
            'aliases' => ['testimonials featured story', 'testimonials image layout', 'testimonials featured layout', 'visual testimonials section'],
            'media' => 'image',
            'layout' => 'featured',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'testimonials_image_wall_premium' => [
            'aliases' => ['testimonials image wall', 'testimonials image layout', 'testimonials wall layout', 'visual testimonials section'],
            'media' => 'image',
            'layout' => 'wall',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'testimonials_editorial_quotes_premium' => [
            'aliases' => ['testimonials editorial quotes', 'testimonials image layout', 'testimonials editorial layout', 'visual testimonials section'],
            'media' => 'image',
            'layout' => 'editorial',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'testimonials_client_spotlight_premium' => [
            'aliases' => ['testimonials client spotlight', 'testimonials image layout', 'testimonials spotlight layout', 'visual testimonials section'],
            'media' => 'image',
            'layout' => 'spotlight',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'process_visual_steps_premium' => [
            'aliases' => ['process visual steps', 'process image layout', 'process steps layout', 'visual process section'],
            'media' => 'image',
            'layout' => 'steps',
            'intent' => ['process'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'process_image_timeline_premium' => [
            'aliases' => ['process image timeline', 'process image layout', 'process timeline layout', 'visual process section'],
            'media' => 'image',
            'layout' => 'timeline',
            'intent' => ['process'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'process_numbered_panels_premium' => [
            'aliases' => ['process numbered panels', 'process image layout', 'process panels layout', 'visual process section'],
            'media' => 'image',
            'layout' => 'panels',
            'intent' => ['process'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'process_editorial_journey_premium' => [
            'aliases' => ['process editorial journey', 'process image layout', 'process journey layout', 'visual process section'],
            'media' => 'image',
            'layout' => 'journey',
            'intent' => ['process'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'process_media_roadmap_premium' => [
            'aliases' => ['process media roadmap', 'process image layout', 'process roadmap layout', 'visual process section'],
            'media' => 'image',
            'layout' => 'roadmap',
            'intent' => ['process'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'cta_image_split_premium' => [
            'aliases' => ['cta image split', 'cta image layout', 'cta split layout', 'visual cta section'],
            'media' => 'image',
            'layout' => 'split',
            'intent' => ['conversion'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'cta_background_media_premium' => [
            'aliases' => ['cta background media', 'cta image layout', 'cta background layout', 'visual cta section'],
            'media' => 'image',
            'layout' => 'background',
            'intent' => ['conversion'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'cta_floating_panel_premium' => [
            'aliases' => ['cta floating panel', 'cta image layout', 'cta floating layout', 'visual cta section'],
            'media' => 'image',
            'layout' => 'floating',
            'intent' => ['conversion'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'cta_editorial_banner_premium' => [
            'aliases' => ['cta editorial banner', 'cta image layout', 'cta editorial layout', 'visual cta section'],
            'media' => 'image',
            'layout' => 'editorial',
            'intent' => ['conversion'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'cta_media_cards_premium' => [
            'aliases' => ['cta media cards', 'cta image layout', 'cta cards layout', 'visual cta section'],
            'media' => 'image',
            'layout' => 'cards',
            'intent' => ['conversion'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'stats_photo_metrics_premium' => [
            'aliases' => ['stats photo metrics', 'stats image layout', 'stats photo layout', 'visual stats section'],
            'media' => 'image',
            'layout' => 'photo',
            'intent' => ['stats'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'stats_editorial_numbers_premium' => [
            'aliases' => ['stats editorial numbers', 'stats image layout', 'stats editorial layout', 'visual stats section'],
            'media' => 'image',
            'layout' => 'editorial',
            'intent' => ['stats'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'stats_image_panels_premium' => [
            'aliases' => ['stats image panels', 'stats image layout', 'stats panels layout', 'visual stats section'],
            'media' => 'image',
            'layout' => 'panels',
            'intent' => ['stats'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'stats_visual_mosaic_premium' => [
            'aliases' => ['stats visual mosaic', 'stats image layout', 'stats mosaic layout', 'visual stats section'],
            'media' => 'image',
            'layout' => 'mosaic',
            'intent' => ['stats'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'trust_logo_story_premium' => [
            'aliases' => ['trust logo story', 'trust image layout', 'trust logos layout', 'visual trust section'],
            'media' => 'image',
            'layout' => 'logos',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'trust_image_proof_premium' => [
            'aliases' => ['trust image proof', 'trust image layout', 'trust proof layout', 'visual trust section'],
            'media' => 'image',
            'layout' => 'proof',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'trust_certification_cards_premium' => [
            'aliases' => ['trust certification cards', 'trust image layout', 'trust certifications layout', 'visual trust section'],
            'media' => 'image',
            'layout' => 'certifications',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'trust_partner_showcase_premium' => [
            'aliases' => ['trust partner showcase', 'trust image layout', 'trust partners layout', 'visual trust section'],
            'media' => 'image',
            'layout' => 'partners',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'contact_image_form_premium' => [
            'aliases' => ['contact image form', 'contact image layout', 'contact form layout', 'visual contact section'],
            'media' => 'image',
            'layout' => 'form',
            'intent' => ['contact'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'contact_editorial_split_premium' => [
            'aliases' => ['contact editorial split', 'contact image layout', 'contact split layout', 'visual contact section'],
            'media' => 'image',
            'layout' => 'split',
            'intent' => ['contact'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'contact_office_cards_premium' => [
            'aliases' => ['contact office cards', 'contact image layout', 'contact offices layout', 'visual contact section'],
            'media' => 'image',
            'layout' => 'offices',
            'intent' => ['contact'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'contact_visual_inquiry_premium' => [
            'aliases' => ['contact visual inquiry', 'contact image layout', 'contact inquiry layout', 'visual contact section'],
            'media' => 'image',
            'layout' => 'inquiry',
            'intent' => ['contact'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'gallery_editorial_grid_premium' => [
            'aliases' => ['gallery editorial grid', 'gallery image layout', 'gallery editorial layout', 'visual gallery section'],
            'media' => 'image',
            'layout' => 'editorial',
            'intent' => ['gallery'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'gallery_asymmetric_premium' => [
            'aliases' => ['gallery asymmetric', 'gallery image layout', 'gallery asymmetric layout', 'visual gallery section'],
            'media' => 'image',
            'layout' => 'asymmetric',
            'intent' => ['gallery'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'gallery_story_tiles_premium' => [
            'aliases' => ['gallery story tiles', 'gallery image layout', 'gallery tiles layout', 'visual gallery section'],
            'media' => 'image',
            'layout' => 'tiles',
            'intent' => ['gallery'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'gallery_image_rail_premium' => [
            'aliases' => ['gallery image rail', 'gallery image layout', 'gallery rail layout', 'visual gallery section'],
            'media' => 'image',
            'layout' => 'rail',
            'intent' => ['gallery'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'location_photo_cards_premium' => [
            'aliases' => ['location photo cards', 'locations image layout', 'locations cards layout', 'visual locations section'],
            'media' => 'image',
            'layout' => 'cards',
            'intent' => ['location'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'location_city_spotlight_premium' => [
            'aliases' => ['location city spotlight', 'locations image layout', 'locations spotlight layout', 'visual locations section'],
            'media' => 'image',
            'layout' => 'spotlight',
            'intent' => ['location'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'location_multi_office_premium' => [
            'aliases' => ['location multi office', 'locations image layout', 'locations offices layout', 'visual locations section'],
            'media' => 'image',
            'layout' => 'offices',
            'intent' => ['location'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'location_visual_directory_premium' => [
            'aliases' => ['location visual directory', 'locations image layout', 'locations directory layout', 'visual locations section'],
            'media' => 'image',
            'layout' => 'directory',
            'intent' => ['location'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'restaurant_signature_dishes_premium' => [
            'aliases' => ['restaurant signature dishes', 'restaurant dishes layout', 'restaurant image section', 'visual restaurant section'],
            'media' => 'image',
            'layout' => 'dishes',
            'intent' => ['services'],
            'industry_fit' => ['restaurant', 'cafe', 'bakery', 'hospitality', 'food'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'restaurant_story_menu_premium' => [
            'aliases' => ['restaurant story menu', 'restaurant story layout', 'restaurant image section', 'visual restaurant section'],
            'media' => 'image',
            'layout' => 'story',
            'intent' => ['services'],
            'industry_fit' => ['restaurant', 'cafe', 'bakery', 'hospitality', 'food'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'restaurant_atmosphere_gallery_premium' => [
            'aliases' => ['restaurant atmosphere gallery', 'restaurant gallery layout', 'restaurant image section', 'visual restaurant section'],
            'media' => 'image',
            'layout' => 'gallery',
            'intent' => ['services'],
            'industry_fit' => ['restaurant', 'cafe', 'bakery', 'hospitality', 'food'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'restaurant_reservation_cta_premium' => [
            'aliases' => ['restaurant reservation cta', 'restaurant reservation layout', 'restaurant image section', 'visual restaurant section'],
            'media' => 'image',
            'layout' => 'reservation',
            'intent' => ['services'],
            'industry_fit' => ['restaurant', 'cafe', 'bakery', 'hospitality', 'food'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'construction_project_cards_premium' => [
            'aliases' => ['construction project cards', 'construction projects layout', 'construction image section', 'visual construction section'],
            'media' => 'image',
            'layout' => 'projects',
            'intent' => ['services'],
            'industry_fit' => ['construction', 'builder', 'contractor', 'architecture', 'trades'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'construction_service_photos_premium' => [
            'aliases' => ['construction service photos', 'construction services layout', 'construction image section', 'visual construction section'],
            'media' => 'image',
            'layout' => 'services',
            'intent' => ['services'],
            'industry_fit' => ['construction', 'builder', 'contractor', 'architecture', 'trades'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'construction_capability_split_premium' => [
            'aliases' => ['construction capability split', 'construction capabilities layout', 'construction image section', 'visual construction section'],
            'media' => 'image',
            'layout' => 'capabilities',
            'intent' => ['services'],
            'industry_fit' => ['construction', 'builder', 'contractor', 'architecture', 'trades'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'construction_site_progress_premium' => [
            'aliases' => ['construction site progress', 'construction progress layout', 'construction image section', 'visual construction section'],
            'media' => 'image',
            'layout' => 'progress',
            'intent' => ['services'],
            'industry_fit' => ['construction', 'builder', 'contractor', 'architecture', 'trades'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'dental_treatment_cards_premium' => [
            'aliases' => ['dental treatment cards', 'dental treatments layout', 'dental image section', 'visual dental section'],
            'media' => 'image',
            'layout' => 'treatments',
            'intent' => ['services'],
            'industry_fit' => ['dentist', 'dental', 'clinic', 'healthcare'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'dental_clinic_story_premium' => [
            'aliases' => ['dental clinic story', 'dental story layout', 'dental image section', 'visual dental section'],
            'media' => 'image',
            'layout' => 'story',
            'intent' => ['services'],
            'industry_fit' => ['dentist', 'dental', 'clinic', 'healthcare'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'medical_care_pathways_premium' => [
            'aliases' => ['medical care pathways', 'medical pathways layout', 'medical image section', 'visual medical section'],
            'media' => 'image',
            'layout' => 'pathways',
            'intent' => ['services'],
            'industry_fit' => ['medical', 'clinic', 'healthcare', 'doctor'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'medical_facility_showcase_premium' => [
            'aliases' => ['medical facility showcase', 'medical facility layout', 'medical image section', 'visual medical section'],
            'media' => 'image',
            'layout' => 'facility',
            'intent' => ['services'],
            'industry_fit' => ['medical', 'clinic', 'healthcare', 'doctor'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'realestate_property_grid_premium' => [
            'aliases' => ['real estate property grid', 'realestate properties layout', 'realestate image section', 'visual realestate section'],
            'media' => 'image',
            'layout' => 'properties',
            'intent' => ['portfolio'],
            'industry_fit' => ['real-estate', 'property', 'realtor'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'realestate_featured_listing_premium' => [
            'aliases' => ['real estate featured listing', 'realestate featured layout', 'realestate image section', 'visual realestate section'],
            'media' => 'image',
            'layout' => 'featured',
            'intent' => ['portfolio'],
            'industry_fit' => ['real-estate', 'property', 'realtor'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'realestate_neighborhood_cards_premium' => [
            'aliases' => ['real estate neighborhood cards', 'realestate neighborhoods layout', 'realestate image section', 'visual realestate section'],
            'media' => 'image',
            'layout' => 'neighborhoods',
            'intent' => ['portfolio'],
            'industry_fit' => ['real-estate', 'property', 'realtor'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'realestate_agent_story_premium' => [
            'aliases' => ['real estate agent story', 'realestate agent layout', 'realestate image section', 'visual realestate section'],
            'media' => 'image',
            'layout' => 'agent',
            'intent' => ['portfolio'],
            'industry_fit' => ['real-estate', 'property', 'realtor'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'hotel_room_collection_premium' => [
            'aliases' => ['hotel room collection', 'hotel rooms layout', 'hotel image section', 'visual hotel section'],
            'media' => 'image',
            'layout' => 'rooms',
            'intent' => ['services'],
            'industry_fit' => ['hotel', 'hospitality', 'accommodation'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'hotel_experience_cards_premium' => [
            'aliases' => ['hotel experience cards', 'hotel experiences layout', 'hotel image section', 'visual hotel section'],
            'media' => 'image',
            'layout' => 'experiences',
            'intent' => ['services'],
            'industry_fit' => ['hotel', 'hospitality', 'accommodation'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'travel_destination_story_premium' => [
            'aliases' => ['travel destination story', 'travel destination layout', 'travel image section', 'visual travel section'],
            'media' => 'image',
            'layout' => 'destination',
            'intent' => ['portfolio'],
            'industry_fit' => ['travel', 'tourism', 'destination'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'travel_itinerary_visual_premium' => [
            'aliases' => ['travel itinerary visual', 'travel itinerary layout', 'travel image section', 'visual travel section'],
            'media' => 'image',
            'layout' => 'itinerary',
            'intent' => ['portfolio'],
            'industry_fit' => ['travel', 'tourism', 'destination'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe'],
        ],
        'content_editorial_image_stack_premium' => [
            'aliases' => ['editorial image stack', 'content stack layout', 'premium content image section', 'alternate content layout'],
            'media' => 'image',
            'layout' => 'stack',
            'intent' => ['content'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'content_asymmetric_story_premium' => [
            'aliases' => ['asymmetric story', 'content asymmetric layout', 'premium content image section', 'alternate content layout'],
            'media' => 'image',
            'layout' => 'asymmetric',
            'intent' => ['content'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'content_media_manifesto_premium' => [
            'aliases' => ['media manifesto', 'content manifesto layout', 'premium content image section', 'alternate content layout'],
            'media' => 'image',
            'layout' => 'manifesto',
            'intent' => ['content'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'content_visual_quote_premium' => [
            'aliases' => ['visual quote', 'content quote layout', 'premium content image section', 'alternate content layout'],
            'media' => 'image',
            'layout' => 'quote',
            'intent' => ['content'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'features_overlap_cards_premium' => [
            'aliases' => ['features overlap cards', 'features overlap layout', 'premium features image section', 'alternate features layout'],
            'media' => 'image',
            'layout' => 'overlap',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'features_fullbleed_panels_premium' => [
            'aliases' => ['features full bleed panels', 'features fullbleed layout', 'premium features image section', 'alternate features layout'],
            'media' => 'image',
            'layout' => 'fullbleed',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'features_image_index_premium' => [
            'aliases' => ['features image index', 'features index layout', 'premium features image section', 'alternate features layout'],
            'media' => 'image',
            'layout' => 'index',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'features_editorial_mosaic_premium' => [
            'aliases' => ['features editorial mosaic', 'features mosaic layout', 'premium features image section', 'alternate features layout'],
            'media' => 'image',
            'layout' => 'mosaic',
            'intent' => ['features'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'services_fullbleed_overlay_premium' => [
            'aliases' => ['services full bleed overlay', 'services overlay layout', 'premium services image section', 'alternate services layout'],
            'media' => 'image',
            'layout' => 'overlay',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'services_staggered_media_premium' => [
            'aliases' => ['services staggered media', 'services staggered layout', 'premium services image section', 'alternate services layout'],
            'media' => 'image',
            'layout' => 'staggered',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'services_image_accordion_premium' => [
            'aliases' => ['services image accordion', 'services accordion layout', 'premium services image section', 'alternate services layout'],
            'media' => 'image',
            'layout' => 'accordion',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'services_visual_directory_premium' => [
            'aliases' => ['services visual directory', 'services directory layout', 'premium services image section', 'alternate services layout'],
            'media' => 'image',
            'layout' => 'directory',
            'intent' => ['services'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'portfolio_fullbleed_projects_premium' => [
            'aliases' => ['portfolio full bleed projects', 'portfolio fullbleed layout', 'premium portfolio image section', 'alternate portfolio layout'],
            'media' => 'image',
            'layout' => 'fullbleed',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'portfolio_staggered_gallery_premium' => [
            'aliases' => ['portfolio staggered gallery', 'portfolio staggered layout', 'premium portfolio image section', 'alternate portfolio layout'],
            'media' => 'image',
            'layout' => 'staggered',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'portfolio_story_index_premium' => [
            'aliases' => ['portfolio story index', 'portfolio index layout', 'premium portfolio image section', 'alternate portfolio layout'],
            'media' => 'image',
            'layout' => 'index',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'portfolio_media_ledger_premium' => [
            'aliases' => ['portfolio media ledger', 'portfolio ledger layout', 'premium portfolio image section', 'alternate portfolio layout'],
            'media' => 'image',
            'layout' => 'ledger',
            'intent' => ['portfolio'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'proof_case_story_premium' => [
            'aliases' => ['proof case story', 'proof case layout', 'premium proof image section', 'alternate proof layout'],
            'media' => 'image',
            'layout' => 'case',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'proof_metric_gallery_premium' => [
            'aliases' => ['proof metric gallery', 'proof metrics layout', 'premium proof image section', 'alternate proof layout'],
            'media' => 'image',
            'layout' => 'metrics',
            'intent' => ['proof'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'brand_value_cards_premium' => [
            'aliases' => ['brand value cards', 'brand values layout', 'premium brand image section', 'alternate brand layout'],
            'media' => 'image',
            'layout' => 'values',
            'intent' => ['about'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'brand_visual_principles_premium' => [
            'aliases' => ['brand visual principles', 'brand principles layout', 'premium brand image section', 'alternate brand layout'],
            'media' => 'image',
            'layout' => 'principles',
            'intent' => ['about'],
            'capabilities' => ['supports-image','supports-repeaters','supports-universal-background','theme-aware','layout-swap-safe','alternate-layout'],
        ],
        'about_chapter_index_premium' => [
            'aliases' => ['chapter index', 'editorial chapters', 'about narrative', 'sticky story', 'low image about'],
            'media' => 'none',
            'layout' => ['chapter-index', 'sticky-editorial', 'low-image'],
            'intent' => ['about', 'story'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
        'services_orbit_map_premium' => [
            'aliases' => ['service orbit', 'connected services', 'offer ecosystem', 'service map', 'low image services'],
            'media' => 'none',
            'layout' => ['orbit-map', 'connected-system', 'low-image'],
            'intent' => ['services', 'offerings'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
        'process_constellation_premium' => [
            'aliases' => ['process constellation', 'connected workflow', 'milestone path', 'process map', 'low image process'],
            'media' => 'none',
            'layout' => ['constellation', 'connected-timeline', 'low-image'],
            'intent' => ['process', 'workflow'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
        'proof_metric_staircase_premium' => [
            'aliases' => ['proof staircase', 'metric staircase', 'evidence steps', 'outcome sequence', 'low image proof'],
            'media' => 'none',
            'layout' => ['metric-staircase', 'stepped-evidence', 'low-image'],
            'intent' => ['proof', 'stats'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
        'trust_evidence_ledger_premium' => [
            'aliases' => ['evidence ledger', 'trust ledger', 'claims proof', 'credibility ledger', 'low image trust'],
            'media' => 'none',
            'layout' => ['evidence-ledger', 'structured-proof', 'low-image'],
            'intent' => ['proof', 'trust'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
        'faq_decision_tree_premium' => [
            'aliases' => ['faq decision tree', 'guided faq', 'question paths', 'decision support', 'low image faq'],
            'media' => 'none',
            'layout' => ['decision-tree', 'branching-faq', 'low-image'],
            'intent' => ['faq', 'education'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
        'cta_ticket_premium' => [
            'aliases' => ['ticket cta', 'perforated call to action', 'conversion ticket', 'event ticket cta', 'low image cta'],
            'media' => 'none',
            'layout' => ['ticket', 'perforated-panel', 'low-image'],
            'intent' => ['cta', 'conversion'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-buttons', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
        'contact_availability_board_premium' => [
            'aliases' => ['contact availability board', 'contact routes', 'inquiry directory', 'contact board', 'low image contact'],
            'media' => 'none',
            'layout' => ['availability-board', 'contact-directory', 'low-image'],
            'intent' => ['contact', 'conversion'],
            'industry' => ['universal'],
            'capabilities' => ['supports-repeaters', 'supports-buttons', 'supports-universal-background', 'theme-aware', 'layout-swap-safe', 'alternate-layout', 'low-image'],
        ],
    ],
];
