<?php

return [
        'starter' => [
            'label' => 'Starter',
            'family' => 'personal',
            'tier' => 'starter',
            'rank' => 10,
            'price_usd' => 49,
            'credits' => 150,
            'description' => 'Launch one complete business website with essential AI and Sparks.',
            'billing' => ['paypal_plan_id' => env('PAYPAL_PLAN_PERSONAL_STARTER_ID', env('PAYPAL_PLAN_STARTER_ID'))],
            'capabilities' => [
                'max_sites' => 1, 'max_pages_per_site' => 5, 'max_sparks_per_site' => 15,
                'max_owned_sparks' => 15, 'free_built_in_sparks' => 5, 'template_limit' => 5,
                'template_access_level' => 'starter', 'spark_access_level' => 'free',
                'analytics_level' => 'basic', 'leads_level' => 'inbox', 'sales_level' => 'none',
                'team_members' => 0, 'white_label_level' => 'none', 'api_access' => false,
                'ai_website_generation' => true, 'ai_content_generation' => true, 'ai_image_selection' => true,
                'theme_customization' => true, 'header_footer_builder' => true, 'contact_forms' => true,
                'blog_level' => 'basic', 'landing_pages' => false, 'lead_management' => false,
                'form_submission_management' => false, 'website_duplicate_draft' => false,
                'custom_scripts' => false, 'custom_forms' => false, 'booking_ui_sparks' => false,
                'version_history' => false, 'redirect_management' => false, 'priority_ai' => false,
                'branding_removed' => false, 'custom_domain' => false, 'export_static' => true,
                'seo_level' => 'basic', 'support_level' => 'standard',
            ],
        ],
        'growth' => [
            'label' => 'Growth',
            'family' => 'personal',
            'tier' => 'growth',
            'rank' => 20,
            'price_usd' => 79,
            'credits' => 350,
            'description' => 'More pages, premium creative access, and marketing tools for a growing business.',
            'billing' => ['paypal_plan_id' => env('PAYPAL_PLAN_PERSONAL_GROWTH_ID', env('PAYPAL_PLAN_GROWTH_ID'))],
            'capabilities' => [
                'max_sites' => 1, 'max_pages_per_site' => 10, 'max_sparks_per_site' => 30,
                'max_owned_sparks' => 30, 'free_built_in_sparks' => 10, 'template_limit' => 10,
                'template_access_level' => 'growth', 'spark_access_level' => 'growth',
                'analytics_level' => 'standard', 'leads_level' => 'history', 'sales_level' => 'basic',
                'team_members' => 0, 'white_label_level' => 'none', 'api_access' => false,
                'ai_website_generation' => true, 'ai_content_generation' => true, 'ai_image_selection' => true,
                'theme_customization' => true, 'header_footer_builder' => true, 'contact_forms' => true,
                'blog_level' => 'enhanced', 'landing_pages' => true, 'lead_management' => true,
                'form_submission_management' => true, 'website_duplicate_draft' => true,
                'custom_scripts' => true, 'custom_forms' => false, 'booking_ui_sparks' => false,
                'version_history' => false, 'redirect_management' => false, 'priority_ai' => false,
                'branding_removed' => false, 'custom_domain' => false, 'export_static' => true,
                'seo_level' => 'enhanced', 'support_level' => 'priority_email',
            ],
        ],
        'pro' => [
            'label' => 'Pro',
            'family' => 'personal',
            'tier' => 'pro',
            'rank' => 30,
            'price_usd' => 129,
            'credits' => 750,
            'description' => 'The complete single-website Cosmic experience with advanced AI, analytics, leads, and sales.',
            'billing' => ['paypal_plan_id' => env('PAYPAL_PLAN_PERSONAL_PRO_ID', env('PAYPAL_PLAN_PRO_ID'))],
            'capabilities' => [
                'max_sites' => 1, 'max_pages_per_site' => null, 'max_sparks_per_site' => null,
                'max_owned_sparks' => null, 'free_built_in_sparks' => 15, 'template_limit' => null,
                'template_access_level' => 'pro', 'spark_access_level' => 'pro',
                'analytics_level' => 'advanced', 'leads_level' => 'full', 'sales_level' => 'full',
                'team_members' => 0, 'white_label_level' => 'branding_removed', 'api_access' => false,
                'ai_website_generation' => true, 'ai_content_generation' => true, 'ai_image_selection' => true,
                'theme_customization' => true, 'header_footer_builder' => true, 'contact_forms' => true,
                'blog_level' => 'advanced', 'landing_pages' => true, 'lead_management' => true,
                'form_submission_management' => true, 'website_duplicate_draft' => true,
                'custom_scripts' => true, 'custom_forms' => true, 'booking_ui_sparks' => true,
                'version_history' => true, 'redirect_management' => true, 'priority_ai' => true,
                'branding_removed' => true, 'custom_domain' => true, 'export_static' => true,
                'seo_level' => 'advanced', 'support_level' => 'priority',
            ],
        ],
        'agency_starter' => [
            'label' => 'Starter Agency',
            'family' => 'agency',
            'tier' => 'starter',
            'rank' => 110,
            'price_usd' => 99,
            'credits' => 500,
            'description' => 'Manage up to 3 client websites with shared credits, previews, and essential agency tools.',
            'billing' => ['paypal_plan_id' => env('PAYPAL_PLAN_AGENCY_STARTER_ID', env('PAYPAL_PLAN_AGENCY_BASIC_ID'))],
            'capabilities' => [
                'max_sites' => 3, 'max_pages_per_site' => 5, 'max_sparks_per_site' => 15,
                'max_owned_sparks' => 15, 'free_built_in_sparks' => 5, 'template_limit' => 3, 'marketplace_preview_limit' => 15,
                'template_access_level' => 'agency_starter', 'spark_access_level' => 'agency_starter',
                'analytics_level' => 'per_website', 'leads_level' => 'per_website', 'sales_level' => 'none',
                'team_members' => 0, 'white_label_level' => 'none', 'api_access' => false,
                'website_clone' => true, 'client_preview_links' => true,
                'website_search_filter' => true, 'per_website_lead_inbox' => true,
                'per_website_analytics_summary' => true, 'agency_workspace' => true,
                'activity_history' => true, 'aggregated_analytics' => false,
                'aggregated_leads' => false, 'aggregated_sales' => false,
                'client_handoff' => false, 'shared_sparks' => false, 'shared_templates' => false,
                'custom_preview_branding' => false, 'bulk_export' => false,
            ],
        ],
        'agency_growth' => [
            'label' => 'Growth Agency',
            'family' => 'agency',
            'tier' => 'growth',
            'rank' => 120,
            'price_usd' => 199,
            'credits' => 1500,
            'description' => 'Operate up to 10 client websites with aggregated insights, shared assets, and team access.',
            'billing' => ['paypal_plan_id' => env('PAYPAL_PLAN_AGENCY_GROWTH_ID')],
            'capabilities' => [
                'max_sites' => 10, 'max_pages_per_site' => 10, 'max_sparks_per_site' => 30,
                'max_owned_sparks' => 30, 'free_built_in_sparks' => 10, 'template_limit' => 10, 'marketplace_preview_limit' => 30,
                'template_access_level' => 'agency_growth', 'spark_access_level' => 'agency_growth',
                'analytics_level' => 'aggregated', 'leads_level' => 'aggregated', 'sales_level' => 'summary',
                'team_members' => 3, 'white_label_level' => 'basic', 'api_access' => false,
                'website_clone' => true, 'client_preview_links' => true, 'shared_assets' => true,
                'website_search_filter' => true, 'per_website_lead_inbox' => true,
                'per_website_analytics_summary' => true, 'agency_workspace' => true,
                'activity_history' => true, 'agency_insights' => true,
                'aggregated_analytics' => true, 'aggregated_leads' => true,
                'aggregated_sales' => false, 'website_date_filtering' => true,
                'client_handoff' => true, 'ownership_transfer' => false,
                'shared_sparks' => true, 'shared_templates' => true,
                'custom_preview_branding' => true, 'branded_reports' => false,
                'advanced_white_label' => false, 'granular_permissions' => false,
                'bulk_actions' => false, 'bulk_export' => false, 'client_accounts' => false,
                'revenue_reporting' => false, 'conversion_reporting' => false,
                'lead_source_reporting' => false, 'sales_funnel_reporting' => false,
                'ai_insights_foundation' => false, 'webhooks' => false,
                'priority_ai' => false, 'advanced_publication_history' => false, 'early_access' => false,
            ],
        ],
        'agency_pro' => [
            'label' => 'Pro Agency',
            'family' => 'agency',
            'tier' => 'pro',
            'rank' => 130,
            'price_usd' => 399,
            'credits' => 5000,
            'description' => 'Unlimited websites with full agency insights, teams, sales, leads, white label, API, and webhooks.',
            'billing' => ['paypal_plan_id' => env('PAYPAL_PLAN_AGENCY_PRO_ID')],
            'capabilities' => [
                'max_sites' => null, 'max_pages_per_site' => null, 'max_sparks_per_site' => null,
                'max_owned_sparks' => null, 'free_built_in_sparks' => 15, 'template_limit' => null, 'marketplace_preview_limit' => null,
                'template_access_level' => 'all', 'spark_access_level' => 'all',
                'analytics_level' => 'full_agency', 'leads_level' => 'full_agency', 'sales_level' => 'full_agency',
                'team_members' => 10, 'white_label_level' => 'full', 'api_access' => true,
                'webhooks' => true, 'website_clone' => true, 'client_preview_links' => true,
                'shared_assets' => true, 'bulk_actions' => true, 'client_accounts' => true,
                'website_search_filter' => true, 'per_website_lead_inbox' => true,
                'per_website_analytics_summary' => true, 'agency_workspace' => true,
                'activity_history' => true, 'agency_insights' => true,
                'aggregated_analytics' => true, 'aggregated_leads' => true,
                'aggregated_sales' => true, 'revenue_reporting' => true,
                'conversion_reporting' => true, 'lead_source_reporting' => true,
                'sales_funnel_reporting' => true, 'ai_insights_foundation' => true,
                'website_date_filtering' => true, 'client_handoff' => true,
                'ownership_transfer' => true, 'shared_sparks' => true, 'shared_templates' => true,
                'custom_preview_branding' => true, 'branded_reports' => true,
                'advanced_white_label' => true, 'granular_permissions' => true,
                'priority_ai' => true, 'advanced_publication_history' => true,
                'bulk_export' => true, 'early_access' => true,
            ],
        ],
    ];
