<?php

return [
    'construction' => ['Home', 'About', 'Services', 'Projects', 'Contact'],
    'restaurant' => ['Home', 'About', 'Menu', 'Gallery', 'Reservations'],
    'coffee' => ['Home', 'About', 'Menu', 'Gallery', 'Contact'],
    'bakery' => ['Home', 'About', 'Menu', 'Custom Cakes', 'Contact'],
    'dentist' => ['Home', 'About', 'Treatments', 'Team', 'Book Appointment'],
    'medical' => ['Home', 'About', 'Services', 'Doctors', 'Appointments'],
    'lawyer' => ['Home', 'About', 'Practice Areas', 'Case Results', 'Contact'],
    'fitness' => ['Home', 'About', 'Programs', 'Membership', 'Contact'],
    'real-estate' => ['Home', 'About', 'Properties', 'Agents', 'Contact'],
    'hotel' => ['Home', 'About', 'Rooms', 'Gallery', 'Book Now'],
    'travel' => ['Home', 'About', 'Destinations', 'Tour Packages', 'Contact'],
    'technology' => ['Home', 'About', 'Solutions', 'Case Studies', 'Contact'],
    'education' => ['Home', 'About', 'Courses', 'Admissions', 'Contact'],
    'finance' => ['Home', 'About', 'Services', 'Resources', 'Contact'],
    'electrician' => ['Home', 'About', 'Services', 'Projects', 'Contact'],
    'plumbing' => ['Home', 'About', 'Services', 'Emergency Service', 'Contact'],
    'cleaning' => ['Home', 'About', 'Services', 'Pricing', 'Contact'],
    'landscaping' => ['Home', 'About', 'Services', 'Projects', 'Contact'],
    'automotive' => ['Home', 'About', 'Services', 'Gallery', 'Book Service'],
    'salon' => ['Home', 'About', 'Services', 'Gallery', 'Book Appointment'],
    'default' => ['Home', 'About', 'Services', 'Contact'],
];
