import { router, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';

export default function Branding({ dashboard }) {
    const branding = dashboard.agency_branding || {};
    const [previewUrl, setPreviewUrl] = useState(branding.logo_url || null);
    const [copied, setCopied] = useState(null);
    const form = useForm({
        agency_name: branding.agency_name || '', tagline: branding.tagline || '',
        primary_color: branding.primary_color || '#23966B', accent_color: branding.accent_color || '#42B993',
        support_email: branding.support_email || '', website_url: branding.website_url || '',
        logo: null, logo_action: 'keep', remove_cosmic_branding: Boolean(branding.remove_cosmic_branding),
        portal_title: branding.portal_title || 'Welcome to your client portal', portal_welcome: branding.portal_welcome || 'Review your websites, check publication status, and open secure previews from one place.',
    });
    const linkForm = useForm({ website_id: branding.preview_links?.[0]?.website_id || '', label: '', expires_in_days: 7 });
    const canManage = branding.available && branding.is_owner;
    const initials = useMemo(() => String(form.data.agency_name || 'Your Agency').split(/\s+/).map(v=>v[0]).join('').slice(0,2).toUpperCase(), [form.data.agency_name]);

    const submit = (event) => { event.preventDefault(); form.post(route('workspace.branding.update', branding.workspace_id), { forceFormData: true, preserveScroll: true }); };
    const createLink = (event) => { event.preventDefault(); if (!linkForm.data.website_id) return; linkForm.post(route('preview-links.store', linkForm.data.website_id), { preserveScroll: true, onSuccess:()=>linkForm.reset('label') }); };
    const copy = async (url, id) => { await navigator.clipboard.writeText(url); setCopied(id); setTimeout(()=>setCopied(null), 1600); };

    if (!branding.is_agency) return <section className="cosmic-branding-page"><p className="text-sm font-medium text-violet-600">White Label</p><h1 className="mt-2 text-3xl font-semibold text-white">Agency Branding</h1><div className="mt-8 rounded-2xl border border-white/10 bg-[#111113] p-8 text-slate-400">Agency branding is available on Agency plans.</div></section>;

    return <section className="cosmic-branding-page">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-violet-600">White Label</p><h1 className="mt-2 text-3xl font-semibold text-white">Agency Branding</h1><p className="mt-3 max-w-2xl text-sm text-slate-400">Create the reusable brand identity for client previews, reports, and your future agency portal.</p></div><div className="flex items-center gap-3"><a href={route('agency-reports.index')} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-semibold text-slate-200 hover:bg-white/5">Open branded reports</a><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-widest text-slate-400">{branding.level || 'none'}</span></div></div>
        {!branding.available && <div className="mt-8 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5 text-sm text-amber-200">Upgrade to Growth Agency or Pro Agency to activate agency branding.</div>}
        <div className="mt-8 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
            <form onSubmit={submit} className="space-y-5 rounded-2xl border border-white/10 bg-[#111113] p-6">
                <div><h2 className="text-lg font-semibold text-white">Brand identity</h2><p className="mt-1 text-sm text-slate-500">These values become the single source of truth for white-label surfaces.</p></div>
                <div className="grid gap-4 md:grid-cols-2"><Field label="Agency name" error={form.errors.agency_name}><input disabled={!canManage} value={form.data.agency_name} onChange={e=>form.setData('agency_name',e.target.value)} className="w-full rounded-xl border-white/10 bg-white/5 text-white"/></Field><Field label="Tagline" error={form.errors.tagline}><input disabled={!canManage} value={form.data.tagline} onChange={e=>form.setData('tagline',e.target.value)} className="w-full rounded-xl border-white/10 bg-white/5 text-white"/></Field></div>
                <div className="grid gap-4 md:grid-cols-2"><Field label="Primary color"><input type="color" disabled={!canManage} value={form.data.primary_color} onChange={e=>form.setData('primary_color',e.target.value)} className="h-11 w-full rounded-xl border-white/10 bg-white/5 p-1"/></Field><Field label="Accent color"><input type="color" disabled={!canManage} value={form.data.accent_color} onChange={e=>form.setData('accent_color',e.target.value)} className="h-11 w-full rounded-xl border-white/10 bg-white/5 p-1"/></Field></div>
                <div className="grid gap-4 md:grid-cols-2"><Field label="Support email" error={form.errors.support_email}><input disabled={!canManage} value={form.data.support_email} onChange={e=>form.setData('support_email',e.target.value)} className="w-full rounded-xl border-white/10 bg-white/5 text-white"/></Field><Field label="Agency website" error={form.errors.website_url}><input disabled={!canManage} value={form.data.website_url} onChange={e=>form.setData('website_url',e.target.value)} className="w-full rounded-xl border-white/10 bg-white/5 text-white"/></Field></div>
                <Field label="Agency logo" error={form.errors.logo}><input type="file" accept="image/*" disabled={!canManage} onChange={e=>{const file=e.target.files?.[0]||null; form.setData('logo',file); form.setData('logo_action',file?'replace':'keep'); if(file)setPreviewUrl(URL.createObjectURL(file));}} className="block w-full text-sm text-slate-400"/></Field>
                {branding.custom_portal_available ? <div className="cosmic-branding-portal-card rounded-xl border p-4"><div className="mb-4"><p className="text-sm font-semibold text-white">Custom agency portal</p><p className="mt-1 text-xs text-slate-400">Customize the welcome screen shown to client accounts on Pro Agency.</p></div><div className="grid gap-4"><Field label="Portal title" error={form.errors.portal_title}><input disabled={!canManage} value={form.data.portal_title} onChange={e=>form.setData('portal_title',e.target.value)} className="w-full rounded-xl border-white/10 bg-white/5 text-white"/></Field><Field label="Welcome message" error={form.errors.portal_welcome}><textarea rows={3} disabled={!canManage} value={form.data.portal_welcome} onChange={e=>form.setData('portal_welcome',e.target.value)} className="w-full rounded-xl border-white/10 bg-white/5 text-white"/></Field></div></div> : <div className="rounded-xl border border-white/10 bg-white/[0.02] p-4 text-sm text-slate-500"><span className="font-semibold text-slate-300">Custom agency portal</span> is available on Pro Agency with full white-label access.</div>}
                <div className="rounded-xl border border-white/10 bg-white/[0.02] p-4"><label className="flex items-start gap-3"><input type="checkbox" disabled={!canManage || !branding.can_remove_cosmic_branding} checked={form.data.remove_cosmic_branding} onChange={e=>form.setData('remove_cosmic_branding',e.target.checked)} className="mt-1 h-4 w-4 rounded border-white/20 bg-transparent"/><span><span className="block text-sm font-semibold text-white">Remove Cosmic branding</span><span className="mt-1 block text-xs leading-5 text-slate-500">Hide Cosmic attribution from eligible client-facing preview surfaces and use your agency identity instead.</span></span></label></div>
                <div className="flex flex-col gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm text-slate-500">{form.recentlySuccessful ? 'Branding saved.' : branding.is_owner ? 'Owner-managed workspace identity.' : 'Only the owner can edit.'}</span><div className="flex items-center gap-3">{canManage&&<button type="button" onClick={()=>{if(window.confirm('Reset agency branding, portal copy, logo, and white-label preferences to defaults?')) router.delete(route('workspace.branding.reset', branding.workspace_id),{preserveScroll:true});}} className="rounded-xl border border-rose-400/20 px-4 py-2.5 text-sm font-semibold text-rose-300 hover:bg-rose-400/5">Reset defaults</button>}<button disabled={!canManage || form.processing} className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-violet-700 disabled:opacity-40">{form.processing ? 'Saving…' : 'Save Branding'}</button></div></div>
            </form>
            <div className="cosmic-branding-live-preview rounded-2xl border border-white/10 bg-[#111113] p-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Live preview</p><div className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-white text-slate-900"><div className="flex items-center gap-3 p-5" style={{backgroundColor:form.data.primary_color}}>{previewUrl ? <img src={previewUrl} alt="" className="h-10 w-10 rounded-lg bg-white object-contain p-1"/> : <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white font-bold" style={{color:form.data.primary_color}}>{initials}</div>}<div className="min-w-0 text-white"><p className="truncate font-semibold">{form.data.agency_name || 'Your Agency'}</p><p className="truncate text-xs text-white/70">{form.data.tagline || 'Client experience, branded by you.'}</p></div></div><div className="p-5"><p className="text-sm font-semibold">Client website preview</p><p className="mt-2 text-sm text-slate-500">{form.data.remove_cosmic_branding ? 'Cosmic attribution is hidden on eligible client-facing surfaces.' : 'Client-facing surfaces retain a subtle Built with Cosmic attribution.'}</p><button type="button" className="mt-5 rounded-lg px-4 py-2 text-sm font-semibold text-white" style={{backgroundColor:form.data.accent_color}}>View project</button></div></div></div>
        </div>

        <div className="mt-6 rounded-2xl border border-white/10 bg-[#111113] p-6">
            <div><h2 className="text-lg font-semibold text-white">Branded preview links</h2><p className="mt-1 text-sm text-slate-500">Create secure, no-login links for client review. Links can expire or be revoked at any time.</p></div>
            <form onSubmit={createLink} className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_170px_auto]">
                <select disabled={!canManage} value={linkForm.data.website_id} onChange={e=>linkForm.setData('website_id',e.target.value)} className="cosmic-dashboard-select rounded-xl border-white/10 bg-white/5 text-white"><option value="">Select website</option>{(branding.preview_links||[]).map(site=><option key={site.website_id} value={site.website_id}>{site.website_name}</option>)}</select>
                <input disabled={!canManage} value={linkForm.data.label} onChange={e=>linkForm.setData('label',e.target.value)} placeholder="Client or review label" className="rounded-xl border-white/10 bg-white/5 text-white"/>
                <select disabled={!canManage} value={linkForm.data.expires_in_days} onChange={e=>linkForm.setData('expires_in_days',Number(e.target.value))} className="cosmic-dashboard-select rounded-xl border-white/10 bg-white/5 text-white"><option value={1}>1 day</option><option value={3}>3 days</option><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select>
                <button disabled={!canManage || linkForm.processing || !linkForm.data.website_id} className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-violet-700 disabled:opacity-40">Create link</button>
            </form>
            <div className="mt-6 space-y-5">{(branding.preview_links||[]).map(site=><div key={site.website_id}><p className="mb-2 text-sm font-semibold text-white">{site.website_name}</p>{site.links.length===0?<p className="rounded-xl border border-dashed border-white/10 p-4 text-sm text-slate-500">No preview links yet.</p>:<div className="space-y-2">{site.links.map(link=><div key={link.id} className="flex flex-col gap-3 rounded-xl border border-white/10 bg-white/[0.02] p-4 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-medium text-white">{link.label || 'Client preview'}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${link.active?'bg-emerald-400/10 text-emerald-300':'bg-rose-400/10 text-rose-300'}`}>{link.active?'Active':'Inactive'}</span></div><p className="mt-1 truncate text-xs text-slate-500">{link.url}</p><p className="mt-1 text-xs text-slate-600">{link.views} views{link.expires_at?` · Expires ${new Date(link.expires_at).toLocaleDateString()}`:' · No expiry'}</p></div><div className="flex gap-2"><button type="button" disabled={!link.active} onClick={()=>copy(link.url,link.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300 disabled:opacity-30">{copied===link.id?'Copied':'Copy'}</button>{link.active&&canManage&&<button type="button" onClick={()=>router.delete(route('preview-links.revoke',link.id),{preserveScroll:true})} className="rounded-lg border border-rose-400/20 px-3 py-2 text-xs font-semibold text-rose-300">Revoke</button>}</div></div>)}</div>}</div>)}</div>
        </div>
    </section>;
}

function Field({label,error,children}) { return <label className="block"><span className="mb-2 block text-sm font-medium text-slate-300">{label}</span>{children}{error && <span className="mt-1 block text-xs text-rose-300">{error}</span>}</label> }
