<?php

namespace App\Cosmic\Pricing;

class BlockPricingRegistry
{
    public static function all(): array
    {
        return [
            // Core Collection — first 15 blocks available to Starter.
            'hero_headline' => ['label' => 'Hero Headline', 'category' => 'core', 'credits' => 10],
            'hero_centered_cta' => ['label' => 'Centered CTA Hero', 'category' => 'core', 'credits' => 10],
            'feature_image_left' => ['label' => 'Feature Image Left', 'category' => 'core', 'credits' => 10],
            'feature_image_right' => ['label' => 'Feature Image Right', 'category' => 'core', 'credits' => 10],
            'services_cards' => ['label' => 'Services Cards', 'category' => 'core', 'credits' => 10],
            'services_bento' => ['label' => 'Services Bento', 'category' => 'core', 'credits' => 20],
            'stats_modern' => ['label' => 'Modern Stats', 'category' => 'core', 'credits' => 10],
            'stats_animated_counters_premium' => ['label' => 'Animated Counters', 'category' => 'signature', 'credits' => 130],
            'stats_revenue_dashboard_premium' => ['label' => 'Revenue Dashboard', 'category' => 'signature', 'credits' => 140],
            'stats_growth_charts_premium' => ['label' => 'Growth Charts', 'category' => 'signature', 'credits' => 140],
            'stats_achievements_premium' => ['label' => 'Achievements', 'category' => 'signature', 'credits' => 130],
            'stats_global_presence_premium' => ['label' => 'Global Presence', 'category' => 'signature', 'credits' => 135],
            'stats_timeline_metrics_premium' => ['label' => 'Timeline Metrics', 'category' => 'signature', 'credits' => 135],
            'testimonials_carousel' => ['label' => 'Testimonials', 'category' => 'core', 'credits' => 10],
            'faq_accordion' => ['label' => 'FAQ Accordion', 'category' => 'core', 'credits' => 10],
            'faq_accordion_pro' => ['label' => 'Accordion Pro', 'category' => 'signature', 'credits' => 135],
            'faq_search_premium' => ['label' => 'Search FAQ', 'category' => 'signature', 'credits' => 135],
            'faq_categories_premium' => ['label' => 'FAQ Categories', 'category' => 'signature', 'credits' => 135],
            'faq_support_portal_premium' => ['label' => 'Support Portal', 'category' => 'signature', 'credits' => 135],
            'faq_documentation_premium' => ['label' => 'Documentation', 'category' => 'signature', 'credits' => 135],
            'lead_magnet_premium' => ['label' => 'Lead Magnet', 'category' => 'signature', 'credits' => 130],
            'lead_free_audit_premium' => ['label' => 'Free Audit', 'category' => 'signature', 'credits' => 135],
            'lead_website_audit_premium' => ['label' => 'Website Audit', 'category' => 'signature', 'credits' => 140],
            'lead_quote_form_premium' => ['label' => 'Quote Form', 'category' => 'signature', 'credits' => 135],
            'lead_roi_calculator_premium' => ['label' => 'ROI Calculator', 'category' => 'signature', 'credits' => 145],
            'lead_cost_calculator_premium' => ['label' => 'Cost Calculator', 'category' => 'signature', 'credits' => 145],
            'lead_consultation_booking_premium' => ['label' => 'Consultation Booking', 'category' => 'signature', 'credits' => 140],
            'sales_comparison_premium' => ['label' => 'Sales Comparison Table', 'category' => 'signature', 'credits' => 145],
            'sales_feature_matrix_premium' => ['label' => 'Sales Feature Matrix', 'category' => 'signature', 'credits' => 145],
            'sales_competitor_comparison_premium' => ['label' => 'Competitor Comparison', 'category' => 'signature', 'credits' => 155],
            'sales_roi_premium' => ['label' => 'Sales ROI', 'category' => 'signature', 'credits' => 150],
            'sales_guarantee_premium' => ['label' => 'Guarantee', 'category' => 'signature', 'credits' => 140],
            'sales_trust_premium' => ['label' => 'Trust Section', 'category' => 'signature', 'credits' => 140],
            'sales_integrations_premium' => ['label' => 'Integrations', 'category' => 'signature', 'credits' => 145],
            'agency_dashboard_preview_premium' => ['label' => 'Agency Dashboard Preview', 'category' => 'signature', 'credits' => 155],
            'agency_client_portal_premium' => ['label' => 'Client Portal', 'category' => 'signature', 'credits' => 155],
            'agency_white_label_showcase_premium' => ['label' => 'White Label Showcase', 'category' => 'signature', 'credits' => 155],
            'agency_website_management_premium' => ['label' => 'Website Management', 'category' => 'signature', 'credits' => 155],
            'agency_maintenance_plans_premium' => ['label' => 'Maintenance Plans', 'category' => 'signature', 'credits' => 150],
            'agency_support_plans_premium' => ['label' => 'Support Plans', 'category' => 'signature', 'credits' => 150],
            'agency_workflow_premium' => ['label' => 'Agency Workflow', 'category' => 'signature', 'credits' => 150],
            'agency_project_pipeline_premium' => ['label' => 'Project Pipeline', 'category' => 'signature', 'credits' => 155],
            'agency_client_reviews_premium' => ['label' => 'Client Reviews', 'category' => 'signature', 'credits' => 150],
            'agency_website_reports_premium' => ['label' => 'Website Reports', 'category' => 'signature', 'credits' => 155],
            'ai_prompt_showcase_premium' => ['label' => 'AI Prompt Showcase', 'category' => 'signature', 'credits' => 160],
            'ai_workflow_premium' => ['label' => 'AI Workflow', 'category' => 'signature', 'credits' => 160],
            'ai_assistant_premium' => ['label' => 'AI Assistant', 'category' => 'signature', 'credits' => 160],
            'ai_timeline_premium' => ['label' => 'AI Timeline', 'category' => 'signature', 'credits' => 160],
            'ai_builder_premium' => ['label' => 'AI Builder', 'category' => 'signature', 'credits' => 165],
            'ai_automation_premium' => ['label' => 'Automation', 'category' => 'signature', 'credits' => 165],
            'ai_credits_dashboard_premium' => ['label' => 'Credits Dashboard', 'category' => 'signature', 'credits' => 165],
            'ai_generation_process_premium' => ['label' => 'Generation Process', 'category' => 'signature', 'credits' => 165],
            'ai_statistics_premium' => ['label' => 'AI Statistics', 'category' => 'signature', 'credits' => 165],
            'ai_prompt_examples_premium' => ['label' => 'Prompt Examples', 'category' => 'signature', 'credits' => 165],
            'image_cta_banner' => ['label' => 'Image CTA Banner', 'category' => 'core', 'credits' => 10],
            'pricing_cards' => ['label' => 'Pricing Cards', 'category' => 'core', 'credits' => 20],
            'team_modern' => ['label' => 'Team Modern', 'category' => 'core', 'credits' => 10],
            'team_cards_premium' => ['label' => 'Team Cards', 'category' => 'signature', 'credits' => 130],
            'team_timeline_premium' => ['label' => 'Team Timeline', 'category' => 'signature', 'credits' => 130],
            'team_org_chart_premium' => ['label' => 'Organization Chart', 'category' => 'signature', 'credits' => 140],
            'team_leadership_premium' => ['label' => 'Leadership', 'category' => 'signature', 'credits' => 130],
            'team_culture_premium' => ['label' => 'Culture', 'category' => 'signature', 'credits' => 120],
            'team_open_positions_premium' => ['label' => 'Open Positions', 'category' => 'signature', 'credits' => 130],
            'contact_form_modern' => ['label' => 'Contact Form', 'category' => 'core', 'credits' => 10],
            'contact_details' => ['label' => 'Contact Details', 'category' => 'core', 'credits' => 10],
            'location_map' => ['label' => 'Location Map', 'category' => 'core', 'credits' => 10],

            // Growth Collection.
            'hero_background_image' => ['label' => 'Background Image Hero', 'category' => 'growth', 'credits' => 30],
            'hero_slider_fade' => ['label' => 'Fade Slider Hero', 'category' => 'signature', 'credits' => 150],
            'hero_ken_burns_premium' => ['label' => 'Ken Burns Cinematic Hero', 'category' => 'signature', 'credits' => 150],
            'hero_crossfade_gallery_premium' => ['label' => 'Crossfade Gallery Hero', 'category' => 'signature', 'credits' => 150],
            'hero_cinematic_slider_premium' => ['label' => 'Cinematic Slider Hero', 'category' => 'signature', 'credits' => 165],
            'hero_split_slider_premium' => ['label' => 'Split Slider Hero', 'category' => 'signature', 'credits' => 160],
            'hero_vertical_story_premium' => ['label' => 'Vertical Story Hero', 'category' => 'signature', 'credits' => 160],
            'hero_parallax_layers_premium' => ['label' => 'Parallax Layers Hero', 'category' => 'signature', 'credits' => 165],
            'hero_mouse_parallax_premium' => ['label' => 'Mouse Parallax Hero', 'category' => 'signature', 'credits' => 165],
            'hero_reveal_parallax_premium' => ['label' => 'Reveal Parallax Hero', 'category' => 'signature', 'credits' => 165],
            'hero_zoom_scroll_premium' => ['label' => 'Zoom Scroll Hero', 'category' => 'signature', 'credits' => 165],
            'hero_pinned_story_premium' => ['label' => 'Pinned Story Hero', 'category' => 'signature', 'credits' => 180],
            'hero_video_cinematic_premium' => ['label' => 'Video Cinematic Hero', 'category' => 'signature', 'credits' => 180],
            'hero_video_split_premium' => ['label' => 'Video Split Hero', 'category' => 'signature', 'credits' => 180],
            'hero_aurora_motion_premium' => ['label' => 'Aurora Motion Hero', 'category' => 'signature', 'credits' => 165],
            'hero_mesh_gradient_motion_premium' => ['label' => 'Mesh Gradient Motion Hero', 'category' => 'signature', 'credits' => 165],
            'hero_spotlight_cursor_premium' => ['label' => 'Spotlight Cursor Hero', 'category' => 'signature', 'credits' => 170],
            'hero_floating_cards_motion_premium' => ['label' => 'Floating Cards Motion Hero', 'category' => 'signature', 'credits' => 170],
            'hero_3d_tilt_product_premium' => ['label' => '3D Tilt Product Hero', 'category' => 'signature', 'credits' => 175],
            'hero_infinite_marquee_premium' => ['label' => 'Infinite Marquee Hero', 'category' => 'signature', 'credits' => 165],
            'hero_rotating_words_premium' => ['label' => 'Rotating Words Hero', 'category' => 'signature', 'credits' => 165],
            'hero_typewriter_premium' => ['label' => 'Typewriter Premium Hero', 'category' => 'signature', 'credits' => 165],
            'hero_curtain_reveal_premium' => ['label' => 'Curtain Reveal Hero', 'category' => 'signature', 'credits' => 175],
            'hero_image_mask_reveal_premium' => ['label' => 'Image Mask Reveal Hero', 'category' => 'signature', 'credits' => 175],
            'hero_stacked_cards_premium' => ['label' => 'Stacked Cards Hero', 'category' => 'signature', 'credits' => 175],
            'hero_perspective_carousel_premium' => ['label' => 'Perspective Carousel Hero', 'category' => 'signature', 'credits' => 180],
            'hero_before_after_premium' => ['label' => 'Before / After Hero', 'category' => 'signature', 'credits' => 180],
            'hero_scroll_morph_premium' => ['label' => 'Scroll Morph Hero', 'category' => 'signature', 'credits' => 180],
            'hero_glass_orb_premium' => ['label' => 'Glass Orb Hero', 'category' => 'signature', 'credits' => 175],
            'hero_particle_constellation_premium' => ['label' => 'Particle Constellation Hero', 'category' => 'signature', 'credits' => 180],
            'hero_grid_pulse_tech_premium' => ['label' => 'Grid Pulse Tech Hero', 'category' => 'signature', 'credits' => 175],
            'hero_light_trails_premium' => ['label' => 'Beam / Light Trails Hero', 'category' => 'signature', 'credits' => 175],
            'hero_device_showcase_premium' => ['label' => 'Device Showcase Hero', 'category' => 'signature', 'credits' => 180],
            'hero_app_screens_carousel_premium' => ['label' => 'App Screens Carousel Hero', 'category' => 'signature', 'credits' => 180],
            'hero_editorial_image_sequence_premium' => ['label' => 'Editorial Image Sequence Hero', 'category' => 'signature', 'credits' => 175],
            'hero_interactive_bento_premium' => ['label' => 'Interactive Bento Hero', 'category' => 'signature', 'credits' => 180],

            'hero_editorial_overlay' => ['label' => 'Editorial Overlay Hero', 'category' => 'growth', 'credits' => 30],
            'hero_split_image' => ['label' => 'Split Image Hero', 'category' => 'growth', 'credits' => 30],
            'hero_floating_cards' => ['label' => 'Floating Cards Hero', 'category' => 'growth', 'credits' => 40],
            'process_timeline' => ['label' => 'Process Timeline', 'category' => 'growth', 'credits' => 30],
            'case_studies_grid' => ['label' => 'Case Studies Grid', 'category' => 'growth', 'credits' => 30],
            'jobs_list' => ['label' => 'Jobs List', 'category' => 'growth', 'credits' => 20],

            'content_grid_classic' => ['label' => 'Content Loop · Grid', 'category' => 'growth', 'credits' => 30],
            'content_grid_editorial' => ['label' => 'Content Loop · Editorial', 'category' => 'growth', 'credits' => 30],
            'content_grid_compact' => ['label' => 'Content Loop · List', 'category' => 'growth', 'credits' => 30],
            'content_featured_entry' => ['label' => 'Featured Post', 'category' => 'growth', 'credits' => 30],
            'content_latest_entries' => ['label' => 'Latest Posts', 'category' => 'growth', 'credits' => 30],
            'content_events_grid' => ['label' => 'Upcoming Events', 'category' => 'growth', 'credits' => 30],
            'events_grid' => ['label' => 'Events Grid', 'category' => 'growth', 'credits' => 30],
            'blog_mini_hero' => ['label' => 'Blog Mini Hero', 'category' => 'growth', 'credits' => 20],
            'mini_hero_minimal' => ['label' => 'Mini Hero Minimal', 'category' => 'growth', 'credits' => 20],
            'mini_hero_split' => ['label' => 'Mini Hero Split Image', 'category' => 'growth', 'credits' => 20],
            'mini_hero_promo' => ['label' => 'Mini Hero Promo', 'category' => 'growth', 'credits' => 20],
            'blog_hub' => ['label' => 'Blog Hub', 'category' => 'growth', 'credits' => 30],
            'blog_magazine_premium' => ['label' => 'Magazine Layout', 'category' => 'signature', 'credits' => 135],
            'blog_featured_article_premium' => ['label' => 'Featured Article', 'category' => 'signature', 'credits' => 135],
            'blog_editors_pick_premium' => ['label' => "Editor's Pick", 'category' => 'signature', 'credits' => 135],
            'blog_sidebar_news_premium' => ['label' => 'Sidebar News', 'category' => 'signature', 'credits' => 135],
            'blog_newsletter_premium' => ['label' => 'Blog Newsletter', 'category' => 'signature', 'credits' => 135],
            'blog_trending_premium' => ['label' => 'Trending', 'category' => 'signature', 'credits' => 135],
            'blog_categories_grid_premium' => ['label' => 'Categories Grid', 'category' => 'signature', 'credits' => 135],
            'blog_author_profile_premium' => ['label' => 'Author Profile', 'category' => 'signature', 'credits' => 135],
            'newsletter_cta' => ['label' => 'Newsletter CTA', 'category' => 'growth', 'credits' => 20],
            'latest_resources' => ['label' => 'Latest Resources', 'category' => 'growth', 'credits' => 30],

            // Commerce Collection — reusable live catalog Sparks.
            'commerce_product_grid' => ['label' => 'Product Grid', 'category' => 'growth', 'credits' => 30],
            'commerce_catalog_grid' => ['label' => 'Shop Catalog Grid', 'category' => 'growth', 'credits' => 30],
            'commerce_catalog_editorial' => ['label' => 'Shop Catalog Editorial', 'category' => 'growth', 'credits' => 40],
            'commerce_catalog_compact' => ['label' => 'Shop Catalog Compact', 'category' => 'growth', 'credits' => 30],
            'commerce_categories' => ['label' => 'Shop Categories', 'category' => 'growth', 'credits' => 20],
            'commerce_product_gallery' => ['label' => 'Product Gallery', 'category' => 'growth', 'credits' => 30],
            'commerce_price' => ['label' => 'Product Price', 'category' => 'growth', 'credits' => 20],
            'commerce_variation_selector' => ['label' => 'Variation Selector', 'category' => 'growth', 'credits' => 30],
            'commerce_related_products' => ['label' => 'Related Products', 'category' => 'growth', 'credits' => 30],
            'commerce_featured_products' => ['label' => 'Featured Products', 'category' => 'growth', 'credits' => 30],
            'commerce_featured_collection' => ['label' => 'Featured Collection', 'category' => 'growth', 'credits' => 30],
            'commerce_promo_split' => ['label' => 'Promo Split Banner', 'category' => 'growth', 'credits' => 20],
            'commerce_benefits_strip' => ['label' => 'Benefits / Trust Strip', 'category' => 'growth', 'credits' => 20],
            'commerce_mini_cart' => ['label' => 'Mini Cart Shell', 'category' => 'growth', 'credits' => 30],
            'commerce_cart_classic' => ['label' => 'Cart Classic', 'category' => 'growth', 'credits' => 30],
            'commerce_cart_split' => ['label' => 'Cart Split Summary', 'category' => 'growth', 'credits' => 40],
            'commerce_cart_compact' => ['label' => 'Cart Compact', 'category' => 'growth', 'credits' => 30],
            'commerce_checkout_classic' => ['label' => 'Checkout Classic', 'category' => 'growth', 'credits' => 30],
            'commerce_checkout_split' => ['label' => 'Checkout Split', 'category' => 'growth', 'credits' => 40],
            'commerce_checkout_express' => ['label' => 'Checkout Express', 'category' => 'growth', 'credits' => 30],

            // Signature Collection.
            'hero_split_editorial' => ['label' => 'Hero Split Editorial', 'category' => 'signature', 'credits' => 60],
            'hero_floating_glass' => ['label' => 'Floating Glass Hero', 'category' => 'signature', 'credits' => 70],
            'hero_saas_dashboard' => ['label' => 'SaaS Dashboard Hero', 'category' => 'signature', 'credits' => 75],
            'hero_luxury_fullscreen' => ['label' => 'Luxury Fullscreen Hero', 'category' => 'signature', 'credits' => 80],
            'hero_video_premium' => ['label' => 'Video Hero Premium', 'category' => 'signature', 'credits' => 85],
            'hero_ai_conversation' => ['label' => 'AI Conversation Hero', 'category' => 'signature', 'credits' => 90],
            'hero_agency_showcase' => ['label' => 'Agency Showcase Hero', 'category' => 'signature', 'credits' => 95],
            'hero_bento_premium' => ['label' => 'Bento Hero', 'category' => 'signature', 'credits' => 100],
            'services_bento_premium' => ['label' => 'Bento Services Premium', 'category' => 'signature', 'credits' => 105],
            'services_pricing_comparison' => ['label' => 'Pricing Comparison Premium', 'category' => 'signature', 'credits' => 110],
            'services_feature_comparison' => ['label' => 'Feature Comparison Premium', 'category' => 'signature', 'credits' => 115],
            'services_hover_cards' => ['label' => 'Hover Cards Premium', 'category' => 'signature', 'credits' => 120],
            'services_sticky_scroll' => ['label' => 'Sticky Scroll Services', 'category' => 'signature', 'credits' => 125],
            'services_horizontal' => ['label' => 'Horizontal Services', 'category' => 'signature', 'credits' => 125],
            'services_interactive_tabs' => ['label' => 'Interactive Tabs', 'category' => 'signature', 'credits' => 125],
            'services_mega_grid' => ['label' => 'Mega Grid', 'category' => 'signature', 'credits' => 125],
            'pricing_comparison_premium' => ['label' => 'Comparison Table', 'category' => 'signature', 'credits' => 140],
            'pricing_toggle_premium' => ['label' => 'Toggle Monthly/Yearly', 'category' => 'signature', 'credits' => 140],
            'pricing_enterprise_premium' => ['label' => 'Enterprise Pricing', 'category' => 'signature', 'credits' => 145],
            'pricing_calculator_premium' => ['label' => 'Pricing Calculator', 'category' => 'signature', 'credits' => 145],
            'pricing_credit_premium' => ['label' => 'Credit Pricing', 'category' => 'signature', 'credits' => 145],
            'pricing_agency_premium' => ['label' => 'Agency Pricing', 'category' => 'signature', 'credits' => 150],
            'pricing_feature_matrix_premium' => ['label' => 'Feature Matrix', 'category' => 'signature', 'credits' => 150],
            'cta_glass_premium' => ['label' => 'Glass CTA', 'category' => 'signature', 'credits' => 125],
            'cta_gradient_premium' => ['label' => 'Gradient CTA', 'category' => 'signature', 'credits' => 125],
            'cta_newsletter_premium' => ['label' => 'Newsletter CTA', 'category' => 'signature', 'credits' => 125],
            'cta_book_demo_premium' => ['label' => 'Book Demo CTA', 'category' => 'signature', 'credits' => 130],
            'cta_calendly_premium' => ['label' => 'Calendly CTA', 'category' => 'signature', 'credits' => 130],
            'cta_free_trial_premium' => ['label' => 'Free Trial CTA', 'category' => 'signature', 'credits' => 125],
            'cta_countdown_premium' => ['label' => 'Countdown CTA', 'category' => 'signature', 'credits' => 130],
            'cta_limited_offer_premium' => ['label' => 'Limited Offer CTA', 'category' => 'signature', 'credits' => 125],
            'contact_split_premium' => ['label' => 'Split Contact', 'category' => 'signature', 'credits' => 130],
            'contact_map_premium' => ['label' => 'Map Contact', 'category' => 'signature', 'credits' => 130],
            'contact_appointment_premium' => ['label' => 'Appointment Booking', 'category' => 'signature', 'credits' => 135],
            'contact_support_center_premium' => ['label' => 'Support Center', 'category' => 'signature', 'credits' => 135],
            'contact_faq_premium' => ['label' => 'FAQ + Contact', 'category' => 'signature', 'credits' => 135],
            'contact_multistep_premium' => ['label' => 'Multi-step Contact', 'category' => 'signature', 'credits' => 140],
            'contact_live_chat_premium' => ['label' => 'Live Chat CTA', 'category' => 'signature', 'credits' => 130],

            'about_timeline_story' => ['label' => 'Timeline Story', 'category' => 'signature', 'credits' => 125],
            'about_founder_story' => ['label' => 'Founder Story', 'category' => 'signature', 'credits' => 125],
            'about_mission_grid' => ['label' => 'Mission Grid', 'category' => 'signature', 'credits' => 125],
            'about_interactive_stats' => ['label' => 'Interactive Company Stats', 'category' => 'signature', 'credits' => 125],
            'about_brand_journey' => ['label' => 'Brand Journey', 'category' => 'signature', 'credits' => 125],
            'about_awards_timeline' => ['label' => 'Awards Timeline', 'category' => 'signature', 'credits' => 125],
            'about_culture_section' => ['label' => 'Culture Section', 'category' => 'signature', 'credits' => 125],
            'about_office_gallery' => ['label' => 'Office Gallery', 'category' => 'signature', 'credits' => 125],
            'portfolio_masonry' => ['label' => 'Masonry Portfolio', 'category' => 'signature', 'credits' => 130],
            'portfolio_pinterest' => ['label' => 'Pinterest Portfolio', 'category' => 'signature', 'credits' => 130],
            'portfolio_hover_video' => ['label' => 'Hover Video Portfolio', 'category' => 'signature', 'credits' => 135],
            'portfolio_case_study' => ['label' => 'Case Study Portfolio', 'category' => 'signature', 'credits' => 135],
            'portfolio_before_after' => ['label' => 'Before After Portfolio', 'category' => 'signature', 'credits' => 135],
            'portfolio_filterable' => ['label' => 'Filterable Portfolio', 'category' => 'signature', 'credits' => 135],
            'portfolio_animated' => ['label' => 'Animated Portfolio', 'category' => 'signature', 'credits' => 135],
            'portfolio_project_timeline' => ['label' => 'Project Timeline', 'category' => 'signature', 'credits' => 135],
            'testimonials_video_premium' => ['label' => 'Video Testimonials', 'category' => 'signature', 'credits' => 135],
            'testimonials_scrolling_marquee' => ['label' => 'Scrolling Marquee', 'category' => 'signature', 'credits' => 135],
            'testimonials_wall_of_love' => ['label' => 'Wall of Love', 'category' => 'signature', 'credits' => 135],
            'testimonials_card_stack' => ['label' => 'Card Stack', 'category' => 'signature', 'credits' => 135],
            'testimonials_trust_dashboard' => ['label' => 'Trust Dashboard', 'category' => 'signature', 'credits' => 135],
            'testimonials_review_grid' => ['label' => 'Review Grid', 'category' => 'signature', 'credits' => 135],
            'testimonials_review_carousel_pro' => ['label' => 'Review Carousel Pro', 'category' => 'signature', 'credits' => 135],
            'hero_parallax' => ['label' => 'Hero Parallax', 'category' => 'signature', 'credits' => 100],
            'hero_video_style' => ['label' => 'Video Style Hero', 'category' => 'signature', 'credits' => 50],
            'hero_video_background' => ['label' => 'Video Background Hero', 'category' => 'signature', 'credits' => 50],
        ];
    }

    public static function get(string $type): array
    {
        return self::all()[$type] ?? ['label' => str($type)->headline()->toString(), 'category' => 'growth', 'credits' => 20];
    }

    public static function cost(string $type): int
    {
        return (int) self::get($type)['credits'];
    }

    public static function estimate(array $types): int
    {
        return collect($types)->sum(fn ($type) => self::cost((string) $type));
    }
}
