import { EditableText } from "../Shared/EditableText";
import { RepeatableControls, RepeatableRemoveButton, cloneLast, removeAt } from "../Shared/RepeatableControls";
import { getEffectiveTheme } from "../../../../theme/Theme";
const base=[{key:"eyebrow",type:"text",label:"Eyebrow"},{key:"heading",type:"text",label:"Heading"},{key:"text",type:"textarea",label:"Text"}];
const item=[{key:"title",type:"text",label:"Title"},{key:"text",type:"textarea",label:"Text"}];
const defs={
 sales_comparison_premium:{title:"Sales Comparison Table",eyebrow:"COMPARE OPTIONS",heading:"Make the decision easier to understand.",text:"Compare real options using supplied features and terms.",items:[{title:"Option A",text:"Add factual strengths and limits."},{title:"Option B",text:"Add factual strengths and limits."},{title:"Best fit",text:"Explain who each option suits."}]},
 sales_feature_matrix_premium:{title:"Sales Feature Matrix",eyebrow:"FEATURE MATRIX",heading:"See what matters at a glance.",text:"Organise supplied capabilities into a clear matrix.",items:[{title:"Core",text:"List real capabilities."},{title:"Advanced",text:"List real capabilities."},{title:"Support",text:"List real support details."}]},
 sales_competitor_comparison_premium:{title:"Competitor Comparison",eyebrow:"WHY CHOOSE US",heading:"Compare on facts, not noise.",text:"Use only verifiable competitor and product information.",items:[{title:"Your offer",text:"State factual strengths."},{title:"Alternative",text:"Use verified public or supplied facts."},{title:"Decision criteria",text:"Compare relevant criteria neutrally."}]},
 sales_roi_premium:{title:"Sales ROI",eyebrow:"BUSINESS CASE",heading:"Frame the value with transparent assumptions.",text:"Use supplied inputs to explain potential value without guarantees.",items:[{title:"Investment",text:"Use supplied cost or effort."},{title:"Potential value",text:"Use supplied assumptions only."},{title:"Payback logic",text:"Explain the calculation clearly."}]},
 sales_guarantee_premium:{title:"Guarantee",eyebrow:"OUR COMMITMENT",heading:"Make the promise clear — and keep it accurate.",text:"Present a real supplied guarantee, warranty, or assurance without inventing terms.",items:[{title:"What is covered",text:"Add the actual coverage or commitment."},{title:"What to expect",text:"Explain the real process or remedy."},{title:"Terms",text:"Link or summarise the supplied conditions."}]},
 sales_trust_premium:{title:"Trust Section",eyebrow:"WHY TRUST US",heading:"Give buyers reasons to feel confident.",text:"Show only real trust signals such as verified credentials, policies, clients, or security practices.",items:[{title:"Verified proof",text:"Add a real certification, client proof, or credential."},{title:"Clear process",text:"Explain a real safeguard or working standard."},{title:"Support",text:"Add a factual support or service commitment."}]},
 sales_integrations_premium:{title:"Integrations",eyebrow:"WORKS WITH YOUR STACK",heading:"Connect the tools your customers already use.",text:"Show only real or planned integrations supplied by the business.",items:[{title:"Platform one",text:"Add a real supported integration."},{title:"Platform two",text:"Add a real supported integration."},{title:"Platform three",text:"Add a real supported integration."}]}
};
function schema(type){const d=defs[type];return {type,title:d.title,category:"Sales",purpose:d.text,description:d.text,tags:["sales","comparison","premium","pro"],defaults:d,fields:[...base,{key:"items",type:"repeater",label:"Items",fields:item},{key:"note",type:"textarea",label:"Note"}]};}
export const SalesComparisonPremiumSchema=schema("sales_comparison_premium");
export const SalesFeatureMatrixPremiumSchema=schema("sales_feature_matrix_premium");
export const SalesCompetitorComparisonPremiumSchema=schema("sales_competitor_comparison_premium");
export const SalesRoiPremiumSchema=schema("sales_roi_premium");
export const SalesGuaranteePremiumSchema=schema("sales_guarantee_premium");
export const SalesTrustPremiumSchema=schema("sales_trust_premium");
export const SalesIntegrationsPremiumSchema=schema("sales_integrations_premium");
function Block({block,onUpdate,globalTheme,schema}){const theme=getEffectiveTheme(block.resolvedTheme,globalTheme);const d={...schema.defaults,...block};const items=d.items||[];return <section className={`px-6 py-20 ${theme.bg}`}><div className="mx-auto max-w-7xl"><EditableText value={d.eyebrow} onSave={eyebrow=>onUpdate({eyebrow})} className={`text-xs font-bold uppercase tracking-[.22em] ${theme.sub}`}/><EditableText value={d.heading} onSave={heading=>onUpdate({heading})} className={`mt-4 block max-w-4xl text-4xl font-black tracking-tight sm:text-5xl ${theme.text}`}/><EditableText value={d.text} isTextArea onSave={text=>onUpdate({text})} className={`mt-4 block max-w-3xl leading-7 ${theme.sub}`}/><div className="mt-10 grid gap-4 lg:grid-cols-3">{items.slice(0,6).map((x,i)=><article key={i} className={`rounded-3xl border p-6 ${theme.border} ${theme.card}`}><div className={`text-xs font-bold ${theme.sub}`}>0{i+1}</div><EditableText value={x.title} onSave={v=>{const next=[...items];next[i]={...next[i],title:v};onUpdate({items:next})}} className={`mt-8 block text-xl font-bold ${theme.text}`}/><EditableText value={x.text} isTextArea onSave={v=>{const next=[...items];next[i]={...next[i],text:v};onUpdate({items:next})}} className={`mt-3 block text-sm leading-6 ${theme.sub}`}/><RepeatableRemoveButton disabled={items.length<=1} onRemove={()=>onUpdate({items:removeAt(items,i,1)})}/></article>)}</div><RepeatableControls addLabel="Add sales item" removeLabel="Remove last" canRemove={items.length>1} onAdd={()=>items.length<6&&onUpdate({items:cloneLast(items,{title:"New item",text:"Describe this item."})})} onRemove={()=>items.length>1&&onUpdate({items:items.slice(0,-1)})}/></div></section>}
export const SalesComparisonPremiumBlock=p=><Block {...p} schema={SalesComparisonPremiumSchema}/>;
export const SalesFeatureMatrixPremiumBlock=p=><Block {...p} schema={SalesFeatureMatrixPremiumSchema}/>;
export const SalesCompetitorComparisonPremiumBlock=p=><Block {...p} schema={SalesCompetitorComparisonPremiumSchema}/>;
export const SalesRoiPremiumBlock=p=><Block {...p} schema={SalesRoiPremiumSchema}/>;
export const SalesGuaranteePremiumBlock=p=><Block {...p} schema={SalesGuaranteePremiumSchema}/>;
export const SalesTrustPremiumBlock=p=><Block {...p} schema={SalesTrustPremiumSchema}/>;
export const SalesIntegrationsPremiumBlock=p=><Block {...p} schema={SalesIntegrationsPremiumSchema}/>;
