export const ACTION_PRICING = {
    add_page: 30,
    add_menu_item: 10,
    generate_page: 5,
    generate_website: 10,
    ai_rewrite: 2,
};

export const BLOCK_PRICING = {
    hero_headline: { category: 'core', credits: 10 },
    hero_centered_cta: { category: 'core', credits: 10 },
    feature_image_left: { category: 'core', credits: 10 },
    feature_image_right: { category: 'core', credits: 10 },
    services_cards: { category: 'core', credits: 10 },
    services_bento: { category: 'core', credits: 20 },
    stats_modern: { category: 'core', credits: 10 },
    testimonials_carousel: { category: 'core', credits: 10 },
    faq_accordion: { category: 'core', credits: 10 },
    image_cta_banner: { category: 'core', credits: 10 },
    pricing_cards: { category: 'core', credits: 20 },
    team_modern: { category: 'core', credits: 10 },
    contact_form_modern: { category: 'core', credits: 10 },
    contact_details: { category: 'core', credits: 10 },
    location_map: { category: 'core', credits: 10 },
    hero_background_image: { category: 'growth', credits: 30 },
    hero_editorial_overlay: { category: 'growth', credits: 30 },
    hero_split_image: { category: 'growth', credits: 30 },
    hero_floating_cards: { category: 'growth', credits: 40 },
    process_timeline: { category: 'growth', credits: 30 },
    case_studies_grid: { category: 'growth', credits: 30 },
    jobs_list: { category: 'growth', credits: 20 },
    events_grid: { category: 'growth', credits: 30 },
    blog_mini_hero: { category: 'growth', credits: 20 },
    blog_hub: { category: 'growth', credits: 30 },
    newsletter_cta: { category: 'growth', credits: 20 },
    latest_resources: { category: 'growth', credits: 30 },
    hero_parallax: { category: 'signature', credits: 100 },
    hero_video_style: { category: 'signature', credits: 50 },
    hero_video_background: { category: 'signature', credits: 50 },
};

export const getBlockPrice = (type) => BLOCK_PRICING[type] || { category: 'growth', credits: 20 };
