<?php

namespace App\AI\Schemas;

class SchemaManager
{
    public static function map(): array
    {
        return [

            'hero_headline' => 'heroHeadlineSchema',

            'hero_floating_cards' => 'heroFloatingCardsSchema',

            'hero_video_background' => 'heroVideoBackgroundSchema',

            'hero_video_style' => 'heroVideoStyleSchema',

            'hero_background_image' => 'heroBackgroundImageSchema',

            'hero_slider_fade' => 'heroSliderFadeSchema',

            'hero_parallax' => 'heroParallaxSchema',

            'hero_editorial_overlay' => 'heroEditorialOverlaySchema',

            'hero_split_image' => 'heroSplitImageSchema',

            'hero_split_editorial' => 'heroSplitEditorialSchema',
            'hero_floating_glass' => 'heroFloatingGlassSchema',
            'hero_saas_dashboard' => 'heroSaasDashboardSchema',
            'hero_luxury_fullscreen' => 'heroLuxuryFullscreenSchema',
            'hero_video_premium' => 'heroVideoPremiumSchema',
            'hero_ai_conversation' => 'heroAiConversationSchema',
            'hero_agency_showcase' => 'heroAgencyShowcaseSchema',
            'hero_bento_premium' => 'heroBentoPremiumSchema',
            'hero_ken_burns_premium' => 'heroParallaxSchema',
            'hero_crossfade_gallery_premium' => 'heroParallaxSchema',
            'hero_cinematic_slider_premium' => 'heroParallaxSchema',
            'hero_split_slider_premium' => 'heroParallaxSchema',
            'hero_vertical_story_premium' => 'heroParallaxSchema',
            'hero_parallax_layers_premium' => 'heroParallaxSchema',
            'hero_mouse_parallax_premium' => 'heroParallaxSchema',
            'hero_reveal_parallax_premium' => 'heroParallaxSchema',
            'hero_zoom_scroll_premium' => 'heroParallaxSchema',
            'hero_pinned_story_premium' => 'heroParallaxSchema',
            'hero_video_cinematic_premium' => 'heroParallaxSchema',
            'hero_video_split_premium' => 'heroParallaxSchema',
            'hero_aurora_motion_premium' => 'heroParallaxSchema',
            'hero_mesh_gradient_motion_premium' => 'heroParallaxSchema',
            'hero_spotlight_cursor_premium' => 'heroParallaxSchema',
            'hero_floating_cards_motion_premium' => 'heroParallaxSchema',
            'hero_3d_tilt_product_premium' => 'heroParallaxSchema',
            'hero_infinite_marquee_premium' => 'heroParallaxSchema',
            'hero_rotating_words_premium' => 'heroParallaxSchema',
            'hero_typewriter_premium' => 'heroParallaxSchema',
            'hero_curtain_reveal_premium' => 'heroParallaxSchema',
            'hero_image_mask_reveal_premium' => 'heroParallaxSchema',
            'hero_stacked_cards_premium' => 'heroParallaxSchema',
            'hero_perspective_carousel_premium' => 'heroParallaxSchema',
            'hero_before_after_premium' => 'heroParallaxSchema',
            'hero_scroll_morph_premium' => 'heroParallaxSchema',
            'hero_glass_orb_premium' => 'heroParallaxSchema',
            'hero_particle_constellation_premium' => 'heroParallaxSchema',
            'hero_grid_pulse_tech_premium' => 'heroParallaxSchema',
            'hero_light_trails_premium' => 'heroParallaxSchema',
            'hero_device_showcase_premium' => 'heroParallaxSchema',
            'hero_app_screens_carousel_premium' => 'heroParallaxSchema',
            'hero_editorial_image_sequence_premium' => 'heroParallaxSchema',
            'hero_interactive_bento_premium' => 'heroParallaxSchema',

            'about_founder_visual_premium' => 'aboutFounderVisualPremiumSchema',
            'about_image_manifesto_premium' => 'aboutImageManifestoPremiumSchema',
            'about_journey_gallery_premium' => 'aboutJourneyGalleryPremiumSchema',
            'about_story_collage_premium' => 'aboutStoryCollagePremiumSchema',
            'brand_value_cards_premium' => 'brandValueCardsPremiumSchema',
            'brand_visual_principles_premium' => 'brandVisualPrinciplesPremiumSchema',
            'construction_capability_split_premium' => 'constructionCapabilitySplitPremiumSchema',
            'construction_project_cards_premium' => 'constructionProjectCardsPremiumSchema',
            'construction_service_photos_premium' => 'constructionServicePhotosPremiumSchema',
            'construction_site_progress_premium' => 'constructionSiteProgressPremiumSchema',
            'contact_editorial_split_premium' => 'contactEditorialSplitPremiumSchema',
            'contact_image_form_premium' => 'contactImageFormPremiumSchema',
            'contact_office_cards_premium' => 'contactOfficeCardsPremiumSchema',
            'contact_visual_inquiry_premium' => 'contactVisualInquiryPremiumSchema',
            'content_asymmetric_story_premium' => 'contentAsymmetricStoryPremiumSchema',
            'content_editorial_image_stack_premium' => 'contentEditorialImageStackPremiumSchema',
            'content_media_manifesto_premium' => 'contentMediaManifestoPremiumSchema',
            'content_visual_quote_premium' => 'contentVisualQuotePremiumSchema',
            'cta_background_media_premium' => 'ctaBackgroundMediaPremiumSchema',
            'cta_editorial_banner_premium' => 'ctaEditorialBannerPremiumSchema',
            'cta_floating_panel_premium' => 'ctaFloatingPanelPremiumSchema',
            'cta_image_split_premium' => 'ctaImageSplitPremiumSchema',
            'cta_media_cards_premium' => 'ctaMediaCardsPremiumSchema',
            'dental_clinic_story_premium' => 'dentalClinicStoryPremiumSchema',
            'dental_treatment_cards_premium' => 'dentalTreatmentCardsPremiumSchema',
            'features_asymmetric_media_premium' => 'featuresAsymmetricMediaPremiumSchema',
            'features_editorial_mosaic_premium' => 'featuresEditorialMosaicPremiumSchema',
            'features_fullbleed_panels_premium' => 'featuresFullbleedPanelsPremiumSchema',
            'features_image_index_premium' => 'featuresImageIndexPremiumSchema',
            'features_image_stack_premium' => 'featuresImageStackPremiumSchema',
            'features_media_steps_premium' => 'featuresMediaStepsPremiumSchema',
            'features_overlap_cards_premium' => 'featuresOverlapCardsPremiumSchema',
            'features_spotlight_cards_premium' => 'featuresSpotlightCardsPremiumSchema',
            'features_visual_split_premium' => 'featuresVisualSplitPremiumSchema',
            'gallery_asymmetric_premium' => 'galleryAsymmetricPremiumSchema',
            'gallery_editorial_grid_premium' => 'galleryEditorialGridPremiumSchema',
            'gallery_image_rail_premium' => 'galleryImageRailPremiumSchema',
            'gallery_story_tiles_premium' => 'galleryStoryTilesPremiumSchema',
            'hotel_experience_cards_premium' => 'hotelExperienceCardsPremiumSchema',
            'hotel_room_collection_premium' => 'hotelRoomCollectionPremiumSchema',
            'location_city_spotlight_premium' => 'locationCitySpotlightPremiumSchema',
            'location_multi_office_premium' => 'locationMultiOfficePremiumSchema',
            'location_photo_cards_premium' => 'locationPhotoCardsPremiumSchema',
            'location_visual_directory_premium' => 'locationVisualDirectoryPremiumSchema',
            'medical_care_pathways_premium' => 'medicalCarePathwaysPremiumSchema',
            'medical_facility_showcase_premium' => 'medicalFacilityShowcasePremiumSchema',
            'portfolio_cinematic_grid_premium' => 'portfolioCinematicGridPremiumSchema',
            'portfolio_editorial_cards_premium' => 'portfolioEditorialCardsPremiumSchema',
            'portfolio_fullbleed_projects_premium' => 'portfolioFullbleedProjectsPremiumSchema',
            'portfolio_image_index_premium' => 'portfolioImageIndexPremiumSchema',
            'portfolio_media_ledger_premium' => 'portfolioMediaLedgerPremiumSchema',
            'portfolio_project_panels_premium' => 'portfolioProjectPanelsPremiumSchema',
            'portfolio_split_showcase_premium' => 'portfolioSplitShowcasePremiumSchema',
            'portfolio_staggered_gallery_premium' => 'portfolioStaggeredGalleryPremiumSchema',
            'portfolio_story_index_premium' => 'portfolioStoryIndexPremiumSchema',
            'process_editorial_journey_premium' => 'processEditorialJourneyPremiumSchema',
            'process_image_timeline_premium' => 'processImageTimelinePremiumSchema',
            'process_media_roadmap_premium' => 'processMediaRoadmapPremiumSchema',
            'process_numbered_panels_premium' => 'processNumberedPanelsPremiumSchema',
            'process_visual_steps_premium' => 'processVisualStepsPremiumSchema',
            'proof_case_story_premium' => 'proofCaseStoryPremiumSchema',
            'proof_metric_gallery_premium' => 'proofMetricGalleryPremiumSchema',
            'realestate_agent_story_premium' => 'realestateAgentStoryPremiumSchema',
            'realestate_featured_listing_premium' => 'realestateFeaturedListingPremiumSchema',
            'realestate_neighborhood_cards_premium' => 'realestateNeighborhoodCardsPremiumSchema',
            'realestate_property_grid_premium' => 'realestatePropertyGridPremiumSchema',
            'restaurant_atmosphere_gallery_premium' => 'restaurantAtmosphereGalleryPremiumSchema',
            'restaurant_reservation_cta_premium' => 'restaurantReservationCtaPremiumSchema',
            'restaurant_signature_dishes_premium' => 'restaurantSignatureDishesPremiumSchema',
            'restaurant_story_menu_premium' => 'restaurantStoryMenuPremiumSchema',
            'services_editorial_rows_premium' => 'servicesEditorialRowsPremiumSchema',
            'services_fullbleed_overlay_premium' => 'servicesFullbleedOverlayPremiumSchema',
            'services_horizontal_media_premium' => 'servicesHorizontalMediaPremiumSchema',
            'services_image_accordion_premium' => 'servicesImageAccordionPremiumSchema',
            'services_image_trio_premium' => 'servicesImageTrioPremiumSchema',
            'services_mosaic_media_premium' => 'servicesMosaicMediaPremiumSchema',
            'services_numbered_images_premium' => 'servicesNumberedImagesPremiumSchema',
            'services_overlay_grid_premium' => 'servicesOverlayGridPremiumSchema',
            'services_staggered_media_premium' => 'servicesStaggeredMediaPremiumSchema',
            'services_visual_directory_premium' => 'servicesVisualDirectoryPremiumSchema',
            'stats_editorial_numbers_premium' => 'statsEditorialNumbersPremiumSchema',
            'stats_image_panels_premium' => 'statsImagePanelsPremiumSchema',
            'stats_photo_metrics_premium' => 'statsPhotoMetricsPremiumSchema',
            'stats_visual_mosaic_premium' => 'statsVisualMosaicPremiumSchema',
            'team_image_grid_premium' => 'teamImageGridPremiumSchema',
            'team_leadership_split_premium' => 'teamLeadershipSplitPremiumSchema',
            'team_people_mosaic_premium' => 'teamPeopleMosaicPremiumSchema',
            'team_portrait_editorial_premium' => 'teamPortraitEditorialPremiumSchema',
            'team_profile_overlay_premium' => 'teamProfileOverlayPremiumSchema',
            'testimonials_client_spotlight_premium' => 'testimonialsClientSpotlightPremiumSchema',
            'testimonials_editorial_quotes_premium' => 'testimonialsEditorialQuotesPremiumSchema',
            'testimonials_featured_story_premium' => 'testimonialsFeaturedStoryPremiumSchema',
            'testimonials_image_wall_premium' => 'testimonialsImageWallPremiumSchema',
            'testimonials_portrait_cards_premium' => 'testimonialsPortraitCardsPremiumSchema',
            'travel_destination_story_premium' => 'travelDestinationStoryPremiumSchema',
            'travel_itinerary_visual_premium' => 'travelItineraryVisualPremiumSchema',
            'trust_certification_cards_premium' => 'trustCertificationCardsPremiumSchema',
            'trust_image_proof_premium' => 'trustImageProofPremiumSchema',
            'trust_logo_story_premium' => 'trustLogoStoryPremiumSchema',
            'trust_partner_showcase_premium' => 'trustPartnerShowcasePremiumSchema',

            'blog_mini_hero' => 'blogMiniHeroSchema',
            'commerce_cart_classic' => 'commerceCartClassicSchema',
            'commerce_cart_compact' => 'commerceCartCompactSchema',
            'commerce_cart_split' => 'commerceCartSplitSchema',

            'commerce_catalog_compact' => 'commerceCatalogCompactSchema',
            'commerce_catalog_editorial' => 'commerceCatalogEditorialSchema',
            'commerce_catalog_grid' => 'commerceCatalogGridSchema',
            'commerce_categories' => 'commerceCategoriesSchema',
            'commerce_checkout_classic' => 'commerceCheckoutClassicSchema',
            'commerce_checkout_express' => 'commerceCheckoutExpressSchema',
            'commerce_checkout_split' => 'commerceCheckoutSplitSchema',
            'commerce_featured_collection' => 'commerceFeaturedCollectionSchema',
            'commerce_featured_products' => 'commerceFeaturedProductsSchema',
            'commerce_mini_cart' => 'commerceMiniCartSchema',
            'commerce_price' => 'commercePriceSchema',
            'commerce_product_gallery' => 'commerceProductGallerySchema',
            'commerce_promo_split' => 'commercePromoSplitSchema',
            'commerce_related_products' => 'commerceRelatedProductsSchema',
            'commerce_variation_selector' => 'commerceVariationSelectorSchema',
            'content_events_grid' => 'contentEventsGridSchema',
            'content_featured_entry' => 'contentFeaturedEntrySchema',
            'content_grid_classic' => 'contentGridClassicSchema',
            'content_grid_compact' => 'contentGridCompactSchema',
            'content_grid_editorial' => 'contentGridEditorialSchema',
            'content_latest_entries' => 'contentLatestEntriesSchema',

            'mini_hero_minimal' => 'miniHeroMinimalSchema',
            'mini_hero_promo' => 'miniHeroPromoSchema',
            'mini_hero_split' => 'miniHeroSplitSchema',
            'newsletter_cta' => 'newsletterCtaSchema',

            'image_cta_banner' => 'imageCtaBannerSchema',

            'feature_image_left' => 'featureImageLeftSchema',

            'feature_image_right' => 'featureImageRightSchema',

            'services_cards' => 'servicesCardsSchema',

            'services_bento' => 'servicesBentoSchema',
            'services_bento_premium' => 'servicesBentoPremiumSchema',
            'services_editorial_premium' => 'servicesEditorialPremiumSchema',
            'services_showcase_premium' => 'servicesShowcasePremiumSchema',
            'services_minimal_luxury' => 'servicesMinimalLuxurySchema',
            'services_contrast_premium' => 'servicesContrastPremiumSchema',
            'services_split_premium' => 'servicesSplitPremiumSchema',
            'services_grid_premium' => 'servicesGridPremiumSchema',
            'services_feature_premium' => 'servicesFeaturePremiumSchema',
            'services_pricing_comparison' => 'servicesPricingComparisonSchema',
            'services_feature_comparison' => 'servicesFeatureComparisonSchema',
            'services_hover_cards' => 'servicesHoverCardsSchema',
            'services_sticky_scroll' => 'servicesStickyScrollSchema',
            'services_horizontal' => 'servicesHorizontalSchema',
            'services_interactive_tabs' => 'servicesInteractiveTabsSchema',
            'services_mega_grid' => 'servicesMegaGridSchema',
            'about_timeline_story' => 'aboutTimelineStorySchema',
            'about_founder_story' => 'aboutFounderStorySchema',
            'about_mission_grid' => 'aboutMissionGridSchema',
            'about_interactive_stats' => 'aboutInteractiveStatsSchema',
            'about_brand_journey' => 'aboutBrandJourneySchema',
            'about_awards_timeline' => 'aboutAwardsTimelineSchema',
            'about_culture_section' => 'aboutCultureSectionSchema',
            'about_office_gallery' => 'aboutOfficeGallerySchema',
            'portfolio_masonry' => 'portfolioMasonrySchema',
            'portfolio_pinterest' => 'portfolioPinterestSchema',
            'portfolio_hover_video' => 'portfolioHoverVideoSchema',
            'portfolio_case_study' => 'portfolioCaseStudySchema',
            'portfolio_before_after' => 'portfolioBeforeAfterSchema',
            'portfolio_filterable' => 'portfolioFilterableSchema',
            'portfolio_animated' => 'portfolioAnimatedSchema',
            'portfolio_project_timeline' => 'portfolioProjectTimelineSchema',

            'process_timeline' => 'processTimelineSchema',

            'stats_modern' => 'statsModernSchema',
            'stats_animated_counters_premium' => 'statsAnimatedCountersPremiumSchema',
            'stats_revenue_dashboard_premium' => 'statsRevenueDashboardPremiumSchema',
            'stats_growth_charts_premium' => 'statsGrowthChartsPremiumSchema',
            'stats_achievements_premium' => 'statsAchievementsPremiumSchema',
            'stats_global_presence_premium' => 'statsGlobalPresencePremiumSchema',
            'stats_timeline_metrics_premium' => 'statsTimelineMetricsPremiumSchema',

            'team_modern' => 'teamModernSchema',
            'team_cards_premium' => 'teamCardsPremiumSchema',
            'team_timeline_premium' => 'teamTimelinePremiumSchema',
            'team_org_chart_premium' => 'teamOrgChartPremiumSchema',
            'team_leadership_premium' => 'teamLeadershipPremiumSchema',
            'team_culture_premium' => 'teamCulturePremiumSchema',
            'team_open_positions_premium' => 'teamOpenPositionsPremiumSchema',

            'testimonials_carousel' => 'testimonialsSchema',
            'testimonials_video_premium' => 'testimonialsVideoPremiumSchema',
            'testimonials_scrolling_marquee' => 'testimonialsScrollingMarqueeSchema',
            'testimonials_wall_of_love' => 'testimonialsWallOfLoveSchema',
            'testimonials_card_stack' => 'testimonialsCardStackSchema',
            'testimonials_trust_dashboard' => 'testimonialsTrustDashboardSchema',
            'testimonials_review_grid' => 'testimonialsReviewGridSchema',
            'testimonials_review_carousel_pro' => 'testimonialsReviewCarouselProSchema',

            'hero_centered_cta' => 'heroCtaSchema',
            'cta_glass_premium' => 'ctaGlassPremiumSchema',
            'cta_gradient_premium' => 'ctaGradientPremiumSchema',
            'cta_newsletter_premium' => 'ctaNewsletterPremiumSchema',
            'cta_book_demo_premium' => 'ctaBookDemoPremiumSchema',
            'cta_calendly_premium' => 'ctaCalendlyPremiumSchema',
            'cta_free_trial_premium' => 'ctaFreeTrialPremiumSchema',
            'cta_countdown_premium' => 'ctaCountdownPremiumSchema',
            'cta_limited_offer_premium' => 'ctaLimitedOfferPremiumSchema',

            'pricing_cards' => 'pricingCardsSchema',
            'pricing_comparison_premium' => 'pricingComparisonPremiumSchema',
            'pricing_toggle_premium' => 'pricingTogglePremiumSchema',
            'pricing_enterprise_premium' => 'pricingEnterprisePremiumSchema',
            'pricing_calculator_premium' => 'pricingCalculatorPremiumSchema',
            'pricing_credit_premium' => 'pricingCreditPremiumSchema',
            'pricing_agency_premium' => 'pricingAgencyPremiumSchema',
            'pricing_feature_matrix_premium' => 'pricingFeatureMatrixPremiumSchema',

            'contact_form_modern' => 'contactFormModernSchema',
            'contact_split_premium' => 'contactSplitPremiumSchema',
            'contact_map_premium' => 'contactMapPremiumSchema',
            'contact_appointment_premium' => 'contactAppointmentPremiumSchema',
            'contact_support_center_premium' => 'contactSupportCenterPremiumSchema',
            'contact_faq_premium' => 'contactFaqPremiumSchema',
            'contact_multistep_premium' => 'contactMultiStepPremiumSchema',
            'contact_live_chat_premium' => 'contactLiveChatPremiumSchema',
            'blog_hub' => 'dynamicBlogHubSchema',
            'latest_resources' => 'dynamicLatestResourcesSchema',
            'commerce_product_grid' => 'dynamicCommerceProductGridSchema',
            'commerce_benefits_strip' => 'dynamicCommerceBenefitsStripSchema',
            'blog_magazine_premium' => 'blogMagazinePremiumSchema',
            'blog_featured_article_premium' => 'blogFeaturedArticlePremiumSchema',
            'blog_editors_pick_premium' => 'blogEditorsPickPremiumSchema',
            'blog_sidebar_news_premium' => 'blogSidebarNewsPremiumSchema',
            'blog_newsletter_premium' => 'blogNewsletterPremiumSchema',
            'blog_trending_premium' => 'blogTrendingPremiumSchema',
            'blog_categories_grid_premium' => 'blogCategoriesGridPremiumSchema',
            'blog_author_profile_premium' => 'blogAuthorProfilePremiumSchema',

            'faq_accordion' => 'faqAccordionSchema',
            'faq_accordion_pro' => 'faqAccordionProSchema',
            'faq_search_premium' => 'faqSearchPremiumSchema',
            'faq_categories_premium' => 'faqCategoriesPremiumSchema',
            'faq_support_portal_premium' => 'faqSupportPortalPremiumSchema',
            'faq_documentation_premium' => 'faqDocumentationPremiumSchema',
            'lead_magnet_premium' => 'leadMagnetPremiumSchema',
            'lead_free_audit_premium' => 'leadFreeAuditPremiumSchema',
            'lead_website_audit_premium' => 'leadWebsiteAuditPremiumSchema',
            'lead_quote_form_premium' => 'leadQuoteFormPremiumSchema',
            'lead_roi_calculator_premium' => 'leadRoiCalculatorPremiumSchema',
            'lead_cost_calculator_premium' => 'leadCostCalculatorPremiumSchema',
            'lead_consultation_booking_premium' => 'leadConsultationBookingPremiumSchema',
            'sales_comparison_premium' => 'salesComparisonPremiumSchema',
            'sales_feature_matrix_premium' => 'salesFeatureMatrixPremiumSchema',
            'sales_competitor_comparison_premium' => 'salesCompetitorComparisonPremiumSchema',
            'sales_roi_premium' => 'salesRoiPremiumSchema',
            'sales_guarantee_premium' => 'salesGuaranteePremiumSchema',
            'sales_trust_premium' => 'salesTrustPremiumSchema',
            'sales_integrations_premium' => 'salesIntegrationsPremiumSchema',
            'agency_dashboard_preview_premium' => 'agencyDashboardPreviewPremiumSchema',
            'agency_client_portal_premium' => 'agencyClientPortalPremiumSchema',
            'agency_white_label_showcase_premium' => 'agencyWhiteLabelShowcasePremiumSchema',
            'agency_website_management_premium' => 'agencyWebsiteManagementPremiumSchema',
            'agency_maintenance_plans_premium' => 'agencyMaintenancePlansPremiumSchema',
            'agency_support_plans_premium' => 'agencySupportPlansPremiumSchema',
            'agency_workflow_premium' => 'agencyWorkflowPremiumSchema',
            'agency_project_pipeline_premium' => 'agencyProjectPipelinePremiumSchema',
            'agency_client_reviews_premium' => 'agencyClientReviewsPremiumSchema',
            'agency_website_reports_premium' => 'agencyWebsiteReportsPremiumSchema',
            'ai_prompt_showcase_premium' => 'aiPromptShowcasePremiumSchema',
            'ai_workflow_premium' => 'aiWorkflowPremiumSchema',
            'ai_assistant_premium' => 'aiAssistantPremiumSchema',
            'ai_timeline_premium' => 'aiTimelinePremiumSchema',
            'ai_builder_premium' => 'aiBuilderPremiumSchema',
            'ai_automation_premium' => 'aiAutomationPremiumSchema',
            'ai_credits_dashboard_premium' => 'aiCreditsDashboardPremiumSchema',
            'ai_generation_process_premium' => 'aiGenerationProcessPremiumSchema',
            'ai_statistics_premium' => 'aiStatisticsPremiumSchema',
            'ai_prompt_examples_premium' => 'aiPromptExamplesPremiumSchema',

            'contact_details' => 'contactDetailsSchema',

            'location_map' => 'locationMapSchema',

            'case_studies_grid' => 'caseStudiesGridSchema',

            'jobs_list' => 'jobsListSchema',

            'events_grid' => 'eventsGridSchema',

        ];
    }
}
