<?php

namespace App\AI\Schemas;

class SchemaManager
{
    public static function map(): array
    {
        return [

            'hero_headline' => 'heroHeadlineSchema',

            'hero_floating_cards' => 'heroFloatingCardsSchema',

            'hero_video_background' => 'heroVideoBackgroundSchema',

            'hero_video_style' => 'heroVideoStyleSchema',

            'hero_background_image' => 'heroBackgroundImageSchema',

            'hero_slider_fade' => 'heroSliderFadeSchema',

            'hero_parallax' => 'heroParallaxSchema',

            'hero_editorial_overlay' => 'heroEditorialOverlaySchema',

            'hero_split_image' => 'heroSplitImageSchema',

            'hero_split_editorial' => 'heroSplitEditorialSchema',
            'hero_floating_glass' => 'heroFloatingGlassSchema',
            'hero_saas_dashboard' => 'heroSaasDashboardSchema',
            'hero_luxury_fullscreen' => 'heroLuxuryFullscreenSchema',
            'hero_video_premium' => 'heroVideoPremiumSchema',
            'hero_ai_conversation' => 'heroAiConversationSchema',
            'hero_agency_showcase' => 'heroAgencyShowcaseSchema',
            'hero_bento_premium' => 'heroBentoPremiumSchema',
            'hero_ken_burns_premium' => 'heroParallaxSchema',
            'hero_crossfade_gallery_premium' => 'heroParallaxSchema',
            'hero_cinematic_slider_premium' => 'heroParallaxSchema',
            'hero_split_slider_premium' => 'heroParallaxSchema',
            'hero_vertical_story_premium' => 'heroParallaxSchema',
            'hero_parallax_layers_premium' => 'heroParallaxSchema',
            'hero_mouse_parallax_premium' => 'heroParallaxSchema',
            'hero_reveal_parallax_premium' => 'heroParallaxSchema',
            'hero_zoom_scroll_premium' => 'heroParallaxSchema',
            'hero_pinned_story_premium' => 'heroParallaxSchema',
            'hero_video_cinematic_premium' => 'heroParallaxSchema',
            'hero_video_split_premium' => 'heroParallaxSchema',
            'hero_aurora_motion_premium' => 'heroParallaxSchema',
            'hero_mesh_gradient_motion_premium' => 'heroParallaxSchema',
            'hero_spotlight_cursor_premium' => 'heroParallaxSchema',
            'hero_floating_cards_motion_premium' => 'heroParallaxSchema',
            'hero_3d_tilt_product_premium' => 'heroParallaxSchema',
            'hero_infinite_marquee_premium' => 'heroParallaxSchema',
            'hero_rotating_words_premium' => 'heroParallaxSchema',
            'hero_typewriter_premium' => 'heroParallaxSchema',
            'hero_curtain_reveal_premium' => 'heroParallaxSchema',
            'hero_image_mask_reveal_premium' => 'heroParallaxSchema',
            'hero_stacked_cards_premium' => 'heroParallaxSchema',
            'hero_perspective_carousel_premium' => 'heroParallaxSchema',
            'hero_before_after_premium' => 'heroParallaxSchema',
            'hero_scroll_morph_premium' => 'heroParallaxSchema',
            'hero_glass_orb_premium' => 'heroParallaxSchema',
            'hero_particle_constellation_premium' => 'heroParallaxSchema',
            'hero_grid_pulse_tech_premium' => 'heroParallaxSchema',
            'hero_light_trails_premium' => 'heroParallaxSchema',
            'hero_device_showcase_premium' => 'heroParallaxSchema',
            'hero_app_screens_carousel_premium' => 'heroParallaxSchema',
            'hero_editorial_image_sequence_premium' => 'heroParallaxSchema',
            'hero_interactive_bento_premium' => 'heroParallaxSchema',

            'image_cta_banner' => 'imageCtaBannerSchema',

            'feature_image_left' => 'featureImageLeftSchema',

            'feature_image_right' => 'featureImageRightSchema',

            'services_cards' => 'servicesCardsSchema',

            'services_bento' => 'servicesBentoSchema',
            'services_bento_premium' => 'servicesBentoPremiumSchema',
            'services_pricing_comparison' => 'servicesPricingComparisonSchema',
            'services_feature_comparison' => 'servicesFeatureComparisonSchema',
            'services_hover_cards' => 'servicesHoverCardsSchema',
            'services_sticky_scroll' => 'servicesStickyScrollSchema',
            'services_horizontal' => 'servicesHorizontalSchema',
            'services_interactive_tabs' => 'servicesInteractiveTabsSchema',
            'services_mega_grid' => 'servicesMegaGridSchema',
            'about_timeline_story' => 'aboutTimelineStorySchema',
            'about_founder_story' => 'aboutFounderStorySchema',
            'about_mission_grid' => 'aboutMissionGridSchema',
            'about_interactive_stats' => 'aboutInteractiveStatsSchema',
            'about_brand_journey' => 'aboutBrandJourneySchema',
            'about_awards_timeline' => 'aboutAwardsTimelineSchema',
            'about_culture_section' => 'aboutCultureSectionSchema',
            'about_office_gallery' => 'aboutOfficeGallerySchema',
            'portfolio_masonry' => 'portfolioMasonrySchema',
            'portfolio_pinterest' => 'portfolioPinterestSchema',
            'portfolio_hover_video' => 'portfolioHoverVideoSchema',
            'portfolio_case_study' => 'portfolioCaseStudySchema',
            'portfolio_before_after' => 'portfolioBeforeAfterSchema',
            'portfolio_filterable' => 'portfolioFilterableSchema',
            'portfolio_animated' => 'portfolioAnimatedSchema',
            'portfolio_project_timeline' => 'portfolioProjectTimelineSchema',

            'process_timeline' => 'processTimelineSchema',

            'stats_modern' => 'statsModernSchema',
            'stats_animated_counters_premium' => 'statsAnimatedCountersPremiumSchema',
            'stats_revenue_dashboard_premium' => 'statsRevenueDashboardPremiumSchema',
            'stats_growth_charts_premium' => 'statsGrowthChartsPremiumSchema',
            'stats_achievements_premium' => 'statsAchievementsPremiumSchema',
            'stats_global_presence_premium' => 'statsGlobalPresencePremiumSchema',
            'stats_timeline_metrics_premium' => 'statsTimelineMetricsPremiumSchema',

            'team_modern' => 'teamModernSchema',
            'team_cards_premium' => 'teamCardsPremiumSchema',
            'team_timeline_premium' => 'teamTimelinePremiumSchema',
            'team_org_chart_premium' => 'teamOrgChartPremiumSchema',
            'team_leadership_premium' => 'teamLeadershipPremiumSchema',
            'team_culture_premium' => 'teamCulturePremiumSchema',
            'team_open_positions_premium' => 'teamOpenPositionsPremiumSchema',

            'testimonials_carousel' => 'testimonialsSchema',
            'testimonials_video_premium' => 'testimonialsVideoPremiumSchema',
            'testimonials_scrolling_marquee' => 'testimonialsScrollingMarqueeSchema',
            'testimonials_wall_of_love' => 'testimonialsWallOfLoveSchema',
            'testimonials_card_stack' => 'testimonialsCardStackSchema',
            'testimonials_trust_dashboard' => 'testimonialsTrustDashboardSchema',
            'testimonials_review_grid' => 'testimonialsReviewGridSchema',
            'testimonials_review_carousel_pro' => 'testimonialsReviewCarouselProSchema',

            'hero_centered_cta' => 'heroCtaSchema',
            'cta_glass_premium' => 'ctaGlassPremiumSchema',
            'cta_gradient_premium' => 'ctaGradientPremiumSchema',
            'cta_newsletter_premium' => 'ctaNewsletterPremiumSchema',
            'cta_book_demo_premium' => 'ctaBookDemoPremiumSchema',
            'cta_calendly_premium' => 'ctaCalendlyPremiumSchema',
            'cta_free_trial_premium' => 'ctaFreeTrialPremiumSchema',
            'cta_countdown_premium' => 'ctaCountdownPremiumSchema',
            'cta_limited_offer_premium' => 'ctaLimitedOfferPremiumSchema',

            'pricing_cards' => 'pricingCardsSchema',
            'pricing_comparison_premium' => 'pricingComparisonPremiumSchema',
            'pricing_toggle_premium' => 'pricingTogglePremiumSchema',
            'pricing_enterprise_premium' => 'pricingEnterprisePremiumSchema',
            'pricing_calculator_premium' => 'pricingCalculatorPremiumSchema',
            'pricing_credit_premium' => 'pricingCreditPremiumSchema',
            'pricing_agency_premium' => 'pricingAgencyPremiumSchema',
            'pricing_feature_matrix_premium' => 'pricingFeatureMatrixPremiumSchema',

            'contact_form_modern' => 'contactFormModernSchema',
            'contact_split_premium' => 'contactSplitPremiumSchema',
            'contact_map_premium' => 'contactMapPremiumSchema',
            'contact_appointment_premium' => 'contactAppointmentPremiumSchema',
            'contact_support_center_premium' => 'contactSupportCenterPremiumSchema',
            'contact_faq_premium' => 'contactFaqPremiumSchema',
            'contact_multistep_premium' => 'contactMultiStepPremiumSchema',
            'contact_live_chat_premium' => 'contactLiveChatPremiumSchema',
            'blog_magazine_premium' => 'blogMagazinePremiumSchema',
            'blog_featured_article_premium' => 'blogFeaturedArticlePremiumSchema',
            'blog_editors_pick_premium' => 'blogEditorsPickPremiumSchema',
            'blog_sidebar_news_premium' => 'blogSidebarNewsPremiumSchema',
            'blog_newsletter_premium' => 'blogNewsletterPremiumSchema',
            'blog_trending_premium' => 'blogTrendingPremiumSchema',
            'blog_categories_grid_premium' => 'blogCategoriesGridPremiumSchema',
            'blog_author_profile_premium' => 'blogAuthorProfilePremiumSchema',

            'faq_accordion' => 'faqAccordionSchema',
            'faq_accordion_pro' => 'faqAccordionProSchema',
            'faq_search_premium' => 'faqSearchPremiumSchema',
            'faq_categories_premium' => 'faqCategoriesPremiumSchema',
            'faq_support_portal_premium' => 'faqSupportPortalPremiumSchema',
            'faq_documentation_premium' => 'faqDocumentationPremiumSchema',
            'lead_magnet_premium' => 'leadMagnetPremiumSchema',
            'lead_free_audit_premium' => 'leadFreeAuditPremiumSchema',
            'lead_website_audit_premium' => 'leadWebsiteAuditPremiumSchema',
            'lead_quote_form_premium' => 'leadQuoteFormPremiumSchema',
            'lead_roi_calculator_premium' => 'leadRoiCalculatorPremiumSchema',
            'lead_cost_calculator_premium' => 'leadCostCalculatorPremiumSchema',
            'lead_consultation_booking_premium' => 'leadConsultationBookingPremiumSchema',
            'sales_comparison_premium' => 'salesComparisonPremiumSchema',
            'sales_feature_matrix_premium' => 'salesFeatureMatrixPremiumSchema',
            'sales_competitor_comparison_premium' => 'salesCompetitorComparisonPremiumSchema',
            'sales_roi_premium' => 'salesRoiPremiumSchema',
            'sales_guarantee_premium' => 'salesGuaranteePremiumSchema',
            'sales_trust_premium' => 'salesTrustPremiumSchema',
            'sales_integrations_premium' => 'salesIntegrationsPremiumSchema',
            'agency_dashboard_preview_premium' => 'agencyDashboardPreviewPremiumSchema',
            'agency_client_portal_premium' => 'agencyClientPortalPremiumSchema',
            'agency_white_label_showcase_premium' => 'agencyWhiteLabelShowcasePremiumSchema',
            'agency_website_management_premium' => 'agencyWebsiteManagementPremiumSchema',
            'agency_maintenance_plans_premium' => 'agencyMaintenancePlansPremiumSchema',
            'agency_support_plans_premium' => 'agencySupportPlansPremiumSchema',
            'agency_workflow_premium' => 'agencyWorkflowPremiumSchema',
            'agency_project_pipeline_premium' => 'agencyProjectPipelinePremiumSchema',
            'agency_client_reviews_premium' => 'agencyClientReviewsPremiumSchema',
            'agency_website_reports_premium' => 'agencyWebsiteReportsPremiumSchema',
            'ai_prompt_showcase_premium' => 'aiPromptShowcasePremiumSchema',
            'ai_workflow_premium' => 'aiWorkflowPremiumSchema',
            'ai_assistant_premium' => 'aiAssistantPremiumSchema',
            'ai_timeline_premium' => 'aiTimelinePremiumSchema',
            'ai_builder_premium' => 'aiBuilderPremiumSchema',
            'ai_automation_premium' => 'aiAutomationPremiumSchema',
            'ai_credits_dashboard_premium' => 'aiCreditsDashboardPremiumSchema',
            'ai_generation_process_premium' => 'aiGenerationProcessPremiumSchema',
            'ai_statistics_premium' => 'aiStatisticsPremiumSchema',
            'ai_prompt_examples_premium' => 'aiPromptExamplesPremiumSchema',

            'contact_details' => 'contactDetailsSchema',

            'location_map' => 'locationMapSchema',

            'case_studies_grid' => 'caseStudiesGridSchema',

            'jobs_list' => 'jobsListSchema',

            'events_grid' => 'eventsGridSchema',

        ];
    }
}
